/**
 * Authentic SMS Hospital Interventional Radiology 2026 Cases
 * Parsed directly from authentic hospital discharge PDFs and operative reports in:
 * E:\DSA SMS jaipur\02_Discharge_Cards_and_Summaries\Monthly_Discharges_2026
 * E:\DSA SMS jaipur\01_Clinical_Operative_Cases_and_Reports\2026_Cases
 * Total Cases Extracted: 104
 */

export interface Real2026Case {
  id: string;
  filePath?: string;
  fileName?: string;
  patientName: string;
  age: string;
  gender: 'Male' | 'Female';
  crNo: string;
  admissionNo: string;
  admissionDate: string;
  dischargeDate: string;
  procedureDate: string;
  procedureIsoDate: string; // YYYY-MM-DD for calendar & scheduler
  procedureName: string;
  diagnosis: string;
  category: string;
  operatingFaculty: string;
  procedureDetail: string;
  ward: 'Old Gastro IR Ward' | 'IR ICU';
  bedNo: string;
}

export const REAL_2026_CLINICAL_CASES: Real2026Case[] = [
  {
    "id": "SMS2026-CASE-41662",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\ASHOK DISCAHRGE.pdf",
    "fileName": "ASHOK DISCAHRGE.pdf",
    "patientName": "Ashok Kumar",
    "age": "27Y",
    "gender": "Male",
    "crNo": "240422084057436",
    "admissionNo": "A/SMSH/25/156507",
    "admissionDate": "12-12-2025",
    "dischargeDate": "",
    "procedureDate": "12-12-2025",
    "procedureIsoDate": "2025-12-12",
    "procedureName": "AV Fistuloplasty for Dialysis Access",
    "diagnosis": "(S) Other disorders of arteries and arterioles (I77)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-81305",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\7-8-2026\\RAHUL GANGWAL VARICOCELE.pdf",
    "fileName": "RAHUL GANGWAL VARICOCELE.pdf",
    "patientName": "Rahul Gangwal",
    "age": "24Y",
    "gender": "Male",
    "crNo": "110524207227141",
    "admissionNo": "A/SMSH/26/97446",
    "admissionDate": "03-08-2026",
    "dischargeDate": "07-08-2026",
    "procedureDate": "03-08-2026",
    "procedureIsoDate": "2026-08-03",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of other sites (I86)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62566",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\8-8-2026\\ANMOL UPADHYAY.pdf",
    "fileName": "ANMOL UPADHYAY.pdf",
    "patientName": "Anmol Upadhyay",
    "age": "25Y",
    "gender": "Male",
    "crNo": "230921100309368",
    "admissionNo": "A/SMSH/26/99394",
    "admissionDate": "07-08-2026",
    "dischargeDate": "08-08-2026",
    "procedureDate": "07-08-2026",
    "procedureIsoDate": "2026-08-07",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Cellulitis and acute lymphangitis (L03)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-86480",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\8-8-2026\\RUKSANA BEGUM PTBD.pdf",
    "fileName": "RUKSANA BEGUM PTBD.pdf",
    "patientName": "Ruksana Begum",
    "age": "62Y",
    "gender": "Female",
    "crNo": "150922126499296",
    "admissionNo": "A/SMSH/26/98446",
    "admissionDate": "05-08-2026",
    "dischargeDate": "08-08-2026",
    "procedureDate": "05-08-2026",
    "procedureIsoDate": "2026-08-05",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Calculus of bile duct w/o cholangitis or cholecyst w/o obst (K8050)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-38161",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\BILKISH PTBD.pdf",
    "fileName": "BILKISH PTBD.pdf",
    "patientName": "Bilkish",
    "age": "18Y",
    "gender": "Female",
    "crNo": "090423155391215",
    "admissionNo": "A/SMSH/26/105513",
    "admissionDate": "20-08-2026",
    "dischargeDate": "31-08-2026",
    "procedureDate": "20-08-2026",
    "procedureIsoDate": "2026-08-20",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Congenital malform of gallbladder, bile ducts and liver (Q44)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG guidance using 18 G Chiba needle, right hepatic ducts accessed. PTFE guidewire used to negotiate through the HJ Loop, and 8 fr RBC catheter placed on right sides. Catheter secured. Patient tolerated the procedure well.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34315",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\BINTU CHOLANGIOPLASTY.pdf",
    "fileName": "BINTU CHOLANGIOPLASTY.pdf",
    "patientName": "Bintu Devi",
    "age": "38Y",
    "gender": "Female",
    "crNo": "200223148476666",
    "admissionNo": "A/SMSH/26/106350",
    "admissionDate": "22-08-2026",
    "dischargeDate": "25-08-2026",
    "procedureDate": "22-08-2026",
    "procedureIsoDate": "2026-08-22",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of biliary tract (K83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-74677",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\DIL KESH AVM.pdf",
    "fileName": "DIL KESH AVM.pdf",
    "patientName": "Dil Kesh Saini",
    "age": "23Y",
    "gender": "Male",
    "crNo": "141022130452048",
    "admissionNo": "A/SMSH/26/104852",
    "admissionDate": "19-08-2026",
    "dischargeDate": "21-08-2026",
    "procedureDate": "19-08-2026",
    "procedureIsoDate": "2026-08-19",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and \ufb02uoro guidance, left CFA punctured and 5Fr sheath placed. . Using Cobra catheter and guidewire combination, right CIA accessed. Over the wire , the cathter was exchanged with MPA catheter and selective angiogram taken from CFA, ATA and TP trunk Large nidi were seen in the knee, ankle and foot region with supply from the popliteal artery, ATA and PTA along with early draining veins Patient tolerated the procedure well. DR ALOK VERMA",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-11022",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\GHANSHYAM DVT L SUBCLAVIAN VEIN.pdf",
    "fileName": "GHANSHYAM DVT L SUBCLAVIAN VEIN.pdf",
    "patientName": "Ghanshyam Sharma",
    "age": "25Y",
    "gender": "Male",
    "crNo": "290722119051812",
    "admissionNo": "A/SMSH/26/109038",
    "admissionDate": "29-08-2026",
    "dischargeDate": "31-08-2026",
    "procedureDate": "29-08-2026",
    "procedureIsoDate": "2026-08-29",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other venous embolism and thrombosis (I82)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-96178",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\HIMANI BANSAL PICC.pdf",
    "fileName": "HIMANI BANSAL PICC.pdf",
    "patientName": "Himani Bansal",
    "age": "27Y",
    "gender": "Female",
    "crNo": "050224194613817",
    "admissionNo": "A/SMSH/26/101822",
    "admissionDate": "12-08-2026",
    "dischargeDate": "13-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of breast (C50)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right brachial vein punctured in mid arm using 21 G needle. Wire parked in IVC. Peel away sheath placed. 5 Fr dual lumen PICC line placed with tip at RA SVC junction. Peel away sheath removed. Back\ufb02ow checked for both lumen. Flushing done with heparinized saline. Dressing applied. Procedure uneventful. DR NARESH SIR Discharge Medications S No. Medicine Dose /Power Frequency Days Instructions 1 Ibuprofen and Paracetamol Tablets IP Ibuprofen 400 ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-21814",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\KARAN VARICOCELE.pdf",
    "fileName": "KARAN VARICOCELE.pdf",
    "patientName": "Karan Sahu",
    "age": "22Y",
    "gender": "Male",
    "crNo": "060323150751296",
    "admissionNo": "A/SMSH/26/104082",
    "admissionDate": "18-08-2026",
    "dischargeDate": "19-08-2026",
    "procedureDate": "18-08-2026",
    "procedureIsoDate": "2026-08-18",
    "procedureName": "Digital Subtraction Venography",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and \ufb02uoro guidance, right CFV punctured and 5Fr sheath placed. . Using Cobra catheter and guidewire combination, left renal vein accessed. Venogram taken with valsalva revealed dilated left testicular vein along with opaci\ufb01cation of the varicocele. Left testicular vein accessed, and using microcatheter, multiple microcoils of varying sizes used for embolisation of the caudal part of testicular vein at the level of pelvic rim. Check venogram with valsalva ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-01742",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\MANOJ CHOLANGIOPLASTY.pdf",
    "fileName": "MANOJ CHOLANGIOPLASTY.pdf",
    "patientName": "Manoj Kumar",
    "age": "47Y",
    "gender": "Male",
    "crNo": "231223189777254",
    "admissionNo": "A/SMSH/26/104470",
    "admissionDate": "18-08-2026",
    "dischargeDate": "22-08-2026",
    "procedureDate": "18-08-2026",
    "procedureIsoDate": "2026-08-18",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-07255",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\NEELAM LAMA.pdf",
    "fileName": "NEELAM LAMA.pdf",
    "patientName": "Neelam Dabani",
    "age": "30Y",
    "gender": "Female",
    "crNo": "250723169033137",
    "admissionNo": "A/SMSH/26/107543",
    "admissionDate": "25-08-2026",
    "dischargeDate": "25-08-2026",
    "procedureDate": "25-08-2026",
    "procedureIsoDate": "2026-08-25",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Fever of other and unknown origin (R50)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-27701",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\RAJENDRA BAE.pdf",
    "fileName": "RAJENDRA BAE.pdf",
    "patientName": "Rajendra",
    "age": "56Y",
    "gender": "Male",
    "crNo": "150325245703880",
    "admissionNo": "A/SMSH/26/101885",
    "admissionDate": "12-08-2026",
    "dischargeDate": "18-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "Bronchial Artery Embolization (BAE)",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-70081",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\RAMSWAROOP VARICOSE VEIN.pdf",
    "fileName": "RAMSWAROOP VARICOSE VEIN.pdf",
    "patientName": "Ramswroop Meena",
    "age": "52Y",
    "gender": "Male",
    "crNo": "300522102102897",
    "admissionNo": "A/SMSH/26/101609",
    "admissionDate": "12-08-2026",
    "dischargeDate": "14-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV punctured around ankle joint. 7Fr sheath placed. Venogram taken. Due to tortuosity of the vein, wire could not be negotiated. Hence access also taken in the GSV in below knee region and mid thigh. 7 Fr sheaths placed at both sites. Venaseal closure system was used and tip of the delivery catheter placed from all three sheaths. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Few ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-44180",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\VIVEK FISTULOPLASTY.pdf",
    "fileName": "VIVEK FISTULOPLASTY.pdf",
    "patientName": "Vivek Kumar",
    "age": "16Y",
    "gender": "Male",
    "crNo": "160724214867644",
    "admissionNo": "A/SMSH/26/101597",
    "admissionDate": "12-08-2026",
    "dischargeDate": "15-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "AV Fistuloplasty for Dialysis Access",
    "diagnosis": "(S) Chronic kidney disease (CKD) (N18)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93993",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\August\\nitin venous malformation.pdf",
    "fileName": "nitin venous malformation.pdf",
    "patientName": "Nitin Kumar",
    "age": "20Y",
    "gender": "Male",
    "crNo": "240325246681495",
    "admissionNo": "A/SMSH/26/110645",
    "admissionDate": "01-09-2026",
    "dischargeDate": "03-09-2026",
    "procedureDate": "01-09-2026",
    "procedureIsoDate": "2026-09-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-13371",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\OEC Elite CFD Tech Data JB00104XX Jun 23.pdf.pdf",
    "fileName": "OEC Elite CFD Tech Data JB00104XX Jun 23.pdf.pdf",
    "patientName": "Oec Elite Cfd Tech Data Jb00104Xx Jun 23.Pdf",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-87006",
    "admissionNo": "A/SMSH/26/27006",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Diagnostic Digital Subtraction Angiography (DSA)",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-59611",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\PaySlip_0C13C61C20250303.pdf",
    "fileName": "PaySlip_0C13C61C20250303.pdf",
    "patientName": "Payslip",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-46714",
    "admissionNo": "A/SMSH/26/56714",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-02069",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\RMC-366965_20250303_CB7A.pdf",
    "fileName": "RMC-366965_20250303_CB7A.pdf",
    "patientName": "Rmc",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-33718",
    "admissionNo": "A/SMSH/26/93718",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-87020",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\Ramkumar JNA.pdf",
    "fileName": "Ramkumar JNA.pdf",
    "patientName": "Ramkumar Parmar",
    "age": "19Y",
    "gender": "Male",
    "crNo": "190724215305721",
    "admissionNo": "A/SMSH/26/11496",
    "admissionDate": "27-01-2026",
    "dischargeDate": "01-05-2026",
    "procedureDate": "27-01-2026",
    "procedureIsoDate": "2026-01-27",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-40143",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\SEETA.pdf",
    "fileName": "SEETA.pdf",
    "patientName": "Seeta Meena",
    "age": "23Y",
    "gender": "Female",
    "crNo": "240423157389947",
    "admissionNo": "A/SMSH/26/08932",
    "admissionDate": "21-01-2026",
    "dischargeDate": "22-01-2026",
    "procedureDate": "21-01-2026",
    "procedureIsoDate": "2026-01-21",
    "procedureName": "Digital Subtraction Venography",
    "diagnosis": "(S) Venous insu\ufb03ciency (chronic) (peripheral) (I872)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-88744",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\September\\Rajkumar SEMS disch.pdf",
    "fileName": "Rajkumar SEMS disch.pdf",
    "patientName": "Rajkumar",
    "age": "46Y",
    "gender": "Male",
    "crNo": "110726298011846",
    "admissionNo": "A/SMSH/26/116769",
    "admissionDate": "14-09-2026",
    "dischargeDate": "19-09-2026",
    "procedureDate": "14-09-2026",
    "procedureIsoDate": "2026-09-14",
    "procedureName": "Biliary SEMS Stenting",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-86323",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\September\\dil kesh AVM embolisation.pdf",
    "fileName": "dil kesh AVM embolisation.pdf",
    "patientName": "Dil Kesh Saini",
    "age": "23Y",
    "gender": "Male",
    "crNo": "141022130452048",
    "admissionNo": "A/SMSH/26/117294",
    "admissionDate": "15-09-2026",
    "dischargeDate": "19-09-2026",
    "procedureDate": "15-09-2026",
    "procedureIsoDate": "2026-09-15",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-56120",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\hcc management.pdf",
    "fileName": "hcc management.pdf",
    "patientName": "Hcc Management",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-38098",
    "admissionNo": "A/SMSH/26/18098",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Transarterial Chemoembolization (TACE)",
    "diagnosis": "tumour size, rim and non-",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-04718",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\ilovepdf_merged (6).pdf",
    "fileName": "ilovepdf_merged (6).pdf",
    "patientName": "Ilovepdf",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-49402",
    "admissionNo": "A/SMSH/26/59402",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-32318",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\khushbeena.pdf",
    "fileName": "khushbeena.pdf",
    "patientName": "Khushbeena",
    "age": "24Y",
    "gender": "Female",
    "crNo": "030723165758041",
    "admissionNo": "A/SMSH/25/155407",
    "admissionDate": "10-12-2025",
    "dischargeDate": "",
    "procedureDate": "10-12-2025",
    "procedureIsoDate": "2025-12-10",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Spontaneous abortion (O03)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-51164",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\letter for medical report Readiodiagnosis (1).pdf",
    "fileName": "letter for medical report Readiodiagnosis (1).pdf",
    "patientName": "Letter For Medical Report Readiodiagnosis",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-75040",
    "admissionNo": "A/SMSH/26/25040",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-87733",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\mangla ram.pdf",
    "fileName": "mangla ram.pdf",
    "patientName": "Mangala Ram Godara",
    "age": "18Y",
    "gender": "Male",
    "crNo": "120625255202748",
    "admissionNo": "A/SMSH/26/07688",
    "admissionDate": "19-01-2026",
    "dischargeDate": "22-01-2026",
    "procedureDate": "19-01-2026",
    "procedureIsoDate": "2026-01-19",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of nasopharynx (D106)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-82923",
    "filePath": "E:\\DSA SMS jaipur\\01_Clinical_Operative_Cases_and_Reports\\2026_Cases\\saf form.pdf",
    "fileName": "saf form.pdf",
    "patientName": "Saf Form",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-30973",
    "admissionNo": "A/SMSH/26/30973",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Venous Malformation Sclerotherapy",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-80227",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\AUGUST 2026\\GIRIJA.pdf",
    "fileName": "GIRIJA.pdf",
    "patientName": "Girija",
    "age": "20Y",
    "gender": "Female",
    "crNo": "190626295959787",
    "admissionNo": "A/SMSH/26/96787",
    "admissionDate": "01-08-2026",
    "dischargeDate": "03-08-2026",
    "procedureDate": "01-08-2026",
    "procedureIsoDate": "2026-08-01",
    "procedureName": "Pseudoaneurysm Coiling & Thrombin Injection",
    "diagnosis": "(S) Postpartum hemorrhage (O72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-31188",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\AUGUST 2026\\KAILASH.pdf",
    "fileName": "KAILASH.pdf",
    "patientName": "Kailash Kanwar",
    "age": "47Y",
    "gender": "Female",
    "crNo": "140622112878788",
    "admissionNo": "A/SMSH/26/87786",
    "admissionDate": "13-07-2026",
    "dischargeDate": "03-08-2026",
    "procedureDate": "13-07-2026",
    "procedureIsoDate": "2026-07-13",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-44726",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\DISCHARGE OF KAUSHAL SHARMA --VENASEAL.pdf",
    "fileName": "DISCHARGE OF KAUSHAL SHARMA --VENASEAL.pdf",
    "patientName": "Kaushal Sharma",
    "age": "30Y",
    "gender": "Male",
    "crNo": "211119050148684",
    "admissionNo": "A/SMSH/26/68183",
    "admissionDate": "02-06-2026",
    "dischargeDate": "04-06-2026",
    "procedureDate": "02-06-2026",
    "procedureIsoDate": "2026-06-02",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-36555",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\ASIN.pdf",
    "fileName": "ASIN.pdf",
    "patientName": "Aasin",
    "age": "50Y",
    "gender": "Male",
    "crNo": "300425250781323",
    "admissionNo": "A/SMSH/26/91010",
    "admissionDate": "20-07-2026",
    "dischargeDate": "27-07-2026",
    "procedureDate": "20-07-2026",
    "procedureIsoDate": "2026-07-20",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of liver and intrahepatic bile ducts (C22)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-73399",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\BADAN SINGH.pdf",
    "fileName": "BADAN SINGH.pdf",
    "patientName": "Badan Singh",
    "age": "34Y",
    "gender": "Male",
    "crNo": "091123184442640",
    "admissionNo": "A/SMSH/26/81059",
    "admissionDate": "29-06-2026",
    "dischargeDate": "04-07-2026",
    "procedureDate": "29-06-2026",
    "procedureIsoDate": "2026-06-29",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62461",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\BANAY SINGH.pdf",
    "fileName": "BANAY SINGH.pdf",
    "patientName": "Banay Singh Ursf",
    "age": "55Y",
    "gender": "Male",
    "crNo": "060125237223193",
    "admissionNo": "A/SMSH/26/87427",
    "admissionDate": "13-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "13-07-2026",
    "procedureIsoDate": "2026-07-13",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of liver (K76)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-03749",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\BHASKAR.pdf",
    "fileName": "BHASKAR.pdf",
    "patientName": "Bhaskar Saini",
    "age": "28Y",
    "gender": "Male",
    "crNo": "300626296932158",
    "admissionNo": "A/SMSH/26/94267",
    "admissionDate": "27-07-2026",
    "dischargeDate": "29-07-2026",
    "procedureDate": "27-07-2026",
    "procedureIsoDate": "2026-07-27",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-66052",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\GANGA.pdf",
    "fileName": "GANGA.pdf",
    "patientName": "Ganga",
    "age": "38Y",
    "gender": "Female",
    "crNo": "211025271482635",
    "admissionNo": "A/SMSH/26/81301",
    "admissionDate": "30-06-2026",
    "dischargeDate": "03-07-2026",
    "procedureDate": "30-06-2026",
    "procedureIsoDate": "2026-06-30",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-18349",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\GIRIRAJ.pdf",
    "fileName": "GIRIRAJ.pdf",
    "patientName": "Giriraj Panchal",
    "age": "41Y",
    "gender": "Male",
    "crNo": "020824217316124",
    "admissionNo": "A/SMSH/26/81742",
    "admissionDate": "01-07-2026",
    "dischargeDate": "03-07-2026",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other disorders of veins (I87)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-27618",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\GOPAL.pdf",
    "fileName": "GOPAL.pdf",
    "patientName": "Gopal",
    "age": "71Y",
    "gender": "Male",
    "crNo": "230425250000892",
    "admissionNo": "A/SMSH/26/90724",
    "admissionDate": "19-07-2026",
    "dischargeDate": "28-07-2026",
    "procedureDate": "19-07-2026",
    "procedureIsoDate": "2026-07-19",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34683",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\GUMAN SINGH.pdf",
    "fileName": "GUMAN SINGH.pdf",
    "patientName": "Guman Singh",
    "age": "69Y",
    "gender": "Male",
    "crNo": "080325244960920",
    "admissionNo": "A/SMSH/26/84071",
    "admissionDate": "06-07-2026",
    "dischargeDate": "08-07-2026",
    "procedureDate": "06-07-2026",
    "procedureIsoDate": "2026-07-06",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-20542",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\HARIRAM.pdf",
    "fileName": "HARIRAM.pdf",
    "patientName": "Hariram Singh",
    "age": "31Y",
    "gender": "Male",
    "crNo": "080422014240233",
    "admissionNo": "A/SMSH/26/86264",
    "admissionDate": "10-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "10-07-2026",
    "procedureIsoDate": "2026-07-10",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Injury of intra-abdominal organs (S36)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-78025",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\HIRDESH KUMAR.pdf",
    "fileName": "HIRDESH KUMAR.pdf",
    "patientName": "Hirdesh Kumar",
    "age": "46Y",
    "gender": "Male",
    "crNo": "160626295602461",
    "admissionNo": "A/SMSH/26/81366",
    "admissionDate": "30-06-2026",
    "dischargeDate": "02-07-2026",
    "procedureDate": "30-06-2026",
    "procedureIsoDate": "2026-06-30",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other aneurysm (I72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-88431",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF ABHISHEK YADAV -Digital subtraction venography.pdf",
    "fileName": "DISCHARGE OF ABHISHEK YADAV -Digital subtraction venography.pdf",
    "patientName": "Abhishek Yadav",
    "age": "20Y",
    "gender": "Male",
    "crNo": "150923176861567",
    "admissionNo": "A/SMSH/26/77931",
    "admissionDate": "22-06-2026",
    "dischargeDate": "27-06-2026",
    "procedureDate": "22-06-2026",
    "procedureIsoDate": "2026-06-22",
    "procedureName": "Digital Subtraction Venography",
    "diagnosis": "(S) Scrotal varices (I861)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-47312",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF DHEERAJ BHAGORIYA -RIGHT FOOT AVM.pdf",
    "fileName": "DISCHARGE OF DHEERAJ BHAGORIYA -RIGHT FOOT AVM.pdf",
    "patientName": "Dheeraj Bagoriya",
    "age": "24Y",
    "gender": "Male",
    "crNo": "121125273970868",
    "admissionNo": "A/SMSH/26/70947",
    "admissionDate": "08-06-2026",
    "dischargeDate": "10-06-2026",
    "procedureDate": "08-06-2026",
    "procedureIsoDate": "2026-06-08",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Arteriovenous malformation of vessel of lower limb (Q2732)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-52449",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF MUKESH KUMAR SAINI -VENASEAL.pdf",
    "fileName": "DISCHARGE OF MUKESH KUMAR SAINI -VENASEAL.pdf",
    "patientName": "Mukesh Kumar Saini",
    "age": "55Y",
    "gender": "Male",
    "crNo": "080622112088863",
    "admissionNo": "A/SMSH/26/74575",
    "admissionDate": "15-06-2026",
    "dischargeDate": "18-06-2026",
    "procedureDate": "15-06-2026",
    "procedureIsoDate": "2026-06-15",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-19161",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF NARESH KUMAR - PANCREATITS WITH HEMETMESIS.pdf",
    "fileName": "DISCHARGE OF NARESH KUMAR - PANCREATITS WITH HEMETMESIS.pdf",
    "patientName": "Naresh Kumar",
    "age": "43Y",
    "gender": "Male",
    "crNo": "100626295134878",
    "admissionNo": "A/SMSH/26/78044",
    "admissionDate": "22-06-2026",
    "dischargeDate": "24-06-2026",
    "procedureDate": "22-06-2026",
    "procedureIsoDate": "2026-06-22",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Acute pancreatitis (K85)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-96301",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF PRAVEEN CHOUDHARY -DSA(NECK SWELLING).pdf",
    "fileName": "DISCHARGE OF PRAVEEN CHOUDHARY -DSA(NECK SWELLING).pdf",
    "patientName": "Praveen Choudhary",
    "age": "22Y",
    "gender": "Male",
    "crNo": "240224197370410",
    "admissionNo": "A/SMSH/26/73631",
    "admissionDate": "13-06-2026",
    "dischargeDate": "14-06-2026",
    "procedureDate": "13-06-2026",
    "procedureIsoDate": "2026-06-13",
    "procedureName": "Diagnostic Digital Subtraction Angiography (DSA)",
    "diagnosis": "(S) Localized swelling, mass and lump, neck (R221)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-16801",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF RUKSANA BEGUM.pdf",
    "fileName": "DISCHARGE OF RUKSANA BEGUM.pdf",
    "patientName": "Ruksana Begum",
    "age": "62Y",
    "gender": "Female",
    "crNo": "150922126499296",
    "admissionNo": "A/SMSH/26/72354",
    "admissionDate": "10-06-2026",
    "dischargeDate": "23-06-2026",
    "procedureDate": "10-06-2026",
    "procedureIsoDate": "2026-06-10",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Calculus of bile duct w/o cholangitis or cholecyst w/o obst (K8050)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-58733",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF SOMA DEVI.pdf",
    "fileName": "DISCHARGE OF SOMA DEVI.pdf",
    "patientName": "Soma Devi",
    "age": "63Y",
    "gender": "Female",
    "crNo": "080623162894273",
    "admissionNo": "A/SMSH/26/67443",
    "admissionDate": "01-06-2026",
    "dischargeDate": "10-06-2026",
    "procedureDate": "01-06-2026",
    "procedureIsoDate": "2026-06-01",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG guidance, PTBD catheter (8 Fr) is placed in the right biliary duct system using catheter and wire. Catheter is secured. Patient tolerated the procedure well. No intra/post procedure complications seen. Manual compression bandage applied. Post procedure plan: Catheter care and out\ufb02ow monitoring Inj. Ceftriaxone 1gm BD Inj. Pantoprazole 40mg OD Inj. Ondansetron 2cc SOS Inj. PCM /Tramadol in infusion SOS IV Fluid 60ml/hr DR AYUSH KHANDELWAL 2. 03/06 /2026 10",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-26238",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF SURJIT KUMAR -DSA( TREATED PTB WITH HEMOPTYSIS.pdf",
    "fileName": "DISCHARGE OF SURJIT KUMAR -DSA( TREATED PTB WITH HEMOPTYSIS.pdf",
    "patientName": "Surjit Kumar",
    "age": "29Y",
    "gender": "Male",
    "crNo": "270526293789368",
    "admissionNo": "A/SMSH/26/73230",
    "admissionDate": "12-06-2026",
    "dischargeDate": "13-06-2026",
    "procedureDate": "12-06-2026",
    "procedureIsoDate": "2026-06-12",
    "procedureName": "Diagnostic Digital Subtraction Angiography (DSA)",
    "diagnosis": "(S) Hemoptysis (R042)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-86005",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF VANSH RECURRENT JNA -PVA EMBOLIZATION.pdf",
    "fileName": "DISCHARGE OF VANSH RECURRENT JNA -PVA EMBOLIZATION.pdf",
    "patientName": "Vansh Kumar",
    "age": "14Y",
    "gender": "Male",
    "crNo": "110423155670044",
    "admissionNo": "A/SMSH/26/79603",
    "admissionDate": "26-06-2026",
    "dischargeDate": "30-06-2026",
    "procedureDate": "26-06-2026",
    "procedureIsoDate": "2026-06-26",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of nasopharynx (D106)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition USG and \ufb02uoroscopy guidance, Right CFA access taken with 18 G needle and 5 F sheath placed. With the help of 5 Fr AR catheter, right CCA, ECA and ICA run were performed in AP and lateral views which revealed abnormal blush from internal maxillary artery branch of right ECA and mild blush from right ICA. After superselective cannulation of IMA using microcatheter, embolisation of culprit branches done using 355-500 micron PVA particles. Post embolization right ECA r",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-59064",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\DISCHARGE OF YOGESH JOSHI-Venogram and Sclerotherapy.pdf",
    "fileName": "DISCHARGE OF YOGESH JOSHI-Venogram and Sclerotherapy.pdf",
    "patientName": "Yogesh Joshi",
    "age": "48Y",
    "gender": "Male",
    "crNo": "111122134385376",
    "admissionNo": "A/SMSH/26/73671",
    "admissionDate": "13-06-2026",
    "dischargeDate": "16-06-2026",
    "procedureDate": "13-06-2026",
    "procedureIsoDate": "2026-06-13",
    "procedureName": "Venous Malformation Sclerotherapy",
    "diagnosis": "(S) Varicose veins of right lower extremity with pain (I83811)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and \ufb02uoro guidance, varicosities in the right leg punctured and venogram taken which revealed dilated varicosities. Sclerotherapy done using 3 cc foam preparation of polidocanol . Ablation of one of the perforator in lower leg was also done Procedure uneventful. Bandage applied DR NARESH MANGALHARA, DR ALOK VERMA Discharge Medications [Page 2] Patient Discharge Details General Advise",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-05269",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\Discharge of yash mishra face avm.pdf",
    "fileName": "Discharge of yash mishra face avm.pdf",
    "patientName": "Yash Mishra",
    "age": "17Y",
    "gender": "Male",
    "crNo": "190822122249531",
    "admissionNo": "A/SMSH/26/67962",
    "admissionDate": "02-06-2026",
    "dischargeDate": "05-06-2026",
    "procedureDate": "02-06-2026",
    "procedureIsoDate": "2026-06-02",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Arteriovenous malformation, other site (Q2739)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-35399",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\JNA DSA  DISCHARGE OF VANSH KUMAR MEGHWAL.pdf",
    "fileName": "JNA DSA  DISCHARGE OF VANSH KUMAR MEGHWAL.pdf",
    "patientName": "Vansh Kumar",
    "age": "14Y",
    "gender": "Male",
    "crNo": "110423155670044",
    "admissionNo": "A/SMSH/26/71578",
    "admissionDate": "09-06-2026",
    "dischargeDate": "24-06-2026",
    "procedureDate": "09-06-2026",
    "procedureIsoDate": "2026-06-09",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of nasopharynx (D106)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-20520",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\SATISH KUMAR YOGI\\JNA DISCHARGE OF SATISH KUMAR YOGI.pdf",
    "fileName": "JNA DISCHARGE OF SATISH KUMAR YOGI.pdf",
    "patientName": "Satish Kumar",
    "age": "14Y",
    "gender": "Male",
    "crNo": "290526294004300",
    "admissionNo": "A/SMSH/26/66626",
    "admissionDate": "29-05-2026",
    "dischargeDate": "03-06-2026",
    "procedureDate": "29-05-2026",
    "procedureIsoDate": "2026-05-29",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-59807",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\USHA POONIA VENASEAL DISCHARGE.pdf",
    "fileName": "USHA POONIA VENASEAL DISCHARGE.pdf",
    "patientName": "Usha Punia",
    "age": "39Y",
    "gender": "Female",
    "crNo": "261222140947203",
    "admissionNo": "A/SMSH/26/69248",
    "admissionDate": "04-06-2026",
    "dischargeDate": "08-06-2026",
    "procedureDate": "04-06-2026",
    "procedureIsoDate": "2026-06-04",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, left GSV punctured in lower thigh. 8 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Sclerotherapy done for few varicosities in the lower leg using foam polidocanol",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-19984",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\discharge  of lokesh kumar - left gluteal av malformation.pdf",
    "fileName": "discharge  of lokesh kumar - left gluteal av malformation.pdf",
    "patientName": "Lokesh Kumar",
    "age": "29Y",
    "gender": "Male",
    "crNo": "280924224991812",
    "admissionNo": "A/SMSH/26/70248",
    "admissionDate": "06-06-2026",
    "dischargeDate": "09-06-2026",
    "procedureDate": "06-06-2026",
    "procedureIsoDate": "2026-06-06",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Arteriovenous malformation of vessel of lower limb (Q2732)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and \ufb02uoro guidance, right CFA access taken. Access was obtained with 18 G needle and 5 F sheath placed. 3500 units of heparin administered Using C 1 catheter, left CIA catheterised and Angiogram taken in AP and oblique views which revealed abnormal blush from posterior division of left internal iliac artery and opaci\ufb01cation of early venous drainage. Superselective cannulation of superior gluteal artery done using microcatheter. Embolisation done using glu",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-97353",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\discharge of jilajeet -venaseal.pdf",
    "fileName": "discharge of jilajeet -venaseal.pdf",
    "patientName": "Jilajeet Meena",
    "age": "25Y",
    "gender": "Male",
    "crNo": "140722116873722",
    "admissionNo": "A/SMSH/26/78196",
    "admissionDate": "23-06-2026",
    "dischargeDate": "27-06-2026",
    "procedureDate": "23-06-2026",
    "procedureIsoDate": "2026-06-23",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of right lower extremity with pain (I83811)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV punctured around knee joint. 7Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Foam sclerotherapy using polidocanol done for few varicosities and perforator in the leg.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-32238",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\June 2026\\discharge og geeta PTBD EXTERNAL.pdf",
    "fileName": "discharge og geeta PTBD EXTERNAL.pdf",
    "patientName": "Geeta",
    "age": "55Y",
    "gender": "Female",
    "crNo": "240125239115165",
    "admissionNo": "A/SMSH/26/78332",
    "admissionDate": "23-06-2026",
    "dischargeDate": "30-06-2026",
    "procedureDate": "23-06-2026",
    "procedureIsoDate": "2026-06-23",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Obstruction of bile duct (K831)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-68631",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\KHEMCHAND.pdf",
    "fileName": "KHEMCHAND.pdf",
    "patientName": "Khem Chand",
    "age": "31Y",
    "gender": "Male",
    "crNo": "291223190352683",
    "admissionNo": "A/SMSH/26/88782",
    "admissionDate": "15-07-2026",
    "dischargeDate": "20-07-2026",
    "procedureDate": "15-07-2026",
    "procedureIsoDate": "2026-07-15",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Super\ufb01cial injury of head (S00)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93148",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\KHUSHPREET.pdf",
    "fileName": "KHUSHPREET.pdf",
    "patientName": "Khushpreet Kaur",
    "age": "19Y",
    "gender": "Female",
    "crNo": "120419081907658",
    "admissionNo": "A/SMSH/26/88066",
    "admissionDate": "14-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "14-07-2026",
    "procedureIsoDate": "2026-07-14",
    "procedureName": "Central Venoplasty with Balloon Dilation",
    "diagnosis": "(S) Congenital malformations of great veins (Q26)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and \ufb02uoro guidance, Right femoral vein access taken with 18 G needle and 5F sheath placed. With the help of 5Fr MPA catheter, venogram revealed occlusion of IVC near RA-IVC junction. Sheath exchanged for 11 Fr sheath and attempts were made to cross the occlusion using multiple guidewires and catheter combination but could not be crossed. Under strict aseptic condition under USG and \ufb02uoro guidance, Right internal jugular vein access taken with 18 G needle ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-70792",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\LAKHPATI.pdf",
    "fileName": "LAKHPATI.pdf",
    "patientName": "Lakhpati Devi",
    "age": "37Y",
    "gender": "Female",
    "crNo": "290722119136000",
    "admissionNo": "A/SMSH/26/88562",
    "admissionDate": "15-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "15-07-2026",
    "procedureIsoDate": "2026-07-15",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-65675",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\MANISH.pdf",
    "fileName": "MANISH.pdf",
    "patientName": "Manish",
    "age": "45Y",
    "gender": "Male",
    "crNo": "170922126914031",
    "admissionNo": "A/SMSH/26/93009",
    "admissionDate": "24-07-2026",
    "dischargeDate": "25-07-2026",
    "procedureDate": "24-07-2026",
    "procedureIsoDate": "2026-07-24",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-99135",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\MANOJ.pdf",
    "fileName": "MANOJ.pdf",
    "patientName": "Manoj Kumar Sharma",
    "age": "29Y",
    "gender": "Male",
    "crNo": "150626295494245",
    "admissionNo": "A/SMSH/26/84252",
    "admissionDate": "06-07-2026",
    "dischargeDate": "08-07-2026",
    "procedureDate": "06-07-2026",
    "procedureIsoDate": "2026-07-06",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-92299",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\MOHANLAL.pdf",
    "fileName": "MOHANLAL.pdf",
    "patientName": "Mohan Lal Jangid",
    "age": "62Y",
    "gender": "Male",
    "crNo": "010823170196868",
    "admissionNo": "A/SMSH/26/94726",
    "admissionDate": "28-07-2026",
    "dischargeDate": "30-07-2026",
    "procedureDate": "28-07-2026",
    "procedureIsoDate": "2026-07-28",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of liver (K76)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-12833",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\MOHOMMAD HAMID.pdf",
    "fileName": "MOHOMMAD HAMID.pdf",
    "patientName": "Mohammad Hamid",
    "age": "73Y",
    "gender": "Male",
    "crNo": "190821094846943",
    "admissionNo": "A/SMSH/26/81828",
    "admissionDate": "01-07-2026",
    "dischargeDate": "06-07-2026",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of liver and intrahepatic bile ducts (C22)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-87268",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\NARENDRA.pdf",
    "fileName": "NARENDRA.pdf",
    "patientName": "Narendra Singh",
    "age": "32Y",
    "gender": "Male",
    "crNo": "180424204232731",
    "admissionNo": "A/SMSH/26/94771",
    "admissionDate": "28-07-2026",
    "dischargeDate": "30-07-2026",
    "procedureDate": "28-07-2026",
    "procedureIsoDate": "2026-07-28",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-81106",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\PINKY.pdf",
    "fileName": "PINKY.pdf",
    "patientName": "Pinky Sen",
    "age": "34Y",
    "gender": "Female",
    "crNo": "180622113424717",
    "admissionNo": "A/SMSH/26/91892",
    "admissionDate": "22-07-2026",
    "dischargeDate": "23-07-2026",
    "procedureDate": "22-07-2026",
    "procedureIsoDate": "2026-07-22",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV punctured around ankle joint. 7Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Few perforators were ablated along SSV in leg. Foam sclerotherapy using polidocanol done for few varicosities in the leg.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-77209",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\PURVESH.pdf",
    "fileName": "PURVESH.pdf",
    "patientName": "Purvesh Vashista",
    "age": "23Y",
    "gender": "Male",
    "crNo": "150123143497080",
    "admissionNo": "A/SMSH/26/89618",
    "admissionDate": "17-07-2026",
    "dischargeDate": "22-07-2026",
    "procedureDate": "17-07-2026",
    "procedureIsoDate": "2026-07-17",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of other sites (I86)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-13465",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\RAJESH SAINI.pdf",
    "fileName": "RAJESH SAINI.pdf",
    "patientName": "Rajesh Kumar Saini",
    "age": "43Y",
    "gender": "Male",
    "crNo": "120422010810218",
    "admissionNo": "A/SMSH/26/92412",
    "admissionDate": "23-07-2026",
    "dischargeDate": "25-07-2026",
    "procedureDate": "23-07-2026",
    "procedureIsoDate": "2026-07-23",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62503",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\RAJU.pdf",
    "fileName": "RAJU.pdf",
    "patientName": "Raju",
    "age": "37Y",
    "gender": "Male",
    "crNo": "100726297933980",
    "admissionNo": "A/SMSH/26/94127",
    "admissionDate": "27-07-2026",
    "dischargeDate": "31-07-2026",
    "procedureDate": "27-07-2026",
    "procedureIsoDate": "2026-07-27",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-50462",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\RAVINDRA.pdf",
    "fileName": "RAVINDRA.pdf",
    "patientName": "Ravinder",
    "age": "54Y",
    "gender": "Male",
    "crNo": "251122136517991",
    "admissionNo": "A/SMSH/26/82853",
    "admissionDate": "03-07-2026",
    "dischargeDate": "06-07-2026",
    "procedureDate": "03-07-2026",
    "procedureIsoDate": "2026-07-03",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV and SSV punctured around ankle 7Fr sheaths placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Foam sclerotherapy using polidocanol done for few varicosities in the leg. 7Fr sheaths placed in SSV. Venogram taken. Venaseal closure system was used and tip of the del",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-77583",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\SANGITA.pdf",
    "fileName": "SANGITA.pdf",
    "patientName": "Sangita Mahawar",
    "age": "31Y",
    "gender": "Female",
    "crNo": "141122134767815",
    "admissionNo": "A/SMSH/26/92528",
    "admissionDate": "23-07-2026",
    "dischargeDate": "24-07-2026",
    "procedureDate": "23-07-2026",
    "procedureIsoDate": "2026-07-23",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemorrhage in early pregnancy (O20)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-40344",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\SANTOSH.pdf",
    "fileName": "SANTOSH.pdf",
    "patientName": "Santosh Kumari",
    "age": "28Y",
    "gender": "Female",
    "crNo": "030424202576231",
    "admissionNo": "A/SMSH/26/88995",
    "admissionDate": "16-07-2026",
    "dischargeDate": "21-07-2026",
    "procedureDate": "16-07-2026",
    "procedureIsoDate": "2026-07-16",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62511",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\SATVEER.pdf",
    "fileName": "SATVEER.pdf",
    "patientName": "Satveer",
    "age": "24Y",
    "gender": "Male",
    "crNo": "141022130544854",
    "admissionNo": "A/SMSH/26/89308",
    "admissionDate": "16-07-2026",
    "dischargeDate": "21-07-2026",
    "procedureDate": "16-07-2026",
    "procedureIsoDate": "2026-07-16",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of other sites (I86)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-67327",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\SUKPAL.pdf",
    "fileName": "SUKPAL.pdf",
    "patientName": "Sukpal Chodhary",
    "age": "44Y",
    "gender": "Male",
    "crNo": "110626295149784",
    "admissionNo": "A/SMSH/26/88400",
    "admissionDate": "14-07-2026",
    "dischargeDate": "18-07-2026",
    "procedureDate": "14-07-2026",
    "procedureIsoDate": "2026-07-14",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other aneurysm (I72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-71937",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\UDAL SINGH.pdf",
    "fileName": "UDAL SINGH.pdf",
    "patientName": "Udal Singh",
    "age": "30Y",
    "gender": "Male",
    "crNo": "280922128475404",
    "admissionNo": "A/SMSH/26/87593",
    "admissionDate": "13-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "13-07-2026",
    "procedureIsoDate": "2026-07-13",
    "procedureName": "Central Venoplasty with Balloon Dilation",
    "diagnosis": "(S) Other venous embolism and thrombosis (I82)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and \ufb02uoro guidance, Right femoral vein access taken with 18 G needle and 5F sheath placed. With the help of 5Fr MPA catheter, venogram revealed stenosis of the inferior vena cava near IVC-RA junction. 8 Fr long sheath exchanged and the stenosis was crossed using help of multiple guidewires and MPA catheter. IV Heparin administered prior to dilation of the narrowing using balloons of size (12x40 mm, 16x40mm, 18x40mm and 20x40mm) over sti\ufb00 guidewire. Post v",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-73518",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\laxmi devi.pdf",
    "fileName": "laxmi devi.pdf",
    "patientName": "Laxmi Devi",
    "age": "48Y",
    "gender": "Female",
    "crNo": "020726297170653",
    "admissionNo": "A/SMSH/26/82980",
    "admissionDate": "03-07-2026",
    "dischargeDate": "04-07-2026",
    "procedureDate": "03-07-2026",
    "procedureIsoDate": "2026-07-03",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Unspeci\ufb01ed lump in breast (N63)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34671",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\July 2026\\rajesh.pdf",
    "fileName": "rajesh.pdf",
    "patientName": "Rajesh Kumar Saini",
    "age": "43Y",
    "gender": "Male",
    "crNo": "120422010810218",
    "admissionNo": "A/SMSH/26/84322",
    "admissionDate": "06-07-2026",
    "dischargeDate": "07-07-2026",
    "procedureDate": "06-07-2026",
    "procedureIsoDate": "2026-07-06",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Fever of other and unknown origin (R50)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-68873",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\KALURAM DISCHARGE.pdf",
    "fileName": "KALURAM DISCHARGE.pdf",
    "patientName": "Kaluram",
    "age": "51Y",
    "gender": "Male",
    "crNo": "090321123816678",
    "admissionNo": "A/SMSH/25/154353",
    "admissionDate": "08-12-2025",
    "dischargeDate": "",
    "procedureDate": "08-12-2025",
    "procedureIsoDate": "2025-12-08",
    "procedureName": "Bronchial Artery Embolization (BAE)",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-49654",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\KESARI DEVI DISDCHARGE.pdf",
    "fileName": "KESARI DEVI DISDCHARGE.pdf",
    "patientName": "Kesari Devi",
    "age": "58Y",
    "gender": "Female",
    "crNo": "220823173259594",
    "admissionNo": "A/SMSH/25/151909",
    "admissionDate": "02-12-2025",
    "dischargeDate": "",
    "procedureDate": "02-12-2025",
    "procedureIsoDate": "2025-12-02",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemangioma and lymphangioma, any site (D18)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-58595",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\Kamlesh Cephalic vein thrombosis.pdf",
    "fileName": "Kamlesh Cephalic vein thrombosis.pdf",
    "patientName": "Kamlesh Kumar",
    "age": "33Y",
    "gender": "Male",
    "crNo": "130224195848385",
    "admissionNo": "A/SMSH/26/52457",
    "admissionDate": "30-04-2026",
    "dischargeDate": "02-05-2026",
    "procedureDate": "30-04-2026",
    "procedureIsoDate": "2026-04-30",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Acute embolism and thrombosis of super\ufb01c vn unsp up extrem (I82619)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-47355",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\RAJAN DEVI VARICOSE.pdf",
    "fileName": "RAJAN DEVI VARICOSE.pdf",
    "patientName": "Rajan Devi",
    "age": "60Y",
    "gender": "Female",
    "crNo": "260523161427191",
    "admissionNo": "A/SMSH/26/59522",
    "admissionDate": "14-05-2026",
    "dischargeDate": "16-05-2026",
    "procedureDate": "14-05-2026",
    "procedureIsoDate": "2026-05-14",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right SSV punctured at mid leg. 7 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SPJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-29388",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\Seema Devi Central Venoplasty.pdf",
    "fileName": "Seema Devi Central Venoplasty.pdf",
    "patientName": "Seema Devi",
    "age": "37Y",
    "gender": "Female",
    "crNo": "071024226168327",
    "admissionNo": "A/SMSH/26/54435",
    "admissionDate": "04-05-2026",
    "dischargeDate": "07-05-2026",
    "procedureDate": "04-05-2026",
    "procedureIsoDate": "2026-05-04",
    "procedureName": "Central Venoplasty with Balloon Dilation",
    "diagnosis": "(S) Other disorders of veins (I87)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-42722",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\bintu devi discharge.pdf",
    "fileName": "bintu devi discharge.pdf",
    "patientName": "Bintu Devi",
    "age": "38Y",
    "gender": "Female",
    "crNo": "200223148476666",
    "admissionNo": "A/SMSH/26/53059",
    "admissionDate": "01-05-2026",
    "dischargeDate": "04-05-2026",
    "procedureDate": "01-05-2026",
    "procedureIsoDate": "2026-05-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of biliary tract (K83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-12041",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\brahm singh biopsy liver.pdf",
    "fileName": "brahm singh biopsy liver.pdf",
    "patientName": "Braham Singh",
    "age": "36Y",
    "gender": "Male",
    "crNo": "131023180827588",
    "admissionNo": "A/SMSH/26/56658",
    "admissionDate": "08-05-2026",
    "dischargeDate": "11-05-2026",
    "procedureDate": "08-05-2026",
    "procedureIsoDate": "2026-05-08",
    "procedureName": "USG / CT Guided Core Needle Biopsy",
    "diagnosis": "(S) Malignant neoplasm of liver and intrahepatic bile ducts (C22)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-05088",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\geeta sems post ptbd.pdf",
    "fileName": "geeta sems post ptbd.pdf",
    "patientName": "Geeta Kirtani",
    "age": "49Y",
    "gender": "Female",
    "crNo": "010423154384056",
    "admissionNo": "A/SMSH/26/56331",
    "admissionDate": "08-05-2026",
    "dischargeDate": "13-05-2026",
    "procedureDate": "08-05-2026",
    "procedureIsoDate": "2026-05-08",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93013",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\gopal psa.pdf",
    "fileName": "gopal psa.pdf",
    "patientName": "Gopal Khatik",
    "age": "60Y",
    "gender": "Male",
    "crNo": "140224195969723",
    "admissionNo": "A/SMSH/26/65259",
    "admissionDate": "26-05-2026",
    "dischargeDate": "28-05-2026",
    "procedureDate": "26-05-2026",
    "procedureIsoDate": "2026-05-26",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other aneurysm (I72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93068",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\hamid TACE.pdf",
    "fileName": "hamid TACE.pdf",
    "patientName": "Mohammad Hamid",
    "age": "73Y",
    "gender": "Male",
    "crNo": "190821094846943",
    "admissionNo": "A/SMSH/26/54436",
    "admissionDate": "04-05-2026",
    "dischargeDate": "07-05-2026",
    "procedureDate": "04-05-2026",
    "procedureIsoDate": "2026-05-04",
    "procedureName": "Transarterial Chemoembolization (TACE)",
    "diagnosis": "(S) Liver cell carcinoma (C220)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62727",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\hpr gaurang.pdf",
    "fileName": "hpr gaurang.pdf",
    "patientName": "Hpr Gaurang",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-91202",
    "admissionNo": "A/SMSH/26/81202",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "15-05-2026",
    "procedureIsoDate": "2026-05-15",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-61036",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\leela tace.pdf",
    "fileName": "leela tace.pdf",
    "patientName": "Leela Devi",
    "age": "70Y",
    "gender": "Female",
    "crNo": "201022131310724",
    "admissionNo": "A/SMSH/26/55038",
    "admissionDate": "05-05-2026",
    "dischargeDate": "09-05-2026",
    "procedureDate": "05-05-2026",
    "procedureIsoDate": "2026-05-05",
    "procedureName": "Transarterial Chemoembolization (TACE)",
    "diagnosis": "(S) Liver cell carcinoma (C220)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93133",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\mamta kanwar hemangioma.pdf",
    "fileName": "mamta kanwar hemangioma.pdf",
    "patientName": "Mamta Kanwar",
    "age": "40Y",
    "gender": "Female",
    "crNo": "090226283791145",
    "admissionNo": "A/SMSH/26/56669",
    "admissionDate": "08-05-2026",
    "dischargeDate": "11-05-2026",
    "procedureDate": "08-05-2026",
    "procedureIsoDate": "2026-05-08",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemangioma and lymphangioma, any site (D18)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34165",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\May 2026\\manoj venaseal.pdf",
    "fileName": "manoj venaseal.pdf",
    "patientName": "Manoj Kumar Garg",
    "age": "52Y",
    "gender": "Male",
    "crNo": "080526291833172",
    "admissionNo": "A/SMSH/26/57589",
    "admissionDate": "11-05-2026",
    "dischargeDate": "14-05-2026",
    "procedureDate": "11-05-2026",
    "procedureIsoDate": "2026-05-11",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, left SSV punctured at lower leg. 7 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm proximal to the SPJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Foam sclerotherapy using polidocanol done for few varicosities in the leg.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-55971",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\Memorisation.pdf",
    "fileName": "Memorisation.pdf",
    "patientName": "Memorisation",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-67486",
    "admissionNo": "A/SMSH/26/97486",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-21969",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\PANKAJ DISCHARGE.pdf",
    "fileName": "PANKAJ DISCHARGE.pdf",
    "patientName": "Pankaj Kumar",
    "age": "16Y",
    "gender": "Male",
    "crNo": "100723166614220",
    "admissionNo": "A/SMSH/25/164684",
    "admissionDate": "31-12-2025",
    "dischargeDate": "",
    "procedureDate": "31-12-2025",
    "procedureIsoDate": "2025-12-31",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-99836",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\USG Physics Navni Garg.pdf",
    "fileName": "USG Physics Navni Garg.pdf",
    "patientName": "Usg Physics Navni Garg",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-38788",
    "admissionNo": "A/SMSH/26/88788",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-30783",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\dilip.pdf",
    "fileName": "dilip.pdf",
    "patientName": "Dilip",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-19159",
    "admissionNo": "A/SMSH/26/39159",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-92652",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\dopplerphysicsnani-170418192156.pdf",
    "fileName": "dopplerphysicsnani-170418192156.pdf",
    "patientName": "Dopplerphysicsnani",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-86077",
    "admissionNo": "A/SMSH/26/96077",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-56375",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\labreport_V_SSH_26_912321.pdf (1).pdf",
    "fileName": "labreport_V_SSH_26_912321.pdf (1).pdf",
    "patientName": "Labreport",
    "age": "45Y",
    "gender": "Male",
    "crNo": "260421060337417",
    "admissionNo": "A/SMSH/26/15504",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "13-04-2026",
    "procedureIsoDate": "2026-04-13",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-55554",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\narayan lal vv discharge.pdf",
    "fileName": "narayan lal vv discharge.pdf",
    "patientName": "Narayan Lal Jat",
    "age": "28Y",
    "gender": "Male",
    "crNo": "210224197012601",
    "admissionNo": "A/SMSH/26/12465",
    "admissionDate": "29-01-2026",
    "dischargeDate": "",
    "procedureDate": "29-01-2026",
    "procedureIsoDate": "2026-01-29",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, left SSV punctured at lower leg . 7 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm proximal to the SPJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Popliteal vein was compressible",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-25570",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\rajha discharge.pdf",
    "fileName": "rajha discharge.pdf",
    "patientName": "Rajha Singh",
    "age": "83Y",
    "gender": "Male",
    "crNo": "180320111341094",
    "admissionNo": "A/SMSH/26/07662",
    "admissionDate": "19-01-2026",
    "dischargeDate": "",
    "procedureDate": "19-01-2026",
    "procedureIsoDate": "2026-01-19",
    "procedureName": "USG / CT Guided Core Needle Biopsy",
    "diagnosis": "(S) Secondary malignant neoplasm of bone (C7951)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-46711",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\ramkishor discharge.pdf",
    "fileName": "ramkishor discharge.pdf",
    "patientName": "Ramkishor Meena",
    "age": "37Y",
    "gender": "Male",
    "crNo": "181122135414924",
    "admissionNo": "A/SMSH/26/07928",
    "admissionDate": "19-01-2026",
    "dischargeDate": "",
    "procedureDate": "19-01-2026",
    "procedureIsoDate": "2026-01-19",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with ulcer of ankle (I83023)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-90428",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\rsna (2).pdf",
    "fileName": "rsna (2).pdf",
    "patientName": "Rsna",
    "age": "45Y",
    "gender": "Male",
    "crNo": "SMS26-82642",
    "admissionNo": "A/SMSH/26/32642",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-40944",
    "filePath": "E:\\DSA SMS jaipur\\02_Discharge_Cards_and_Summaries\\Monthly_Discharges_2026\\saurabh discharge.pdf",
    "fileName": "saurabh discharge.pdf",
    "patientName": "Sourabh",
    "age": "19Y",
    "gender": "Male",
    "crNo": "260923178270004",
    "admissionNo": "A/SMSH/25/164680",
    "admissionDate": "31-12-2025",
    "dischargeDate": "",
    "procedureDate": "31-12-2025",
    "procedureIsoDate": "2025-12-31",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  }
];
