/**
 * De-identified SMS Hospital Interventional Radiology 2026 Reference Cases
 * Fully sanitized synthetic reference dataset for clinical simulation,
 * discharge workflow evaluation, and departmental analytics.
 * All patient names, registration numbers, and file paths are de-identified synthetic values.
 * Total Reference Cases: 104
 */

export interface Real2026Case {
  id: string;
  filePath?: string;
  fileName?: string;
  patientName: string;
  age: string;
  gender: 'Male' | 'Female';
  crNo: string;
  admissionNo: string;
  admissionDate: string;
  dischargeDate: string;
  procedureDate: string;
  procedureIsoDate: string; // YYYY-MM-DD for calendar & scheduler
  procedureName: string;
  diagnosis: string;
  category: string;
  operatingFaculty: string;
  procedureDetail: string;
  ward: 'Old Gastro IR Ward' | 'IR ICU';
  bedNo: string;
}

export const REAL_2026_CLINICAL_CASES: Real2026Case[] = [
  {
    "id": "SMS2026-CASE-41662",
    "filePath": "synthetic_cases/2026/case_001.pdf",
    "fileName": "case_001.pdf",
    "patientName": "Synthetic Patient 001",
    "age": "27Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-001",
    "admissionNo": "ADM-SYN-2026-001",
    "admissionDate": "12-12-2025",
    "dischargeDate": "",
    "procedureDate": "12-12-2025",
    "procedureIsoDate": "2025-12-12",
    "procedureName": "AV Fistuloplasty for Dialysis Access",
    "diagnosis": "(S) Other disorders of arteries and arterioles (I77)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-81305",
    "filePath": "synthetic_cases/2026/case_002.pdf",
    "fileName": "case_002.pdf",
    "patientName": "Synthetic Patient 002",
    "age": "24Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-002",
    "admissionNo": "ADM-SYN-2026-002",
    "admissionDate": "03-08-2026",
    "dischargeDate": "07-08-2026",
    "procedureDate": "03-08-2026",
    "procedureIsoDate": "2026-08-03",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of other sites (I86)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62566",
    "filePath": "synthetic_cases/2026/case_003.pdf",
    "fileName": "case_003.pdf",
    "patientName": "Synthetic Patient 003",
    "age": "25Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-003",
    "admissionNo": "ADM-SYN-2026-003",
    "admissionDate": "07-08-2026",
    "dischargeDate": "08-08-2026",
    "procedureDate": "07-08-2026",
    "procedureIsoDate": "2026-08-07",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Cellulitis and acute lymphangitis (L03)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-86480",
    "filePath": "synthetic_cases/2026/case_004.pdf",
    "fileName": "case_004.pdf",
    "patientName": "Synthetic Patient 004",
    "age": "62Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-004",
    "admissionNo": "ADM-SYN-2026-004",
    "admissionDate": "05-08-2026",
    "dischargeDate": "08-08-2026",
    "procedureDate": "05-08-2026",
    "procedureIsoDate": "2026-08-05",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Calculus of bile duct w/o cholangitis or cholecyst w/o obst (K8050)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-38161",
    "filePath": "synthetic_cases/2026/case_005.pdf",
    "fileName": "case_005.pdf",
    "patientName": "Synthetic Patient 005",
    "age": "18Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-005",
    "admissionNo": "ADM-SYN-2026-005",
    "admissionDate": "20-08-2026",
    "dischargeDate": "31-08-2026",
    "procedureDate": "20-08-2026",
    "procedureIsoDate": "2026-08-20",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Congenital malform of gallbladder, bile ducts and liver (Q44)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG guidance using 18 G Chiba needle, right hepatic ducts accessed. PTFE guidewire used to negotiate through the HJ Loop, and 8 fr RBC catheter placed on right sides. Catheter secured. Patient tolerated the procedure well.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34315",
    "filePath": "synthetic_cases/2026/case_006.pdf",
    "fileName": "case_006.pdf",
    "patientName": "Synthetic Patient 006",
    "age": "38Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-006",
    "admissionNo": "ADM-SYN-2026-006",
    "admissionDate": "22-08-2026",
    "dischargeDate": "25-08-2026",
    "procedureDate": "22-08-2026",
    "procedureIsoDate": "2026-08-22",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of biliary tract (K83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-74677",
    "filePath": "synthetic_cases/2026/case_007.pdf",
    "fileName": "case_007.pdf",
    "patientName": "Synthetic Patient 007",
    "age": "23Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-007",
    "admissionNo": "ADM-SYN-2026-007",
    "admissionDate": "19-08-2026",
    "dischargeDate": "21-08-2026",
    "procedureDate": "19-08-2026",
    "procedureIsoDate": "2026-08-19",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and ﬂuoro guidance, left CFA punctured and 5Fr sheath placed. . Using Cobra catheter and guidewire combination, right CIA accessed. Over the wire , the cathter was exchanged with MPA catheter and selective angiogram taken from CFA, ATA and TP trunk Large nidi were seen in the knee, ankle and foot region with supply from the popliteal artery, ATA and PTA along with early draining veins Patient tolerated the procedure well. DR ALOK VERMA",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-11022",
    "filePath": "synthetic_cases/2026/case_008.pdf",
    "fileName": "case_008.pdf",
    "patientName": "Synthetic Patient 008",
    "age": "25Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-008",
    "admissionNo": "ADM-SYN-2026-008",
    "admissionDate": "29-08-2026",
    "dischargeDate": "31-08-2026",
    "procedureDate": "29-08-2026",
    "procedureIsoDate": "2026-08-29",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other venous embolism and thrombosis (I82)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-96178",
    "filePath": "synthetic_cases/2026/case_009.pdf",
    "fileName": "case_009.pdf",
    "patientName": "Synthetic Patient 009",
    "age": "27Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-009",
    "admissionNo": "ADM-SYN-2026-009",
    "admissionDate": "12-08-2026",
    "dischargeDate": "13-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of breast (C50)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right brachial vein punctured in mid arm using 21 G needle. Wire parked in IVC. Peel away sheath placed. 5 Fr dual lumen PICC line placed with tip at RA SVC junction. Peel away sheath removed. Backﬂow checked for both lumen. Flushing done with heparinized saline. Dressing applied. Procedure uneventful. DR NARESH SIR Discharge Medications S No. Medicine Dose /Power Frequency Days Instructions 1 Ibuprofen and Paracetamol Tablets IP Ibuprofen 400 ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-21814",
    "filePath": "synthetic_cases/2026/case_010.pdf",
    "fileName": "case_010.pdf",
    "patientName": "Synthetic Patient 010",
    "age": "22Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-010",
    "admissionNo": "ADM-SYN-2026-010",
    "admissionDate": "18-08-2026",
    "dischargeDate": "19-08-2026",
    "procedureDate": "18-08-2026",
    "procedureIsoDate": "2026-08-18",
    "procedureName": "Digital Subtraction Venography",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and ﬂuoro guidance, right CFV punctured and 5Fr sheath placed. . Using Cobra catheter and guidewire combination, left renal vein accessed. Venogram taken with valsalva revealed dilated left testicular vein along with opaciﬁcation of the varicocele. Left testicular vein accessed, and using microcatheter, multiple microcoils of varying sizes used for embolisation of the caudal part of testicular vein at the level of pelvic rim. Check venogram with valsalva ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-01742",
    "filePath": "synthetic_cases/2026/case_011.pdf",
    "fileName": "case_011.pdf",
    "patientName": "Synthetic Patient 011",
    "age": "47Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-011",
    "admissionNo": "ADM-SYN-2026-011",
    "admissionDate": "18-08-2026",
    "dischargeDate": "22-08-2026",
    "procedureDate": "18-08-2026",
    "procedureIsoDate": "2026-08-18",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-07255",
    "filePath": "synthetic_cases/2026/case_012.pdf",
    "fileName": "case_012.pdf",
    "patientName": "Synthetic Patient 012",
    "age": "30Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-012",
    "admissionNo": "ADM-SYN-2026-012",
    "admissionDate": "25-08-2026",
    "dischargeDate": "25-08-2026",
    "procedureDate": "25-08-2026",
    "procedureIsoDate": "2026-08-25",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Fever of other and unknown origin (R50)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-27701",
    "filePath": "synthetic_cases/2026/case_013.pdf",
    "fileName": "case_013.pdf",
    "patientName": "Synthetic Patient 013",
    "age": "56Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-013",
    "admissionNo": "ADM-SYN-2026-013",
    "admissionDate": "12-08-2026",
    "dischargeDate": "18-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "Bronchial Artery Embolization (BAE)",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-70081",
    "filePath": "synthetic_cases/2026/case_014.pdf",
    "fileName": "case_014.pdf",
    "patientName": "Synthetic Patient 014",
    "age": "52Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-014",
    "admissionNo": "ADM-SYN-2026-014",
    "admissionDate": "12-08-2026",
    "dischargeDate": "14-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV punctured around ankle joint. 7Fr sheath placed. Venogram taken. Due to tortuosity of the vein, wire could not be negotiated. Hence access also taken in the GSV in below knee region and mid thigh. 7 Fr sheaths placed at both sites. Venaseal closure system was used and tip of the delivery catheter placed from all three sheaths. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Few ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-44180",
    "filePath": "synthetic_cases/2026/case_015.pdf",
    "fileName": "case_015.pdf",
    "patientName": "Synthetic Patient 015",
    "age": "16Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-015",
    "admissionNo": "ADM-SYN-2026-015",
    "admissionDate": "12-08-2026",
    "dischargeDate": "15-08-2026",
    "procedureDate": "12-08-2026",
    "procedureIsoDate": "2026-08-12",
    "procedureName": "AV Fistuloplasty for Dialysis Access",
    "diagnosis": "(S) Chronic kidney disease (CKD) (N18)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93993",
    "filePath": "synthetic_cases/2026/case_016.pdf",
    "fileName": "case_016.pdf",
    "patientName": "Synthetic Patient 016",
    "age": "20Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-016",
    "admissionNo": "ADM-SYN-2026-016",
    "admissionDate": "01-09-2026",
    "dischargeDate": "03-09-2026",
    "procedureDate": "01-09-2026",
    "procedureIsoDate": "2026-09-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-13371",
    "filePath": "synthetic_cases/2026/case_017.pdf",
    "fileName": "case_017.pdf",
    "patientName": "Synthetic Patient 017",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-017",
    "admissionNo": "ADM-SYN-2026-017",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Diagnostic Digital Subtraction Angiography (DSA)",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-59611",
    "filePath": "synthetic_cases/2026/case_018.pdf",
    "fileName": "case_018.pdf",
    "patientName": "Synthetic Patient 018",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-018",
    "admissionNo": "ADM-SYN-2026-018",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-02069",
    "filePath": "synthetic_cases/2026/case_019.pdf",
    "fileName": "case_019.pdf",
    "patientName": "Synthetic Patient 019",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-019",
    "admissionNo": "ADM-SYN-2026-019",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-87020",
    "filePath": "synthetic_cases/2026/case_020.pdf",
    "fileName": "case_020.pdf",
    "patientName": "Synthetic Patient 020",
    "age": "19Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-020",
    "admissionNo": "ADM-SYN-2026-020",
    "admissionDate": "27-01-2026",
    "dischargeDate": "01-05-2026",
    "procedureDate": "27-01-2026",
    "procedureIsoDate": "2026-01-27",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-40143",
    "filePath": "synthetic_cases/2026/case_021.pdf",
    "fileName": "case_021.pdf",
    "patientName": "Synthetic Patient 021",
    "age": "23Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-021",
    "admissionNo": "ADM-SYN-2026-021",
    "admissionDate": "21-01-2026",
    "dischargeDate": "22-01-2026",
    "procedureDate": "21-01-2026",
    "procedureIsoDate": "2026-01-21",
    "procedureName": "Digital Subtraction Venography",
    "diagnosis": "(S) Venous insuﬃciency (chronic) (peripheral) (I872)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-88744",
    "filePath": "synthetic_cases/2026/case_022.pdf",
    "fileName": "case_022.pdf",
    "patientName": "Synthetic Patient 022",
    "age": "46Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-022",
    "admissionNo": "ADM-SYN-2026-022",
    "admissionDate": "14-09-2026",
    "dischargeDate": "19-09-2026",
    "procedureDate": "14-09-2026",
    "procedureIsoDate": "2026-09-14",
    "procedureName": "Biliary SEMS Stenting",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-86323",
    "filePath": "synthetic_cases/2026/case_023.pdf",
    "fileName": "case_023.pdf",
    "patientName": "Synthetic Patient 023",
    "age": "23Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-023",
    "admissionNo": "ADM-SYN-2026-023",
    "admissionDate": "15-09-2026",
    "dischargeDate": "19-09-2026",
    "procedureDate": "15-09-2026",
    "procedureIsoDate": "2026-09-15",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-56120",
    "filePath": "synthetic_cases/2026/case_024.pdf",
    "fileName": "case_024.pdf",
    "patientName": "Synthetic Patient 024",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-024",
    "admissionNo": "ADM-SYN-2026-024",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Transarterial Chemoembolization (TACE)",
    "diagnosis": "tumour size, rim and non-",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-04718",
    "filePath": "synthetic_cases/2026/case_025.pdf",
    "fileName": "case_025.pdf",
    "patientName": "Synthetic Patient 025",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-025",
    "admissionNo": "ADM-SYN-2026-025",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-32318",
    "filePath": "synthetic_cases/2026/case_026.pdf",
    "fileName": "case_026.pdf",
    "patientName": "Synthetic Patient 026",
    "age": "24Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-026",
    "admissionNo": "ADM-SYN-2026-026",
    "admissionDate": "10-12-2025",
    "dischargeDate": "",
    "procedureDate": "10-12-2025",
    "procedureIsoDate": "2025-12-10",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Spontaneous abortion (O03)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-51164",
    "filePath": "synthetic_cases/2026/case_027.pdf",
    "fileName": "case_027.pdf",
    "patientName": "Synthetic Patient 027",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-027",
    "admissionNo": "ADM-SYN-2026-027",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-87733",
    "filePath": "synthetic_cases/2026/case_028.pdf",
    "fileName": "case_028.pdf",
    "patientName": "Synthetic Patient 028",
    "age": "18Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-028",
    "admissionNo": "ADM-SYN-2026-028",
    "admissionDate": "19-01-2026",
    "dischargeDate": "22-01-2026",
    "procedureDate": "19-01-2026",
    "procedureIsoDate": "2026-01-19",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of nasopharynx (D106)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-82923",
    "filePath": "synthetic_cases/2026/case_029.pdf",
    "fileName": "case_029.pdf",
    "patientName": "Synthetic Patient 029",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-029",
    "admissionNo": "ADM-SYN-2026-029",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Venous Malformation Sclerotherapy",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-80227",
    "filePath": "synthetic_cases/2026/case_030.pdf",
    "fileName": "case_030.pdf",
    "patientName": "Synthetic Patient 030",
    "age": "20Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-030",
    "admissionNo": "ADM-SYN-2026-030",
    "admissionDate": "01-08-2026",
    "dischargeDate": "03-08-2026",
    "procedureDate": "01-08-2026",
    "procedureIsoDate": "2026-08-01",
    "procedureName": "Pseudoaneurysm Coiling & Thrombin Injection",
    "diagnosis": "(S) Postpartum hemorrhage (O72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-31188",
    "filePath": "synthetic_cases/2026/case_031.pdf",
    "fileName": "case_031.pdf",
    "patientName": "Synthetic Patient 031",
    "age": "47Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-031",
    "admissionNo": "ADM-SYN-2026-031",
    "admissionDate": "13-07-2026",
    "dischargeDate": "03-08-2026",
    "procedureDate": "13-07-2026",
    "procedureIsoDate": "2026-07-13",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-44726",
    "filePath": "synthetic_cases/2026/case_032.pdf",
    "fileName": "case_032.pdf",
    "patientName": "Synthetic Patient 032",
    "age": "30Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-032",
    "admissionNo": "ADM-SYN-2026-032",
    "admissionDate": "02-06-2026",
    "dischargeDate": "04-06-2026",
    "procedureDate": "02-06-2026",
    "procedureIsoDate": "2026-06-02",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-36555",
    "filePath": "synthetic_cases/2026/case_033.pdf",
    "fileName": "case_033.pdf",
    "patientName": "Synthetic Patient 033",
    "age": "50Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-033",
    "admissionNo": "ADM-SYN-2026-033",
    "admissionDate": "20-07-2026",
    "dischargeDate": "27-07-2026",
    "procedureDate": "20-07-2026",
    "procedureIsoDate": "2026-07-20",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of liver and intrahepatic bile ducts (C22)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-73399",
    "filePath": "synthetic_cases/2026/case_034.pdf",
    "fileName": "case_034.pdf",
    "patientName": "Synthetic Patient 034",
    "age": "34Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-034",
    "admissionNo": "ADM-SYN-2026-034",
    "admissionDate": "29-06-2026",
    "dischargeDate": "04-07-2026",
    "procedureDate": "29-06-2026",
    "procedureIsoDate": "2026-06-29",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62461",
    "filePath": "synthetic_cases/2026/case_035.pdf",
    "fileName": "case_035.pdf",
    "patientName": "Synthetic Patient 035",
    "age": "55Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-035",
    "admissionNo": "ADM-SYN-2026-035",
    "admissionDate": "13-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "13-07-2026",
    "procedureIsoDate": "2026-07-13",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of liver (K76)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-03749",
    "filePath": "synthetic_cases/2026/case_036.pdf",
    "fileName": "case_036.pdf",
    "patientName": "Synthetic Patient 036",
    "age": "28Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-036",
    "admissionNo": "ADM-SYN-2026-036",
    "admissionDate": "27-07-2026",
    "dischargeDate": "29-07-2026",
    "procedureDate": "27-07-2026",
    "procedureIsoDate": "2026-07-27",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-66052",
    "filePath": "synthetic_cases/2026/case_037.pdf",
    "fileName": "case_037.pdf",
    "patientName": "Synthetic Patient 037",
    "age": "38Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-037",
    "admissionNo": "ADM-SYN-2026-037",
    "admissionDate": "30-06-2026",
    "dischargeDate": "03-07-2026",
    "procedureDate": "30-06-2026",
    "procedureIsoDate": "2026-06-30",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-18349",
    "filePath": "synthetic_cases/2026/case_038.pdf",
    "fileName": "case_038.pdf",
    "patientName": "Synthetic Patient 038",
    "age": "41Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-038",
    "admissionNo": "ADM-SYN-2026-038",
    "admissionDate": "01-07-2026",
    "dischargeDate": "03-07-2026",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other disorders of veins (I87)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-27618",
    "filePath": "synthetic_cases/2026/case_039.pdf",
    "fileName": "case_039.pdf",
    "patientName": "Synthetic Patient 039",
    "age": "71Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-039",
    "admissionNo": "ADM-SYN-2026-039",
    "admissionDate": "19-07-2026",
    "dischargeDate": "28-07-2026",
    "procedureDate": "19-07-2026",
    "procedureIsoDate": "2026-07-19",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34683",
    "filePath": "synthetic_cases/2026/case_040.pdf",
    "fileName": "case_040.pdf",
    "patientName": "Synthetic Patient 040",
    "age": "69Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-040",
    "admissionNo": "ADM-SYN-2026-040",
    "admissionDate": "06-07-2026",
    "dischargeDate": "08-07-2026",
    "procedureDate": "06-07-2026",
    "procedureIsoDate": "2026-07-06",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-20542",
    "filePath": "synthetic_cases/2026/case_041.pdf",
    "fileName": "case_041.pdf",
    "patientName": "Synthetic Patient 041",
    "age": "31Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-041",
    "admissionNo": "ADM-SYN-2026-041",
    "admissionDate": "10-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "10-07-2026",
    "procedureIsoDate": "2026-07-10",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Injury of intra-abdominal organs (S36)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-78025",
    "filePath": "synthetic_cases/2026/case_042.pdf",
    "fileName": "case_042.pdf",
    "patientName": "Synthetic Patient 042",
    "age": "46Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-042",
    "admissionNo": "ADM-SYN-2026-042",
    "admissionDate": "30-06-2026",
    "dischargeDate": "02-07-2026",
    "procedureDate": "30-06-2026",
    "procedureIsoDate": "2026-06-30",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other aneurysm (I72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-88431",
    "filePath": "synthetic_cases/2026/case_043.pdf",
    "fileName": "case_043.pdf",
    "patientName": "Synthetic Patient 043",
    "age": "20Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-043",
    "admissionNo": "ADM-SYN-2026-043",
    "admissionDate": "22-06-2026",
    "dischargeDate": "27-06-2026",
    "procedureDate": "22-06-2026",
    "procedureIsoDate": "2026-06-22",
    "procedureName": "Digital Subtraction Venography",
    "diagnosis": "(S) Scrotal varices (I861)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-47312",
    "filePath": "synthetic_cases/2026/case_044.pdf",
    "fileName": "case_044.pdf",
    "patientName": "Synthetic Patient 044",
    "age": "24Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-044",
    "admissionNo": "ADM-SYN-2026-044",
    "admissionDate": "08-06-2026",
    "dischargeDate": "10-06-2026",
    "procedureDate": "08-06-2026",
    "procedureIsoDate": "2026-06-08",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Arteriovenous malformation of vessel of lower limb (Q2732)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-52449",
    "filePath": "synthetic_cases/2026/case_045.pdf",
    "fileName": "case_045.pdf",
    "patientName": "Synthetic Patient 045",
    "age": "55Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-045",
    "admissionNo": "ADM-SYN-2026-045",
    "admissionDate": "15-06-2026",
    "dischargeDate": "18-06-2026",
    "procedureDate": "15-06-2026",
    "procedureIsoDate": "2026-06-15",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-19161",
    "filePath": "synthetic_cases/2026/case_046.pdf",
    "fileName": "case_046.pdf",
    "patientName": "Synthetic Patient 046",
    "age": "43Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-046",
    "admissionNo": "ADM-SYN-2026-046",
    "admissionDate": "22-06-2026",
    "dischargeDate": "24-06-2026",
    "procedureDate": "22-06-2026",
    "procedureIsoDate": "2026-06-22",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Acute pancreatitis (K85)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-96301",
    "filePath": "synthetic_cases/2026/case_047.pdf",
    "fileName": "case_047.pdf",
    "patientName": "Synthetic Patient 047",
    "age": "22Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-047",
    "admissionNo": "ADM-SYN-2026-047",
    "admissionDate": "13-06-2026",
    "dischargeDate": "14-06-2026",
    "procedureDate": "13-06-2026",
    "procedureIsoDate": "2026-06-13",
    "procedureName": "Diagnostic Digital Subtraction Angiography (DSA)",
    "diagnosis": "(S) Localized swelling, mass and lump, neck (R221)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-16801",
    "filePath": "synthetic_cases/2026/case_048.pdf",
    "fileName": "case_048.pdf",
    "patientName": "Synthetic Patient 048",
    "age": "62Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-048",
    "admissionNo": "ADM-SYN-2026-048",
    "admissionDate": "10-06-2026",
    "dischargeDate": "23-06-2026",
    "procedureDate": "10-06-2026",
    "procedureIsoDate": "2026-06-10",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Calculus of bile duct w/o cholangitis or cholecyst w/o obst (K8050)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-58733",
    "filePath": "synthetic_cases/2026/case_049.pdf",
    "fileName": "case_049.pdf",
    "patientName": "Synthetic Patient 049",
    "age": "63Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-049",
    "admissionNo": "ADM-SYN-2026-049",
    "admissionDate": "01-06-2026",
    "dischargeDate": "10-06-2026",
    "procedureDate": "01-06-2026",
    "procedureIsoDate": "2026-06-01",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG guidance, PTBD catheter (8 Fr) is placed in the right biliary duct system using catheter and wire. Catheter is secured. Patient tolerated the procedure well. No intra/post procedure complications seen. Manual compression bandage applied. Post procedure plan: Catheter care and outﬂow monitoring Inj. Ceftriaxone 1gm BD Inj. Pantoprazole 40mg OD Inj. Ondansetron 2cc SOS Inj. PCM /Tramadol in infusion SOS IV Fluid 60ml/hr DR AYUSH KHANDELWAL 2. 03/06 /2026 10",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-26238",
    "filePath": "synthetic_cases/2026/case_050.pdf",
    "fileName": "case_050.pdf",
    "patientName": "Synthetic Patient 050",
    "age": "29Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-050",
    "admissionNo": "ADM-SYN-2026-050",
    "admissionDate": "12-06-2026",
    "dischargeDate": "13-06-2026",
    "procedureDate": "12-06-2026",
    "procedureIsoDate": "2026-06-12",
    "procedureName": "Diagnostic Digital Subtraction Angiography (DSA)",
    "diagnosis": "(S) Hemoptysis (R042)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-86005",
    "filePath": "synthetic_cases/2026/case_051.pdf",
    "fileName": "case_051.pdf",
    "patientName": "Synthetic Patient 051",
    "age": "14Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-051",
    "admissionNo": "ADM-SYN-2026-051",
    "admissionDate": "26-06-2026",
    "dischargeDate": "30-06-2026",
    "procedureDate": "26-06-2026",
    "procedureIsoDate": "2026-06-26",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of nasopharynx (D106)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition USG and ﬂuoroscopy guidance, Right CFA access taken with 18 G needle and 5 F sheath placed. With the help of 5 Fr AR catheter, right CCA, ECA and ICA run were performed in AP and lateral views which revealed abnormal blush from internal maxillary artery branch of right ECA and mild blush from right ICA. After superselective cannulation of IMA using microcatheter, embolisation of culprit branches done using 355-500 micron PVA particles. Post embolization right ECA r",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-59064",
    "filePath": "synthetic_cases/2026/case_052.pdf",
    "fileName": "case_052.pdf",
    "patientName": "Synthetic Patient 052",
    "age": "48Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-052",
    "admissionNo": "ADM-SYN-2026-052",
    "admissionDate": "13-06-2026",
    "dischargeDate": "16-06-2026",
    "procedureDate": "13-06-2026",
    "procedureIsoDate": "2026-06-13",
    "procedureName": "Venous Malformation Sclerotherapy",
    "diagnosis": "(S) Varicose veins of right lower extremity with pain (I83811)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and ﬂuoro guidance, varicosities in the right leg punctured and venogram taken which revealed dilated varicosities. Sclerotherapy done using 3 cc foam preparation of polidocanol . Ablation of one of the perforator in lower leg was also done Procedure uneventful. Bandage applied DR NARESH MANGALHARA, DR ALOK VERMA Discharge Medications [Page 2] Patient Discharge Details General Advise",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-05269",
    "filePath": "synthetic_cases/2026/case_053.pdf",
    "fileName": "case_053.pdf",
    "patientName": "Synthetic Patient 053",
    "age": "17Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-053",
    "admissionNo": "ADM-SYN-2026-053",
    "admissionDate": "02-06-2026",
    "dischargeDate": "05-06-2026",
    "procedureDate": "02-06-2026",
    "procedureIsoDate": "2026-06-02",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Arteriovenous malformation, other site (Q2739)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-35399",
    "filePath": "synthetic_cases/2026/case_054.pdf",
    "fileName": "case_054.pdf",
    "patientName": "Synthetic Patient 054",
    "age": "14Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-054",
    "admissionNo": "ADM-SYN-2026-054",
    "admissionDate": "09-06-2026",
    "dischargeDate": "24-06-2026",
    "procedureDate": "09-06-2026",
    "procedureIsoDate": "2026-06-09",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of nasopharynx (D106)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-20520",
    "filePath": "synthetic_cases/2026/case_055.pdf",
    "fileName": "case_055.pdf",
    "patientName": "Synthetic Patient 055",
    "age": "14Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-055",
    "admissionNo": "ADM-SYN-2026-055",
    "admissionDate": "29-05-2026",
    "dischargeDate": "03-06-2026",
    "procedureDate": "29-05-2026",
    "procedureIsoDate": "2026-05-29",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-59807",
    "filePath": "synthetic_cases/2026/case_056.pdf",
    "fileName": "case_056.pdf",
    "patientName": "Synthetic Patient 056",
    "age": "39Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-056",
    "admissionNo": "ADM-SYN-2026-056",
    "admissionDate": "04-06-2026",
    "dischargeDate": "08-06-2026",
    "procedureDate": "04-06-2026",
    "procedureIsoDate": "2026-06-04",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, left GSV punctured in lower thigh. 8 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Sclerotherapy done for few varicosities in the lower leg using foam polidocanol",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-19984",
    "filePath": "synthetic_cases/2026/case_057.pdf",
    "fileName": "case_057.pdf",
    "patientName": "Synthetic Patient 057",
    "age": "29Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-057",
    "admissionNo": "ADM-SYN-2026-057",
    "admissionDate": "06-06-2026",
    "dischargeDate": "09-06-2026",
    "procedureDate": "06-06-2026",
    "procedureIsoDate": "2026-06-06",
    "procedureName": "Arteriovenous Malformation (AVM) Sclerotherapy / Embolization",
    "diagnosis": "(S) Arteriovenous malformation of vessel of lower limb (Q2732)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and ﬂuoro guidance, right CFA access taken. Access was obtained with 18 G needle and 5 F sheath placed. 3500 units of heparin administered Using C 1 catheter, left CIA catheterised and Angiogram taken in AP and oblique views which revealed abnormal blush from posterior division of left internal iliac artery and opaciﬁcation of early venous drainage. Superselective cannulation of superior gluteal artery done using microcatheter. Embolisation done using glu",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-97353",
    "filePath": "synthetic_cases/2026/case_058.pdf",
    "fileName": "case_058.pdf",
    "patientName": "Synthetic Patient 058",
    "age": "25Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-058",
    "admissionNo": "ADM-SYN-2026-058",
    "admissionDate": "23-06-2026",
    "dischargeDate": "27-06-2026",
    "procedureDate": "23-06-2026",
    "procedureIsoDate": "2026-06-23",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of right lower extremity with pain (I83811)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV punctured around knee joint. 7Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Foam sclerotherapy using polidocanol done for few varicosities and perforator in the leg.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-32238",
    "filePath": "synthetic_cases/2026/case_059.pdf",
    "fileName": "case_059.pdf",
    "patientName": "Synthetic Patient 059",
    "age": "55Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-059",
    "admissionNo": "ADM-SYN-2026-059",
    "admissionDate": "23-06-2026",
    "dischargeDate": "30-06-2026",
    "procedureDate": "23-06-2026",
    "procedureIsoDate": "2026-06-23",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Obstruction of bile duct (K831)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-68631",
    "filePath": "synthetic_cases/2026/case_060.pdf",
    "fileName": "case_060.pdf",
    "patientName": "Synthetic Patient 060",
    "age": "31Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-060",
    "admissionNo": "ADM-SYN-2026-060",
    "admissionDate": "15-07-2026",
    "dischargeDate": "20-07-2026",
    "procedureDate": "15-07-2026",
    "procedureIsoDate": "2026-07-15",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Superﬁcial injury of head (S00)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93148",
    "filePath": "synthetic_cases/2026/case_061.pdf",
    "fileName": "case_061.pdf",
    "patientName": "Synthetic Patient 061",
    "age": "19Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-061",
    "admissionNo": "ADM-SYN-2026-061",
    "admissionDate": "14-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "14-07-2026",
    "procedureIsoDate": "2026-07-14",
    "procedureName": "Central Venoplasty with Balloon Dilation",
    "diagnosis": "(S) Congenital malformations of great veins (Q26)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and ﬂuoro guidance, Right femoral vein access taken with 18 G needle and 5F sheath placed. With the help of 5Fr MPA catheter, venogram revealed occlusion of IVC near RA-IVC junction. Sheath exchanged for 11 Fr sheath and attempts were made to cross the occlusion using multiple guidewires and catheter combination but could not be crossed. Under strict aseptic condition under USG and ﬂuoro guidance, Right internal jugular vein access taken with 18 G needle ",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-70792",
    "filePath": "synthetic_cases/2026/case_062.pdf",
    "fileName": "case_062.pdf",
    "patientName": "Synthetic Patient 062",
    "age": "37Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-062",
    "admissionNo": "ADM-SYN-2026-062",
    "admissionDate": "15-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "15-07-2026",
    "procedureIsoDate": "2026-07-15",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other congenital malformations of peripheral vascular system (Q27)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-65675",
    "filePath": "synthetic_cases/2026/case_063.pdf",
    "fileName": "case_063.pdf",
    "patientName": "Synthetic Patient 063",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-063",
    "admissionNo": "ADM-SYN-2026-063",
    "admissionDate": "24-07-2026",
    "dischargeDate": "25-07-2026",
    "procedureDate": "24-07-2026",
    "procedureIsoDate": "2026-07-24",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-99135",
    "filePath": "synthetic_cases/2026/case_064.pdf",
    "fileName": "case_064.pdf",
    "patientName": "Synthetic Patient 064",
    "age": "29Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-064",
    "admissionNo": "ADM-SYN-2026-064",
    "admissionDate": "06-07-2026",
    "dischargeDate": "08-07-2026",
    "procedureDate": "06-07-2026",
    "procedureIsoDate": "2026-07-06",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-92299",
    "filePath": "synthetic_cases/2026/case_065.pdf",
    "fileName": "case_065.pdf",
    "patientName": "Synthetic Patient 065",
    "age": "62Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-065",
    "admissionNo": "ADM-SYN-2026-065",
    "admissionDate": "28-07-2026",
    "dischargeDate": "30-07-2026",
    "procedureDate": "28-07-2026",
    "procedureIsoDate": "2026-07-28",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of liver (K76)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-12833",
    "filePath": "synthetic_cases/2026/case_066.pdf",
    "fileName": "case_066.pdf",
    "patientName": "Synthetic Patient 066",
    "age": "73Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-066",
    "admissionNo": "ADM-SYN-2026-066",
    "admissionDate": "01-07-2026",
    "dischargeDate": "06-07-2026",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Malignant neoplasm of liver and intrahepatic bile ducts (C22)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-87268",
    "filePath": "synthetic_cases/2026/case_067.pdf",
    "fileName": "case_067.pdf",
    "patientName": "Synthetic Patient 067",
    "age": "32Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-067",
    "admissionNo": "ADM-SYN-2026-067",
    "admissionDate": "28-07-2026",
    "dischargeDate": "30-07-2026",
    "procedureDate": "28-07-2026",
    "procedureIsoDate": "2026-07-28",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-81106",
    "filePath": "synthetic_cases/2026/case_068.pdf",
    "fileName": "case_068.pdf",
    "patientName": "Synthetic Patient 068",
    "age": "34Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-068",
    "admissionNo": "ADM-SYN-2026-068",
    "admissionDate": "22-07-2026",
    "dischargeDate": "23-07-2026",
    "procedureDate": "22-07-2026",
    "procedureIsoDate": "2026-07-22",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV punctured around ankle joint. 7Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Few perforators were ablated along SSV in leg. Foam sclerotherapy using polidocanol done for few varicosities in the leg.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-77209",
    "filePath": "synthetic_cases/2026/case_069.pdf",
    "fileName": "case_069.pdf",
    "patientName": "Synthetic Patient 069",
    "age": "23Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-069",
    "admissionNo": "ADM-SYN-2026-069",
    "admissionDate": "17-07-2026",
    "dischargeDate": "22-07-2026",
    "procedureDate": "17-07-2026",
    "procedureIsoDate": "2026-07-17",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of other sites (I86)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-13465",
    "filePath": "synthetic_cases/2026/case_070.pdf",
    "fileName": "case_070.pdf",
    "patientName": "Synthetic Patient 070",
    "age": "43Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-070",
    "admissionNo": "ADM-SYN-2026-070",
    "admissionDate": "23-07-2026",
    "dischargeDate": "25-07-2026",
    "procedureDate": "23-07-2026",
    "procedureIsoDate": "2026-07-23",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62503",
    "filePath": "synthetic_cases/2026/case_071.pdf",
    "fileName": "case_071.pdf",
    "patientName": "Synthetic Patient 071",
    "age": "37Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-071",
    "admissionNo": "ADM-SYN-2026-071",
    "admissionDate": "27-07-2026",
    "dischargeDate": "31-07-2026",
    "procedureDate": "27-07-2026",
    "procedureIsoDate": "2026-07-27",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-50462",
    "filePath": "synthetic_cases/2026/case_072.pdf",
    "fileName": "case_072.pdf",
    "patientName": "Synthetic Patient 072",
    "age": "54Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-072",
    "admissionNo": "ADM-SYN-2026-072",
    "admissionDate": "03-07-2026",
    "dischargeDate": "06-07-2026",
    "procedureDate": "03-07-2026",
    "procedureIsoDate": "2026-07-03",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right GSV and SSV punctured around ankle 7Fr sheaths placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SFJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Foam sclerotherapy using polidocanol done for few varicosities in the leg. 7Fr sheaths placed in SSV. Venogram taken. Venaseal closure system was used and tip of the del",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-77583",
    "filePath": "synthetic_cases/2026/case_073.pdf",
    "fileName": "case_073.pdf",
    "patientName": "Synthetic Patient 073",
    "age": "31Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-073",
    "admissionNo": "ADM-SYN-2026-073",
    "admissionDate": "23-07-2026",
    "dischargeDate": "24-07-2026",
    "procedureDate": "23-07-2026",
    "procedureIsoDate": "2026-07-23",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemorrhage in early pregnancy (O20)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-40344",
    "filePath": "synthetic_cases/2026/case_074.pdf",
    "fileName": "case_074.pdf",
    "patientName": "Synthetic Patient 074",
    "age": "28Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-074",
    "admissionNo": "ADM-SYN-2026-074",
    "admissionDate": "16-07-2026",
    "dischargeDate": "21-07-2026",
    "procedureDate": "16-07-2026",
    "procedureIsoDate": "2026-07-16",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62511",
    "filePath": "synthetic_cases/2026/case_075.pdf",
    "fileName": "case_075.pdf",
    "patientName": "Synthetic Patient 075",
    "age": "24Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-075",
    "admissionNo": "ADM-SYN-2026-075",
    "admissionDate": "16-07-2026",
    "dischargeDate": "21-07-2026",
    "procedureDate": "16-07-2026",
    "procedureIsoDate": "2026-07-16",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Varicose veins of other sites (I86)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-67327",
    "filePath": "synthetic_cases/2026/case_076.pdf",
    "fileName": "case_076.pdf",
    "patientName": "Synthetic Patient 076",
    "age": "44Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-076",
    "admissionNo": "ADM-SYN-2026-076",
    "admissionDate": "14-07-2026",
    "dischargeDate": "18-07-2026",
    "procedureDate": "14-07-2026",
    "procedureIsoDate": "2026-07-14",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other aneurysm (I72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-71937",
    "filePath": "synthetic_cases/2026/case_077.pdf",
    "fileName": "case_077.pdf",
    "patientName": "Synthetic Patient 077",
    "age": "30Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-077",
    "admissionNo": "ADM-SYN-2026-077",
    "admissionDate": "13-07-2026",
    "dischargeDate": "16-07-2026",
    "procedureDate": "13-07-2026",
    "procedureIsoDate": "2026-07-13",
    "procedureName": "Central Venoplasty with Balloon Dilation",
    "diagnosis": "(S) Other venous embolism and thrombosis (I82)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition under USG and ﬂuoro guidance, Right femoral vein access taken with 18 G needle and 5F sheath placed. With the help of 5Fr MPA catheter, venogram revealed stenosis of the inferior vena cava near IVC-RA junction. 8 Fr long sheath exchanged and the stenosis was crossed using help of multiple guidewires and MPA catheter. IV Heparin administered prior to dilation of the narrowing using balloons of size (12x40 mm, 16x40mm, 18x40mm and 20x40mm) over stiﬀ guidewire. Post v",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-73518",
    "filePath": "synthetic_cases/2026/case_078.pdf",
    "fileName": "case_078.pdf",
    "patientName": "Synthetic Patient 078",
    "age": "48Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-078",
    "admissionNo": "ADM-SYN-2026-078",
    "admissionDate": "03-07-2026",
    "dischargeDate": "04-07-2026",
    "procedureDate": "03-07-2026",
    "procedureIsoDate": "2026-07-03",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Unspeciﬁed lump in breast (N63)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34671",
    "filePath": "synthetic_cases/2026/case_079.pdf",
    "fileName": "case_079.pdf",
    "patientName": "Synthetic Patient 079",
    "age": "43Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-079",
    "admissionNo": "ADM-SYN-2026-079",
    "admissionDate": "06-07-2026",
    "dischargeDate": "07-07-2026",
    "procedureDate": "06-07-2026",
    "procedureIsoDate": "2026-07-06",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Fever of other and unknown origin (R50)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-68873",
    "filePath": "synthetic_cases/2026/case_080.pdf",
    "fileName": "case_080.pdf",
    "patientName": "Synthetic Patient 080",
    "age": "51Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-080",
    "admissionNo": "ADM-SYN-2026-080",
    "admissionDate": "08-12-2025",
    "dischargeDate": "",
    "procedureDate": "08-12-2025",
    "procedureIsoDate": "2025-12-08",
    "procedureName": "Bronchial Artery Embolization (BAE)",
    "diagnosis": "(S) Hemorrhage from respiratory passages (R04)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-49654",
    "filePath": "synthetic_cases/2026/case_081.pdf",
    "fileName": "case_081.pdf",
    "patientName": "Synthetic Patient 081",
    "age": "58Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-081",
    "admissionNo": "ADM-SYN-2026-081",
    "admissionDate": "02-12-2025",
    "dischargeDate": "",
    "procedureDate": "02-12-2025",
    "procedureIsoDate": "2025-12-02",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemangioma and lymphangioma, any site (D18)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-58595",
    "filePath": "synthetic_cases/2026/case_082.pdf",
    "fileName": "case_082.pdf",
    "patientName": "Synthetic Patient 082",
    "age": "33Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-082",
    "admissionNo": "ADM-SYN-2026-082",
    "admissionDate": "30-04-2026",
    "dischargeDate": "02-05-2026",
    "procedureDate": "30-04-2026",
    "procedureIsoDate": "2026-04-30",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Acute embolism and thrombosis of superﬁc vn unsp up extrem (I82619)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-47355",
    "filePath": "synthetic_cases/2026/case_083.pdf",
    "fileName": "case_083.pdf",
    "patientName": "Synthetic Patient 083",
    "age": "60Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-083",
    "admissionNo": "ADM-SYN-2026-083",
    "admissionDate": "14-05-2026",
    "dischargeDate": "16-05-2026",
    "procedureDate": "14-05-2026",
    "procedureIsoDate": "2026-05-14",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, right SSV punctured at mid leg. 7 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm caudal to the SPJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-29388",
    "filePath": "synthetic_cases/2026/case_084.pdf",
    "fileName": "case_084.pdf",
    "patientName": "Synthetic Patient 084",
    "age": "37Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-084",
    "admissionNo": "ADM-SYN-2026-084",
    "admissionDate": "04-05-2026",
    "dischargeDate": "07-05-2026",
    "procedureDate": "04-05-2026",
    "procedureIsoDate": "2026-05-04",
    "procedureName": "Central Venoplasty with Balloon Dilation",
    "diagnosis": "(S) Other disorders of veins (I87)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-42722",
    "filePath": "synthetic_cases/2026/case_085.pdf",
    "fileName": "case_085.pdf",
    "patientName": "Synthetic Patient 085",
    "age": "38Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-085",
    "admissionNo": "ADM-SYN-2026-085",
    "admissionDate": "01-05-2026",
    "dischargeDate": "04-05-2026",
    "procedureDate": "01-05-2026",
    "procedureIsoDate": "2026-05-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other diseases of biliary tract (K83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-12041",
    "filePath": "synthetic_cases/2026/case_086.pdf",
    "fileName": "case_086.pdf",
    "patientName": "Synthetic Patient 086",
    "age": "36Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-086",
    "admissionNo": "ADM-SYN-2026-086",
    "admissionDate": "08-05-2026",
    "dischargeDate": "11-05-2026",
    "procedureDate": "08-05-2026",
    "procedureIsoDate": "2026-05-08",
    "procedureName": "USG / CT Guided Core Needle Biopsy",
    "diagnosis": "(S) Malignant neoplasm of liver and intrahepatic bile ducts (C22)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-05088",
    "filePath": "synthetic_cases/2026/case_087.pdf",
    "fileName": "case_087.pdf",
    "patientName": "Synthetic Patient 087",
    "age": "49Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-087",
    "admissionNo": "ADM-SYN-2026-087",
    "admissionDate": "08-05-2026",
    "dischargeDate": "13-05-2026",
    "procedureDate": "08-05-2026",
    "procedureIsoDate": "2026-05-08",
    "procedureName": "Percutaneous Transhepatic Biliary Drainage (PTBD)",
    "diagnosis": "(S) Malignant neoplasm of gallbladder (C23)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93013",
    "filePath": "synthetic_cases/2026/case_088.pdf",
    "fileName": "case_088.pdf",
    "patientName": "Synthetic Patient 088",
    "age": "60Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-088",
    "admissionNo": "ADM-SYN-2026-088",
    "admissionDate": "26-05-2026",
    "dischargeDate": "28-05-2026",
    "procedureDate": "26-05-2026",
    "procedureIsoDate": "2026-05-26",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Other aneurysm (I72)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93068",
    "filePath": "synthetic_cases/2026/case_089.pdf",
    "fileName": "case_089.pdf",
    "patientName": "Synthetic Patient 089",
    "age": "73Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-089",
    "admissionNo": "ADM-SYN-2026-089",
    "admissionDate": "04-05-2026",
    "dischargeDate": "07-05-2026",
    "procedureDate": "04-05-2026",
    "procedureIsoDate": "2026-05-04",
    "procedureName": "Transarterial Chemoembolization (TACE)",
    "diagnosis": "(S) Liver cell carcinoma (C220)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-62727",
    "filePath": "synthetic_cases/2026/case_090.pdf",
    "fileName": "case_090.pdf",
    "patientName": "Synthetic Patient 090",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-090",
    "admissionNo": "ADM-SYN-2026-090",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "15-05-2026",
    "procedureIsoDate": "2026-05-15",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-61036",
    "filePath": "synthetic_cases/2026/case_091.pdf",
    "fileName": "case_091.pdf",
    "patientName": "Synthetic Patient 091",
    "age": "70Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-091",
    "admissionNo": "ADM-SYN-2026-091",
    "admissionDate": "05-05-2026",
    "dischargeDate": "09-05-2026",
    "procedureDate": "05-05-2026",
    "procedureIsoDate": "2026-05-05",
    "procedureName": "Transarterial Chemoembolization (TACE)",
    "diagnosis": "(S) Liver cell carcinoma (C220)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-93133",
    "filePath": "synthetic_cases/2026/case_092.pdf",
    "fileName": "case_092.pdf",
    "patientName": "Synthetic Patient 092",
    "age": "40Y",
    "gender": "Female",
    "crNo": "CR-SYN-2026-092",
    "admissionNo": "ADM-SYN-2026-092",
    "admissionDate": "08-05-2026",
    "dischargeDate": "11-05-2026",
    "procedureDate": "08-05-2026",
    "procedureIsoDate": "2026-05-08",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "(S) Hemangioma and lymphangioma, any site (D18)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-34165",
    "filePath": "synthetic_cases/2026/case_093.pdf",
    "fileName": "case_093.pdf",
    "patientName": "Synthetic Patient 093",
    "age": "52Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-093",
    "admissionNo": "ADM-SYN-2026-093",
    "admissionDate": "11-05-2026",
    "dischargeDate": "14-05-2026",
    "procedureDate": "11-05-2026",
    "procedureIsoDate": "2026-05-11",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of lower extremities (I83)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, left SSV punctured at lower leg. 7 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm proximal to the SPJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Foam sclerotherapy using polidocanol done for few varicosities in the leg.",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-55971",
    "filePath": "synthetic_cases/2026/case_094.pdf",
    "fileName": "case_094.pdf",
    "patientName": "Synthetic Patient 094",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-094",
    "admissionNo": "ADM-SYN-2026-094",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-21969",
    "filePath": "synthetic_cases/2026/case_095.pdf",
    "fileName": "case_095.pdf",
    "patientName": "Synthetic Patient 095",
    "age": "16Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-095",
    "admissionNo": "ADM-SYN-2026-095",
    "admissionDate": "31-12-2025",
    "dischargeDate": "",
    "procedureDate": "31-12-2025",
    "procedureIsoDate": "2025-12-31",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-99836",
    "filePath": "synthetic_cases/2026/case_096.pdf",
    "fileName": "case_096.pdf",
    "patientName": "Synthetic Patient 096",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-096",
    "admissionNo": "ADM-SYN-2026-096",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-30783",
    "filePath": "synthetic_cases/2026/case_097.pdf",
    "fileName": "case_097.pdf",
    "patientName": "Synthetic Patient 097",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-097",
    "admissionNo": "ADM-SYN-2026-097",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-92652",
    "filePath": "synthetic_cases/2026/case_098.pdf",
    "fileName": "case_098.pdf",
    "patientName": "Synthetic Patient 098",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-098",
    "admissionNo": "ADM-SYN-2026-098",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-56375",
    "filePath": "synthetic_cases/2026/case_099.pdf",
    "fileName": "case_099.pdf",
    "patientName": "Synthetic Patient 099",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-099",
    "admissionNo": "ADM-SYN-2026-099",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "13-04-2026",
    "procedureIsoDate": "2026-04-13",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-55554",
    "filePath": "synthetic_cases/2026/case_100.pdf",
    "fileName": "case_100.pdf",
    "patientName": "Synthetic Patient 100",
    "age": "28Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-100",
    "admissionNo": "ADM-SYN-2026-100",
    "admissionDate": "29-01-2026",
    "dischargeDate": "",
    "procedureDate": "29-01-2026",
    "procedureIsoDate": "2026-01-29",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with pain (I83812)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "Under strict aseptic condition, under USG guidance, left SSV punctured at lower leg . 7 Fr sheath placed. Venogram taken. Venaseal closure system was used and tip of the delivery catheter placed 5 cm proximal to the SPJ. Glue embolisation done. Post procedure ultrasound revealed glue cast with resulting non compressibility. Popliteal vein was compressible",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-25570",
    "filePath": "synthetic_cases/2026/case_101.pdf",
    "fileName": "case_101.pdf",
    "patientName": "Synthetic Patient 101",
    "age": "83Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-101",
    "admissionNo": "ADM-SYN-2026-101",
    "admissionDate": "19-01-2026",
    "dischargeDate": "",
    "procedureDate": "19-01-2026",
    "procedureIsoDate": "2026-01-19",
    "procedureName": "USG / CT Guided Core Needle Biopsy",
    "diagnosis": "(S) Secondary malignant neoplasm of bone (C7951)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-46711",
    "filePath": "synthetic_cases/2026/case_102.pdf",
    "fileName": "case_102.pdf",
    "patientName": "Synthetic Patient 102",
    "age": "37Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-102",
    "admissionNo": "ADM-SYN-2026-102",
    "admissionDate": "19-01-2026",
    "dischargeDate": "",
    "procedureDate": "19-01-2026",
    "procedureIsoDate": "2026-01-19",
    "procedureName": "Endovenous Cyanoacrylate Embolization (VenaSeal)",
    "diagnosis": "(S) Varicose veins of left lower extremity with ulcer of ankle (I83023)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-90428",
    "filePath": "synthetic_cases/2026/case_103.pdf",
    "fileName": "case_103.pdf",
    "patientName": "Synthetic Patient 103",
    "age": "45Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-103",
    "admissionNo": "ADM-SYN-2026-103",
    "admissionDate": "",
    "dischargeDate": "",
    "procedureDate": "01-07-2026",
    "procedureIsoDate": "2026-07-01",
    "procedureName": "Interventional Radiology Procedure",
    "diagnosis": "",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Naresh Mangalhara (Associate Professor)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  },
  {
    "id": "SMS2026-CASE-40944",
    "filePath": "synthetic_cases/2026/case_104.pdf",
    "fileName": "case_104.pdf",
    "patientName": "Synthetic Patient 104",
    "age": "19Y",
    "gender": "Male",
    "crNo": "CR-SYN-2026-104",
    "admissionNo": "ADM-SYN-2026-104",
    "admissionDate": "31-12-2025",
    "dischargeDate": "",
    "procedureDate": "31-12-2025",
    "procedureIsoDate": "2025-12-31",
    "procedureName": "Juvenile Nasopharyngeal Angiofibroma (JNA) Embolization",
    "diagnosis": "(S) Benign neoplasm of mouth and pharynx (D10)",
    "category": "Interventional Radiology",
    "operatingFaculty": "Dr. Meenu Bagarhatta (Sr. Prof & Head)",
    "procedureDetail": "",
    "ward": "Old Gastro IR Ward",
    "bedNo": "Bed 01"
  }
];
