import { MasterProcedure } from './types';

/**
 * Category 05: Aortic & Great Vessels (4 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_05_AORTIC: MasterProcedure[] = [
  {
    id: 'cat05-tevar-aneurysm',
    categoryNumber: 5,
    categoryName: 'Aortic & Great Vessels',
    title: 'Thoracic Endovascular Aortic Repair (TEVAR) for Descending Thoracic Aneurysm',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Thoracic Endovascular Aortic Repair (TEVAR)',
      packageCode: '1849-VS006A',
      icd10: 'I71.2',
      tariffInr: 85000,
    },
    modality: 'XA',
    targetAnatomy: ["Descending Thoracic Aorta", "Aortic Arch"],
    sedation: 'General Anesthesia or Deep Sedation',
    accessSiteDefault: 'Right Common Femoral Artery via surgical cutdown or bilateral ProGlide Pre-close',
    sheathDefault: '20F - 24F Large Bore Sheath (DrySeal)',
    cathetersAndWires: '0.035" Lunderquist Extra Stiff wire, 5F Pigtail, Gore TAG / Medtronic Valiant Stent-Graft (28-42mm)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Thoracic Stent-Graft Endoprosthesis (34mm x 150mm)',
    proceduralNarrativeTemplate:
      'Patient supine under general anesthesia with CSF drain in place. Bilateral CFA accessed; right CFA pre-closed with dual ProGlide sutures. 5F pigtail positioned in ascending aorta from left CFA. Aortography sized aneurysm and confirmed landing zones (distal to left subclavian artery). 0.035" Lunderquist wire placed in ascending aorta. Thoracic stent-graft advanced and deployed under induced hypotension (SBP <80 mmHg) ensuring precise landing. Balloon moulding performed. Completion aortogram demonstrated total aneurysm exclusion, widely patent LSA, and zero endoleak. Pre-close sutures tied achieving complete femoral hemostasis.',
    postOpCare: {
      immobilizationHours: 8,
      immobilizationInstructions: 'Strict supine flat bedrest x 8 hours; maintain MAP 85-90 mmHg to ensure spinal cord perfusion.',
      hematomaChecks: 'Check bilateral femoral access sites, neuro checks (lower limb motor/sensory), and distal pulses q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'CT Angiography of Thorax at 1 month to confirm complete aneurysm exclusion.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr; maintain CSF drainage pressure <10 mmHg if drain in place.',
      medications: ["Tab Aspirin 75mg OD", "IV Cefuroxime 1.5g BD x 24h", "Strict Blood Pressure control (Beta-blockers)"],
      redFlags: ["Spinal cord ischemia / paraplegia", "Stroke / neurological deficit", "Type I endoleak / aortic rupture", "Femoral thrombosis"],
    },
    consentId: 'consent-tevar-aorta',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat05-tevar-dissection',
    categoryNumber: 5,
    categoryName: 'Aortic & Great Vessels',
    title: 'TEVAR for Complicated Acute Type B Aortic Dissection',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Thoracic Endovascular Aortic Repair (TEVAR)',
      packageCode: '1849-VS006A',
      icd10: 'I71.0',
      tariffInr: 85000,
    },
    modality: 'XA',
    targetAnatomy: ["Descending Thoracic Aorta True Lumen", "Primary Entry Tear"],
    sedation: 'General Anesthesia or Deep Sedation',
    accessSiteDefault: 'Right CFA (Pre-close) + Left Brachial / Radial access for roadmapping',
    sheathDefault: '20F - 22F Sheath',
    cathetersAndWires: '0.035" Lunderquist wire, intravascular ultrasound (IVUS), tapered thoracic stent-graft',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Thoracic Stent-Graft (30-34mm x 160mm tapered)',
    proceduralNarrativeTemplate:
      'Indicated for acute complicated Type B dissection (refractory pain, malperfusion, rapid expansion). Left radial pigtail placed for continuous true lumen monitoring. IVUS confirmed guidewire exclusively in true lumen throughout aorta. Thoracic stent-graft deployed across primary proximal entry tear under controlled hypotension. True lumen expanded with immediate restoration of visceral branch perfusion and decompression of false lumen. No distal ballooning performed to prevent intimal tear propagation. Femoral hemostasis achieved.',
    postOpCare: {
      immobilizationHours: 8,
      immobilizationInstructions: 'Strict supine bedrest x 8 hours. Strict SBP target <120 mmHg.',
      hematomaChecks: 'Monitor bilateral femoral sites, distal pulses, and lower limb power q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Post-op CTA Chest/Abdomen at 5 days to assess true lumen expansion.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["IV Labetalol / Nicardipine infusion for tight BP control", "Tab Aspirin 75mg OD"],
      redFlags: ["Retrograde Type A dissection", "Paraplegia", "Visceral malperfusion"],
    },
    consentId: 'consent-tevar-aorta',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat05-evar-aaa',
    categoryNumber: 5,
    categoryName: 'Aortic & Great Vessels',
    title: 'Endovascular Aneurysm Repair (EVAR) for Infrarenal Abdominal Aortic Aneurysm (AAA)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Endovascular Aneurysm Repair (EVAR)',
      packageCode: '1849-VS007A',
      icd10: 'I71.4',
      tariffInr: 80000,
    },
    modality: 'XA',
    targetAnatomy: ["Infrarenal Abdominal Aorta", "Bilateral Common Iliac Arteries"],
    sedation: 'General Anesthesia or Deep Sedation',
    accessSiteDefault: 'Bilateral CFA access (Percutaneous Pre-Close with Perclose ProStyle)',
    sheathDefault: '16F - 18F Main Device Sheath + 12F - 14F Contralateral Sheath',
    cathetersAndWires: '0.035" Lunderquist wires, 5F pigtail, bifurcated modular endograft (Medtronic Endurant / Gore Excluder / Cook Zenith)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Bifurcated Aortic Endograft System (Main Body + Contralateral Limb)',
    proceduralNarrativeTemplate:
      'Bilateral percutaneous CFA access with dual ProStyle devices. Diagnostic pigtail in upper abdominal aorta. Sizing aortography identified renal artery origins and aortic neck. 0.035" Lunderquist wire placed. Main bifurcated stent-graft deployed precisely infrarenal without compromising lowest renal artery. Contralateral gate cannulated and confirmed on orthogonal views. Contralateral iliac limb deployed overlapping main body. Stent junctions and landing zones moulded with compliant Coda balloon. Completion aortogram demonstrated complete AAA exclusion, brisk bilateral iliac flow, patent renal arteries, and zero Type I/III endoleaks. Pre-close sutures deployed achieving immediate hemostasis.',
    postOpCare: {
      immobilizationHours: 8,
      immobilizationInstructions: 'Strict flat bedrest x 8 hours; bilateral legs immobilized.',
      hematomaChecks: 'Check bilateral groins for hematoma, pulsatile mass, or distal ischemia q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Doppler USG at 24 hours; Triphasic CTA Abdomen at 1 month to exclude endoleak.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Tab Aspirin 75mg OD", "Tab Atorvastatin 40mg HS"],
      redFlags: ["Type IA / IB Endoleak", "Acute limb thrombosis", "Renal artery occlusion", "Groin hematoma"],
    },
    consentId: 'consent-evar-aorta',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat05-type2-endoleak-translumbar',
    categoryNumber: 5,
    categoryName: 'Aortic & Great Vessels',
    title: 'Type II Endoleak Direct Translumbar Sac Puncture & Embolization',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transcatheter Embolization',
      packageCode: '1849-IN063A',
      icd10: 'I77.0',
      tariffInr: 35000,
    },
    modality: 'XA',
    targetAnatomy: ["Aneurysm Sac", "Lumbar Arteries", "Inferior Mesenteric Artery"],
    sedation: 'General Anesthesia or Deep Sedation',
    accessSiteDefault: 'Left Translumbar Percutaneous Approach under CT / Fluoroscopy',
    sheathDefault: '4F - 5F Sheath',
    cathetersAndWires: '21G 20cm Chiba needle, 0.018" wire, 2.7F microcatheter',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'Microcoils + Cyanoacrylate Glue (n-BCA) / Onyx (EVOH)',
    proceduralNarrativeTemplate:
      'Indicated for expanding AAA sac post-EVAR due to persistent Type II endoleak from lumbar/IMA nidus. Patient prone. Under CT/fluoroscopy, 21G needle advanced from left translumbar approach directly into endoleak cavity within excluded aneurysm sac. Contrast injection confirmed endoleak cavity communicating with feeding lumbar branches. 2.7F microcatheter advanced coaxially into nidus. Dense coil packing performed followed by n-BCA glue injection (1:2 ratio). Repeat contrast injection showed complete thrombosis of endoleak cavity without outflow. Needle withdrawn; puncture site dressed.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours.',
      hematomaChecks: 'Monitor vitals, back pain, and flank hematoma q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Follow-up CTA Abdomen at 6 weeks.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Tramadol 50mg SOS"],
      redFlags: ["Retroperitoneal hemorrhage", "Spinal stroke", "Bowel ischemia"],
    },
    consentId: 'consent-evar-aorta',
    calculatorId: 'cigarroa_macd',
  },
];
