import { MasterProcedure } from './types';

/**
 * Category 01: Image-Guided Percutaneous Biopsies & Cytology (53 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_01_BIOPSIES: MasterProcedure[] = [
  // 1. Liver Target Core Needle Biopsy (US)
  {
    id: 'cat01-liver-core-target',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Targeted Core Needle Biopsy of Liver Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C22.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Liver Segmental Lesion', 'Right/Left Hepatic Lobe'],
    sedation: 'Local Anesthesia (2% Lignocaine 10-15 mL)',
    accessSiteDefault: 'Right intercostal or subcostal approach depending on lesion segment',
    sheathDefault: 'Coaxial 17G introducer needle',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Gel-foam slurry track embolization as needed',
    proceduralNarrativeTemplate:
      'Patient positioned supine/left lateral. High-resolution ultrasound scanning localized target liver lesion. Sterile prep and drape. Local infiltration with 2% lignocaine down to Glisson capsule under real-time US. Under sonographic guidance, a 17G coaxial needle was advanced to the lesion margin. 18G semi-automated core biopsy gun fired. 3 adequate core cylinders (1.5-2.0 cm) obtained, placed in 10% formalin. Track sealed with gelfoam slurry. Post-procedure ultrasound showed no intrahepatic hematoma or free subcapsular fluid.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Right lateral decubitus positioning (liver pressure) x 2 hours, then flat supine x 2 hours.',
      hematomaChecks: 'Monitor BP, pulse, and abdominal pain score q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Bedside USG abdomen if sudden drop in BP or hemoglobin.',
      hydrationProtocol: 'Oral fluids after 2 hours if non-nauseated.',
      medications: ['Tab Paracetamol 650mg PO TDS PRN', 'Cap Pantoprazole 40mg PO OD'],
      redFlags: ['Right upper quadrant pain radiating to shoulder', 'Tachycardia', 'Hypotension', 'Abdominal distension'],
    },
    consentId: 'consent-liver-biopsy',
    calculatorId: 'calc-child-pugh',
  },

  // 2. Non-Targeted Liver Biopsy for Diffuse Liver Disease (US)
  {
    id: 'cat01-liver-diffuse-core',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Non-Targeted Liver Biopsy for Diffuse Parenchymal Disease',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'K74.6',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Segment VI/VII Hepatic Parenchyma'],
    sedation: 'Local Anesthesia (2% Lignocaine 10 mL)',
    accessSiteDefault: 'Right mid-axillary intercostal approach (8th-9th ICS)',
    sheathDefault: '16G/18G BioPince or semi-automatic core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Sterile preparation of right lateral chest/abdominal wall. Real-time ultrasound confirmed avascular path through Segment VI/VII parenchyma avoiding gallbladder and major portal tracts. Infiltration of 2% lignocaine. During suspended expiration, 16G full-core cutting needle passed into liver parenchyma. Two high-quality cores (>2.5 cm total, >10 portal tracts) retrieved for histopathology and staging of fibrosis. No hemoperitoneum on color Doppler.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Right lateral compression x 2 hours, then flat supine x 2 hours.',
      hematomaChecks: 'Pulse and blood pressure q15m x 1h, q30m x 2h.',
      hydrationProtocol: 'Maintenance IV/oral fluids.',
      medications: ['Tab Paracetamol 650mg SOS', 'Tab Tramadol 50mg SOS'],
      redFlags: ['Right hypochondrial pain', 'Pallor', 'Syncope', 'Tachycardia'],
    },
    consentId: 'consent-liver-biopsy',
    calculatorId: 'calc-albi',
  },

  // 3. Liver Allograft Biopsy (US)
  {
    id: 'cat01-liver-allograft-biopsy',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Liver Allograft Biopsy for Rejection Surveillance',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'T86.41',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Transplanted Liver Graft (Segment V/VI or Left Lobe Graft)'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Subcostal or mid-abdominal based on graft surgical anatomy',
    sheathDefault: '18G semi-automated core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Transplant liver graft evaluated with gray-scale and Doppler ultrasound. Hepatic artery resistive indices and portal vein velocities documented prior to puncture. Under direct sonographic observation, 18G core needle passed into the superficial anterior allograft parenchyma. Two 18mm cores harvested for Banff scoring. Doppler interrogation confirmed patent capsular vasculature with absence of pseudoaneurysm.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict bed rest flat supine x 4 hours.',
      hematomaChecks: 'Vitals q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Transplant Doppler USG at 4h if drop in hematocrit.',
      hydrationProtocol: 'Resume baseline transplant fluid regimen.',
      medications: ['Continue immunosuppressants as per protocol', 'Paracetamol 650mg PRN'],
      redFlags: ['Graft tenderness', 'Hypotension', 'Abdominal distension'],
    },
    consentId: 'consent-transplant-biopsy',
    calculatorId: 'calc-meld',
  },

  // 4. Transjugular Liver Biopsy (TJLB)
  {
    id: 'cat01-tjlb',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Transjugular Liver Biopsy (TJLB) with Hepatic Venous Pressure Gradient (HVPG)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transjugular Liver Biopsy (TJLB)',
      packageCode: '2849-IN 059A',
      icd10: 'K74.6',
      tariffInr: 8000,
    },
    modality: 'XA',
    targetAnatomy: ['Right Hepatic Vein', 'Right Liver Lobe Parenchyma'],
    sedation: 'Local Anesthesia + IV Conscious Sedation',
    accessSiteDefault: 'Right internal jugular vein (US-guided)',
    sheathDefault: '7F 45cm transjugular access sheath (LABS / Cook Quick-Core set)',
    cathetersAndWires: '0.035" Rosen wire, MPA/Cobra catheter, 19G Ross / Quick-Core TJLB needle',
    proceduralNarrativeTemplate:
      'Under sterile technique and US guidance, right IJV punctured. 7F 45cm Cook LABS sheath placed in right hepatic vein over Rosen wire. Right hepatic venogram performed in AP and 30 deg RAO views to confirm parenchymal branch position. Wedge (WHVP) and Free (FHVP) pressures measured in triplicate. Transjugular 19G cutting needle advanced through sheath, pointed anteriorly into liver parenchyma. Under fluoroscopy, 3 core biopsies obtained. Post-biopsy venogram demonstrated no capsular perforation or extravasation. Sheath removed and hemostasis achieved with 10 minutes manual compression.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bed rest with head elevated 30 degrees x 4 hours; avoid neck flexion.',
      hematomaChecks: 'Check right neck puncture site for swelling/hematoma q15m x 1h, q30m x 2h.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr for 4 hours.',
      medications: ['Tab Paracetamol 650mg SOS', 'Antiemetic IV Ondansetron 4mg PRN'],
      redFlags: ['Neck swelling / hematoma', 'Dyspnea / stridor', 'Severe abdominal pain', 'Hypotension'],
    },
    consentId: 'consent-tjlb',
    calculatorId: 'calc-hvpg',
  },

  // 5. Native Kidney Core Biopsy (US)
  {
    id: 'cat01-kidney-native-core',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Native Renal Cortical Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'N04.9',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Lower Pole Renal Cortex (Left Kidney Preferred)'],
    sedation: 'Local Anesthesia (2% Lignocaine 15 mL)',
    accessSiteDefault: 'Prone posterior lumbar flank approach',
    sheathDefault: '16G/18G automated core biopsy needle with depth stop',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Patient placed prone with abdominal roll. High-frequency US located left kidney lower pole cortex away from renal sinus and major vessels. Local anesthesia infiltrated down to renal capsule. Under direct real-time sonography during held inspiration, 16G automated biopsy gun placed in cortex and fired. Two cores inspected under dissecting microscope verifying glomeruli count (>10 per core). Split for light microscopy, immunofluorescence, and electron microscopy. Color Doppler confirmed intact subcapsular space with no active perinephric bleed.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat supine bed rest with sandbag under lumbar area x 6 hours.',
      hematomaChecks: 'Monitor for flank swelling, BP, and inspect every voided urine sample for gross hematuria.',
      requiredImaging: 'Emergency bedside USG kidney if gross hematuria with clots or drop in BP.',
      hydrationProtocol: 'Oral hydration 150-200 mL/hr to maintain brisk urine flow.',
      medications: ['Tab Paracetamol 650mg PO', 'Cap Pantoprazole 40mg'],
      redFlags: ['Gross macroscopic hematuria', 'Clot retention / bladder spasms', 'Severe flank pain', 'Hypotension'],
    },
    consentId: 'consent-renal-biopsy',
    calculatorId: 'calc-ckd-epi',
  },

  // 6. Renal Allograft Core Biopsy (US)
  {
    id: 'cat01-kidney-allograft-core',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Transplant Renal Allograft Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'T86.10',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Transplanted Kidney Cortex (Iliac Fossa)'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Right/Left iliac fossa overlying graft upper/lower pole',
    sheathDefault: '16G/18G automated core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Sterile prep of recipient iliac fossa. High-resolution linear transducer identified transplant renal cortex and avoided pelvic vessels and renal hilum. Local anesthesia infiltrated. Under sonographic guidance, 18G core needle introduced tangentially into cortex. Two cores obtained and confirmed adequate for Banff classification. Doppler assessment verified patent intralobar flow without arteriovenous fistula or pseudoaneurysm.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict bed rest supine x 6 hours. Light pressure dressing over iliac fossa.',
      hematomaChecks: 'Vitals and inspection of urine for hematuria q30m x 4h, then q1h.',
      hydrationProtocol: 'Maintain normal post-transplant fluid balance.',
      medications: ['Standard immunosuppressive regimen', 'Paracetamol 650mg PRN'],
      redFlags: ['Gross hematuria', 'Graft pain / tenderness', 'Drop in urine output', 'Tachycardia'],
    },
    consentId: 'consent-transplant-biopsy',
    calculatorId: 'calc-ckd-epi',
  },

  // 7. Renal Cortical Mass Biopsy (US)
  {
    id: 'cat01-kidney-mass-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Renal Mass / Neoplasm',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C64.9',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Renal Parenchymal Mass / Exophytic Renal Neoplasm'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Flank or posterior oblique approach',
    sheathDefault: '17G coaxial introducer needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Renal mass mapped under ultrasound. Prone/lateral position. Skin and tract infiltrated with 2% lignocaine. 17G coaxial needle advanced to tumor capsule avoiding intervening bowel and large vessels. 18G semi-automatic cutting needle introduced through cannula. 3 cores obtained from viable peripheral tumor tissue avoiding central cystic/necrotic components. Coaxial cannula removed with gelfoam tract embolization.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours.',
      hematomaChecks: 'Check vitals and urine color with each micturition.',
      hydrationProtocol: 'Oral hydration promoted.',
      medications: ['Tab Paracetamol 650mg TDS PRN'],
      redFlags: ['Hematuria', 'Flank fullness', 'Persistent pain', 'Syncope'],
    },
    consentId: 'consent-renal-biopsy',
    calculatorId: 'calc-ckd-epi',
  },

  // 8. Renal Mass Core Biopsy (CT)
  {
    id: 'cat01-kidney-mass-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Core Needle Biopsy of Renal Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C64.9',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Endophytic / Small Solid Renal Mass'],
    sedation: 'Local Anesthesia + IV Conscious Sedation',
    accessSiteDefault: 'Posterior retroperitoneal approach under CT guidance',
    sheathDefault: '17G coaxial trocar system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Patient positioned prone on CT table. Initial non-contrast CT identified target renal lesion. Radiopaque grid placed, trajectory, entry site, and angle determined. Skin prep, drape, and 10 mL 2% lignocaine infiltration. 17G coaxial needle advanced in planned trajectory under CT fluoroscopy verification. Coaxial tip confirmed within lesion margin. 18G automated core needle fired; 3 cores retrieved. Control CT confirmed lack of active perinephric hemorrhage or subcapsular hematoma.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict bedrest flat in bed x 4 hours.',
      hematomaChecks: 'Vitals q15m x 1h, q30m x 2h. Monitor urine clarity.',
      hydrationProtocol: 'Oral fluids encouraged after 2 hours.',
      medications: ['Tab Paracetamol 650mg SOS', 'Tab Tramadol 50mg SOS'],
      redFlags: ['Gross hematuria', 'Severe flank pain', 'Tachycardia'],
    },
    consentId: 'consent-renal-biopsy',
    calculatorId: 'calc-ckd-epi',
  },

  // 9. Spleen Focal Lesion Biopsy (US)
  {
    id: 'cat01-spleen-us-core',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Splenic Focal Lesion Core Needle Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D73.8',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Splenic Parenchymal Lesion / Lymphoma / Granuloma'],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Left posterolateral 9th-10th intercostal space',
    sheathDefault: '19G coaxial needle system',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Gel-foam slurry / torpedoes for track plugging',
    proceduralNarrativeTemplate:
      'Patient placed in right lateral decubitus. Ultrasound demonstrated splenic lesion with safe window traversing minimal normal splenic parenchyma, avoiding pleural reflection and colon. Local anesthesia administered. 19G coaxial needle inserted under real-time US during breath-hold. 20G cutting needle advanced; 2 cores obtained. Biopsy track thoroughly embolized with gelfoam torpedoes to prevent hemoperitoneum. Post-biopsy Doppler scan showed no active blush or subcapsular fluid.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict left lateral decubitus bed rest x 4 hours, then supine x 2 hours.',
      hematomaChecks: 'Continuous BP/pulse monitoring q15m x 2h, then q30m x 4h.',
      requiredImaging: 'Bedside ultrasound at 4 hours post-biopsy to assess for subcapsular hematoma.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr for 6 hours.',
      medications: ['IV Tramadol 50mg SOS', 'IV Ondansetron 4mg'],
      redFlags: ['Left shoulder pain (Kehr sign)', 'Hypotension', 'Abdominal rigidity'],
    },
    consentId: 'consent-spleen-biopsy',
  },

  // 10. Spleen Focal Lesion Biopsy (CT)
  {
    id: 'cat01-spleen-ct-core',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Deep Splenic Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D73.8',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Deep Splenic Medullary Lesion / Solitary Splenic Metastasis'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Left posterior subcostal / low intercostal trajectory',
    sheathDefault: '19G coaxial cannula',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Gelfoam pledgets for track embolization',
    proceduralNarrativeTemplate:
      'Prone/right lateral decubitus on CT gantry. Planning CT revealed deep focal splenic lesion. Trans-splenic tract minimized. Infiltration of 2% lignocaine. 19G coaxial guide needle inserted under step-and-shoot CT fluoroscopy. 20G automated core needle fired twice. Track sealed with gelfoam slurry during withdrawal. Post-procedure CT verified intact splenic capsule without perisplenic hematoma.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours; compress left flank.',
      hematomaChecks: 'Vitals q15m x 2h, q30m x 2h, q1h x 2h.',
      requiredImaging: 'Ultrasound spleen at 4-6 hours if abdominal discomfort occurs.',
      hydrationProtocol: 'IV fluids 75-100 mL/hr.',
      medications: ['Tab Paracetamol 650mg', 'IV Pantoprazole 40mg'],
      redFlags: ['Left hypochondrial pain', 'Left shoulder pain', 'Tachycardia', 'Hypotension'],
    },
    consentId: 'consent-spleen-biopsy',
  },

  // 11. Pancreatic Head / Uncinate Mass Biopsy (US)
  {
    id: 'cat01-pancreas-head-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Pancreatic Head Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C25.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Pancreatic Head / Processus Uncinatus'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Anterior transabdominal epigastric approach',
    sheathDefault: '18G/20G coaxial system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Supine position. High-resolution curved array transducer with gentle graded compression displaced overlying transverse colon and stomach. Target hypoechoic mass in pancreatic head identified, clear of SMA and SMV. Local anesthesia injected. 18G coaxial needle advanced into the mass. 20G core needle fired 3 times. Rapid on-site evaluation (ROSE) confirmed adenocarcinoma. Track cleared without complications.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours.',
      hematomaChecks: 'BP and pulse q15m x 1h, q30m x 2h. Check for epigastric guarding.',
      hydrationProtocol: 'IV fluids 100 mL/hr x 4 hours. NPO x 2 hours.',
      medications: ['IV Tramadol 50mg PRN', 'IV Ondansetron 4mg'],
      redFlags: ['Severe epigastric pain radiating to back (acute pancreatitis)', 'Vomiting', 'Hypotension'],
    },
    consentId: 'consent-pancreas-biopsy',
  },

  // 12. Pancreatic Body / Tail Mass Biopsy (CT)
  {
    id: 'cat01-pancreas-tail-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Pancreatic Body / Tail Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C25.2',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Pancreatic Body / Tail Lesion'],
    sedation: 'Local Anesthesia + IV Conscious Sedation',
    accessSiteDefault: 'Posterior trans-splenic or anterior trans-gastric route under CT',
    sheathDefault: '18G coaxial needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'CT planning scan performed. Safe posterior/anterior trajectory mapped avoiding major splenic vessels. Infiltration of 2% lignocaine. 18G coaxial needle placed into pancreatic tail mass with CT fluoroscopy. 20G cutting needle deployed; 3 diagnostic tissue cores obtained. Formalin fixation for histology and IHC. Post-biopsy CT revealed no retroperitoneal hematoma or active contrast leak.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bed rest x 4 hours.',
      hematomaChecks: 'Vitals q30m x 4h.',
      hydrationProtocol: 'IV fluids 100 mL/hr; monitor serum amylase/lipase if severe pain.',
      medications: ['Tab Paracetamol 650mg', 'IV Pantoprazole 40mg'],
      redFlags: ['Acute worsening back pain', 'Tachycardia', 'Fever'],
    },
    consentId: 'consent-pancreas-biopsy',
  },

  // 13. EUS-Guided FNA Pancreas
  {
    id: 'cat01-pancreas-eus-fna',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Endoscopic Ultrasound-Guided Fine Needle Aspiration (EUS-FNA/FNB) of Pancreatic Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C25.9',
      tariffInr: 5000,
    },
    modality: 'EUS',
    targetAnatomy: ['Pancreas Head / Body / Uncinate via Transgastric / Transduodenal route'],
    sedation: 'Deep Conscious Sedation / MAC with Propofol',
    accessSiteDefault: 'Endoscopic transgastric / transduodenal wall puncture',
    sheathDefault: '22G / 25G Acquire / ProCore EUS biopsy needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Linear echoendoscope introduced into duodenum/stomach under sedation. Pancreatic mass visualized. Power Doppler verified no intervening blood vessels in needle path. 22G FNB Franseen tip needle passed into mass under real-time EUS. Stylet removed, negative suction applied, 10-15 fanning passes made. Adequate tissue cylinder expressed for histopathology. Endoscopic inspection confirmed dry puncture site.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Recovery in PACU x 2 hours until fully awake.',
      hematomaChecks: 'Monitor for hematemesis, melena, or abdominal peritonism.',
      hydrationProtocol: 'NPO x 2 hours, then sips of clear water.',
      medications: ['IV Pantoprazole 40mg', 'Analgesics as required'],
      redFlags: ['Severe abdominal pain', 'Hematemesis', 'Fever'],
    },
    consentId: 'consent-eus-biopsy',
  },

  // 14. Peripheral Lung Nodule Biopsy (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-lung-nodule-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Core Needle Biopsy of Lung Nodule / Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C34.9',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Pulmonary Parenchyma / Lung Nodule / Bronchogenic Carcinoma'],
    sedation: 'Local Anesthesia (2% Lignocaine 10 mL)',
    accessSiteDefault: 'Transthoracic percutaneous route planned via least pleural-to-lesion distance',
    sheathDefault: '18G/19G coaxial needle with locking stylet',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Patient placed in prone/supine/lateral position based on nodule location. CT scout and fine 1mm slices performed. Trajectory selected to cross single pleural interface perpendicularly and avoid bullae or pulmonary vessels. Local anesthesia infiltrated down to parietal pleura. 19G coaxial needle advanced into pulmonary nodule under CT guidance during quiet expiration. 20G automated cutting needle obtained 3 diagnostic cores. Immediate post-biopsy CT demonstrated no pneumothorax or minor track hemorrhage. Patient rolled puncture-side down.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Puncture side down (dependent position) bed rest x 2 hours to promote pleural sealing, then flat supine x 2 hours. Avoid coughing and deep inspiration.',
      hematomaChecks: 'Monitor respiratory rate, SpO2, and pulse continuously. Check for hemoptysis.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Maintenance oral fluids after 2 hours.',
      medications: ['Tab Codeine phosphate 10mg PO PRN for dry cough suppression', 'Tab Paracetamol 650mg'],
      redFlags: ['Sudden pleuritic chest pain', 'Desaturation (SpO2 < 92%)', 'Hemoptysis > 30 mL', 'Dyspnea / tachypnea'],
    },
    consentId: 'consent-lung-biopsy',
  },

  // 15. Subpleural Lung Lesion Biopsy (US) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-lung-subpleural-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Subpleural Lung Mass / Consolidation',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C34.9',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Subpleural Lung Mass / Peripheral Pulmonary Consolidation'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Intercostal space directly overlying subpleural mass abutting chest wall',
    sheathDefault: '18G semi-automated core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Sonographic evaluation demonstrated solid subpleural pulmonary lesion abutting the pleura with complete absence of intervening aerated lung parenchyma. Pleural sliding absent over the mass. Local anesthesia infiltrated down to parietal pleura. 18G cutting needle advanced into solid mass under real-time US vision. 3 core biopsies acquired. Real-time lung ultrasound post-procedure verified normal lung sliding in adjacent zones and no pleural fluid collection.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Puncture side down x 2 hours, then supine x 2 hours.',
      hematomaChecks: 'SpO2 and vitals surveillance q15m x 1h, q30m x 2h.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Oral fluids after 2 hours.',
      medications: ['Tab Paracetamol 650mg SOS', 'Tab Codeine 10mg for cough'],
      redFlags: ['Chest pain', 'Dyspnea', 'Hemoptysis', 'Desaturation'],
    },
    consentId: 'consent-lung-biopsy',
  },

  // 16. Lung FNAC (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-lung-fnac-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Fine Needle Aspiration Cytology (FNAC) of Pulmonary Nodule',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'R91.1',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Small Pulmonary Solitary Nodule'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Transthoracic intercostal space under CT fluoroscopy',
    sheathDefault: '22G Chiba needle with stylet',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'CT localization of lung nodule. Local anesthesia injected. 22G Chiba needle advanced through pleura into center of nodule under CT guidance. Stylet removed, 20 mL syringe attached, back-and-forth passes performed with continuous suction. Aspirate smeared onto slides (air-dried and alcohol-fixed) for cytological examination and GeneXpert evaluation.',
    postOpCare: {
      immobilizationHours: 3,
      immobilizationInstructions: 'Puncture side down x 1-2 hours.',
      hematomaChecks: 'Monitor SpO2 and vital signs q15m x 1h, then q30m.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Routine oral hydration.',
      medications: ['Paracetamol 650mg PRN'],
      redFlags: ['Acute shortness of breath', 'Chest pain', 'Hemoptysis'],
    },
    consentId: 'consent-lung-biopsy',
  },

  // 17. Cavitary / Necrotic Lung Mass Biopsy (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-lung-cavitary-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Biopsy of Cavitary / Partially Necrotic Pulmonary Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C34.9',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Solid Peripheral Rim of Cavitary Lung Mass'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'CT guided transthoracic access',
    sheathDefault: '18G coaxial system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Planning CT delineated thick irregular wall of cavitary mass. Trajectory planned specifically to biopsy the hyperdense solid vascular wall while intentionally avoiding central fluid/air cavity to minimize risk of hemoptysis and pneumothorax. 18G coaxial guide needle parked at outer rim margin. 20G automated core gun harvested 3 solid tissue cores. Samples sent for histopathology and mycobacterial/fungal culture.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict bedrest in lateral decubitus on punctured side x 2h, then supine x 2h.',
      hematomaChecks: 'Continuous pulse oximetry; watch for hemoptysis.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Maintenance hydration.',
      medications: ['Tab Paracetamol 650mg SOS', 'Tab Codeine 10mg for cough'],
      redFlags: ['Hemoptysis', 'Shortness of breath', 'Pleuritic chest pain'],
    },
    consentId: 'consent-lung-biopsy',
  },

  // 18. Anterior Mediastinal Mass Biopsy (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-mediastinal-anterior-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Core Biopsy of Anterior Mediastinal Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D38.3',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Anterior Mediastinal Mass (Thymoma / Lymphoma / Germ Cell Tumor)'],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Parasternal anterior intercostal approach (internal mammary artery avoided)',
    sheathDefault: '18G coaxial needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Contrast-enhanced CT localized anterior mediastinal mass. Internal thoracic (internal mammary) vessels clearly mapped on CT. Parasternal extrapleural approach selected. Local anesthesia with 2% lignocaine. 18G coaxial guide needle advanced directly into anterior mediastinal mass without traversing aerated lung or pleura. 20G cutting needle took 4 cores for histology, IHC, and flow cytometry. No internal mammary injury or mediastinal hematoma.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Flat bed rest x 4 hours.',
      hematomaChecks: 'Vitals and respiratory pattern monitored q15m x 1h, q30m x 2h.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Oral fluids after 2 hours.',
      medications: ['Tab Paracetamol 650mg PO', 'Cap Pantoprazole 40mg'],
      redFlags: ['Retrosternal chest pressure', 'Dyspnea', 'Stridor', 'Hemothorax symptoms'],
    },
    consentId: 'consent-mediastinal-biopsy',
  },

  // 19. Middle Mediastinal Mass Biopsy (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-mediastinal-middle-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Middle Mediastinal / Subcarinal Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D38.3',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Subcarinal / Paratracheal Lymphadenopathy'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Posterior paravertebral or anterior transpulmonary route under CT',
    sheathDefault: '19G coaxial needle system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'CT planning visualized subcarinal lymph node mass. Trajectory mapped avoiding aorta, pulmonary artery trunks, and azygos vein. 19G coaxial needle introduced under CT guidance. 20G automated needle fired 3 times. Cores confirmed solid tissue. Post-procedure CT showed dry track.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours.',
      hematomaChecks: 'Vital signs q15m x 1h, q30m x 2h.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'IV fluids 75 mL/hr.',
      medications: ['Tab Paracetamol 650mg SOS'],
      redFlags: ['Dyspnea', 'Hemoptysis', 'Chest tightness'],
    },
    consentId: 'consent-mediastinal-biopsy',
  },

  // 20. Posterior Mediastinal Mass Biopsy (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-mediastinal-posterior-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Posterior Mediastinal / Paravertebral Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D38.3',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Posterior Mediastinal Neurogenic Tumor / Paravertebral Lesion'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Prone posterior paravertebral extrapleural approach',
    sheathDefault: '18G coaxial needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Prone position on CT table. Posterior mediastinal mass identified abutting dorsal spine. Paravertebral extrapleural access planned avoiding descending aorta and intercostal neurovascular bundles. 18G coaxial cannula placed. 20G core needle fired 3 times. Histology cores retrieved.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Flat supine/prone bedrest x 4 hours.',
      hematomaChecks: 'Monitor neurological signs in lower limbs and vital signs.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Routine oral fluids.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Radicular pain', 'Lower limb paresthesia / weakness', 'Dyspnea'],
    },
    consentId: 'consent-mediastinal-biopsy',
  },

  // 21. Pleural Mass Biopsy (US) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-pleural-mass-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Pleural Mass / Mesothelioma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C45.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Parietal / Visceral Pleura / Pleural Nodules'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Intercostal space directly over nodular pleural thickening',
    sheathDefault: '18G semi-automated core biopsy gun',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Ultrasound showed nodular hypoechoic pleural thickening with associated pleural effusion. Infiltration of local anesthesia along the superior rib border. Under continuous US visualization, 18G cutting needle advanced tangentially into the thickened pleural plaque, avoiding lung parenchyma. 3 diagnostic cores obtained for histopathology and calretinin/WT1 immunohistochemistry.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest in semi-fowler position.',
      hematomaChecks: 'Monitor chest pain and SpO2.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Oral fluids as tolerated.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Acute pleuritic chest pain', 'Desaturation', 'Cough with hemoptysis'],
    },
    consentId: 'consent-pleural-biopsy',
  },

  // 22. Pleural Thickening Biopsy (CT) - Thoracic Mandatory CXR rule!
  {
    id: 'cat01-pleural-plaque-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Biopsy of Diffuse Pleural Plaque / Thickening',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C45.0',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Posterior / Diaphragmatic Pleural Thickening'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'CT guided tangential intercostal approach',
    sheathDefault: '18G cutting needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'CT demonstrated circumferential pleural rind. Tangential needle trajectory chosen along rib axis to sample parietal pleura without violating visceral pleura and aerated lung. 18G core needle introduced under CT fluoroscopy; 3 cores retrieved.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bed rest in comfortable position x 4 hours.',
      hematomaChecks: 'Vitals and chest surveillance.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Standard hydration.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Chest pain', 'Shortness of breath', 'Tachycardia'],
    },
    consentId: 'consent-pleural-biopsy',
  },

  // 23. Left Adrenal Gland Core Biopsy (CT)
  {
    id: 'cat01-adrenal-left-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Core Biopsy of Left Adrenal Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C74.9',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Left Adrenal Gland / Adrenocortical Mass / Metastasis'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Prone posterior trans-renal or trans-retroperitoneal paravertebral approach',
    sheathDefault: '18G coaxial system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Pheochromocytoma excluded via prior negative plasma free metanephrines. Patient prone on CT table. Direct posterior trans-retroperitoneal route mapped avoiding kidney, spleen, and pleura. 18G coaxial needle advanced to left adrenal capsule under CT fluoroscopy. 20G automated core needle fired; 3 cores taken. Blood pressure remained stable throughout.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Flat bed rest x 4 hours.',
      hematomaChecks: 'Monitor blood pressure and pulse q15m x 2h (watch for hypertensive surge or hypotensive hemorrhage).',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ['Tab Paracetamol 650mg', 'IV Pantoprazole 40mg'],
      redFlags: ['Sudden hypertensive crisis (headache, sweating)', 'Flank pain', 'Tachycardia'],
    },
    consentId: 'consent-adrenal-biopsy',
  },

  // 24. Right Adrenal Gland Core Biopsy (CT)
  {
    id: 'cat01-adrenal-right-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Core Biopsy of Right Adrenal Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C74.9',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Right Adrenal Gland / Transhepatic / Retroperitoneal approach'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Transhepatic or posterior retroperitoneal approach',
    sheathDefault: '18G coaxial system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Prior biochemical testing negative for pheochromocytoma. Right adrenal mass approached transhepatically through posterior right liver lobe under CT guidance. 18G coaxial needle passed through liver parenchyma directly into right adrenal gland, avoiding the IVC. 3 core biopsies harvested. Transhepatic track sealed with gelfoam on withdrawal.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Right lateral decubitus x 2 hours, then supine x 2 hours.',
      hematomaChecks: 'Check BP and pulse q15m x 1h, q30m x 2h.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Right upper quadrant / flank pain', 'Hypotension', 'Tachycardia'],
    },
    consentId: 'consent-adrenal-biopsy',
  },

  // 25. Retroperitoneal Sarcoma Biopsy (CT)
  {
    id: 'cat01-retroperitoneal-sarcoma-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Retroperitoneal Sarcoma / Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C48.0',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Retroperitoneal Mesenchymal Mass / Liposarcoma / Leiomyosarcoma'],
    sedation: 'Local Anesthesia (2% Lignocaine 15 mL)',
    accessSiteDefault: 'Direct posterior flank approach (retroperitoneal track to prevent peritoneal seeding)',
    sheathDefault: '16G/17G coaxial needle system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Direct posterior retroperitoneal approach planned strictly to avoid transgressing peritoneal cavity (preventing intraperitoneal tumor seeding). 17G coaxial needle advanced into solid non-necrotic portion of retroperitoneal tumor. 18G core needle fired 4 times. Adequate cores obtained for histology, cytogenetics (MDM2 FISH), and molecular profiling. Coaxial track coagulated with gelfoam slurry.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours.',
      hematomaChecks: 'Vitals q30m x 4h.',
      hydrationProtocol: 'Oral fluids encouraged.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Severe flank / back pain', 'Hypotension', 'Hematuria'],
    },
    consentId: 'consent-retroperitoneal-biopsy',
  },

  // 26. Retroperitoneal Lymph Node Biopsy (CT)
  {
    id: 'cat01-retroperitoneal-ln-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Para-Aortic / Retroperitoneal Lymph Nodes',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C77.2',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Para-Aortic / Interaortocaval / Paracaval Lymph Node'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Posterior paravertebral or anterior transmesenteric route',
    sheathDefault: '18G coaxial system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Target para-aortic lymph node mapped on contrast CT. Trajectory planned avoiding aorta, IVC, ureters, and lumbar arteries. 18G coaxial needle positioned within the node. 20G automated cutting needle obtained 3 cores. Samples partitioned for histology and flow cytometry.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Flat bedrest x 4 hours.',
      hematomaChecks: 'BP and pulse q15m x 1h, q30m x 2h.',
      hydrationProtocol: 'Oral hydration promoted.',
      medications: ['Tab Paracetamol 650mg PRN'],
      redFlags: ['Abdominal pain', 'Backache', 'Tachycardia'],
    },
    consentId: 'consent-lymph-biopsy',
  },

  // 27. Deep Pelvic Mass Biopsy (CT)
  {
    id: 'cat01-pelvic-mass-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Percutaneous Core Biopsy of Deep Pelvic Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D39.9',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Deep Pelvic Sidewall Mass / Iliac Fossa Lesion'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Transgluteal (greater sciatic foramen) or anterior extraperitoneal iliac approach',
    sheathDefault: '18G coaxial needle system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Prone position. Deep pelvic mass localized. Transgluteal route selected passing through the sacrospinous ligament via greater sciatic foramen medially, strictly avoiding the sciatic nerve and inferior gluteal vessels. 18G coaxial needle advanced under CT guidance into mass. 20G cutting needle took 3 cores. Post-procedure CT showed clear field without pelvic hematoma.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine or lateral bedrest x 4 hours.',
      hematomaChecks: 'Check sciatic nerve sensation (foot dorsiflexion/sensation) and vitals q30m.',
      hydrationProtocol: 'Oral fluids after 2 hours.',
      medications: ['Tab Paracetamol 650mg', 'Tab Tramadol 50mg PRN'],
      redFlags: ['Gluteal pain', 'Sciatic shooting pain / foot drop', 'Pelvic pressure'],
    },
    consentId: 'consent-pelvic-biopsy',
  },

  // 28. Pelvic Presacral Mass Biopsy (CT)
  {
    id: 'cat01-presacral-mass-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Biopsy of Presacral / Retrorectal Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D48.7',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Presacral Space / Retrorectal Tumor (Chordoma / Schwannoma / Teratoma)'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Prone trans-coccygeal or parasacral posterior approach',
    sheathDefault: '18G coaxial needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Patient prone. Presacral mass mapped anterior to sacrococcygeal junction and posterior to rectum. Parasacral extrarectal trajectory planned avoiding rectal lumen and internal iliac branches. 18G coaxial guide needle inserted. 20G core needle fired; 3 specimens retrieved for pathology.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Prone/lateral positioning x 4 hours.',
      hematomaChecks: 'Monitor for rectal bleeding or perineal pain.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg', 'Tab Metronidazole 400mg TDS x 3 days (prophylactic)'],
      redFlags: ['Rectal bleeding', 'Fever', 'Perianal pain'],
    },
    consentId: 'consent-pelvic-biopsy',
  },

  // 29. Mesenteric Mass Biopsy (US)
  {
    id: 'cat01-mesenteric-mass-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Mesenteric Mass / Lymph Node',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C77.2',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Root of Mesentery / Small Bowel Mesenteric Mass'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Anterior abdominal wall with graded compression',
    sheathDefault: '18G/20G semi-automated core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'High-resolution ultrasound with graded compression displaced overlying gas-filled bowel loops. Mesenteric root mass visualized. Color Doppler verified no intervening superior mesenteric vessels. 18G core needle introduced under real-time guidance; 3 cores taken. Color Doppler showed no active bleeding in the mesentery.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours.',
      hematomaChecks: 'Vitals and abdominal palpation q30m x 4h.',
      hydrationProtocol: 'Oral fluids after 2 hours.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Peritoneal signs / guarding', 'Tachycardia', 'Hypotension'],
    },
    consentId: 'consent-mesenteric-biopsy',
  },

  // 30. Omental Cake / Metastasis Biopsy (US)
  {
    id: 'cat01-omental-cake-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Omental Cake / Carcinomatosis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C48.2',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Greater Omentum / Omental Cake'],
    sedation: 'Local Anesthesia (2% Lignocaine 10 mL)',
    accessSiteDefault: 'Anterior abdominal wall directly overlying omental thickening',
    sheathDefault: '18G semi-automated core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Thickened hypoechoic omental cake demonstrated on ultrasound directly beneath anterior peritoneum. Puncture site cleansed. Infiltration of 2% lignocaine. 18G core needle advanced under real-time US into omental cake, deliberately avoiding bowel loops beneath. 3 tissue cores obtained for histology and IHC (PAX8, WT1, CK7/CK20).',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours.',
      hematomaChecks: 'Vitals q30m x 2h.',
      hydrationProtocol: 'Routine oral fluids.',
      medications: ['Tab Paracetamol 650mg SOS'],
      redFlags: ['Abdominal pain', 'Fever', 'Tachycardia'],
    },
    consentId: 'consent-peritoneal-biopsy',
  },

  // 31. Peritoneal Nodular Biopsy (US)
  {
    id: 'cat01-peritoneal-nodule-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Biopsy of Parietal Peritoneal Nodule',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C48.2',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Parietal Peritoneum / Anterior Abdominal Wall Nodules'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Direct anterior abdominal wall puncture',
    sheathDefault: '18G core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Sonography identified 14mm nodule attached to parietal peritoneum with surrounding ascites. Local anesthesia given. Under real-time sonography, 18G core needle entered nodule tangentially. 3 cores acquired. No intra-abdominal hematoma.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Rest in bed x 2 hours.',
      hematomaChecks: 'Vitals monitoring.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Abdominal pain', 'Puncture site leak'],
    },
    consentId: 'consent-peritoneal-biopsy',
  },

  // 32. Thyroid FNAC (US)
  {
    id: 'cat01-thyroid-fnac-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Fine Needle Aspiration Cytology (FNAC) of Thyroid Nodule',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'E04.1',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Thyroid Nodule (EU-TIRADS 4/5)'],
    sedation: 'Local Anesthesia (2% Lignocaine 2 mL)',
    accessSiteDefault: 'Anterior cervical approach parallel or perpendicular to probe',
    sheathDefault: '23G/25G needle with 10 mL syringe / capillary technique',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Neck extended with shoulder roll. High-frequency linear probe identified solid hypoechoic thyroid nodule with microcalcifications. Aseptic prep. Skin infiltrated with 2% lignocaine. 25G needle introduced under real-time US using non-aspiration capillary technique. 4-6 gentle fanning passes made within the solid component. Material smeared onto 6 glass slides (air-dried for Giemsa and fixed in 95% ethanol for Pap stain). Bethesda system reporting requested.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Apply manual compression over puncture site x 10 minutes. Avoid vigorous neck turning x 2 hours.',
      hematomaChecks: 'Inspect anterior neck for swelling or stridor.',
      hydrationProtocol: 'Immediate oral intake permitted.',
      medications: ['Ice pack application x 15 mins', 'Tab Paracetamol 650mg PRN'],
      redFlags: ['Rapid neck swelling', 'Stridor / difficulty swallowing', 'Dyspnea'],
    },
    consentId: 'consent-thyroid-biopsy',
  },

  // 33. Thyroid Core Needle Biopsy (US)
  {
    id: 'cat01-thyroid-cnb-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy (CNB) of Thyroid Nodule',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'E04.1',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Thyroid Parenchyma / Indeterminate Bethesda III/IV Thyroid Nodule'],
    sedation: 'Local Anesthesia (2% Lignocaine 5 mL)',
    accessSiteDefault: 'Trans-isthmic cervical approach under linear US',
    sheathDefault: '18G/20G core biopsy needle with 1.1cm excursion',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Trans-isthmic approach selected to stabilize needle and avoid carotid artery and jugular vein. Infiltration of 2% lignocaine. Under continuous real-time US, 20G semi-automatic cutting needle introduced along the long axis of probe into thyroid nodule. Fired with 1.1cm throw. 2 intact tissue cores obtained for histological architecture and molecular analysis (BRAF V600E). Manual compression for 15 minutes achieved hemostasis.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Firm pressure dressing on neck. Rest quietly x 2 hours.',
      hematomaChecks: 'Monitor neck circumference and speech/voice quality q30m x 2h.',
      hydrationProtocol: 'Normal hydration.',
      medications: ['Tab Paracetamol 650mg SOS', 'Ice pack to neck'],
      redFlags: ['Neck hematoma', 'Hoarseness / voice change', 'Difficulty breathing'],
    },
    consentId: 'consent-thyroid-biopsy',
  },

  // 34. Parathyroid FNAC + PTH Washout (US)
  {
    id: 'cat01-parathyroid-pth-fnac',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Parathyroid FNAC with Intra-Needle Parathyroid Hormone (PTH) Washout',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'E21.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Inferior / Superior Parathyroid Adenoma'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Anterior neck under high-frequency ultrasound',
    sheathDefault: '25G needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Suspicious hypoechoic polar parathyroid lesion with characteristic peripheral vascular arc identified posterior to thyroid. 25G needle placed into lesion under direct sonographic control. Cytologic aspiration obtained. Needle lumen immediately flushed with 1.0 mL normal saline into EDTA tube and sent for quantitative PTH immunoassay (washout PTH >> serum PTH confirms parathyroid origin). Smears sent for cytopathology.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Manual compression x 10 minutes.',
      hematomaChecks: 'Check neck for hematoma.',
      hydrationProtocol: 'Oral fluids permitted.',
      medications: ['Ice pack to neck'],
      redFlags: ['Neck swelling', 'Stridor'],
    },
    consentId: 'consent-thyroid-biopsy',
  },

  // 35. Cervical LN FNAC + Tg Washout (US)
  {
    id: 'cat01-cervical-ln-tg-fnac',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Cervical Lymph Node FNAC with Thyroglobulin (Tg) Washout',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C77.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Level III/IV/VI Cervical Lymph Node'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Lateral cervical neck space',
    sheathDefault: '23G/25G needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Suspicious round cervical lymph node with loss of fatty hilum and cystic changes localized. 25G needle inserted under US guidance. Aspirate smeared for cytology. Needle immediately flushed with 1.0 mL saline for quantitative Thyroglobulin (Tg) washout measurement for detecting papillary thyroid cancer recurrence.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Direct digital pressure x 10 mins.',
      hematomaChecks: 'Monitor neck for hematoma.',
      hydrationProtocol: 'Routine fluids.',
      medications: ['Paracetamol PRN'],
      redFlags: ['Neck swelling', 'Dysphagia'],
    },
    consentId: 'consent-lymph-biopsy',
  },

  // 36. Cervical LN FNAC + Calcitonin Washout (US)
  {
    id: 'cat01-cervical-ln-calcitonin-fnac',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Cervical Lymph Node FNAC with Calcitonin Washout',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C77.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Level II/III/IV Cervical Lymph Node'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Cervical chain under linear transducer',
    sheathDefault: '25G needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Patient with history of medullary thyroid carcinoma. Cervical lymph node sampled under real-time US with 25G needle. Slides prepared for cytology. Needle flushed with 1 mL saline for Calcitonin washout assay. Puncture site hemostatic.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Pressure on puncture site x 10 mins.',
      hematomaChecks: 'Neck inspection.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Analgesics as required'],
      redFlags: ['Hematoma', 'Stridor'],
    },
    consentId: 'consent-lymph-biopsy',
  },

  // 37. Cervical Lymph Node Core Biopsy (US)
  {
    id: 'cat01-cervical-ln-cnb-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Cervical Lymph Node',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C77.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Deep Cervical / Jugulodigastric / Supraclavicular Lymph Node'],
    sedation: 'Local Anesthesia (2% Lignocaine 5 mL)',
    accessSiteDefault: 'Anterolateral neck avoiding internal jugular vein and carotid artery',
    sheathDefault: '18G/20G core biopsy needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Color Doppler confirmed distance from IJV and carotid bulb. Infiltration of 2% lignocaine. 18G core needle introduced parallel to transducer footprint. Fired across the long axis of the lymph node. 3 cores extracted for histology, IHC for lymphoma typing, and GeneXpert for TB.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Pressure bandage over neck x 2 hours.',
      hematomaChecks: 'Check vitals and neck swelling q30m x 2h.',
      hydrationProtocol: 'Oral intake permitted.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Expanding neck hematoma', 'Dyspnea', 'Voice change'],
    },
    consentId: 'consent-lymph-biopsy',
  },

  // 38. Parotid Gland Mass FNAC (US)
  {
    id: 'cat01-parotid-fnac-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided FNAC of Parotid Gland Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D11.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Parotid Gland Superficial / Deep Lobe Mass'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Preauricular / retromandibular approach',
    sheathDefault: '23G/25G needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'High-frequency US identified well-defined lobulated hypoechoic mass in superficial lobe of parotid. Retromandibular vein and facial nerve plane noted. 23G needle inserted under US guidance; multiple gentle passes made. Cytology smears prepared for Milan System classification.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Firm pressure over preauricular region x 10 minutes.',
      hematomaChecks: 'Examine facial symmetry (facial nerve motor function) and swelling.',
      hydrationProtocol: 'Normal intake.',
      medications: ['Ice pack'],
      redFlags: ['Facial droop / asymmetry', 'Rapid swelling'],
    },
    consentId: 'consent-salivary-biopsy',
  },

  // 39. Parotid Gland Mass Core Biopsy (US)
  {
    id: 'cat01-parotid-cnb-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Needle Biopsy of Parotid Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D11.0',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Parotid Gland Neoplasm (Pleomorphic Adenoma / Warthin / Carcinoma)'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Preauricular approach avoiding facial nerve branches',
    sheathDefault: '20G core needle with 10mm excursion',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Ultrasound mapped tumor margins and retromandibular vein. Local anesthetic infiltrated. 20G semi-automated core biopsy needle guided into tumor under continuous visualization. 2 cores obtained. Facial nerve integrity tested immediately post-procedure (normal eye closure, smile, forehead wrinkle intact).',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Pressure bandage x 2 hours.',
      hematomaChecks: 'Facial nerve check and hematoma checks q30m x 2h.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Facial asymmetry / weakness', 'Hematoma'],
    },
    consentId: 'consent-salivary-biopsy',
  },

  // 40. Submandibular Gland Mass Biopsy (US)
  {
    id: 'cat01-submandibular-biopsy-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core / FNAC of Submandibular Gland Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D11.7',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Submandibular Gland / Sialadenitis / Neoplasm'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Submandibular triangle below inferior border of mandible',
    sheathDefault: '18G/20G core needle or 23G needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Submandibular gland mass localized with ultrasound. Facial artery and vein mapped with color Doppler. 20G core biopsy needle directed under real-time US into lesion. 2 cores acquired. Hemostasis secured with direct pressure.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Direct manual compression x 15 minutes.',
      hematomaChecks: 'Monitor submandibular swelling.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Floor of mouth swelling', 'Stridor'],
    },
    consentId: 'consent-salivary-biopsy',
  },

  // 41. Breast Focal Mass Core Biopsy (US)
  {
    id: 'cat01-breast-core-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided 14G Core Needle Biopsy of Breast Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C50.9',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Breast Parenchyma / BIRADS 4/5 Mass'],
    sedation: 'Local Anesthesia (2% Lignocaine + Adrenaline 1:200,000)',
    accessSiteDefault: 'Skin entry parallel to chest wall along long axis of probe',
    sheathDefault: '14G automated core biopsy gun (Achieve / Bard Magnum)',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Metallic tissue localization marker clip (UltraClip / Hydromark)',
    proceduralNarrativeTemplate:
      'Supine-oblique position with ipsilateral arm raised. High-frequency linear transducer identified irregular hypoechoic breast mass. Infiltration of local anesthesia into dermis, subcutaneous tissue, and pre-pectoral space. 14G automated biopsy needle advanced parallel to chest wall (never perpendicular). 4 cores obtained with complete sample notch filling. Titanium localization clip deployed at center of biopsy cavity under US. Post-procedure compression for 10 minutes.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Tight breast compression bandage x 24 hours. Avoid heavy lifting x 48 hours.',
      hematomaChecks: 'Inspect bandage for strike-through bleeding q30m x 2h.',
      requiredImaging: 'Two-view post-biopsy mammogram to document marker clip deployment.',
      hydrationProtocol: 'Normal hydration.',
      medications: ['Tab Paracetamol 650mg TDS PRN', 'Ice pack over dressing'],
      redFlags: ['Expanding breast hematoma', 'Active bleeding through dressing', 'Severe breast pain'],
    },
    consentId: 'consent-breast-biopsy',
  },

  // 42. Vacuum-Assisted Breast Biopsy (VABB) under US
  {
    id: 'cat01-breast-vabb-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Vacuum-Assisted Breast Biopsy (VABB)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'D24.9',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Breast Mass / Fibroadenoma Excision / BIRADS 3/4'],
    sedation: 'Local Anesthesia + Local Tumescence',
    accessSiteDefault: 'Periareolar or peripheral radial skin nick',
    sheathDefault: '10G/8G EnCor / Mammotome vacuum probe',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Tissue marker clip',
    proceduralNarrativeTemplate:
      'Sterile prep. Tumescent local anesthesia infiltrated around target breast lesion. 3mm skin incision. 10G VABB probe positioned beneath lesion under continuous sonographic guidance. Rotational vacuum cutting performed (360 degrees). Contiguous sequential specimens collected in tissue chamber. Target lesion completely excised sonographically. Titanium clip deployed. Hematoma aspirated via vacuum before probe withdrawal. Manual compression x 15 minutes.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Pressure dressing with elastic adhesive bandage x 48 hours.',
      hematomaChecks: 'Monitor for hematoma and bleeding q30m x 2h.',
      requiredImaging: 'Post-VABB mammogram to verify complete lesion removal and clip location.',
      hydrationProtocol: 'Routine oral intake.',
      medications: ['Tab Paracetamol 650mg TDS', 'Ice packs for 24 hours'],
      redFlags: ['Expanding breast swelling', 'Active bleeding', 'Severe pain'],
    },
    consentId: 'consent-breast-biopsy',
  },

  // 43. Stereotactic Vacuum-Assisted Breast Biopsy
  {
    id: 'cat01-breast-stereo-vabb',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Stereotactic Vacuum-Assisted Breast Biopsy for Microcalcifications',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'R92.0',
      tariffInr: 5000,
    },
    modality: 'XA',
    targetAnatomy: ['Suspicious Breast Microcalcifications (BIRADS 4B/4C)'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Prone stereotactic table with breast aperture',
    sheathDefault: '9G/10G vacuum biopsy probe',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Titanium radiopaque marker clip',
    proceduralNarrativeTemplate:
      'Patient positioned prone on specialized stereotactic mammography table with breast compressed. Scout and +15/-15 degree stereo pair images acquired. Target microcalcifications calculated in X, Y, Z coordinates. Skin cleansed, local anesthesia infiltrated. 9G vacuum probe auto-advanced to target depth. Pre-fire and post-fire stereo verification confirmed needle notch centered on calcifications. 12 directional cores obtained under vacuum. Specimen radiography confirmed presence of calcium specks within cores. Localization clip deployed. Post-clip stereo images verified accurate placement.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Support bra / pressure bandage x 48 hours.',
      hematomaChecks: 'Monitor puncture site for bleeding.',
      requiredImaging: 'Post-procedure 2-view mammogram.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg PRN', 'Ice application'],
      redFlags: ['Breast hematoma', 'Bleeding through bandage'],
    },
    consentId: 'consent-breast-biopsy',
  },

  // 44. MRI-Guided Breast Core / Vacuum Biopsy
  {
    id: 'cat01-breast-mri-biopsy',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'MRI-Guided Vacuum-Assisted Breast Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C50.9',
      tariffInr: 5000,
    },
    modality: 'MRI',
    targetAnatomy: ['MRI-Only Enhancing Breast Lesion / Non-Mass Enhancement'],
    sedation: 'Local Anesthesia + Mild Anxiolytic',
    accessSiteDefault: 'MRI dedicated breast coil grid aperture',
    sheathDefault: '9G MRI-compatible titanium/ceramic vacuum needle',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'MR-compatible tissue clip',
    proceduralNarrativeTemplate:
      'Patient prone in dedicated breast MRI coil. IV gadolinium contrast administered. Enhancing lesion localized on post-contrast subtraction sequences. Target grid coordinates and depth calculated by CAD software. Skin prepped and anesthetized. MR-compatible coaxial sheath introduced. Fiducial obturator placed and fast T1 sequence verified correct position. 9G vacuum biopsy performed acquiring 12 samples. MRI clip deployed. Final T1 sequence documented signal void of clip at biopsy site.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Compression bandage x 24 hours.',
      hematomaChecks: 'Check vitals and compression site.',
      requiredImaging: 'Mammogram within 24h to verify clip position.',
      hydrationProtocol: 'Normal hydration.',
      medications: ['Tab Paracetamol 650mg'],
      redFlags: ['Hematoma', 'Severe pain'],
    },
    consentId: 'consent-breast-biopsy',
  },

  // 45. TRUS-Guided 12-Core Prostate Biopsy
  {
    id: 'cat01-prostate-trus-12core',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Transrectal Ultrasound (TRUS)-Guided 12-Core Systematic Prostate Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C61',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Prostate Peripheral & Transition Zones (Bilateral Base, Mid, Apex)'],
    sedation: 'Periprostatic Nerve Block (1% Lignocaine 10 mL) + Conscious Sedation',
    accessSiteDefault: 'Transrectal end-fire ultrasound probe needle guide',
    sheathDefault: '18G 20cm automated biopsy gun',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Left lateral decubitus position. Povidone-iodine rectal cleansing. Endocavity probe inserted. Prostate volume, zonal anatomy, and hypoechoic nodules documented. Bilateral periprostatic nerve blocks performed at the neurovascular bundles at the base (prostate-seminal vesicle angle). Under real-time TRUS guidance, an 18G spring-loaded needle obtained 12 systematic cores (6 right, 6 left: lateral base, mid, apex, and medial base, mid, apex). Cores separated into labelled vials. Rectal tamponade maintained for 5 minutes.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours. High fluid intake.',
      hematomaChecks: 'Monitor for rectal bleeding, urinary retention, or hematuria.',
      hydrationProtocol: 'Oral hydration 2-3 liters over 24 hours.',
      medications: ['Tab Ciprofloxacin 500mg BD x 3 days', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['High fever with chills (prostatic sepsis)', 'Inability to urinate (urinary retention)', 'Heavy continuous rectal bleeding'],
    },
    consentId: 'consent-prostate-biopsy',
  },

  // 46. Transperineal MRI-Ultrasound Fusion Prostate Biopsy
  {
    id: 'cat01-prostate-transperineal-fusion',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Transperineal MRI-Ultrasound Cognitive / Fusion Targeted Prostate Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C61',
      tariffInr: 5000,
    },
    modality: 'HYBRID',
    targetAnatomy: ['Multiparametric MRI PI-RADS 4/5 Lesion + Systematic Prostate Zones'],
    sedation: 'Spinal Anesthesia / Deep Sedation with Perineal Field Block',
    accessSiteDefault: 'Transperineal template grid puncture (zero rectal mucosal violation)',
    sheathDefault: '18G coaxial perineal needle guide',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Lithotomy position. Perineum prepped sterilely. Stepper-stabilizer and biplane transrectal probe mounted. Pre-procedure mpMRI DICOM co-registered and fused with live ultrasound. Rigid/elastic fusion overlaid target PI-RADS 5 anterior fibromuscular / peripheral zone lesion onto live US. 18G needle advanced transperineally through grid into targeted lesion; 4 targeted cores obtained, followed by 12 systematic template cores. Perineal pressure applied.',
    postOpCare: {
      immobilizationHours: 3,
      immobilizationInstructions: 'Rest flat x 3 hours until sensation recovers from spinal/sedation. Ice to perineum.',
      hematomaChecks: 'Inspect perineal dressing and confirm spontaneous clear voiding before discharge.',
      hydrationProtocol: 'Oral hydration 2.5 L/day.',
      medications: ['Tab Cefuroxime 500mg BD x 3 days', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Urinary retention', 'Perineal hematoma', 'Fever / rigor'],
    },
    consentId: 'consent-prostate-biopsy',
  },

  // 47. Bone Jamshidi Manual Biopsy
  {
    id: 'cat01-bone-jamshidi-manual',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Fluoroscopy / CT-Guided Jamshidi Bone Trephine Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'M89.8',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Appendicular Bone / Iliac Crest / Osteolytic Lesion'],
    sedation: 'Local Anesthesia (2% Lignocaine) + Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous approach over bone cortex',
    sheathDefault: '11G/13G Jamshidi bone trephine needle with extraction cannula',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Bone lesion localized under CT/fluoroscopy. Deep periosteal infiltration of 10 mL 2% lignocaine with complete anesthesia. 11G Jamshidi needle advanced to bone surface. Needle rotated with continuous clockwise-counterclockwise manual pressure to penetrate cortex into marrow. Stylus replaced by extraction rod. Core sheared by oscillating needle and extracted. 2.5 cm intact bone marrow core retrieved and fixed in formalin for decalcification.',
    postOpCare: {
      immobilizationHours: 3,
      immobilizationInstructions: 'Bedrest x 3 hours. Pressure bandage over bone puncture site.',
      hematomaChecks: 'Monitor vital signs and puncture site for soakage.',
      hydrationProtocol: 'Oral hydration.',
      medications: ['Tab Tramadol 50mg SOS', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Uncontrolled bone pain', 'Expanding hematoma', 'Numbness in distal extremity'],
    },
    consentId: 'consent-bone-biopsy',
  },

  // 48. Powered Bonopty Bone Biopsy
  {
    id: 'cat01-bone-powered-bonopty',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Powered Drill / Bonopty Bone Trephine Biopsy for Sclerotic Lesions',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'M89.8',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Dense Osteoblastic / Sclerotic Bone Lesion / Compact Cortex'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous tract perpendicular to bone cortex',
    sheathDefault: 'Bonopty 12G penetration cannula with 14G biopsy drill kit',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'CT planning mapped osteoblastic dense metastatic lesion. Thickened sclerotic cortex identified. Periosteum heavily infiltrated with 2% lignocaine. Bonopty anchoring cannula docked onto bone. High-speed coaxial drill penetrated sclerotic cortex under intermittent CT confirmation. Biopsy drill core harvested 2 intact dense bone cylinders without thermal artifact. Puncture site closed with sterile dressing.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Immobilize limb/area x 4 hours.',
      hematomaChecks: 'Vitals and local site check.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Tramadol 50mg + Paracetamol 325mg BD'],
      redFlags: ['Severe bone pain', 'Bleeding', 'Fever'],
    },
    consentId: 'consent-bone-biopsy',
  },

  // 49. Vertebral Body / Pedicle Core Biopsy (CT)
  {
    id: 'cat01-vertebral-body-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Transpedicular / Extrapedicular Vertebral Body Core Biopsy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'M46.20',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Thoracic / Lumbar Vertebral Body / Spondylodiscitis / Plasmacytoma'],
    sedation: 'Local Anesthesia + IV Conscious Sedation',
    accessSiteDefault: 'Prone posterior transpedicular approach under CT fluoroscopy',
    sheathDefault: '11G/13G coaxial vertebral trephine needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Prone position. Lumbar/thoracic vertebra imaged on fine-cut CT. Transpedicular access planned ensuring needle stayed strictly within pedicle margins (never violating medial wall to protect spinal cord/thecal sac). Local anesthesia infiltrated down to periosteum. 11G bevelled introducer needle passed through pedicle isthmus into vertebral body center. Trephine biopsy needle obtained 2 marrow/bone cores. Samples divided for histopathology, GeneXpert MTB/RIF, and bacterial/fungal cultures. No spinal leak or epidural hematoma.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict flat supine bed rest x 4 hours. Keep spine aligned.',
      hematomaChecks: 'Perform detailed lower extremity neurological exam (motor strength, sensation, reflexes) q30m x 4h.',
      hydrationProtocol: 'Routine oral fluids.',
      medications: ['Tab Tramadol 50mg SOS', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Motor weakness in lower limbs', 'Sensory level / numbness', 'Bowel / bladder incontinence', 'Severe back pain'],
    },
    consentId: 'consent-spine-biopsy',
  },

  // 50. Sacral / Iliac Bone Biopsy (CT)
  {
    id: 'cat01-sacral-bone-ct',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'CT-Guided Core Needle Biopsy of Sacral / Iliac Bone Mass',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C41.4',
      tariffInr: 5000,
    },
    modality: 'CT',
    targetAnatomy: ['Sacral Ala / Sacral Body / Iliac Bone Lesion'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Posterior sacral / pelvic approach under CT',
    sheathDefault: '11G Jamshidi or coaxial bone needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'CT images planned trajectory avoiding anterior sacral foramina, sacral nerve roots, and internal iliac vessels. Local anesthesia given. 11G bone needle placed into sacral lesion. Trephine core biopsy obtained. Intact tissue cylinder sent for histopathology.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest flat x 4 hours.',
      hematomaChecks: 'Monitor perineal sensation, lower limb motor strength, and vitals.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg', 'Tab Tramadol 50mg'],
      redFlags: ['Saddle anesthesia', 'Leg weakness', 'Incontinence'],
    },
    consentId: 'consent-bone-biopsy',
  },

  // 51. Soft Tissue Extremity Sarcoma Biopsy (US/CT)
  {
    id: 'cat01-soft-tissue-extremity',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound / CT-Guided Core Needle Biopsy of Extremity Soft Tissue Sarcoma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C49.2',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Thigh / Calf / Upper Extremity Deep Muscular Mass'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Direct longitudinal approach planned in line with future surgical incision',
    sheathDefault: '14G/16G coaxial core biopsy system',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Consultation with orthopedic oncology verified planned surgical incision plane. Needle trajectory designed strictly within the future resection track and single muscular compartment (avoiding neurovascular bundles and adjacent compartments). Local anesthesia administered. 14G core needle advanced into solid enhancing tumor. 4 cores harvested for histological architecture, IHC, and cytogenetics. Track sealed with gelfoam to prevent tumor seeding.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Limb elevated and rested x 2 hours. Pressure bandage applied.',
      hematomaChecks: 'Distal pulses and compartment softness checked q30m x 2h.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Tight tense swelling (compartment syndrome)', 'Distal pulse loss / numbness', 'Active bleeding'],
    },
    consentId: 'consent-soft-tissue-biopsy',
  },

  // 52. Subcutaneous Nodule / Superficial Inguinal LN Biopsy (US)
  {
    id: 'cat01-subcutaneous-inguinal-us',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Ultrasound-Guided Core Biopsy of Subcutaneous Nodule / Superficial Inguinal Node',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C77.4',
      tariffInr: 5000,
    },
    modality: 'US',
    targetAnatomy: ['Subcutaneous Mass / Superficial Inguinal / Axillary Node'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Direct percutaneous puncture under linear transducer',
    sheathDefault: '18G semi-automated core needle',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'High-frequency linear sonography localized superficial mass. Femoral / axillary vessels identified and safely avoided. 2% lignocaine infiltrated. 18G core needle passed into the lesion. 3 cores obtained. Direct pressure achieved complete hemostasis.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Pressure dressing x 1 hour.',
      hematomaChecks: 'Inspect dressing for bleeding.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Paracetamol 650mg PRN'],
      redFlags: ['Hematoma', 'Redness / discharge'],
    },
    consentId: 'consent-lymph-biopsy',
  },

  // 53. Endobiliary Forceps Biopsy & Brush Cytology under Fluoroscopy
  {
    id: 'cat01-endobiliary-forceps-brush',
    categoryNumber: 1,
    categoryName: 'Image-Guided Percutaneous Biopsies & Cytology',
    title: 'Transhepatic Endobiliary Forceps Biopsy and Brush Cytology',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Tru-Cut Needle Biopsy (US / CT)',
      packageCode: '1849-MG076A',
      icd10: 'C24.0',
      tariffInr: 5000,
    },
    modality: 'XA',
    targetAnatomy: ['Common Bile Duct / Hepatic Duct Bifurcation (Klatskin Tumor)'],
    sedation: 'IV Conscious Sedation + Local Anesthesia',
    accessSiteDefault: 'Percutaneous transhepatic biliary access tract (PTBD sheath)',
    sheathDefault: '8F 25cm vascular / biliary introducer sheath',
    cathetersAndWires: '0.035" stiff guidewire, 5F Kumpe catheter, biopsy forceps (Cook / Cordis 5.4F)',
    proceduralNarrativeTemplate:
      'Through existing or newly created PTBD tract, cholangiography outlined tight stricture at biliary confluence. 8F sheath advanced to proximal stricture margin. Wire crossed the stricture into duodenum. Flexible endobiliary biopsy forceps (5.4F) passed through sheath to stricture under fluoroscopy. Jaws opened, pressed against stricture wall, closed, and extracted. 4 tissue bites harvested. Followed by endobiliary cytology brush rotated 10 times across stricture. Formalin and cytology fixative sent. Biliary drainage catheter replaced over wire.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest flat x 4 hours. Keep biliary bag dependent.',
      hematomaChecks: 'Monitor bile bag output for frank blood; vitals q15m x 1h, q30m x 2h.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ['IV Ceftriaxone 1g BD (prophylaxis)', 'Tab Paracetamol 650mg PRN'],
      redFlags: ['Heavy hemobilia (blood in bile bag)', 'Biliary sepsis (rigors, fever)', 'Severe abdominal peritonism'],
    },
    consentId: 'consent-ptbd-biopsy',
    calculatorId: 'calc-biliary-score',
  },
];
