import { MasterProcedure } from './types';

/**
 * Category 18: Gynecological & Obstetric Interventions (3 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_18_GYN: MasterProcedure[] = [
  {
    id: 'cat18-uae-fibroids',
    categoryNumber: 18,
    categoryName: 'Gynecological & Obstetric Interventions',
    title: 'Uterine Artery Embolization (UAE) for Symptomatic Uterine Fibroids',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Uterine Artery Embolization (UAE)',
      packageCode: '1849-IN073A',
      icd10: 'D25.9',
      tariffInr: 35000,
    },
    modality: 'XA',
    targetAnatomy: ["Bilateral Uterine Arteries (Ascending and Descending Branches)"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Right Common Femoral Artery or Left Transradial Access',
    sheathDefault: '5F 11cm Sheath',
    cathetersAndWires: '5F Roberts Uterine Catheter (RUC) / Cobra, 2.0F - 2.4F microcatheter, 0.014" wire',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'Calibrated Microspheres (Embospheres 500-700um and 700-900um)',
    proceduralNarrativeTemplate:
      'Indicated for menorrhagia and bulk symptoms from symptomatic intramural/submucosal uterine leiomyomas. Access via right CFA. Pelvic arteriogram confirmed enlarged, hypervascular fibroid uterus with bilateral prominent, tortuous uterine arteries. 5F Roberts Uterine Catheter navigated into left internal iliac artery anterior division. 2.0F microcatheter advanced superselectively into horizontal/ascending segment of left uterine artery past cervicovaginal branches. Embolization performed using 500-700um and 700-900um Embospheres until prune-tree stasis reached with 5-beat clearance of contrast column. Catheter redirected into right uterine artery (Waltman loop / cross-over); identical complete bilateral embolization achieved. Completion pelvic angiogram showed total devascularization of fibroid vascular bed with preserved ovarian and internal iliac flow.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine flat bedrest x 6 hours; right leg straight.',
      hematomaChecks: 'Monitor groin puncture site, lower abdominal pain score, and vaginal bleeding q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Pelvic MRI at 3-6 months to assess fibroid volume reduction and infarction rate.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr x 12 hours.',
      medications: ["Patient-Controlled Analgesia (PCA) / IV Morphine / Tramadol protocol for first 12-24 hours", "Tab Diclofenac 50mg TDS", "Cap Pantoprazole 40mg OD", "Tab Ondansetron 4mg TDS"],
      redFlags: ["Post-embolization syndrome (cramping pain, fever, nausea)", "Vaginal expulsion of necrotic fibroid", "Premature ovarian insufficiency", "Groin hematoma"],
    },
    consentId: 'consent-uae-fibroids',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat18-uae-pph-emergency',
    categoryNumber: 18,
    categoryName: 'Gynecological & Obstetric Interventions',
    title: 'Emergency Uterine Artery Embolization for Severe Post-Partum Hemorrhage (PPH)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Uterine Artery Embolization (UAE)',
      packageCode: '1849-IN073A',
      icd10: 'O72.1',
      tariffInr: 40000,
    },
    modality: 'XA',
    targetAnatomy: ["Bilateral Uterine Arteries", "Internal Iliac Anterior Division Branches"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Right CFA under US/Fluoro',
    sheathDefault: '5F - 6F Sheath',
    cathetersAndWires: '5F Cobra, 2.7F microcatheter, 0.014" wire, absorbable Gel-foam sponge',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'Gelfoam Sponge Slurry and Torpedoes',
    proceduralNarrativeTemplate:
      'Life-threatening post-partum hemorrhage following vaginal/cesarean delivery failing uterotonics and bimanual compression. Rapid right CFA access. Pelvic angiogram revealed massive contrast pooling and uterine atony with diffuse hypervascularity. Bilateral uterine arteries rapidly cannulated with 5F Cobra and 2.7F microcatheter. Embolization executed using absorbable Gelfoam sponge slurry and torpedoes until complete arterial stasis achieved in both uterine arteries. Repeat pelvic aortogram showed immediate cessation of active uterine bleeding, preserving future fertility. Patient hemodynamically stabilized on cath-lab table.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict bedrest x 6 hours in ICU.',
      hematomaChecks: 'Continuous vitals monitoring, fundal height/tone check, and per-vaginal bleeding pad count q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Pelvic Doppler USG at 24 hours.',
      hydrationProtocol: 'IV fluids, blood products, and tranexamic acid as per massive transfusion protocol.',
      medications: ["IV Oxytocin continuous infusion", "Broad-spectrum IV antibiotics", "Tab Paracetamol 650mg TDS"],
      redFlags: ["Uterine necrosis", "Recurrent bleeding", "Groin hematoma"],
    },
    consentId: 'consent-uae-fibroids',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat18-ove-pelvic-congestion',
    categoryNumber: 18,
    categoryName: 'Gynecological & Obstetric Interventions',
    title: 'Ovarian Vein Embolization (OVE) with Coils & Sclerosant for Pelvic Congestion Syndrome',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transvenous Embolization / Obliteration of Varices',
      packageCode: '1849-IN061A',
      icd10: 'I86.2',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["Left Ovarian Vein", "Right Ovarian Vein", "Pelvic Venous Plexus"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Right Common Femoral Vein or Right IJV under US',
    sheathDefault: '6F 45cm Long Sheath',
    cathetersAndWires: '5F Cobra, 0.035" stiff Glidewire, 2.7F microcatheter, 0.018"/0.035" detachable microcoils (8-14mm), 3% STS foam',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'Detachable Fibered Coils (8-14mm) + 3% STS Foam Sclerosant',
    proceduralNarrativeTemplate:
      'Indicated for chronic pelvic pain from pelvic congestion syndrome. Right IJV/CFV access. Left renal vein entered; selective left ovarian venogram with Valsalva maneuver demonstrated massive ovarian vein incompetence (diameter 12mm), caudal reflux, and extensive tortuous pelvic/uterine venous varicosities. 2.7F microcatheter advanced into distal pelvic tributaries. Foam sclerotherapy (3% STS 4 mL) delivered into deep pelvic varices. Left ovarian vein trunk densely packed with 8mm-12mm detachable fibered coils from pelvic brim up to 2 cm below left renal vein confluence (sandwich technique). Completion venogram showed total occlusion of ovarian vein with zero reflux.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 4 hours.',
      hematomaChecks: 'Monitor access site and lower pelvic pain q30m x 2h, then q1h.',
      requiredImaging: 'Pelvic Doppler USG at 6 weeks.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Ibuprofen 400mg BD x 3 days"],
      redFlags: ["Coil migration to pulmonary artery / left renal vein", "Thrombophlebitis", "Groin hematoma"],
    },
    consentId: 'consent-ove-pelvic-congestion',
  },
];
