import { MasterProcedure } from './types';

/**
 * Category 15: Spine & Pain Interventions (4 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_15_SPINE_PAIN: MasterProcedure[] = [
  {
    id: 'cat15-pvp-vertebroplasty',
    categoryNumber: 15,
    categoryName: 'Spine & Pain Interventions',
    title: 'Percutaneous Vertebroplasty (PVP) for Osteoporotic Vertebral Compression Fracture',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Vertebroplasty',
      packageCode: '1849-IN069A',
      icd10: 'M80.0',
      tariffInr: 22000,
    },
    modality: 'XA',
    targetAnatomy: ["Vertebral Body (L1/L2/T12/T11)"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Bilateral Transpedicular Approach under Biplane Fluoroscopy',
    sheathDefault: '11G / 13G Vertebroplasty Beveled Needles',
    cathetersAndWires: '11G/13G biopsy/access needles, hydraulic cement delivery syringe, radiopaque PMMA bone cement',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Polymethylmethacrylate (PMMA) High-Viscosity Bone Cement (3-5 mL)',
    proceduralNarrativeTemplate:
      'Patient prone. Biplane fluoroscopy aligned pedicular rings and vertebral endplates. Local anesthesia down to periosteum. 11G beveled vertebroplasty needles advanced transpedicularly into anterior 1/3 of L1 vertebral body. Biopsy obtained. PMMA bone cement mixed to toothpaste-like viscosity. Under continuous biplane lateral fluoroscopy, 4.0 mL of radiopaque PMMA cement incrementally injected into the vertebral body, ensuring uniform trabecular interdigitation from endplate to endplate. Injection strictly halted upon any posterior cortical or epidural venous extension. Needles rotated and withdrawn with stylets. Sterile dressing.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict flat supine bedrest x 2 hours (to allow PMMA polymerization), then log-roll bedrest x 2 hours.',
      hematomaChecks: 'Neurological examination (lower limb power, sensation, deep tendon reflexes) q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Post-procedure Plain Radiograph / CT Spine to verify cement distribution and exclude canal extravasation.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS", "Cap Pantoprazole 40mg OD", "Anti-osteoporotic therapy (Calcium, Vit D3, Teriparatide)"],
      redFlags: ["Cement leakage into spinal canal / epidural space (cord compression)", "Cement pulmonary embolism", "Adjacent level vertebral fracture"],
    },
    consentId: 'consent-vertebroplasty',
  },
  {
    id: 'cat15-bkp-kyphoplasty',
    categoryNumber: 15,
    categoryName: 'Spine & Pain Interventions',
    title: 'Balloon Kyphoplasty (BKP) for Thoracic / Lumbar Vertebral Compression Fracture',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Kyphoplasty',
      packageCode: '1849-IN070A',
      icd10: 'M80.0',
      tariffInr: 35000,
    },
    modality: 'XA',
    targetAnatomy: ["Vertebral Body (Thoracolumbar)"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Bilateral Transpedicular / Extrapedicular Approach',
    sheathDefault: '10G Working Cannulas',
    cathetersAndWires: '10G access needles, inflatable bone tamp balloons (15mm/20mm), digital pressure syringe, PMMA cement',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Kyphoplasty Balloon Tamps + High-Viscosity PMMA Bone Cement',
    proceduralNarrativeTemplate:
      'Prone position. 10G access cannulas placed bilaterally into anterior vertebral body. Inflatable bone tamps inserted and inflated slowly with contrast under pressure monitoring (up to 250 psi) until vertebral height restored and a controlled cancellous cavity created. Balloons deflated and removed. Cavity filled under low pressure with high-viscosity PMMA cement (4.5 mL total). Height restoration confirmed without cement leakage. Cannulas removed.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Flat bedrest x 2 hours, then mobilized with lumbar corset.',
      hematomaChecks: 'Neuro checks of lower limbs q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Plain X-ray spine.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS", "Lumbar belt support"],
      redFlags: ["Spinal cord compression", "Balloon rupture", "Embolism"],
    },
    consentId: 'consent-vertebroplasty',
  },
  {
    id: 'cat15-celiac-plexus-neurolysis',
    categoryNumber: 15,
    categoryName: 'Spine & Pain Interventions',
    title: 'CT-Guided Percutaneous Celiac Plexus Neurolysis (CPN) for Pancreatic Cancer Pain',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Celiac Plexus Block / Neurolysis',
      packageCode: '1849-IN071A',
      icd10: 'C25.9',
      tariffInr: 15000,
    },
    modality: 'CT',
    targetAnatomy: ["Celiac Plexus", "Retrocrural Space", "Pre-aortic Celiac Axis"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Bilateral Transcrural / Retrocrural Approach under CT guidance',
    sheathDefault: '20G - 22G 15cm Chiba Needles',
    cathetersAndWires: 'CT guidance, 22G needles, 0.5% Bupivacaine, Absolute Ethanol (99%) mixed with contrast',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Absolute Alcohol (99%) 40-50 mL + 0.5% Bupivacaine',
    proceduralNarrativeTemplate:
      'Indicated for intractable upper abdominal back pain from unresectable pancreatic head carcinoma. Patient prone. Non-contrast CT identified celiac trunk origin. 22G 15cm Chiba needles advanced bilaterally from retrocrural approach with needle tips positioned anterolateral to aorta at celiac artery level. Aspiration negative for blood and urine. Contrast injection (2 mL) confirmed excellent retroperitoneal diffusion around celiac axis. 10 mL of 0.5% bupivacaine injected bilaterally (diagnostic relief verified), followed by slow injection of 40 mL absolute alcohol (99%). Immediate sympathetic blockade evidenced by warming of feet. Needles withdrawn.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict flat bedrest x 4 hours.',
      hematomaChecks: 'Monitor blood pressure closely (hypotension surveillance) and pain score q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'None routine.',
      hydrationProtocol: 'Liberal IV hydration (100-150 mL/hr) to counteract post-neurolysis orthostatic hypotension.',
      medications: ["Tab Paracetamol 650mg TDS", "IV Tramadol PRN", "Titrate down baseline opioid doses by 50% to prevent overdose"],
      redFlags: ["Severe orthostatic hypotension", "Transient diarrhea (parasympathetic hyperactivity)", "Retroperitoneal hematoma / aortic injury", "Paraplegia (anterior spinal artery ischemia)"],
    },
    consentId: 'consent-celiac-neurolysis',
  },
  {
    id: 'cat15-lumbar-transforaminal-esi',
    categoryNumber: 15,
    categoryName: 'Spine & Pain Interventions',
    title: 'Lumbar Transforaminal Epidural Steroid Injection (TFESI) / Selective Nerve Root Block',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Epidural Steroid Injection',
      packageCode: '1849-IN072A',
      icd10: 'M54.16',
      tariffInr: 8000,
    },
    modality: 'XA',
    targetAnatomy: ["L4 / L5 / S1 Neural Foramen and Nerve Root"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Subpedicular Oblique Approach under Fluoroscopy',
    sheathDefault: '22G / 25G 9cm Quincke Needle',
    cathetersAndWires: 'C-arm fluoroscope, 22G needle, extension tubing, non-ionic contrast, Dexamethasone 8mg + 0.25% Bupivacaine',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Dexamethasone (Non-particulate) 8mg + Bupivacaine 0.25%',
    proceduralNarrativeTemplate:
      'Indicated for acute L5 radiculopathy due to paracentral disc herniation. Prone position. C-arm obliqued 25° and tilted cranio-caudally to align L5 superior articular process. 22G needle advanced into safe triangle below L5 pedicle. Under live fluoroscopy, 1.0 mL non-ionic contrast injected demonstrating classic perineural flow along L5 nerve root into the anterior epidural space without vascular uptake. Mixture of 8mg non-particulate dexamethasone and 1.5 mL 0.25% bupivacaine slowly injected. Complete reproduction and immediate resolution of radicular leg pain.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Recovery observation x 1 hour. Ambulate with assistance.',
      hematomaChecks: 'Check lower extremity power, proprioception, and puncture site q30m.',
      requiredImaging: 'None routine.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS", "Continue physical therapy"],
      redFlags: ["Intravascular injection / spinal cord infarction (mitigated by non-particulate steroid)", "Dural puncture headache", "Transient leg weakness"],
    },
    consentId: 'consent-epidural-injection',
  },
];
