import { MasterProcedure } from './types';

/**
 * Category 16: Neurovascular Interventions (5 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_16_NEURO: MasterProcedure[] = [
  {
    id: 'cat16-diagnostic-4v-dsa',
    categoryNumber: 16,
    categoryName: 'Neurovascular Interventions',
    title: 'Diagnostic 4-Vessel Cerebral Digital Subtraction Angiography (DSA)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Cerebral Angiography',
      packageCode: '1849-CV020A',
      icd10: 'I67.9',
      tariffInr: 15000,
    },
    modality: 'XA',
    targetAnatomy: ["Bilateral Internal Carotid Arteries", "Bilateral Vertebral Arteries", "Circle of Willis"],
    sedation: 'Local Anesthesia with Conscious Sedation / General Anesthesia',
    accessSiteDefault: 'Right Common Femoral Artery or Right Radial Artery',
    sheathDefault: '5F 11cm Vascular Sheath',
    cathetersAndWires: '5F Simmons-2 / Berenstein / H1 catheter, 0.035" hydrophilic Glidewire',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Right CFA punctured at femoral head level; 5F sheath placed. 5F Simmons-2 catheter advanced over 0.035" Glidewire into aortic arch. Selective catheterization of right and left common carotid arteries, internal carotid arteries, and dominant vertebral artery performed. High-frame-rate digital subtraction angiography obtained in AP, lateral, and 3D rotational views with 3D reconstruction of Circle of Willis. Vessel caliber, aneurysm morphology, arteriovenous shunting, collateral flow, and venous sinus phases analyzed. Sheath removed; Angio-Seal vascular closure device deployed achieving instantaneous hemostasis.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 2 hours (with closure device) or 6 hours (with manual compression); right leg straight.',
      hematomaChecks: 'Monitor puncture site, distal pedal pulses, and neurological status (NIHSS assessment) q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'None routine unless acute neurological deficit occurs.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr for rapid contrast clearance.',
      medications: ["Tab Aspirin 75mg OD (if diagnostic)", "Tab Paracetamol 650mg SOS"],
      redFlags: ["Stroke / TIA (iatrogenic thromboembolism or dissection)", "Groin hematoma / retroperitoneal bleed", "Contrast-induced encephalopathy"],
    },
    consentId: 'consent-cerebral-dsa',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat16-stroke-thrombectomy',
    categoryNumber: 16,
    categoryName: 'Neurovascular Interventions',
    title: 'Acute Ischemic Stroke: Mechanical Thrombectomy with Stent Retriever & Direct Aspiration',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Mechanical Thrombectomy for Stroke',
      packageCode: '1849-CV024A',
      icd10: 'I63.5',
      tariffInr: 75000,
    },
    modality: 'XA',
    targetAnatomy: ["Terminal ICA", "Middle Cerebral Artery (M1/M2 Segments)", "Basilar Artery"],
    sedation: 'Local Anesthesia with Conscious Sedation / General Anesthesia',
    accessSiteDefault: 'Right CFA at femoral head level under US/Fluoro',
    sheathDefault: '8F 90cm Guiding Sheath (Ballast / Cerebase) or 8F Balloon Guide Catheter (FlowGate2)',
    cathetersAndWires: '0.035" stiff wire, 6F large-bore aspiration catheter (React 71 / Penumbra RED 72), 0.021" microcatheter, 0.014" microwire (Synchro), Stent Retriever (Solitaire X / Trevo 4-6mm)',
    microcatheterSystem: '0.021" microcatheter',
    embolicOrImplants: 'Solitaire X / Trevo NXT Stent Retriever + Aspiration Catheter',
    proceduralNarrativeTemplate:
      'Emergency code stroke within 24h window for acute right MCA M1 segment occlusion (NIHSS 18). Right CFA accessed; 8F Balloon Guide Catheter positioned in cervical right ICA. Distal intracranial aspiration catheter (React 71) and 0.021" microcatheter advanced over 0.014" wire across M1 occlusion. Microcatheter run confirmed distal M2 branch patency. Solitaire X (4mm x 40mm) stent retriever deployed across clot and unsheathed for 3 minutes for clot integration. Balloon guide inflated with flow arrest. Combined aspiration and stent retriever retrieval performed (SAVE/CAPTIVE technique) under continuous high vacuum aspiration. Thrombus extracted in toto on first pass. Immediate repeat intracranial DSA demonstrated complete, flawless TICI 3 reperfusion with widely patent right MCA and anterior cerebral branches. NIHSS dropped from 18 to 4 in cath-lab.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours in Neuro-ICU. Maintain SBP strictly between 120-140 mmHg.',
      hematomaChecks: 'Continuous neurological examination (NIHSS and GCS) and groin puncture site check q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Non-contrast CT Brain at 24 hours to rule out hemorrhagic transformation and confirm salvage of ischemic penumbra.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr; maintain euvolemia.',
      medications: ["Stat CT Brain before initiating antiplatelet therapy", "Tab Atorvastatin 80mg OD", "IV Labetalol infusion PRN for BP control"],
      redFlags: ["Intracranial hemorrhage / hemorrhagic transformation", "Vessel perforation / subarachnoid hemorrhage", "Distal clot embolization to new territory", "Groin hematoma"],
    },
    consentId: 'consent-stroke-thrombectomy',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat16-aneurysm-coiling',
    categoryNumber: 16,
    categoryName: 'Neurovascular Interventions',
    title: 'Intracranial Aneurysm Endosaccular Coiling with Detachable Microcoils',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Endovascular Coiling of Aneurysm',
      packageCode: '1849-CV025A',
      icd10: 'I60.9',
      tariffInr: 70000,
    },
    modality: 'XA',
    targetAnatomy: ["Anterior Communicating / Posterior Communicating / MCA Bifurcation Aneurysm Sac"],
    sedation: 'Local Anesthesia with Conscious Sedation / General Anesthesia',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '6F 90cm Guiding Sheath',
    cathetersAndWires: '0.035" stiff wire, 5F distal access catheter, 1.7F microcatheter (Headway / Excelsior SL-10), 0.014" Synchro wire, Detachable Platinum Microcoils (Target / Axium / Cosmos)',
    microcatheterSystem: '1.7F microcatheter',
    embolicOrImplants: 'Detachable Platinum Microcoils (Framing, Filling, and Finishing Coils)',
    proceduralNarrativeTemplate:
      'Under general anesthesia, right CFA accessed; 6F guiding catheter navigated into petrous ICA. Working 3D-rotational angiographic view selected. 1.7F microcatheter steam-shaped and navigated into center of 6mm PCom aneurysm sac. Framing coil (Target 3D 6mm x 15cm) deployed creating stable 3D basket. Subsequent filling and finishing microcoils deployed sequentially until complete dense coil packing achieved (>30% packing density). Completion DSA in all projections showed total aneurysm occlusion (Raymond-Roy Class I) with widely patent parent ICA and PCom branches. Sheath removed; Angio-Seal closure.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours.',
      hematomaChecks: 'Continuous neurological and hemodynamic monitoring in Neuro-ICU q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Post-procedure Non-contrast CT Brain; MRA at 6 months.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Therapeutic IV Heparin protocol", "Nimodipine 60mg PO q4h (if subarachnoid hemorrhage)", "Tab Paracetamol 650mg TDS"],
      redFlags: ["Intraprocedural aneurysm rupture", "Thromboembolism of parent vessel / acute stroke", "Coil protrusion into parent artery"],
    },
    consentId: 'consent-aneurysm-coiling',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat16-mma-embolization',
    categoryNumber: 16,
    categoryName: 'Neurovascular Interventions',
    title: 'Middle Meningeal Artery (MMA) Embolization for Chronic Subdural Hematoma (cSDH)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Middle Meningeal Artery Embolization',
      packageCode: '1849-CV026A',
      icd10: 'I62.0',
      tariffInr: 38000,
    },
    modality: 'XA',
    targetAnatomy: ["Middle Meningeal Artery (Anterior and Posterior Convexity Branches)"],
    sedation: 'Local Anesthesia with Conscious Sedation / General Anesthesia',
    accessSiteDefault: 'Right CFA or Right Radial Artery',
    sheathDefault: '5F Sheath',
    cathetersAndWires: '5F Envoy / Simmons, 1.5F - 1.7F microcatheter (Magic / Marathon), 0.014" wire',
    microcatheterSystem: '1.5F microcatheter',
    embolicOrImplants: 'PVA particles (150-250um) or Liquid Embolic (Onyx 18 / Squid 12) or n-BCA glue',
    proceduralNarrativeTemplate:
      'Indicated for recurrent or non-surgical chronic subdural hematoma (cSDH) in elderly patients. Access established. External carotid arteriography performed. 1.5F microcatheter navigated superselectively into anterior and posterior convex branches of MMA distal to petrous and sphenoid origins. Absence of dangerous anastomoses (meningo-ophthalmic, ophthalmic artery collateral) rigorously confirmed on magnified oblique runs. Micro-embolization performed using 150-250um PVA particles followed by Onyx-18 cast in proximal trunks. Complete devascularization of neovascular subdural membrane achieved, stopping microvascular re-bleeding and promoting hematoma resorption.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 4 hours.',
      hematomaChecks: 'Neurological monitoring and access site check q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Non-contrast CT Brain at 1 month to document complete hematoma resolution.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Levetiracetam 500mg BD (seizure prophylaxis)"],
      redFlags: ["Ophthalmic artery embolization / vision loss", "Facial nerve palsy (petrosal branch)", "Hematoma recurrence"],
    },
    consentId: 'consent-cerebral-dsa',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat16-carotid-stenting',
    categoryNumber: 16,
    categoryName: 'Neurovascular Interventions',
    title: 'Carotid Artery Stenting (CAS) with Distal Embolic Protection Device (EPD)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Carotid Artery Stenting',
      packageCode: '1849-VS003A',
      icd10: 'I65.2',
      tariffInr: 45000,
    },
    modality: 'XA',
    targetAnatomy: ["Internal Carotid Artery Bulbar Stenosis", "Common Carotid Artery"],
    sedation: 'Local Anesthesia with Conscious Sedation / General Anesthesia',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '6F - 8F 90cm Guiding Sheath',
    cathetersAndWires: '0.035" stiff wire, Distal Embolic Protection Device (SpiderFX / FilterWire EZ), 0.014" wire, Carotid Nitinol Stent (Acculink / Protégé / CGuard), 5.0mm x 20mm Monorail PTA balloon',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Dedicated Self-Expanding Nitinol Carotid Stent (7-10mm x 30-40mm tapered)',
    proceduralNarrativeTemplate:
      'Symptomatic >70% high-grade bulbar ICA stenosis. Right CFA access. 6F 90cm sheath positioned in distal common carotid artery. Selective carotid angiogram confirmed critical eccentric stenosis. Distal embolic protection filter (SpiderFX 5mm) navigated across stenosis and deployed in cervical ICA below skull base. Pre-dilation performed with 3.5mm balloon. Self-expanding tapered carotid stent (8x6mm x 40mm) deployed across carotid bifurcation. Post-dilation performed with 5.0mm balloon under atropine coverage (1mg IV given to prevent carotid sinus bradycardia). Embolic protection filter captured and retrieved smoothly. Basket inspection showed captured atheromatous debris. Completion DSA confirmed widely patent carotid bulb, zero residual stenosis, and normal intracranial cerebral circulation without distal branch cutoffs.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours; continuous arterial BP monitoring.',
      hematomaChecks: 'Neurological checks and blood pressure surveillance q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Carotid Doppler Ultrasound at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr.',
      medications: ["Dual Antiplatelet Therapy: Aspirin 75mg + Clopidogrel 75mg OD x 3 months", "Tab Atorvastatin 40mg HS", "Maintain SBP 110-130 mmHg"],
      redFlags: ["Hyperperfusion syndrome / intracranial hemorrhage", "Distal stroke / atheroembolism", "Severe hemodynamic depression (bradycardia/hypotension)", "Groin hematoma"],
    },
    consentId: 'consent-carotid-stenting',
    calculatorId: 'cigarroa_macd',
  },
{
    id: 'cat16-jna-embolization',
    categoryNumber: 16,
    categoryName: 'Neurovascular Interventions',
    title: 'Pre-Operative Embolization of Juvenile Nasopharyngeal Angiofibroma (JNA)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Complex Embolization / Head & Neck',
      packageCode: '2849-IR00002550000514',
      icd10: 'D10.6',
      tariffInr: 95000,
    },
    modality: 'XA',
    targetAnatomy: ["Internal Maxillary Artery", "Ascending Pharyngeal Artery", "Accessory Meningeal Branches"],
    sedation: 'General Anesthesia / Conscious Sedation with Anesthesiology Team',
    accessSiteDefault: 'Right Common Femoral Artery (5F Sheath)',
    sheathDefault: '5F 11cm Vascular Introducer Sheath',
    cathetersAndWires: '5F Simmons-2 / C1 diagnostic catheter, 0.035" hydrophilic wire, 2.0F - 2.4F microcatheter (Progreat / Excelsior), 0.014" microwire',
    microcatheterSystem: '2.0F / 2.4F coaxial microcatheter',
    embolicOrImplants: 'Polyvinyl Alcohol (PVA) Particles (300-500 µm or 500-700 µm) / Embosphere microspheres',
    proceduralNarrativeTemplate:
      'Under general anesthesia, right CFA punctured and 5F sheath placed. Selective diagnostic angiography of bilateral external carotid, internal carotid, and vertebral arteries performed. Angiograms demonstrated intensely vascular tumor blush in the nasopharynx and pterygopalatine fossa supplied predominantly by branches of bilateral internal maxillary arteries and ipsilateral ascending pharyngeal artery. Internal carotid runs confirmed absence of significant dangerous intracranial anastomoses. 2.4F microcatheter coaxially navigated superselectively into sphenopalatine and descending palatine branches of the internal maxillary artery. Slow, controlled pulsatile embolization performed using PVA particles (300-500 µm) suspended in non-ionic contrast until complete devascularization and near-total cessation of tumor blush achieved. Post-embolization angiography showed complete devascularization of the angiofibroma with preservation of normal external and internal carotid branch perfusion.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest for 6 hours; right leg kept extended. Check groin for hematoma.',
      hematomaChecks: 'Monitor neurological status, vision, facial symmetry, and groin puncture site every 15 min x 4, every 30 min x 2, then every 1 hr x 2.',
      requiredImaging: 'Pre-operative ENT surgical clearance within 24-48 hours post-embolization.',
      hydrationProtocol: 'IV Normal Saline at 100 mL/hr to maintain adequate diuresis.',
      medications: ["Inj. Paracetamol 1g IV TDS", "Inj. Dexamethasone 8mg IV BD (reduce post-embolization soft tissue edema)", "Inj. Pantoprazole 40mg IV OD"],
      redFlags: ["Acute visual disturbance or diplopia (? accidental ethmoidal/ophthalmic anastomosis embolization)", "Facial nerve weakness", "Expanding groin hematoma"],
    },
    consentId: 'consent-cerebral-dsa',
    calculatorId: 'cigarroa_macd',
  },
];
