import { MasterProcedure } from './types';

/**
 * Category 07: Embolotherapy Trauma & Hemorrhage (5 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_07_EMBOLOTHERAPY: MasterProcedure[] = [
  {
    id: 'cat07-bae-hemoptysis',
    categoryNumber: 7,
    categoryName: 'Embolotherapy Trauma & Hemorrhage',
    title: 'Bronchial Artery Embolization (BAE) for Massive Hemoptysis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Bronchial Artery Embolization (BAE)',
      packageCode: '1849-CV010A',
      icd10: 'R04.2',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["Right / Left Bronchial Arteries", "Intercostobronchial Trunk", "Systemic Collaterals"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '5F 11cm Sheath',
    cathetersAndWires: '5F Mikaelson / Cobra / Simmons catheter, 2.7F / 2.0F microcatheter, 0.014" wire',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'PVA Particles (100-300 µm, 300-500 µm, 500-710 µm, 710-1000 µm) or Embospheres / Microspheres (300-500 µm, 500-700 µm) + Microcoils / Gelfoam slurry',
    proceduralNarrativeTemplate:
      'Indicated for massive hemoptysis (>300 mL/24h). Right CFA accessed. Thoracic descending aortography localized hypervascular bronchial arteries. Selective catheterization of right intercostobronchial trunk and left bronchial artery. Spinal cord collateral (anterior spinal artery / hairpin artery of Adamkiewicz) strictly searched for and ruled out. 2.0F microcatheter advanced distally into bronchial parenchymal branches beyond any spinal takeoff. Embolization performed using PVA particles (300-500 µm or 500-710 µm) or calibrated microspheres until complete prune-tree stasis achieved. Completion angiogram showed total devascularization of hemoptysis nidus with preservation of main bronchial trunk.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine flat bedrest x 6 hours; right leg straight.',
      hematomaChecks: 'Monitor puncture site, vitals, hemoptysis recurrence, and lower extremity motor/sensory function q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Erect Chest X-ray at 4 hours; CT chest if recurrent bleed.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr.',
      medications: ["Tab Tranexamic Acid 500mg TDS x 48h", "Tab Codeine / Dextromethorphan for cough suppression", "IV Ceftriaxone 1g BD"],
      redFlags: ["Spinal cord ischemia / anterior spinal artery syndrome", "Esophageal ulceration / chest pain", "Groin hematoma", "Recurrent hemoptysis"],
    },
    consentId: 'consent-bae-hemoptysis',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat07-pelvic-trauma-embolization',
    categoryNumber: 7,
    categoryName: 'Embolotherapy Trauma & Hemorrhage',
    title: 'Pelvic Trauma: Internal Iliac Artery Bilateral Embolization',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Embolization (TAE)',
      packageCode: '1849-IN063A',
      icd10: 'S35.5',
      tariffInr: 35000,
    },
    modality: 'XA',
    targetAnatomy: ["Internal Iliac Arteries (Anterior / Posterior Divisions)", "Superior Gluteal", "Internal Pudendal"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA under US/Fluoro',
    sheathDefault: '6F Sheath',
    cathetersAndWires: '5F Omni Flush, 5F Cobra, 2.7F microcatheter, 0.035" and 0.018" pushable/detachable coils',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'Gelfoam sponge slurry / Torpedoes, PVA Particles (300-500 µm, 500-710 µm, 710-1000 µm), and/or Microcoils',
    proceduralNarrativeTemplate:
      'Emergency intervention for hemodynamically unstable pelvic fracture with active arterial contrast extravasation. Right CFA accessed. Pelvic angiogram revealed multifocal contrast extravasation from bilateral internal iliac arterial branches (superior gluteal and obturator). Cross-over catheterization of contralateral internal iliac and ipsilateral selective catheterization. Gelfoam torpedoes and 0.035" coils delivered to trunk and major branches. Completion pelvic angiogram demonstrated complete cessation of active extravasation with hemodynamic stabilization (BP normalized from 80/50 to 118/74). Manual pressure hemostasis.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict bedrest x 6 hours.',
      hematomaChecks: 'Continuous invasive BP monitoring, groin check, and lower limb perfusion surveillance q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Repeat Pelvic CT Angiography once stabilized.',
      hydrationProtocol: 'IV fluids and blood products as per massive transfusion protocol.',
      medications: ["Tetanus toxoid", "Broad spectrum IV antibiotics", "Analgesia"],
      redFlags: ["Gluteal necrosis", "Sciatic nerve ischemia", "Groin hematoma", "Re-bleeding"],
    },
    consentId: 'consent-trauma-embolization',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat07-splenic-trauma-embolization',
    categoryNumber: 7,
    categoryName: 'Embolotherapy Trauma & Hemorrhage',
    title: 'Splenic Trauma: Proximal Splenic Artery Plug / Coil Embolization',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Embolization (TAE)',
      packageCode: '1849-IN063A',
      icd10: 'S36.0',
      tariffInr: 32000,
    },
    modality: 'XA',
    targetAnatomy: ["Main Splenic Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA',
    sheathDefault: '6F Sheath',
    cathetersAndWires: '5F Cobra, 0.035" wire, Amplatzer Vascular Plug II (8-10mm) or 0.035" coils',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Amplatzer Vascular Plug II (10mm) / Detachable Coils',
    proceduralNarrativeTemplate:
      'High-grade blunt splenic injury (AAST Grade IV) with pseudoaneurysms and contrast blush. Right CFA accessed. Celiac angiogram performed. 6F sheath placed in mid-splenic artery distal to dorsal pancreatic artery. An Amplatzer Vascular Plug II (10mm) deployed. Follow-up angiogram confirmed flow dampening and immediate cessation of splenic contrast extravasation, while distal spleen remained viable through pancreatic and short gastric collaterals.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict bedrest x 6 hours.',
      hematomaChecks: 'Surveillance of vitals, hematocrit, and left flank pain q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Abdominal USG / CT at 48 hours to confirm splenic preservation.',
      hydrationProtocol: 'IV fluids 100 mL/hr.',
      medications: ["Post-splenectomy immunization counseling if extensive infarction", "IV Ceftriaxone 1g BD"],
      redFlags: ["Delayed splenic rupture", "Splenic abscess", "Re-bleeding"],
    },
    consentId: 'consent-trauma-embolization',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat07-gda-sandwich-coiling',
    categoryNumber: 7,
    categoryName: 'Embolotherapy Trauma & Hemorrhage',
    title: 'Gastroduodenal Artery (GDA) Sandwich Coil Embolization for Duodenal Bleed',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Embolization (TAE)',
      packageCode: '1849-IN063A',
      icd10: 'K26.4',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["Gastroduodenal Artery", "Right Gastroepiploic", "Pancreaticoduodenal Arcades"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '5F Sheath',
    cathetersAndWires: '5F Cobra / Simmons, 2.7F microcatheter, 0.014" wire, microcoils (3-6mm)',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: '0.018" Fibered Microcoils (3mm-6mm)',
    proceduralNarrativeTemplate:
      'Refractory peptic duodenal ulcer bleeding failing endoscopic clips. Celiac angiogram showed GDA blush. 2.7F microcatheter advanced into GDA. Crucial \'sandwich\' technique executed: distal GDA coiled first to prevent retrograde back-bleeding from SMA via inferior pancreaticoduodenal arcades, followed by proximal GDA coiling across the bleeding site. Completion SMA and celiac angiograms confirmed complete elimination of duodenal bleeding from both antegrade and retrograde pathways.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine flat bedrest x 6 hours.',
      hematomaChecks: 'Check groin and monitor for re-bleeding (melena, NG aspirate) q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Upper GI endoscopy / CT on clinical indication.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr.',
      medications: ["IV Pantoprazole 8mg/hr continuous infusion x 72h", "Tab Paracetamol 650mg SOS"],
      redFlags: ["Re-bleeding from SMA arcade collaterals", "Duodenal / hepatic infarction", "Groin bleed"],
    },
    consentId: 'consent-gi-bleed-embolization',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat07-femoral-pseudoaneurysm-thrombin',
    categoryNumber: 7,
    categoryName: 'Embolotherapy Trauma & Hemorrhage',
    title: 'Ultrasound-Guided Percutaneous Thrombin Injection (UGTI) for Femoral Pseudoaneurysm',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Thrombin Injection',
      packageCode: '1849-VS015A',
      icd10: 'I72.4',
      tariffInr: 12000,
    },
    modality: 'US',
    targetAnatomy: ["Common Femoral Artery Pseudoaneurysm Neck and Sac"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous needle puncture under high-frequency linear US',
    sheathDefault: '21G / 22G Spinal Needle',
    cathetersAndWires: 'Direct needle, 1mL syringe with Human Thrombin (1000 IU/mL)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Human Thrombin (500 - 1000 IU)',
    proceduralNarrativeTemplate:
      'High-resolution Doppler ultrasound localized multi-lobulated 3.5cm post-catheterization femoral pseudoaneurysm with typical \'yin-yang\' swirling color flow. Neck length measured (3mm). Under real-time sonography, 22G spinal needle tip positioned precisely in the center of the pseudoaneurysm sac away from the neck. 0.5 mL (500 IU) bovine/human thrombin slowly injected. Instantaneous solid thrombosis of entire sac observed with immediate cessation of swirling flow. Color Doppler confirmed complete thrombosis with widely patent native CFA, SFA, and profunda femoris. Manual pressure maintained x 5 min.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict flat bedrest x 4 hours; treated leg straight.',
      hematomaChecks: 'Color Doppler ultrasound check at bedside at 30 min, 2 hours, and 24 hours.',
      requiredImaging: 'Follow-up duplex Doppler at 24 hours.',
      hydrationProtocol: 'Oral hydration encouraged.',
      medications: ["Tab Paracetamol 650mg SOS"],
      redFlags: ["Distal arterial thromboembolism", "Allergic reaction to thrombin", "Recurrence"],
    },
    consentId: 'consent-pseudoaneurysm-thrombin',
  },
];
