import { MasterProcedure } from './types';

/**
 * Category 04: Lower Extremity & Arterial Revascularization (12 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_04_ARTERIAL: MasterProcedure[] = [
  {
    id: 'cat04-diagnostic-runoff',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Diagnostic Lower Extremity Peripheral Angiography / Runoff',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Peripheral Angiography',
      packageCode: '1849-CV001A',
      icd10: 'I73.9',
      tariffInr: 8000,
    },
    modality: 'XA',
    targetAnatomy: ["Infrarenal Aorta", "Iliac Arteries", "Femoral Arteries", "Popliteal Artery", "Tibial Runoff Vessels"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right or Left CFA under fluoroscopy at femoral head level',
    sheathDefault: '5F 11cm Sheath',
    cathetersAndWires: '5F Pigtail, 5F Omni Flush, 0.035" J-wire',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Right CFA punctured at femoral head level. 5F sheath placed. 5F Omni Flush catheter positioned in abdominal aorta (L1-L2). Stepping digital subtraction angiography (DSA) performed from infrarenal aorta down to bilateral pedal arches. Vessel caliber, flow velocity, collateralization, and hemodynamically significant stenosis or occlusions mapped. Sheath removed; manual compression hemostasis.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine flat bedrest x 6 hours; punctured leg kept straight.',
      hematomaChecks: 'Monitor puncture site and palpate distal pulses (dorsalis pedis, posterior tibial) q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Duplex Ultrasound if distal pulse lost or pulsatile groin mass.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr for contrast elimination.',
      medications: ["Tab Aspirin 75mg OD", "Tab Atorvastatin 40mg HS"],
      redFlags: ["Groin hematoma / pseudoaneurysm", "Loss of pedal pulse / cold limb", "Sudden foot pain"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-cia-angioplasty',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Common Iliac Artery (CIA) Balloon Angioplasty',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transluminal Angioplasty (PTA)',
      packageCode: '1849-VS001A',
      icd10: 'I70.21',
      tariffInr: 18000,
    },
    modality: 'XA',
    targetAnatomy: ["Common Iliac Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Retrograde Ipsilateral or Contralateral CFA',
    sheathDefault: '6F Sheath',
    cathetersAndWires: '0.035" stiff wire, 7mm-9mm x 40mm PTA Balloon',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Retrograde CFA access. Baseline iliac angiogram showed severe focal stenosis of CIA with 25 mmHg systolic pressure gradient. 0.035" stiff Glidewire crossed stenosis. 8mm x 40mm PTA balloon inflated to nominal pressure. Waist effaced. Completion angiogram showed widely patent vessel with residual gradient <5 mmHg.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours.',
      hematomaChecks: 'Check groin site and distal pulses q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Duplex Doppler at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Tab Clopidogrel 75mg OD", "Tab Aspirin 75mg OD"],
      redFlags: ["Groin swelling", "Cold leg", "Severe back pain"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-cia-stenting',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Common Iliac Artery Stenting (Balloon-Expandable / Self-Expanding)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Peripheral Stenting',
      packageCode: '1849-VS002A',
      icd10: 'I70.21',
      tariffInr: 32000,
    },
    modality: 'XA',
    targetAnatomy: ["Common Iliac Artery Ostium / Bifurcation"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Ipsilateral Retrograde CFA',
    sheathDefault: '6F - 7F Sheath',
    cathetersAndWires: '0.035" Amplatz Super Stiff wire, 8-10mm x 40-60mm Balloon-Expandable Stent',
    microcatheterSystem: 'N/A',
    embolicOrImplants: '9mm x 40mm Balloon-Expandable Stent (Omnilink Elite / Express)',
    proceduralNarrativeTemplate:
      'Retrograde CFA access. High-grade calcified ostial CIA stenosis identified. Wire crossed onto Amplatz wire. 9mm x 40mm balloon-expandable stent deployed with 1-2mm protrusion into aortic lumen ensuring ostial coverage. Post-dilated to 9mm. Completion run showed excellent stent expansion, zero residual gradient, and brisk distal runoff.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours.',
      hematomaChecks: 'Monitor groin and pedal pulses q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Doppler USG at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Dual Antiplatelet: Tab Aspirin 75mg + Clopidogrel 75mg OD x 6 months"],
      redFlags: ["Groin bleeding", "Limb ischemia", "Flank pain"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-cerab',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Covered Endovascular Reconstruction of Aortic Bifurcation (CERAB)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Peripheral Stenting',
      packageCode: '1849-VS002A',
      icd10: 'I70.21',
      tariffInr: 65000,
    },
    modality: 'XA',
    targetAnatomy: ["Distal Aorta", "Bilateral Common Iliac Arteries"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Bilateral Retrograde CFA Access',
    sheathDefault: 'Dual 8F - 10F Sheaths',
    cathetersAndWires: '0.035" Amplatz wires, Aortic covered balloon-expandable stent (12-14mm), Bilateral iliac covered stents (7-9mm)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Aortic BeGraft / VBX Stent + Dual Iliac BeGraft Stents',
    proceduralNarrativeTemplate:
      'Indicated for complex TASC II D aortoiliac occlusive disease. Bilateral CFA access. Occlusion traversed from both sides. A 12mm x 40mm balloon-expandable covered stent deployed in distal aorta, flared distally with two 9mm balloons. Simultaneously, bilateral 8mm x 59mm covered stents deployed into the CIA with proximal segments nested tightly within aortic stent (CERAB configuration). Completion angiogram demonstrated anatomical reconstruction of aortic bifurcation with brisk symmetric runoff.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine bedrest x 6 hours; bilateral legs straight.',
      hematomaChecks: 'Monitor bilateral groins and distal pulses q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Bilateral lower extremity Doppler USG at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Dual Antiplatelet Therapy: Aspirin 75mg + Clopidogrel 75mg OD", "Tab Atorvastatin 40mg HS"],
      redFlags: ["Bilateral limb ischemia", "Groin hematoma", "Retroperitoneal hemorrhage"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-sfa-dcb',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Superficial Femoral Artery (SFA) Drug-Coated Balloon (DCB) Angioplasty',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transluminal Angioplasty (PTA)',
      packageCode: '1849-VS001A',
      icd10: 'I70.22',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["Superficial Femoral Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Contralateral Up-and-Over CFA or Antegrade Ipsilateral CFA',
    sheathDefault: '6F Sheath',
    cathetersAndWires: '0.035" / 0.018" wire, 5mm-6mm x 120-200mm Paclitaxel Drug-Coated Balloon (Lutonix / Admiral)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Paclitaxel-Eluting Peripheral Balloon',
    proceduralNarrativeTemplate:
      'Contralateral CFA puncture. 6F 45cm Balkin sheath crossed over aortic bifurcation into ipsilateral SFA. Angiogram showed 15cm complex SFA stenosis. Lesion crossed with 0.018" Glidewire. Pre-dilation with 5mm standard balloon. A 6mm x 150mm paclitaxel drug-coated balloon inflated to nominal pressure for a full 180 seconds to ensure drug delivery into arterial wall. Completion angiogram showed widely patent vessel, no flow-limiting dissection, and brisk 3-vessel runoff.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours.',
      hematomaChecks: 'Puncture site and pedal pulses q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Duplex Doppler at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Tab Aspirin 75mg OD", "Tab Clopidogrel 75mg OD", "Tab Cilostazol 100mg BD"],
      redFlags: ["Groin hematoma", "Acute limb pain", "Distal embolization"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-sfa-viabahn',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'SFA Endovascular Covered Stenting (Viabahn Endoprosthesis)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Peripheral Stenting',
      packageCode: '1849-VS002A',
      icd10: 'I70.22',
      tariffInr: 45000,
    },
    modality: 'XA',
    targetAnatomy: ["Superficial Femoral Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Contralateral Up-and-Over CFA',
    sheathDefault: '6F - 7F Long Sheath',
    cathetersAndWires: '0.035" stiff Glidewire, 6mm x 150-250mm Gore Viabahn Endoprosthesis with Heparin bioactive surface',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Gore Viabahn Covered Stent (6mm x 150mm)',
    proceduralNarrativeTemplate:
      'Indicated for long-segment TASC C/D SFA chronic total occlusion. Recanalization achieved with 0.035" Glidewire and catheter. Pre-dilated with 5mm balloon. A 6mm x 150mm heparin-bonded Viabahn covered stent deployed with 5-10% oversizing. Post-dilated with 6mm balloon. Complete exclusion of diseased segment with brisk inline flow.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours.',
      hematomaChecks: 'Groin checks and pedal pulse palpation q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Doppler USG at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Dual Antiplatelet Therapy x 12 months minimum"],
      redFlags: ["Sudden leg coldness / acute stent thrombosis", "Groin bleed"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-popliteal-supera',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Popliteal Interwoven Nitinol Stenting (Supera)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Peripheral Stenting',
      packageCode: '1849-VS002A',
      icd10: 'I70.23',
      tariffInr: 42000,
    },
    modality: 'XA',
    targetAnatomy: ["Popliteal Artery (P1, P2, P3 Segments)"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Contralateral or Antegrade CFA',
    sheathDefault: '6F Sheath',
    cathetersAndWires: '0.014" / 0.018" wire, 5mm-6mm x 60-100mm Supera Interwoven Nitinol Stent',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Supera High Radial Strength Interwoven Nitinol Stent',
    proceduralNarrativeTemplate:
      'Indicated for severe popliteal stenosis with high flexion stress. Lesion crossed. Aggressive 1:1 pre-dilation performed with non-compliant balloon. A 5.5mm x 80mm Supera interwoven stent deployed using 1:1 nominal deployment technique to avoid compression. Post-dilation performed. Complete luminal restoration with full knee flexion mobility.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict bedrest x 6 hours.',
      hematomaChecks: 'Distal pulse and knee check q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Popliteal Doppler USG at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Aspirin 75mg + Clopidogrel 75mg OD"],
      redFlags: ["Acute popliteal thrombosis", "Groin hematoma"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-btk-dcb',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Below-the-Knee (BTK) Tibial Drug-Coated Balloon Angioplasty',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transluminal Angioplasty (PTA)',
      packageCode: '1849-VS001A',
      icd10: 'I70.24',
      tariffInr: 28000,
    },
    modality: 'XA',
    targetAnatomy: ["Anterior Tibial Artery", "Posterior Tibial Artery", "Peroneal Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Antegrade Ipsilateral CFA Puncture under US',
    sheathDefault: '5F 45cm Sheath',
    cathetersAndWires: '0.014" microguidewire, 2.5mm-3.0mm x 150-200mm Long Tibial DCB',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'Paclitaxel / Sirolimus Tibial Drug-Coated Balloon',
    proceduralNarrativeTemplate:
      'Indicated for Critical Limb-Threatening Ischemia (CLTI / Rutherford 5). Antegrade CFA puncture. 5F sheath placed. 0.014" Command wire crossed long chronic total occlusion of anterior tibial artery into dorsalis pedis. Pre-dilation with 2.5mm x 150mm balloon. 2.75mm x 180mm tibial DCB inflated for 180 seconds. Completion run showed inline single-vessel straight-line pulsatile flow to pedal arch.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours; leg straight.',
      hematomaChecks: 'Hourly distal pulse check and capillary refill assessment.',
      requiredImaging: 'Pedal Doppler at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Dual Antiplatelet Therapy", "Wound care protocol"],
      redFlags: ["Foot compartment syndrome", "Groin bleeding", "Embolization"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-safari-pedal',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Retrograde Tibial / Pedal Access Revascularization (SAFARI Technique)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transluminal Angioplasty (PTA)',
      packageCode: '1849-VS001A',
      icd10: 'I70.24',
      tariffInr: 32000,
    },
    modality: 'XA',
    targetAnatomy: ["Dorsalis Pedis", "Posterior Tibial Artery", "Anterior Tibial Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Retrograde Pedal Artery Puncture under US + Antegrade CFA',
    sheathDefault: '4F / Micro-introducer pedal sheath',
    cathetersAndWires: '21G micropuncture needle, 0.014" guidewire, 2.0mm-3.0mm PTA balloon',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Failed antegrade crossing of flush tibial CTO. Under high-frequency ultrasound, retrograde puncture of dorsalis pedis artery performed with 21G needle. 0.014" wire advanced retrograde through pedal sheath, successfully traversing CTO retrograde into popliteal artery. Wire snared in antegrade sheath (SAFARI technique) establishing through-and-through flossing wire. Antegrade balloon angioplasty performed. Brisk straight-line flow restored to ischemic foot ulcer.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours.',
      hematomaChecks: 'Check pedal puncture site and CFA site q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Pedal duplex at 24 hours.',
      hydrationProtocol: 'IV fluids 75 mL/hr.',
      medications: ["Dual Antiplatelet: Aspirin + Clopidogrel", "IV antibiotics"],
      redFlags: ["Pedal occlusion / hematoma", "Spasm"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-rotarex-atherectomy',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Mechanical Rotational Atherectomy & Thrombectomy (Rotarex)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transluminal Angioplasty (PTA)',
      packageCode: '1849-VS001A',
      icd10: 'I74.3',
      tariffInr: 38000,
    },
    modality: 'XA',
    targetAnatomy: ["Superficial Femoral Artery", "Popliteal Artery"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Contralateral or Antegrade CFA',
    sheathDefault: '6F - 8F Sheath',
    cathetersAndWires: '0.018" dedicated guidewire, 6F Rotarex catheter system',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Indicated for subacute femoropopliteal thrombosis / in-stent restenosis. Rotarex rotational thrombectomy and atherectomy catheter advanced over 0.018" wire. Helix rotated at 40,000 RPM creating continuous Archimedes screw vacuum. Multiple slow passes made debulking thrombus and atheroma. High-grade luminal restoration confirmed on DSA without distal embolization. Adjunctive DCB performed.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours.',
      hematomaChecks: 'Groin check and pedal pulse monitoring q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Doppler at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Therapeutic anticoagulation bridging to antiplatelet"],
      redFlags: ["Distal embolization", "Vessel perforation", "Groin hematoma"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-ivl-shockwave',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Shockwave Intravascular Lithotripsy (IVL) of Calcified Peripheral Arteries',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Percutaneous Transluminal Angioplasty (PTA)',
      packageCode: '1849-VS001A',
      icd10: 'I70.22',
      tariffInr: 45000,
    },
    modality: 'XA',
    targetAnatomy: ["Common Iliac", "SFA", "Popliteal"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Retrograde or Antegrade CFA',
    sheathDefault: '6F - 7F Sheath',
    cathetersAndWires: '0.014" wire, Shockwave M5+ / S4 Lithotripsy Balloon (5.0mm-7.0mm)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Shockwave IVL Peripheral Catheter',
    proceduralNarrativeTemplate:
      'Severe circumferential arterial calcification preventing balloon expansion. Shockwave M5+ IVL balloon positioned across calcified lesion. Balloon inflated to 4 atm. Acoustic sonic pressure waves delivered (up to 300 pulses) fracturing superficial and deep medial calcium. Post-dilation to nominal pressure achieved full expansion without dissection.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours.',
      hematomaChecks: 'Groin check and distal pulse check q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Duplex Doppler at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Dual Antiplatelet Therapy"],
      redFlags: ["Dissection", "Distal embolization", "Hematoma"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'fontaine_rutherford',
  },
  {
    id: 'cat04-cdt-ali',
    categoryNumber: 4,
    categoryName: 'Lower Extremity & Arterial Revascularization',
    title: 'Catheter-Directed Thrombolysis (CDT) for Acute Limb Ischemia (ALI)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Thrombolysis',
      packageCode: '1849-VS005A',
      icd10: 'I74.3',
      tariffInr: 28000,
    },
    modality: 'XA',
    targetAnatomy: ["Femoral", "Popliteal", "Tibial Arteries"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Contralateral Up-and-Over CFA',
    sheathDefault: '5F - 6F Sheath',
    cathetersAndWires: '0.035" wire, 4F/5F Multi-sidehole infusion catheter (Cragg-McNamara / Fountain 10-20cm)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Alteplase (rtPA) continuous infusion',
    proceduralNarrativeTemplate:
      'Indicated for Rutherford IIa/IIb acute limb ischemia. Multi-sidehole catheter embedded directly across thrombosed arterial segment. Bolus rtPA (5mg) delivered, followed by continuous infusion at 0.5 - 1.0 mg/hr along with sub-therapeutic unfractionated heparin (500 units/hr). Patient transferred to ICU. Check angiogram at 12-18 hours demonstrated complete thrombus resolution uncovering underlying focal SFA stenosis, which was successfully treated with DCB.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict ICU bedrest; leg immobilized throughout infusion.',
      hematomaChecks: 'Monitor puncture site, vitals, neurovascular status, and fibrinogen q1h.',
      requiredImaging: 'Check angiogram at 12-18 hours.',
      hydrationProtocol: 'IV fluids titrated to maintain urine output >50 mL/hr.',
      medications: ["IV rtPA infusion protocol", "IV Heparin", "Pain management"],
      redFlags: ["Major systemic / intracranial hemorrhage", "Distal trash embolization", "Groin hematoma"],
    },
    consentId: 'consent-cdt-thrombolysis',
    calculatorId: 'fontaine_rutherford',
  },
{
    id: 'cat04-cfa-thrombin-injection',
    categoryNumber: 4,
    categoryName: 'Peripheral Arterial Interventions',
    title: 'Ultrasound-Guided Percutaneous Thrombin Injection for Femoral Pseudoaneurysm',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Thrombin Injection',
      packageCode: '2849-IR000011300000529',
      icd10: 'I72.4',
      tariffInr: 25000,
    },
    modality: 'US',
    targetAnatomy: ["Common Femoral Artery Pseudoaneurysm Sac"],
    sedation: 'Local Anesthesia (1% Lignocaine)',
    accessSiteDefault: 'Direct Percutaneous Puncture under US Guidance',
    sheathDefault: 'N/A (21G or 22G Chiba Needle)',
    cathetersAndWires: 'N/A',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Human / Bovine Thrombin (500 - 1000 IU/mL)',
    proceduralNarrativeTemplate:
      'High-resolution color Doppler ultrasound of the right groin delineated a 3.2 cm lobulated pseudoaneurysm arising from the anterior wall of the common femoral artery with classic "yin-yang" turbulent flow and a 2.5 mm neck. Under continuous real-time US guidance, a 21G spinal needle was placed into the center of the pseudoaneurysm sac, keeping the tip well away from the neck. Fresh arterial blood aspirated. Human Thrombin (800 IU in 0.8 mL NS) was slowly injected. Immediate, complete internal thrombosis of the aneurysm sac was visualized within 10 seconds under real-time B-mode. Color Doppler confirmed complete absence of flow within the sac with widely patent, laminar flow through the underlying common femoral, superficial femoral, and profunda femoris arteries. Distal pedal pulses remained full and bounding.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bed rest for 2 hours. Pressure bandage over groin. Avoid heavy lifting or strenuous exertion for 48 hours.',
      hematomaChecks: 'Check groin for recurrence of thrill or bruit every 30 min x 2h, then before discharge.',
      requiredImaging: 'Groin color Doppler ultrasound at 24 hours to confirm complete persistent occlusion.',
      hydrationProtocol: 'Oral fluids ad libitum.',
      medications: ["Tab Paracetamol 650mg SOS for mild local ache"],
      redFlags: ["Sudden cold, painful, pale lower limb (? intra-arterial thrombin escape / downstream thrombosis)", "Aneurysm re-expansion"],
    },
    consentId: 'consent-pseudoaneurysm-thrombin',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat04-bae-massive-hemoptysis',
    categoryNumber: 4,
    categoryName: 'Peripheral Arterial Interventions',
    title: 'Bronchial Artery Embolization (BAE) for Massive / Recurrent Hemoptysis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Complex Embolization / Bronchial',
      packageCode: '2849-IR00002550000514',
      icd10: 'R04.2',
      tariffInr: 95000,
    },
    modality: 'XA',
    targetAnatomy: ["Orthotopic Bronchial Arteries", "Intercostobronchial Trunks", "Non-Bronchial Systemic Collaterals"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right Common Femoral Artery (5F Sheath)',
    sheathDefault: '5F 11cm Introducer Sheath',
    cathetersAndWires: '5F Mikaelsson / Simmons-1 / Cobra-2 catheter, 0.035" wire, 2.7F Progreat microcatheter, 0.014" microwire',
    microcatheterSystem: '2.7F Microcatheter',
    embolicOrImplants: 'PVA Particles (355-500 µm) and Platinum Pushable Microcoils',
    proceduralNarrativeTemplate:
      'Indicated for life-threatening recurrent hemoptysis (>400 mL/24h) in post-tubercular bronchiectasis. Right CFA access. Descending thoracic aortogram performed. Right intercostobronchial trunk and left bronchial artery selectively cannulated using 5F Mikaelsson catheter. Runs revealed severe vessel tortuosity, marked hypertrophy, and hypervascular parenchymal blush with systemic-to-pulmonary venous shunting in the right upper and middle lobes. Meticulous magnified evaluation rigorously ruled out origin of the anterior spinal artery (Artery of Adamkiewicz). 2.7F microcatheter navigated distally past spinal collaterals. Embolization performed with 355-500 µm PVA particles until near-complete pruned stasis. Subsequent non-bronchial collateral interrogation showed hypertrophied right internal mammary and lateral thoracic collaterals which were superselectively embolized. Final runs confirmed total cessation of abnormal vascular blush.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest for 6 hours; right leg straight.',
      hematomaChecks: 'Monitor vital signs, oxygen saturation, sputum production, and bilateral lower extremity motor/sensory function (rule out transverse myelitis) every 15 min x 4, every 30 min x 2, then every 1 hr x 2.',
      requiredImaging: 'Chest X-ray at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Inj. Paracetamol 1g IV TDS", "Inj. Tranexamic Acid 500mg IV TDS", "Inj. Codeine/Dextromethorphan syrup SOS to suppress coughing fits"],
      redFlags: ["Bilateral leg weakness or sensory loss (anterior spinal artery ischemia)", "Recurrent massive hemoptysis", "Groin hematoma"],
    },
    consentId: 'consent-bronchial-embolization',
    calculatorId: 'cigarroa_macd',
  },
];
