import { MasterProcedure } from './types';

/**
 * Category 14: MSK Embolization & Sports Medicine (4 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_14_MSK: MasterProcedure[] = [
  {
    id: 'cat14-gae-knee-oa',
    categoryNumber: 14,
    categoryName: 'MSK Embolization & Sports Medicine',
    title: 'Genicular Artery Embolization (GAE) for Mild-to-Moderate Knee Osteoarthritis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Genicular Artery Embolization (GAE)',
      packageCode: '1849-IN067A',
      icd10: 'M17.1',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["Descending Genicular Artery", "Superior Medial / Lateral Genicular Arteries", "Inferior Medial Genicular Artery"],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Ipsilateral Antegrade CFA or Contralateral Retrograde CFA Access',
    sheathDefault: '4F - 5F 11cm Sheath',
    cathetersAndWires: '4F/5F Glidecath / Cobra, 1.7F - 2.0F Microcatheter (Progreat / Carnelian), 0.014" wire',
    microcatheterSystem: '1.7F - 2.0F microcatheter',
    embolicOrImplants: 'Imipenem/Cilastatin (IPM/CS) micro-particles (100-300um) or Embozene (75-100um) calibrated microspheres',
    proceduralNarrativeTemplate:
      'Indicated for severe refractory knee pain from medial compartment osteoarthritis (Kellgren-Lawrence Grade 2-3) failing physical therapy and injections. CFA accessed. Selective popliteal arteriogram performed with knee extended. Hypervascular pathological neo-angiogenesis \'blush\' identified in medial compartment supplied by descending and inferior medial genicular arteries. 2.0F microcatheter advanced superselectively into the hypervascular genicular branches. 100-200um calibrated microspheres slowly infused until pathological blush completely resolved while preserving the normal main trunk of the genicular artery. Completion run showed complete disappearance of abnormal synoviocyte capillary blush.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 4 hours; knee in comfortable semi-flexed position.',
      hematomaChecks: 'Check groin site, pedal pulses, and knee skin temperature/color q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'None routine.',
      hydrationProtocol: 'Oral hydration.',
      medications: ["Tab Paracetamol 650mg TDS x 3 days", "Tab Celecoxib 100mg BD x 3 days"],
      redFlags: ["Cutaneous ischemia / transient skin erythema", "Distal foot embolization", "Groin hematoma"],
    },
    consentId: 'consent-gae-embolization',
  },
  {
    id: 'cat14-frozen-shoulder-embolization',
    categoryNumber: 14,
    categoryName: 'MSK Embolization & Sports Medicine',
    title: 'Shoulder / Adhesive Capsulitis (Frozen Shoulder) Embolization',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Embolization (TAE)',
      packageCode: '1849-IN063A',
      icd10: 'M75.0',
      tariffInr: 28000,
    },
    modality: 'XA',
    targetAnatomy: ["Anterior / Posterior Circumflex Humeral Arteries", "Thoracoacromial Trunk", "Suprascapular Artery"],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Right Radial or CFA Access',
    sheathDefault: '4F - 5F Sheath',
    cathetersAndWires: '4F Cobra, 1.7F - 2.0F microcatheter, 0.014" wire',
    microcatheterSystem: '1.7F microcatheter',
    embolicOrImplants: 'Embozene microspheres (75-100um) or Imipenem/Cilastatin slurry',
    proceduralNarrativeTemplate:
      'Indicated for intractable chronic adhesive capsulitis in the freezing/frozen phase. Diagnostic subclavian and axillary arteriograms demonstrated hypervascular synovial blush over anterior glenohumeral joint capsule and rotator interval supplied by circumflex humeral and thoracoacromial branches. Microcatheter navigated into capsule feeders. Slow particulate embolization performed until pathological synovial blush cleared. Immediate improvement in passive range of motion demonstrated in recovery.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours (if radial access, wrist band x 2h).',
      hematomaChecks: 'Radial/femoral puncture site check and neurovascular check of arm q15m x 1h, then q30m.',
      requiredImaging: 'None routine.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS", "Early active/passive shoulder physiotherapy from Day 2"],
      redFlags: ["Transient skin discoloration over deltoid", "Radial artery spasm", "Hematoma"],
    },
    consentId: 'consent-gae-embolization',
  },
  {
    id: 'cat14-tennis-elbow-tame',
    categoryNumber: 14,
    categoryName: 'MSK Embolization & Sports Medicine',
    title: 'Lateral Epicondylitis (Tennis Elbow) Transcatheter Arterial Micro-Embolization (TAME)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Embolization (TAE)',
      packageCode: '1849-IN063A',
      icd10: 'M77.1',
      tariffInr: 25000,
    },
    modality: 'XA',
    targetAnatomy: ["Radial Recurrent Artery", "Interosseous Recurrent Artery"],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Ipsilateral Brachial or Radial Access',
    sheathDefault: '4F Micro-sheath',
    cathetersAndWires: '4F catheter, 1.7F microcatheter, 0.014" wire',
    microcatheterSystem: '1.7F microcatheter',
    embolicOrImplants: 'Imipenem/Cilastatin emulsion or 100um microspheres',
    proceduralNarrativeTemplate:
      'For chronic refractory lateral epicondylitis. Brachial angiogram revealed abnormal capillary hypervascularity at common extensor tendon insertion. Microcatheter navigated into radial recurrent branch. Embolization performed until hypervascularity abolished. Pain score (VAS) improved significantly post-procedure.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Arm resting on sling x 2 hours.',
      hematomaChecks: 'Monitor puncture site and radial pulse q30m x 2h.',
      requiredImaging: 'None routine.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS"],
      redFlags: ["Transient forearm numbness", "Hematoma"],
    },
    consentId: 'consent-gae-embolization',
  },
  {
    id: 'cat14-shoulder-barbotage',
    categoryNumber: 14,
    categoryName: 'MSK Embolization & Sports Medicine',
    title: 'Ultrasound-Guided Barbotage & Lavage for Calcific Shoulder Tendinopathy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Ultrasound-Guided Joint / Tendon Intervention',
      packageCode: '1849-IN068A',
      icd10: 'M75.3',
      tariffInr: 8000,
    },
    modality: 'US',
    targetAnatomy: ["Supraspinatus Tendon Calcific Deposit", "Subacromial Bursa"],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Direct percutaneous under high-frequency linear US',
    sheathDefault: '18G - 20G Needles (Dual Needle Technique)',
    cathetersAndWires: 'Linear 12-18 MHz US probe, warm normal saline syringes, 1% lignocaine, 40mg Triamcinolone',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Triamcinolone Acetonide 40mg',
    proceduralNarrativeTemplate:
      'High-frequency ultrasound identified dense 14mm calcific deposit with acoustic shadowing in supraspinatus tendon. Under local anesthesia, two 18G needles positioned within calcification under real-time ultrasound. Continuous pulsing lavage (barbotage) with warm sterile saline performed across the needles, flushing and aspirating creamy calcium slurry into syringes. Calcific deposit fully debulked. 40mg triamcinolone + 2 mL 1% lignocaine injected into subacromial-subdeltoid bursa. Post-procedure ultrasound confirmed near-total clearance of calcium.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Arm in sling for 24 hours.',
      hematomaChecks: 'Check puncture site and shoulder range of motion.',
      requiredImaging: 'Ultrasound review at 4 weeks.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS", "Gentle pendulum exercises from 24 hours"],
      redFlags: ["Subdeltoid bursitis flare", "Tendon rupture (avoid intratendinous steroid)", "Infection"],
    },
    consentId: 'consent-joint-injection',
  },
];
