import { MasterProcedure } from './types';

/**
 * Category 06: Visceral & Renal Arteries (3 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_06_VISCERAL_RENAL: MasterProcedure[] = [
  {
    id: 'cat06-renal-angioplasty-stent',
    categoryNumber: 6,
    categoryName: 'Visceral & Renal Arteries',
    title: 'Renal Artery Balloon Angioplasty & Stenting',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Renal Angioplasty / Stenting',
      packageCode: '1849-VS008A',
      icd10: 'I70.1',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["Main Renal Artery Ostium"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '6F 45cm Renal Guiding Sheath (RDC / Vista Brite Tip)',
    cathetersAndWires: '0.014" Spartan / Command guidewire, 5.0mm-7.0mm x 15-20mm Balloon-Expandable Stent',
    microcatheterSystem: 'N/A',
    embolicOrImplants: '5.0mm - 6.0mm x 18mm Balloon-Expandable Stent (Express SD / Herculink)',
    proceduralNarrativeTemplate:
      'Indicated for renovascular hypertension or ischemic nephropathy with >70% ostial renal stenosis. Right CFA accessed; 6F RDC guiding catheter engaged renal ostium. Trans-lesional systolic pressure gradient was 35 mmHg. 0.014" wire carefully crossed stenosis. 5.5mm x 18mm balloon-expandable stent deployed across ostium with 1mm aortic protrusion. Post-dilation performed. Completion angiogram showed widely patent renal artery with no dissection and zero residual gradient.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine bedrest x 6 hours; right leg straight.',
      hematomaChecks: 'Monitor groin puncture site, blood pressure, and urine output q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Renal Artery Doppler Ultrasound at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr.',
      medications: ["Dual Antiplatelet: Aspirin 75mg + Clopidogrel 75mg OD", "Antihypertensives adjusted based on BP response"],
      redFlags: ["Renal artery dissection / thrombosis", "Cholesterol atheroembolization (blue toe)", "Groin hematoma"],
    },
    consentId: 'consent-renal-stent',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat06-renal-denervation-rf',
    categoryNumber: 6,
    categoryName: 'Visceral & Renal Arteries',
    title: 'Renal Denervation (RDN) using Radiofrequency Energy (Symplicity Spyral)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Renal Denervation',
      packageCode: '1849-CV022A',
      icd10: 'I10',
      tariffInr: 45000,
    },
    modality: 'XA',
    targetAnatomy: ["Main Renal Arteries", "Renal Branch Vessels"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA',
    sheathDefault: '6F Sheath',
    cathetersAndWires: 'Symplicity Spyral Multi-Electrode Catheter, 0.014" wire, RF generator',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Symplicity Spyral RF Catheter',
    proceduralNarrativeTemplate:
      'For resistant hypertension failing multiple medications. Bilateral renal arteriograms confirmed suitable anatomy. Symplicity Spyral multi-electrode catheter navigated into main renal artery and branch vessels. Four-quadrant circumferential RF ablations delivered across all segments (main and branches) under conscious sedation with adequate IV analgesia. Complete bilateral ablation accomplished. Final angiograms confirmed normal renal perfusion without spasm or dissection.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours.',
      hematomaChecks: 'BP monitoring and groin check q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Renal Doppler at 1 month.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Tab Aspirin 75mg OD", "Continue baseline antihypertensive regimen"],
      redFlags: ["Renal artery spasm", "Groin hematoma", "Hypotension"],
    },
    consentId: 'consent-renal-stent',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat06-sma-stenting',
    categoryNumber: 6,
    categoryName: 'Visceral & Renal Arteries',
    title: 'Superior Mesenteric Artery (SMA) Stenting for Chronic Mesenteric Ischemia',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Peripheral Stenting',
      packageCode: '1849-VS002A',
      icd10: 'K55.1',
      tariffInr: 35000,
    },
    modality: 'XA',
    targetAnatomy: ["Superior Mesenteric Artery Ostium"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Left Brachial Artery or Right CFA Access',
    sheathDefault: '6F 55cm Guiding Sheath',
    cathetersAndWires: '0.014" / 0.018" wire, 6.0mm-8.0mm x 20-30mm Balloon-Expandable Stent',
    microcatheterSystem: 'N/A',
    embolicOrImplants: '6.0mm - 7.0mm x 20mm Balloon-Expandable Covered / Bare Stent',
    proceduralNarrativeTemplate:
      'Indicated for postprandial angina and profound weight loss due to severe ostial SMA stenosis. Left brachial/femoral access. Lateral projection aortogram delineated down-sloping ostial SMA plaque. 0.014" wire crossed lesion. 6.5mm x 20mm balloon-expandable stent deployed across ostium. Completion run confirmed widely patent SMA with rapid mesenteric bowel opacification and elimination of gradient.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours (if femoral) or 3 hours (if brachial).',
      hematomaChecks: 'Monitor access site, distal pulses, and abdominal pain q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Mesenteric Doppler USG at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Aspirin 75mg + Clopidogrel 75mg OD", "Tab Pantoprazole 40mg OD"],
      redFlags: ["Mesenteric reperfusion injury", "Dissection", "Puncture site hematoma"],
    },
    consentId: 'consent-pad-revascularization',
    calculatorId: 'cigarroa_macd',
  },
{
    id: 'cat06-gda-pseudoaneurysm-embolization',
    categoryNumber: 6,
    categoryName: 'Visceral & Renal Arteries',
    title: 'Gastroduodenal Artery (GDA) Pseudoaneurysm Sandwich Embolization (Coils + Glue)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Complex Visceral Embolization',
      packageCode: '2849-IR00002550000514',
      icd10: 'I72.8',
      tariffInr: 95000,
    },
    modality: 'XA',
    targetAnatomy: ["Gastroduodenal Artery (GDA)", "Superior Pancreaticoduodenal Artery", "Celiac Trunk"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right Common Femoral Artery (5F Sheath)',
    sheathDefault: '5F 11cm Vascular Sheath',
    cathetersAndWires: '5F C1 / Cobra-2 / Simmons-1 catheter, 0.035" hydrophilic wire, 2.7F Progreat microcatheter, 0.014" wire',
    microcatheterSystem: '2.7F Progreat Microcatheter',
    embolicOrImplants: 'Pushable Fibered Platinum Coils (Tornado / Nester 3-6mm) and/or Histoacryl (nBCA) + Lipiodol (1:3)',
    proceduralNarrativeTemplate:
      'Indicated for acute upper gastrointestinal hemorrhage / hemoperitoneum secondary to necrotizing pancreatitis with pseudoaneurysm. Right CFA accessed. Celiac trunk catheterized with 5F Cobra catheter. Angiography demonstrated a 22 mm bleeding pseudoaneurysm arising from the mid-gastroduodenal artery. Microcatheter navigated past the pseudoaneurysm neck into the distal GDA (back-door). Embolization performed with fibered microcoils to eliminate retrograde flow from the inferior pancreaticoduodenal arcades. The microcatheter was then withdrawn to the proximal GDA across the aneurysm neck (front-door), and dense coil packing with nBCA-Lipiodol (1:3 mixture) was performed (Sandwich technique). SMA angiogram confirmed complete absence of collateral backflow into the aneurysm. Celiac run confirmed total thrombosis of pseudoaneurysm with widely preserved hepatic arterial flow.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine bedrest for 6 hours with access limb straight.',
      hematomaChecks: 'Monitor vital signs, abdominal girth, hemoglobin levels, and right groin every 15 min x 4, every 30 min x 2, then every 1 hr x 2.',
      requiredImaging: 'Doppler USG or Contrast CT Abdomen at 48 hours to confirm complete aneurysm thrombosis.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Inj. Paracetamol 1g IV TDS", "Inj. Pantoprazole 40mg IV BD", "Inj. Tramadol 50mg IV SOS for visceral pain"],
      redFlags: ["Re-bleeding / drop in Hb > 2 g/dL", "Hepatic ischemia / elevated transaminases", "Expanding groin hematoma"],
    },
    consentId: 'consent-visceral-embolization',
    calculatorId: 'cigarroa_macd',
  },
];
