import { MasterProcedure } from './types';

/**
 * Category 09: Interventional Oncology Percutaneous Ablation (5 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_09_IO_ABLATION: MasterProcedure[] = [
  {
    id: 'cat09-liver-mwa',
    categoryNumber: 9,
    categoryName: 'Interventional Oncology Percutaneous Ablation',
    title: 'Ultrasound / CT-Guided Microwave Ablation (MWA) of Hepatocellular Carcinoma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Microwave Ablation (MWA)',
      packageCode: '1849-MG081A',
      icd10: 'C22.0',
      tariffInr: 35000,
    },
    modality: 'US',
    targetAnatomy: ["Liver Segment 6/7/8/4 Focal Lesion"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Right intercostal or subcostal approach',
    sheathDefault: '14G - 17G Microwave Antenna (Emprint / NeuWave)',
    cathetersAndWires: 'Coaxial needle, 14G-17G MWA antenna, microwave generator, cooling pump',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Patient supine/lateral. Ultrasound and CT fusion localized 2.8cm HCC in Segment 6. Sterile prep. Local infiltration with 2% lignocaine down to capsule. Under real-time ultrasound and CT guidance, a 14G internally cooled microwave antenna was advanced into the tumor center. Hydrodissection performed with 500 mL 5% Dextrose separating liver capsule from adjacent hepatic flexure of colon. Microwave energy applied at 65W for 6 minutes. Hyperechoic gas bubble completely enveloped tumor with a >5mm ablative safety margin. Track ablation performed during antenna removal. Immediate contrast-enhanced ultrasound confirmed complete non-enhancement (complete necrosis) of lesion.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Right lateral decubitus x 2 hours, then supine bedrest x 2 hours.',
      hematomaChecks: 'Monitor puncture site, pain score, and vitals q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Bedside USG if severe abdominal pain or drop in BP.',
      hydrationProtocol: 'Oral fluids after 2 hours.',
      medications: ["Tab Paracetamol 650mg TDS", "Cap Pantoprazole 40mg OD", "IV Tramadol 50mg SOS"],
      redFlags: ["Thermal injury to adjacent bowel / colon perforation", "Subcapsular hematoma / hemoperitoneum", "Biliary duct thermal stricture"],
    },
    consentId: 'consent-tumor-ablation',
  },
  {
    id: 'cat09-liver-rfa',
    categoryNumber: 9,
    categoryName: 'Interventional Oncology Percutaneous Ablation',
    title: 'Ultrasound-Guided Radiofrequency Ablation (RFA) of Liver Tumors',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Radiofrequency Ablation (RFA)',
      packageCode: '1849-MG080A',
      icd10: 'C22.0',
      tariffInr: 30000,
    },
    modality: 'US',
    targetAnatomy: ["Hepatic Parenchymal Tumor"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Subcostal or intercostal approach',
    sheathDefault: '17G RFA Expandable / Internally Cooled Needle',
    cathetersAndWires: '17G Cool-tip / LeVeen RFA needle, grounding pads, RF generator',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Ultrasound-guided percutaneous access. Dual grounding pads placed on patient thighs. 17G internally cooled RF electrode advanced into tumor core. RF current applied with impedance control protocol, achieving roll-off after 12 minutes. Track ablation completed. Post-ablation ultrasound confirmed complete hyperechoic coverage with clear margins.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 4 hours.',
      hematomaChecks: 'Vitals and site checks q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Contrast CT at 1 month to confirm complete response.',
      hydrationProtocol: 'IV fluids 75 mL/hr.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Pantoprazole 40mg OD"],
      redFlags: ["Pneumothorax (if high dome)", "Bleeding", "Bile leak"],
    },
    consentId: 'consent-tumor-ablation',
  },
  {
    id: 'cat09-lung-mwa',
    categoryNumber: 9,
    categoryName: 'Interventional Oncology Percutaneous Ablation',
    title: 'CT-Guided Microwave Ablation (MWA) of Primary / Secondary Lung Malignancy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Microwave Ablation (MWA)',
      packageCode: '1849-MG081A',
      icd10: 'C34.9',
      tariffInr: 38000,
    },
    modality: 'CT',
    targetAnatomy: ["Peripheral Lung Parenchymal Lesion"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Percutaneous transthoracic approach under CT fluoroscopy',
    sheathDefault: '16G - 17G Microwave Antenna',
    cathetersAndWires: 'CT grid, 17G MWA antenna, thermocouple, artificial pneumothorax set if needed',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Indicated for medically inoperable Stage I NSCLC or solitary lung metastasis. Non-contrast CT thorax performed for lesion targeting. Local anesthesia down to parietal pleura. A 17G microwave antenna was inserted coaxially into the lung nodule, avoiding bullae and pulmonary vessels. Verification scan confirmed central antenna positioning. Microwave ablation delivered at 45W for 5 minutes. Progressive ground-glass halo enveloped lesion representing target thermal margin. Track ablated. Post-procedure CT demonstrated complete lesion coverage.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict supine/ipsilateral dependent bedrest x 4 hours. Minimal coughing.',
      hematomaChecks: 'Monitor oxygen saturation, respiratory rate, and chest pain q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Tab Codeine Phosphate 30mg PO TDS (cough suppression)", "Tab Paracetamol 650mg TDS", "Supplemental Oxygen to keep SpO2 >94%"],
      redFlags: ["Pneumothorax requiring chest tube", "Hemoptysis", "Bronchopleural fistula", "Air embolism"],
    },
    consentId: 'consent-lung-ablation',
  },
  {
    id: 'cat09-renal-cryo',
    categoryNumber: 9,
    categoryName: 'Interventional Oncology Percutaneous Ablation',
    title: 'Percutaneous CT-Guided Cryoablation of Renal Cell Carcinoma (T1a)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Cryoablation',
      packageCode: '1849-MG082A',
      icd10: 'C64',
      tariffInr: 45000,
    },
    modality: 'CT',
    targetAnatomy: ["Exophytic / Endophytic Renal Mass"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Posterior or posterolateral retroperitoneal CT approach',
    sheathDefault: '17G Cryoprobes (Galil / Boston Scientific IceRod)',
    cathetersAndWires: 'CT markers, multiple 17G cryoprobes (dual or triple configuration), argon-helium gas system',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Patient prone. CT localized 3.2cm right exophytic renal mass. Hydrodissection performed using 500 mL saline + dilute contrast displacing ascending colon 2cm away from kidney. Under CT guidance, three 17G IceRod cryoprobes placed into mass in triangular configuration spaced 1.5cm apart. Dual freeze-thaw cycle performed: 10-minute freeze, 8-minute passive thaw, 10-minute freeze. CT confirmed hypodense ice ball completely extending 5mm beyond tumor margins. Active thaw performed and cryoprobes removed under track coagulation.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Strict supine/prone flat bedrest x 4 hours.',
      hematomaChecks: 'Monitor urine for gross hematuria, check BP and flank tenderness q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Bedside USG if flank pain or tachycardia.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Tramadol 50mg SOS", "Cap Pantoprazole 40mg OD"],
      redFlags: ["Gross hematuria / ureteral obstruction by clot", "Retroperitoneal hemorrhage", "Cryoneurolysis / flank paresthesia"],
    },
    consentId: 'consent-tumor-ablation',
  },
  {
    id: 'cat09-osteoid-osteoma-rfa',
    categoryNumber: 9,
    categoryName: 'Interventional Oncology Percutaneous Ablation',
    title: 'CT-Guided Percutaneous Radiofrequency Ablation of Osteoid Osteoma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Radiofrequency Ablation (RFA)',
      packageCode: '1849-MG080A',
      icd10: 'M89.8',
      tariffInr: 25000,
    },
    modality: 'CT',
    targetAnatomy: ["Cortical Bone Nidus (Femur / Tibia / Spine)"],
    sedation: 'Local Anesthesia with Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous cortical drill access',
    sheathDefault: 'Bonopty / Jamshidi bone biopsy coaxial system',
    cathetersAndWires: 'Powered bone drill, 17G RFA needle with 5mm active tip, RF generator',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Indicated for incapacitating nocturnal bone pain due to osteoid osteoma. Patient under spinal or general anesthesia. High-resolution thin-slice CT identified 6mm cortical nidus with surrounding sclerosis in proximal femur. Coaxial drill system traversed dense sclerotic bone directly into nidus. 17G RFA electrode placed with active tip centered in nidus. Target temperature maintained at 90°C for 6 minutes. Completion CT confirmed electrode position. Drill removed; sterile dressing applied. Immediate and permanent pain relief anticipated.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 4 hours.',
      hematomaChecks: 'Neurovascular check of limb and pain assessment q30m x 2h, then q1h.',
      requiredImaging: 'Plain X-ray of limb prior to discharge.',
      hydrationProtocol: 'Oral hydration.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Ibuprofen 400mg TDS x 3 days"],
      redFlags: ["Cortical bone fracture", "Skin burn", "Incomplete nidus ablation"],
    },
    consentId: 'consent-tumor-ablation',
  },
];
