import { MasterProcedure } from './types';

/**
 * Category 10: Venous Interventions (16 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_10_VENOUS: MasterProcedure[] = [
  {
    id: 'cat10-venaseal-gsv',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'VenaSeal Cyanoacrylate Closure of Great Saphenous Vein (GSV)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Endovenous Cyanoacrylate Closure (VenaSeal)',
      packageCode: '1849-VS010A',
      icd10: 'I83.9',
      tariffInr: 35000,
    },
    modality: 'US',
    targetAnatomy: ["Great Saphenous Vein (GSV)", "Saphenofemoral Junction (SFJ)"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Below-knee GSV access under real-time ultrasound guidance',
    sheathDefault: '5F dedicated VenaSeal introducer sheath',
    cathetersAndWires: '0.035" J-wire, 5F dispensing catheter, VenaSeal gun with cyanoacrylate adhesive',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'VenaSeal Cyanoacrylate Medical Adhesive (5 mL)',
    proceduralNarrativeTemplate:
      'Patient supine. Duplex ultrasound confirmed saphenofemoral junction (SFJ) incompetence with severe reflux (>3.0s) and GSV dilation (8.5mm). Under ultrasound guidance, below-knee GSV punctured with 19G needle. 0.035" wire advanced to common femoral vein. 5F delivery sheath and dispenser catheter positioned precisely 5 cm distal to SFJ under direct continuous sonography. Tumescent anesthesia NOT required. 0.09 mL of proprietary cyanoacrylate adhesive delivered via dispenser gun at index site, followed immediately by 3 minutes of direct ultrasound probe compression. Subsequent 0.09 mL glue aliquots delivered every 3 cm down the GSV with 30 seconds compression per segment down to puncture site. Immediate duplex scanning confirmed 100% complete occlusion and acoustic shadowing of GSV throughout treated segment with widely patent common femoral vein.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate ambulation encouraged. Patient ambulates in recovery for 15-20 minutes.',
      hematomaChecks: 'Check puncture site for bleeding; duplex ultrasound sweep of CFV to ensure zero glue protrusion q30m.',
      requiredImaging: 'Venous Duplex Ultrasound at 24-48 hours to confirm GSV occlusion and CFV patency.',
      hydrationProtocol: 'Encourage oral fluids.',
      medications: ["Tab Paracetamol 650mg PO SOS", "Tab Ibuprofen 400mg PO BD x 3 days (if phlebitis occurs)"],
      redFlags: ["Glue migration into common femoral vein / DVT", "Superficial phlebitis / red tender cord", "Paresthesia of saphenous nerve"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-venaseal-ssv',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'VenaSeal Cyanoacrylate Closure of Small Saphenous Vein (SSV)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Endovenous Cyanoacrylate Closure (VenaSeal)',
      packageCode: '1849-VS010A',
      icd10: 'I83.9',
      tariffInr: 35000,
    },
    modality: 'US',
    targetAnatomy: ["Small Saphenous Vein (SSV)", "Saphenopopliteal Junction (SPJ)"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Mid-calf SSV access under ultrasound guidance',
    sheathDefault: '5F VenaSeal sheath',
    cathetersAndWires: '0.035" wire, 5F VenaSeal dispensing catheter, adhesive gun',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'VenaSeal Cyanoacrylate Adhesive',
    proceduralNarrativeTemplate:
      'Patient prone. Duplex ultrasound mapped incompetent small saphenous vein (SSV) draining into popliteal vein via SPJ. Mid-calf percutaneous micropuncture of SSV. Delivery catheter tip positioned precisely 3 cm distal to saphenopopliteal junction to safeguard sural nerve and popliteal vein. Cyanoacrylate glue delivered in standardized aliquots with compression. Completion duplex confirmed complete closure of SSV with fully patent popliteal vein.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate ambulation for 15 minutes.',
      hematomaChecks: 'Monitor calf puncture site and distal pulses q30m x 2h.',
      requiredImaging: 'Duplex ultrasound at 48 hours.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS", "Tab Ibuprofen 400mg BD x 2 days"],
      redFlags: ["Sural nerve paresthesia", "Popliteal DVT", "Superficial phlebitis"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-evla-gsv',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Endovenous Laser Ablation (EVLA) of Great Saphenous Vein (GSV)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Endovenous Laser Therapy (EVLT)',
      packageCode: '1849-VS009A',
      icd10: 'I83.9',
      tariffInr: 25000,
    },
    modality: 'US',
    targetAnatomy: ["Great Saphenous Vein", "Saphenofemoral Junction"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Knee level GSV puncture under ultrasound',
    sheathDefault: '4F - 5F Introducer Sheath',
    cathetersAndWires: '1470nm Radial Laser Fiber, tumescent infiltration pump, 0.035" wire',
    microcatheterSystem: 'N/A',
    embolicOrImplants: '1470nm Radial 2-ring Laser Fiber',
    proceduralNarrativeTemplate:
      'Ultrasound confirmed SFJ incompetence and GSV reflux. Below-knee GSV accessed; 1470nm radial laser fiber advanced to 2 cm distal to SFJ (inferior to superficial epigastric vein). Under ultrasound guidance, ultrasound-guided perivenous tumescent local anesthesia (500 mL dilute cold lignocaine + bicarbonate + adrenaline) infused circumferentially into the saphenous fascial sheath creating a >10mm fluid heat-sink collar. Laser activated at 7W-10W (continuous pullback delivering 60-80 J/cm). Post-ablation duplex confirmed total vein occlusion with no flow and patent CFV.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate ambulation with Class II (20-30 mmHg) graduated compression stockings.',
      hematomaChecks: 'Check puncture site and distal pulses q30m x 2h.',
      requiredImaging: 'Duplex ultrasound at 1 week.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg TDS", "Tab Ibuprofen 400mg BD x 3 days"],
      redFlags: ["Deep vein thrombosis (EHIT)", "Skin burn / hyperpigmentation", "Saphenous nerve injury"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-rfa-gsv',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Radiofrequency Ablation (RFA / ClosureFast) of Great Saphenous Vein',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Radiofrequency Ablation (RFA)',
      packageCode: '1849-VS009A',
      icd10: 'I83.9',
      tariffInr: 28000,
    },
    modality: 'US',
    targetAnatomy: ["Great Saphenous Vein"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Knee / upper calf GSV puncture under US',
    sheathDefault: '7F ClosureFast Introducer Sheath',
    cathetersAndWires: '0.025" wire, ClosureFast 7F segmental RFA catheter (7cm heating element)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'ClosureFast RFA Catheter',
    proceduralNarrativeTemplate:
      'Knee level GSV accessed under ultrasound. ClosureFast catheter advanced to 2.0 cm distal to SFJ. Perivenous tumescent anesthesia delivered under ultrasound guidance along entire GSV. Catheter heated to 120°C for two 20-second cycles at SFJ and one 20-second cycle per 7cm segment sequentially during stepwise pullback. Duplex confirmed complete thermal vein occlusion and patent deep venous system.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate ambulation; Class II stockings applied.',
      hematomaChecks: 'Check puncture site q30m x 2h.',
      requiredImaging: 'Duplex USG at 1 week.',
      hydrationProtocol: 'Oral hydration.',
      medications: ["Tab Paracetamol 650mg SOS", "Tab Ibuprofen 400mg BD x 2 days"],
      redFlags: ["EHIT (Endovenous Heat-Induced Thrombosis)", "Paresthesia", "Phlebitis"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-foam-sclerotherapy',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Ultrasound-Guided Foam Sclerotherapy (STS / Polidocanol) for Varicose Veins',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Varicose Vein Sclerotherapy',
      packageCode: '1849-VS011A',
      icd10: 'I83.8',
      tariffInr: 12000,
    },
    modality: 'US',
    targetAnatomy: ["Tortuous Varicose Tributaries", "Nonsaphenous Varices"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous puncture under high-frequency linear US',
    sheathDefault: '23G - 25G Butterfly needles',
    cathetersAndWires: 'Tessari 3-way stopcock method, 1% - 3% Sodium Tetradecyl Sulfate (STS) or Polidocanol, room air/CO2 (1:4 ratio)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'STS / Polidocanol Sclerosant Microfoam (max 10 mL per session)',
    proceduralNarrativeTemplate:
      'High-resolution ultrasound mapped tortuous superficial varicose tributaries and refluxing channels. Tessari method used to generate microfoam by mixing 2 mL of 1% or 3% STS with 8 mL air across a 3-way stopcock. Direct puncture of target varices with 23G butterfly needle. Intraluminal venous blood flashback confirmed. Microfoam slowly injected under real-time ultrasound monitoring. Sonography showed displacement of blood and acute spasm/echogenic foam filling the entire variceal lumen without deep venous spillover. Direct manual massage and eccentric compression pads applied.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate ambulation for 30 minutes. Continuous Class II compression stocking worn for 7 days.',
      hematomaChecks: 'Monitor puncture sites and distal perfusion q15m x 1h.',
      requiredImaging: 'Clinical and duplex review at 2-4 weeks.',
      hydrationProtocol: 'Oral hydration.',
      medications: ["Tab Paracetamol 650mg SOS"],
      redFlags: ["Deep vein thrombosis", "Cutaneous necrosis / extravasation", "Visual scotoma / migraine (transient microemboli)", "Hyperpigmentation"],
    },
    consentId: 'consent-venous-sclerotherapy',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-perforator-sclerotherapy',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Incompetent Perforator Vein Ultrasound-Guided Foam Sclerotherapy',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Varicose Vein Sclerotherapy',
      packageCode: '1849-VS011A',
      icd10: 'I83.0',
      tariffInr: 12000,
    },
    modality: 'US',
    targetAnatomy: ["Incompetent Cockett / Boyd Perforator Veins"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Direct puncture of perforator vein at fascial defect level',
    sheathDefault: '21G - 23G Needle',
    cathetersAndWires: 'High-frequency US probe, Tessari foam generator, 3% Polidocanol / STS foam',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Polidocanol 3% Foam Sclerosant (2-3 mL)',
    proceduralNarrativeTemplate:
      'Duplex ultrasound identified incompetent calf perforator vein with >500ms bidirectional reflux and diameter >4mm traversing deep muscular fascia. Under direct ultrasound guidance, 21G needle advanced precisely into perforator lumen above deep muscular fascia. 2 mL of 3% STS/polidocanol foam injected under sonographic vision. Foam visualized filling perforator with immediate spasm and thrombosis; injection halted before foam entered deep posterior tibial veins. Local compression applied.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate walking encouraged; compression bandage applied.',
      hematomaChecks: 'Check for local skin blanching or pain q30m x 1h.',
      requiredImaging: 'Duplex ultrasound at 2 weeks.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS"],
      redFlags: ["Deep venous thrombosis", "Skin ulceration", "Phlebitis"],
    },
    consentId: 'consent-venous-sclerotherapy',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-perforator-glue',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Incompetent Perforator Vein Cyanoacrylate Glue Embolization',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Varicose Vein Embolization',
      packageCode: '1849-VS013A',
      icd10: 'I83.0',
      tariffInr: 22000,
    },
    modality: 'US',
    targetAnatomy: ["Incompetent Perforator Vein Trunk"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous puncture under ultrasound',
    sheathDefault: '20G / 21G Needle or 4F Micro-sheath',
    cathetersAndWires: '2.0F microcatheter, 0.014" wire, 5% Dextrose flush, n-BCA glue',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'n-Butyl Cyanoacrylate (n-BCA) Glue / Histoacryl + Lipiodol (1:1 ratio)',
    proceduralNarrativeTemplate:
      'Indicated for recalcitrant venous stasis ulcer overlying incompetent perforator vein. High-frequency ultrasound mapped fascial defect. 20G needle entered perforator trunk. 2.0F microcatheter advanced just superficial to deep fascia. Microcatheter flushed with D5W. Under continuous ultrasound surveillance, 0.3 mL of n-BCA glue + Lipiodol (1:1 ratio) delivered into perforator lumen. Immediate ultrasound transducer compression applied over the site for 60 seconds. Repeat duplex confirmed permanent solid echogenic cast obliterating the perforator with patent deep calf veins. Puncture site dressed.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Immediate ambulation; compression wrap applied over ulcer.',
      hematomaChecks: 'Check puncture site and ulcer dressing q30m x 1h.',
      requiredImaging: 'Duplex ultrasound at 1 week.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS", "Ulcer local care kit"],
      redFlags: ["Deep vein glue migration / DVT", "Local foreign body reaction", "Tender granuloma"],
    },
    consentId: 'consent-venous-sclerotherapy',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-varicose-embolization-microcoils',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Varicose Vein Embolization using Microcoils',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Varicose Vein Embolization',
      packageCode: '1849-VS013A',
      icd10: 'I83.9',
      tariffInr: 25000,
    },
    modality: 'XA',
    targetAnatomy: ["Pelvic Escape Point Varices", "Saphenous Stump Collaterals"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Retrograde Transfemoral or Direct Percutaneous Access under US/Fluoro',
    sheathDefault: '4F - 5F Sheath',
    cathetersAndWires: '5F Cobra, 2.7F microcatheter, 0.014" wire, detachable fibered microcoils',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'Detachable Fibered Microcoils (0.018", 4-8mm)',
    proceduralNarrativeTemplate:
      'Indicated for recurrent varicose veins arising from pelvic venous leak (obturator/pudendal escape points) or complex tortuous tributary lakes. Sheath placed. 2.7F microcatheter navigated directly into refluxing feeder vein. Selective varicography mapped outflow. Multiple 0.018" detachable fibered platinum microcoils deployed forming dense mechanical occlusion scaffold. Flow stasis achieved with no reflux on completion run.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours.',
      hematomaChecks: 'Monitor access site and distal perfusion q30m x 2h.',
      requiredImaging: 'Duplex ultrasound at 2 weeks.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS"],
      redFlags: ["Coil migration", "Superficial phlebitis", "Puncture hematoma"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-varicose-embolization-glue',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Varicose Vein Embolization using Cyanoacrylate Glue (n-BCA)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Varicose Vein Embolization',
      packageCode: '1849-VS013A',
      icd10: 'I83.9',
      tariffInr: 24000,
    },
    modality: 'XA',
    targetAnatomy: ["Recurrent Varicose Vein Nidus", "Incompetent Tributary Veins"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous puncture under ultrasound or transcatheter',
    sheathDefault: '4F Sheath or 20G Needle',
    cathetersAndWires: '2.7F microcatheter, 0.014" wire, D5W non-ionic flush',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'n-BCA Cyanoacrylate Glue + Lipiodol (1:2 ratio)',
    proceduralNarrativeTemplate:
      'Puncture of dominant varicose tributary under ultrasound. 2.7F microcatheter advanced into nidus. D5W flush administered. Under fluoroscopy, 1.5 mL of n-BCA cyanoacrylate glue mixed with Lipiodol (1:2 ratio) slowly injected until total cast formed obliterating the variceal complex. Microcatheter swiftly withdrawn. Duplex confirmed complete absence of flow in treated varices.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours.',
      hematomaChecks: 'Check puncture site and distal pulses q30m x 2h.',
      requiredImaging: 'Duplex ultrasound at 2 weeks.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS"],
      redFlags: ["Glue migration into deep venous system", "Local inflammatory phlebitis", "Skin pigmentation"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-varicose-embolization-coils-glue',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Varicose Vein Embolization using Combined Microcoils Plus Cyanoacrylate Glue',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Varicose Vein Embolization',
      packageCode: '1849-VS013A',
      icd10: 'I83.9',
      tariffInr: 30000,
    },
    modality: 'XA',
    targetAnatomy: ["High-Flow Variceal Tributaries", "Aneurysmal Saphenous Collaterals"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Direct ultrasound puncture or Transfemoral approach',
    sheathDefault: '5F Sheath',
    cathetersAndWires: '5F Cobra, 2.7F microcatheter, 0.014" wire, microcoils (4-8mm), D5W flush',
    microcatheterSystem: '2.7F microcatheter',
    embolicOrImplants: 'Detachable Microcoils + n-BCA Cyanoacrylate Glue / Lipiodol (1:2 ratio)',
    proceduralNarrativeTemplate:
      'For high-flow aneurysmal varicose tributaries where glue alone risks deep venous migration. 2.7F microcatheter navigated to target segment. Distal mechanical flow barrier created using three 0.018" fibered microcoils. Following non-ionic D5W flush, 1.5 mL of n-BCA glue + Lipiodol delivered behind coil nest. Glue rapidly polymerized within the coil matrix creating an impervious, permanent plug. Total occlusion confirmed on completion run.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours.',
      hematomaChecks: 'Site check and pulse check q30m x 2h.',
      requiredImaging: 'Duplex ultrasound at 2 weeks.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Tab Paracetamol 650mg SOS"],
      redFlags: ["Phlebitis", "Coil/glue migration", "Hematoma"],
    },
    consentId: 'consent-venous-ablation',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-dvt-cdt',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Iliofemoral Deep Vein Thrombosis (DVT) Catheter-Directed Thrombolysis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Thrombolysis',
      packageCode: '1849-VS005A',
      icd10: 'I80.2',
      tariffInr: 28000,
    },
    modality: 'XA',
    targetAnatomy: ["Iliac Vein", "Common Femoral Vein", "Femoral Vein"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Ipsilateral Popliteal Vein Puncture under ultrasound',
    sheathDefault: '6F 11cm Sheath',
    cathetersAndWires: '0.035" Glidewire, 5F multi-sidehole infusion catheter (Cragg-McNamara 20-30cm)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Alteplase (rtPA) continuous infusion',
    proceduralNarrativeTemplate:
      'Indicated for extensive acute iliofemoral DVT (phlegmasia cerulea dolens). Ipsilateral popliteal vein punctured under US; 6F sheath placed. Venography showed occlusive thrombus spanning from popliteal vein through common iliac vein into IVC. Glidewire crossed into IVC. Multi-sidehole catheter embedded within thrombus. Bolus rtPA (5mg) delivered, followed by continuous infusion at 0.5 - 1.0 mg/hr with IV unfractionated heparin (500 units/hr). Check venogram at 18 hours demonstrated complete clot lysis revealing severe underlying May-Thurner left common iliac compression, subsequently stented.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict ICU bedrest; leg elevated 15 degrees.',
      hematomaChecks: 'Monitor puncture site, limb circumference, and fibrinogen levels q2h.',
      requiredImaging: 'Check venography at 12-24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["rtPA protocol", "IV Heparin", "Analgesia"],
      redFlags: ["Major hemorrhage / retroperitoneal hematoma", "Pulmonary embolism", "Intracranial bleeding"],
    },
    consentId: 'consent-dvt-thrombectomy',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-may-thurner-stenting',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'May-Thurner Syndrome Balloon Angioplasty & Dedicated Venous Stenting',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Venous Stenting',
      packageCode: '1849-VS014A',
      icd10: 'I87.1',
      tariffInr: 42000,
    },
    modality: 'XA',
    targetAnatomy: ["Left Common Iliac Vein", "IVC Confluence"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Left Popliteal or Left CFV Access',
    sheathDefault: '9F - 10F 45cm Sheath',
    cathetersAndWires: '0.035" stiff Glidewire, 12mm-16mm PTA balloon, dedicated venous stent (Venovo / Abre 14-16mm x 60-90mm)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: '14mm - 16mm x 80mm Dedicated Self-Expanding Nitinol Venous Stent',
    proceduralNarrativeTemplate:
      'Indicated for extrinsic compression of left common iliac vein by right common iliac artery against lumbar spine. Access via left CFV/popliteal. Venogram in 30° RAO projection showed high-grade compression of left CIV with extensive pelvic collateralization. Pull-through gradient was 8 mmHg. Lesion pre-dilated with 12mm balloon. A 14mm x 80mm dedicated Nitinol venous stent (Abre / Venovo) deployed with 3-5mm extension into IVC. Post-dilated with 14mm non-compliant balloon. Completion venogram demonstrated full stent expansion, brisk inline venous drainage into IVC, zero collateral runoff, and normalization of pressure gradient to 0 mmHg.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bedrest x 6 hours; left leg straight.',
      hematomaChecks: 'Monitor access site, distal pulses, and left thigh circumference q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Venous Duplex Ultrasound at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["Therapeutic Anticoagulation: Enoxaparin 1mg/kg BD bridging to DOAC (Rivaroxaban / Apixaban) x 6-12 months"],
      redFlags: ["In-stent thrombosis", "Contralateral iliac vein obstruction by stent overhang", "Groin hematoma"],
    },
    consentId: 'consent-venous-stenting',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-ivc-filter-placement',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Inferior Vena Cava (IVC) Filter Placement (Infrarenal)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'IVC Filter Placement',
      packageCode: '1849-VS016A',
      icd10: 'I82.9',
      tariffInr: 25000,
    },
    modality: 'XA',
    targetAnatomy: ["Infrarenal Inferior Vena Cava"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Right IJV or Right CFV under ultrasound',
    sheathDefault: '6F - 8.5F Filter Delivery Sheath',
    cathetersAndWires: '0.035" J-wire, 5F Pigtail with radiopaque marker increments, Retrievable IVC Filter (Cook Celect / Bard Denali / Cordis TrapEase)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Retrievable Nitinol IVC Filter (Cook Celect / Bard Denali)',
    proceduralNarrativeTemplate:
      'Indicated for acute DVT/PE with absolute contraindication to anticoagulation (recent ICH / GI bleed). Right IJV accessed; 5F pigtail placed in distal IVC. Inferior vena cavogram documented: patent IVC lumen, normal caliber (diameter 19mm, <28mm limit), absence of duplication/circumaortic renal collar, and lowest renal vein inflow level (L1-L2). 8.5F delivery sheath positioned. Retrievable IVC filter deployed with filter apex centered and aligned precisely at or immediately below lowest renal vein margin. Cavogram confirmed symmetrical filter expansion, zero tilt (<5 degrees), and intact hook.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours (neck access) or 4 hours (femoral).',
      hematomaChecks: 'Monitor puncture site q15m x 1h, then q30m.',
      requiredImaging: 'Plain Abdominal Radiograph at 24h to document baseline filter position.',
      hydrationProtocol: 'Oral fluids.',
      medications: ["Resume therapeutic anticoagulation as soon as primary contraindication resolves", "Tab Paracetamol 650mg SOS"],
      redFlags: ["Filter tilt / migration", "IVC perforation", "Filter thrombosis / bilateral leg edema"],
    },
    consentId: 'consent-ivc-filter',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-ivc-filter-retrieval',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Percutaneous IVC Filter Retrieval (Standard / Complex)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'IVC Filter Retrieval',
      packageCode: '1849-VS017A',
      icd10: 'Z98.890',
      tariffInr: 28000,
    },
    modality: 'XA',
    targetAnatomy: ["Infrarenal IVC", "Right IJV"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Right Internal Jugular Vein (IJV) under US',
    sheathDefault: '9F - 11F 45cm Long Retrieval Sheath',
    cathetersAndWires: '5F Cobra, 10mm-15mm Gooseneck Snare / Loop Snare, 0.035" stiff wire',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'N/A',
    proceduralNarrativeTemplate:
      'Right IJV accessed; 9F sheath placed. Preliminary inferior vena cavogram confirmed absence of significant thrombus burden within filter basket (<25% cone volume). Gooseneck snare manipulated under fluoroscopy to engage retrieval hook of filter. Sheath advanced over hook while maintaining steady tension. Filter collapsed smoothly into retrieval sheath and withdrawn intact. Repeat cavogram showed widely patent IVC without extravasation or luminal narrowing.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bedrest x 2 hours.',
      hematomaChecks: 'Neck site check and vitals monitoring q15m x 1h, then q30m.',
      requiredImaging: 'None routine.',
      hydrationProtocol: 'Oral hydration.',
      medications: ["Continue indicated oral anticoagulation"],
      redFlags: ["IVC wall tear / hemorrhage", "Filter strut fracture / embolization", "Neck hematoma"],
    },
    consentId: 'consent-ivc-filter',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-svc-stenting',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Superior Vena Cava (SVC) Syndrome Balloon Angioplasty & Dedicated Stenting',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Venous Stenting',
      packageCode: '1849-VS014A',
      icd10: 'I87.1',
      tariffInr: 38000,
    },
    modality: 'XA',
    targetAnatomy: ["Superior Vena Cava", "Right / Left Innominate Veins", "Right Atrium"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Right CFV and/or Right Basilic / Brachial Vein',
    sheathDefault: '10F - 12F Sheath',
    cathetersAndWires: '0.035" stiff Glidewire, 10mm-14mm balloon, 14mm-18mm x 60-80mm Self-Expanding Stent (Wallstent / Abre)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: '16mm x 60mm Self-Expanding Venous Stent',
    proceduralNarrativeTemplate:
      'Emergency intervention for life-threatening SVC syndrome (facial edema, orthopnea, cerebral venous congestion due to lung malignancy). Right CFV accessed. Cavography revealed high-grade SVC stenosis with extensive azygos collateral flow. Wire crossed stricture into innominate vein. Pre-dilated with 10mm balloon. 16mm x 60mm self-expanding stent deployed spanning from innominate vein to cavoatrial junction. Post-dilated to 14mm. Immediate rapid inline venous return to right atrium demonstrated with dramatic reduction in collateral filling.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Head-of-bed elevated 30-45 degrees; bedrest x 4 hours.',
      hematomaChecks: 'Monitor facial swelling, respiratory status, and groin access site q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Chest Radiograph at 24 hours.',
      hydrationProtocol: 'IV Normal Saline 75 mL/hr.',
      medications: ["IV Dexamethasone 8mg BD", "Therapeutic LMWH Enoxaparin 1mg/kg BD"],
      redFlags: ["Stent migration into right atrium", "SVC rupture / pericardial tamponade", "Acute pulmonary edema (preload surge)"],
    },
    consentId: 'consent-venous-stenting',
    calculatorId: 'caprini_vte',
  },
  {
    id: 'cat10-pe-cdt-ekos',
    categoryNumber: 10,
    categoryName: 'Venous Interventions',
    title: 'Acute Pulmonary Embolism Ultrasound-Accelerated Thrombolysis (EKOS)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Thrombolysis',
      packageCode: '1849-VS005A',
      icd10: 'I26.9',
      tariffInr: 45000,
    },
    modality: 'XA',
    targetAnatomy: ["Main Pulmonary Artery", "Right and Left Pulmonary Arteries"],
    sedation: 'Local Anesthesia / Conscious Sedation',
    accessSiteDefault: 'Right Common Femoral Vein under ultrasound',
    sheathDefault: 'Dual 6F 45cm Sheaths',
    cathetersAndWires: '0.035" stiff wire, 5F Grollman / Berman catheter, Dual EKOS Acoustic Pulse Thrombolysis Catheters (12cm treatment zone)',
    microcatheterSystem: 'N/A',
    embolicOrImplants: 'Alteplase (rtPA) + Ultrasound Acoustic Core',
    proceduralNarrativeTemplate:
      'Indicated for submassive/massive acute pulmonary embolism with RV dysfunction (RV/LV ratio >0.9, elevated troponin). Right CFV accessed. Pulmonary angiogram and baseline pulmonary arterial pressures recorded (PAP 58/28, mean 38 mmHg). EKOS catheters navigated bilaterally into right and left main pulmonary arteries. Ultrasound cores inserted. Low-dose rtPA initiated at 0.5 mg/hr per catheter with ultrasound acoustic energy delivery for 12 hours. Patient transferred to ICU. Post-lysis PAP decreased to mean 22 mmHg with dramatic RV recovery on echocardiogram.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict ICU bedrest during infusion.',
      hematomaChecks: 'Monitor vitals, SpO2, bleeding, and neurological status q1h.',
      requiredImaging: 'Check echocardiogram and follow-up CTPA at 24-48 hours.',
      hydrationProtocol: 'IV Normal Saline titrated to maintain CVP 8-12 mmHg.',
      medications: ["rtPA infusion protocol", "Unfractionated heparin protocol"],
      redFlags: ["Major bleeding / intracranial hemorrhage", "Pulmonary artery rupture", "Arrhythmia"],
    },
    consentId: 'consent-pe-thrombectomy',
    calculatorId: 'pesi_score',
  },
];
