import { MasterProcedure } from './types';

/**
 * Category 02: Catheter Drainages, Fluid Aspiration & Stenting (39 Procedures)
 * Aligned with Rajasthan MAAY / RGHS codes and SMS Medical College clinical protocols.
 */
export const CATEGORY_02_DRAINAGES: MasterProcedure[] = [
  // 1. Liver Amebic Abscess Aspiration & Drainage
  {
    id: 'cat02-liver-amebic-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Percutaneous Catheter Drainage of Amebic Liver Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'A06.4',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Right/Left Hepatic Lobe Amebic Abscess Cavity'],
    sedation: 'Local Anesthesia (2% Lignocaine 10-15 mL)',
    accessSiteDefault: 'Right subcostal or intercostal space traversing normal liver parenchyma',
    sheathDefault: 'Trocar / Seldinger 10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" J-tip Stiff guidewire, 8F-12F fascial dilators, 18G puncture needle',
    proceduralNarrativeTemplate:
      'Real-time ultrasound localized thick-walled liver abscess with liquefaction. Safe route planned traversing at least 1-2 cm of normal hepatic parenchyma to prevent peritoneal spillage. Infiltration of 2% lignocaine. 18G puncture needle advanced into cavity center under continuous sonography. Thick "anchovy-sauce" pus aspirated. 0.035" stiff guidewire coiled within cavity. Tract dilated serially. 10F/12F locking pigtail catheter deployed, locked, and aspirated until dry. Cavity gently irrigated with warm sterile normal saline. Catheter secured to skin with 2-0 silk suture and connected to dependent drainage bag.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours. Keep drainage bag dependent and below bed level.',
      hematomaChecks: 'Monitor drainage output (volume, color, consistency) and vitals q30m x 2h, then q1h.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ['IV Metronidazole 500mg TDS x 10-14 days', 'IV Ceftriaxone 1g BD', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Frank blood in drainage bag', 'Sudden catheter blockage with acute RUQ pain', 'High fever / chills', 'Peritoneal guarding'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 2. Liver Pyogenic Abscess Drainage
  {
    id: 'cat02-liver-pyogenic-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound / CT-Guided Percutaneous Drainage of Pyogenic Liver Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K75.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Septated / Multiloculated Pyogenic Liver Abscess'],
    sedation: 'Local Anesthesia + IV Conscious Sedation',
    accessSiteDefault: 'Right intercostal / subcostal transhepatic route',
    sheathDefault: '12F/14F locking pigtail drainage catheter',
    cathetersAndWires: '18G Chiba/trocar, 0.035" Amplatz stiff guidewire, serial dilators',
    proceduralNarrativeTemplate:
      'Large pyogenic abscess with internal echoes and debris localized. 18G needle placed into cavity. Frank purulent foul-smelling fluid aspirated and sent for gram stain, aerobic/anaerobic culture, and sensitivity. 0.035" Amplatz wire looped inside. Tract dilated to 14F. 12F/14F multi-sidehole pigtail catheter advanced, loop locked. Aggressive aspiration and saline irrigation performed until effluent cleared. Catheter sutured to skin and placed on closed gravity drainage.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bed rest x 4 hours; ensure no kinking or tension on drainage tube.',
      hematomaChecks: 'Drain volume and vital signs monitored q30m x 4h.',
      hydrationProtocol: 'IV fluids 100-125 mL/hr.',
      medications: ['Empiric IV Piperacillin-Tazobactam 4.5g TDS (adjust per culture)', 'IV Paracetamol 1g TDS'],
      redFlags: ['Septic shock (hypotension, tachycardia)', 'Severe abdominal pain', 'Bleeding into drain'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 3. Hydatid Cyst PAIR
  {
    id: 'cat02-hydatid-pair',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Percutaneous Aspiration, Injection & Re-aspiration (PAIR) for Hydatid Cyst',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'B67.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Gharbi Type I/II / WHO CE1/CE2 Hepatic Hydatid Cyst'],
    sedation: 'Local Anesthesia + Deep Sedation with Anesthesia Standby (Anaphylaxis Precaution)',
    accessSiteDefault: 'Transhepatic route through thick mantle of normal liver parenchyma',
    sheathDefault: '18G/19G Teflon-sheathed needle / 6F pigtail',
    cathetersAndWires: '0.035" guidewire, 18G puncture needle',
    embolicOrImplants: 'Scolicidal agent: Hypertonic Saline (20% NaCl) or Absolute Alcohol (95%)',
    proceduralNarrativeTemplate:
      'Patient pre-treated with oral Albendazole x 4 weeks. Full resuscitation and adrenaline on immediate standby. Ultrasound confirmed WHO CE1 unilocular hydatid cyst without cysto-biliary fistula. Safe transhepatic puncture pathway selected. 18G sheathed needle introduced under real-time US. Clear "rock-water" hydatid fluid aspirated (~50-70% cavity volume). Absence of bile confirmed visually and via dipstick. 20% hypertonic saline injected equal to one-third of aspirated volume, left in cavity for 15-20 minutes contact time to kill protoscolices. Fluid completely re-aspirated until cyst collapsed. Needle withdrawn. Puncture tract sealed with gelfoam.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict flat bed rest x 6 hours. Intensive monitoring in high-dependency unit.',
      hematomaChecks: 'Continuous anaphylaxis surveillance (urticaria, bronchospasm, hypotension, tachycardia) q15m x 2h, then q30m x 4h.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ['Tab Albendazole 400mg BD (continue x 4 weeks)', 'IV Hydrocortisone 100mg and Pheniramine on standby', 'Tab Paracetamol 650mg'],
      redFlags: ['Anaphylaxis (stridor, wheeze, rash, hypotension)', 'Severe abdominal pain', 'Biliary peritonitis'],
    },
    consentId: 'consent-hydatid-pair',
  },

  // 4. Hydatid Cyst PAIR-PD
  {
    id: 'cat02-hydatid-pair-pd',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Percutaneous Aspiration, Injection & Reaspiration with Drainage (PAIR-PD) for Large Hydatid Cyst',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'B67.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Large (>10 cm) Hepatic Hydatid Cyst / Gharbi Type III with Daughter Cysts'],
    sedation: 'Local Anesthesia + Anesthesia Monitoring',
    accessSiteDefault: 'Transhepatic intercostal or subcostal route',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" stiff guidewire, 18G needle, dilators',
    embolicOrImplants: 'Hypertonic 20% saline scolicidal agent',
    proceduralNarrativeTemplate:
      'Transhepatic puncture of 12 cm hydatid cyst under US guidance. Clear fluid aspirated, scolicidal hypertonic saline instilled for 15 minutes. Due to cyst size and thick wall, 8F locking pigtail catheter placed over wire into cavity for continuous external drainage to prevent reaccumulation and secondary infection. Cavity collapsed on fluoroscopy/US.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours. Keep catheter bag clamped for 2 hours during any scolicidal flushes, then open.',
      hematomaChecks: 'Monitor for bile staining in drain output and anaphylaxis signs.',
      hydrationProtocol: 'IV fluids 100 mL/hr.',
      medications: ['Tab Albendazole 400mg BD x 3 months', 'IV Ceftriaxone 1g BD'],
      redFlags: ['Bile in drain (cysto-biliary communication)', 'Anaphylaxis', 'Fever'],
    },
    consentId: 'consent-hydatid-pair',
  },

  // 5. Subdiaphragmatic Abscess Drainage
  {
    id: 'cat02-subdiaphragmatic-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound / CT-Guided Percutaneous Drainage of Subdiaphragmatic Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K65.0',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Right/Left Subdiaphragmatic Space'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Subcostal anterior or lateral approach (avoiding transpleural trajectory)',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" Amplatz wire, 18G puncture needle, dilators',
    proceduralNarrativeTemplate:
      'Subdiaphragmatic fluid collection identified abutting diaphragm. CT planned trajectory strictly below costodiaphragmatic pleural reflection (angulated cranially from below costal margin). 18G needle entered collection under CT fluoroscopy. Pus evacuated. 0.035" wire secured in cavity. Tract dilated. 10F pigtail deployed and locked. 180 mL pus evacuated. Saline rinse performed.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Semi-recumbent position (Fowler) x 4 hours to facilitate dependent drainage.',
      hematomaChecks: 'Monitor drain output, respiratory rate, and SpO2.',
      requiredImaging: 'Chest X-ray to confirm no transpleural violation or reactive effusion.',
      hydrationProtocol: 'IV fluids 100 mL/hr.',
      medications: ['IV Piperacillin-Tazobactam 4.5g TDS', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Ipsilateral shoulder tip pain', 'Tachypnea / hypoxia', 'Pus leakage around catheter'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 6. Subhepatic / Morison Pouch Drainage
  {
    id: 'cat02-morison-pouch-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Percutaneous Drainage of Morison Pouch / Subhepatic Collection',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K65.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Hepatorenal Recess (Morison Pouch)'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Right anterior flank / mid-axillary subcostal approach',
    sheathDefault: '10F locking pigtail catheter',
    cathetersAndWires: '0.035" guidewire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Sonography demonstrated anechoic/hypoechoic collection in hepatorenal space. Infiltration of 2% lignocaine. 18G needle introduced under US guidance. Bile-tinged purulent fluid aspirated. 0.035" wire passed. 10F pigtail catheter placed and locked. 250 mL drained. Pigtail stitched securely to flank.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Supine / right lateral bedrest x 2 hours.',
      hematomaChecks: 'Monitor drain volume and color (bile vs pus).',
      hydrationProtocol: 'Routine IV fluids.',
      medications: ['IV Ceftriaxone 1g BD + Metronidazole 500mg TDS'],
      redFlags: ['Abdominal peritonism', 'Bleeding', 'High drain output > 500 mL/day bile'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 7. Pancreatic Pseudocyst Percutaneous Drainage
  {
    id: 'cat02-pancreatic-pseudocyst-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT / Ultrasound-Guided Percutaneous Catheter Drainage of Pancreatic Pseudocyst',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K86.3',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Lesser Sac / Pancreatic Pseudocyst Cavity'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Transgastric or left flank retroperitoneal route',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" stiff guidewire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Planning CT delineated mature thick-walled pseudocyst in lesser sac. Transgastric access chosen (anterior abdominal wall -> stomach anterior wall -> stomach posterior wall -> pseudocyst) to promote internal fistulization. 18G needle entered cyst. Clear brownish fluid aspirated (sent for amylase, lipase, CEA). 0.035" wire coiled. 12F pigtail catheter placed and locked. Rapid decompression achieved.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest flat x 4 hours.',
      hematomaChecks: 'Inspect drain output; monitor for epigastric guarding or hematemesis.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ['IV Pantoprazole 40mg BD', 'IV Octreotide 100mcg SC TDS if high amylase output', 'Tab Paracetamol 650mg'],
      redFlags: ['Frank blood in drainage (pseudoaneurysm rupture into cyst)', 'Peritonitis', 'Septic spike'],
    },
    consentId: 'consent-pancreas-drainage',
    calculatorId: 'calc-pancreatitis-score',
  },

  // 8. WOPN Multi-Catheter Step-Up Drainage
  {
    id: 'cat02-wopn-multicatheter-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT-Guided Multi-Catheter Step-Up Percutaneous Drainage for Walled-Off Pancreatic Necrosis (WOPN)',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K85.9',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Left Paracolic Gutter / Retroperitoneal Pancreatic Necrosis'],
    sedation: 'Local Anesthesia + IV Conscious Sedation',
    accessSiteDefault: 'Left retroperitoneal flank approach (behind descending colon)',
    sheathDefault: '14F-18F large bore sump / locking drainage catheter',
    cathetersAndWires: '0.035" Amplatz wire, serial dilators up to 18F, 18G needle',
    proceduralNarrativeTemplate:
      'CT demonstrated infected walled-off necrosis extending down left anterior pararenal space. Flank retroperitoneal approach used to avoid colon and peritoneal contamination. 18G needle entered necrotic collection. Turbid purulent debris aspirated. Stiff Amplatz wire coiled. Serial dilation performed. 16F large bore drainage catheter placed. Saline pulse-lavage instituted through catheter yielding necrotic tissue fragments. Free gravity drainage established.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest in ICU/HDU. Connect catheter to continuous flush or intermittent saline irrigation protocol.',
      hematomaChecks: 'Monitor vital signs for sepsis control and drain effluent for hemorrhage.',
      hydrationProtocol: 'Vigorous IV hydration per pancreatitis protocol.',
      medications: ['IV Meropenem 1g TDS', 'IV Pantoprazole 40mg BD', 'Nutritional support'],
      redFlags: ['Sudden massive hemorrhage in drain (splenic/GDA erosion)', 'Septic shock', 'Fecal contents in drain'],
    },
    consentId: 'consent-pancreas-drainage',
    calculatorId: 'calc-pancreatitis-score',
  },

  // 9. Retroperitoneal Necrosectomy Tract Upsizing
  {
    id: 'cat02-vplr-tract-necrosectomy',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Percutaneous Necrosectomy Tract Upsizing & Debridement for Infected Pancreatic Necrosis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K85.9',
      tariffInr: 7000,
    },
    modality: 'XA',
    targetAnatomy: ['Retroperitoneal Pancreatic Bed Necrotic Cavity'],
    sedation: 'General Anesthesia or Deep Sedation',
    accessSiteDefault: 'Existing left flank retroperitoneal drainage tract',
    sheathDefault: '24F-30F Amplatz renal sheath',
    cathetersAndWires: '0.035" Super Stiff wire, balloon dilation catheter (30F NephroMax)',
    proceduralNarrativeTemplate:
      'Patient on fluoro table. Existing 14F drain exchanged over stiff wire. Sinogram outlined extensive necrotic cavity. Tract dilated with 30F balloon. 30F Amplatz sheath placed into cavity. Rigid/flexible nephroscope introduced through sheath. High-flow warm saline irrigation. Under direct vision, loose necrotic sequestered fragments grasped with foreign-body forceps and removed. Hemostasis checked. 24F dual-lumen irrigation/drainage tube left in cavity.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours. Continuous saline irrigation at 100 mL/hr through dedicated inlet.',
      hematomaChecks: 'Surveillance for retroperitoneal bleeding and abdominal compartment syndrome.',
      hydrationProtocol: 'IV fluids adjusted to urine output > 0.5 mL/kg/hr.',
      medications: ['Targeted IV antibiotics', 'Adequate analgesia'],
      redFlags: ['Active arterial bleeding from sheath', 'Hypotension', 'Rigidity'],
    },
    consentId: 'consent-pancreas-necrosectomy',
  },

  // 10. Splenic Abscess Drainage
  {
    id: 'cat02-splenic-abscess-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT / Ultrasound-Guided Percutaneous Drainage of Splenic Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'D73.3',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Splenic Parenchymal Abscess'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Posterolateral subcostal or low intercostal route',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" Amplatz wire, 18G puncture needle, dilators',
    proceduralNarrativeTemplate:
      'CT planning visualized splenic abscess. Safe trajectory selected traversing minimal splenic tissue, avoiding pleura and colon. 18G needle entered abscess under CT fluoroscopy. Thick purulent material aspirated. 0.035" wire looped. 10F pigtail deployed and locked. Cavity cleared with saline wash. Post-placement CT showed no perisplenic hemorrhage.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Left lateral bed rest x 4 hours, then supine x 2 hours.',
      hematomaChecks: 'Monitor vitals q15m x 1h, q30m x 2h, then q1h. Check drain output for blood.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ['IV Antibiotics', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Frank blood in drain', 'Left shoulder pain (Kehr sign)', 'Hypotension'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 11. Psoas Abscess Percutaneous Drainage
  {
    id: 'cat02-psoas-abscess-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT-Guided Percutaneous Catheter Drainage of Psoas Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'M60.0',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Iliopsoas Muscle Compartment / Tuberculous or Pyogenic Abscess'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Prone posterolateral retroperitoneal lumbar approach',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" stiff guidewire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Patient prone. CT revealed multi-loculated fluid collection within right/left psoas muscle extending into iliacus. Direct posterior lumbar approach avoiding lumbar plexus nerves and colon. 18G needle placed into collection. Pus aspirated and sent for GeneXpert, pyogenic culture, and AFB. Wire coiled. Serial dilation done. 12F locking pigtail catheter positioned and locked. Complete evacuation achieved.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine or prone comfortable bedrest x 4 hours.',
      hematomaChecks: 'Monitor vitals and lower extremity motor function (femoral nerve) q30m x 4h.',
      hydrationProtocol: 'Oral fluids after 2 hours.',
      medications: ['Empiric IV Ceftriaxone 1g BD', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Femoral nerve neuropathy (quadriceps weakness / knee give-way)', 'Persistent high-grade fever', 'Drain displacement'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 12. Retroperitoneal Abscess Drainage
  {
    id: 'cat02-retroperitoneal-abscess-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT-Guided Percutaneous Drainage of Retroperitoneal / Pararenal Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K65.0',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Anterior / Posterior Pararenal Space'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Flank posterior retroperitoneal approach',
    sheathDefault: '10F/12F pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Retroperitoneal collection visualized on CT. Posterior flank trajectory planned outside peritoneal cavity. 18G needle advanced into cavity. Purulent fluid aspirated. Wire deployed. 10F locking pigtail catheter secured. Cavity irrigated until effluent clear.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Bedrest x 4 hours.',
      hematomaChecks: 'Vitals and drain monitoring.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['IV Antibiotics', 'Paracetamol 650mg'],
      redFlags: ['Abdominal pain', 'Fever', 'Drain hemorrhage'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 13. Pelvic Abscess Transabdominal Drainage
  {
    id: 'cat02-pelvic-abscess-transabdominal',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound / CT-Guided Transabdominal Drainage of Pelvic Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K65.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pouch of Douglas / Deep Pelvic Fluid Collection'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Suprapubic transabdominal approach',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Urinary bladder filled via Foley to provide acoustic window and displace small bowel loops. Pelvic abscess identified in rectovesical pouch. 18G needle inserted suprapubically under US guidance avoiding bladder and iliac vessels. Wire passed into cavity. 10F pigtail catheter placed. 150 mL purulent fluid drained.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Supine bedrest x 2 hours.',
      hematomaChecks: 'Monitor drain volume and Foley catheter output.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['IV Antibiotics', 'Analgesics'],
      redFlags: ['Peritonitis', 'Hematuria (bladder puncture)', 'Fever'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 14. Pelvic Collection Transrectal Drainage
  {
    id: 'cat02-pelvic-collection-transrectal',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Transrectal Ultrasound (TRUS)-Guided Catheter Drainage of Pelvic Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K65.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Deep Pelvic / Rectovesical / Presacral Abscess'],
    sedation: 'Deep Conscious Sedation + Perirectal Block',
    accessSiteDefault: 'Transrectal wall puncture under TRUS',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" stiff guidewire, 18G long needle',
    proceduralNarrativeTemplate:
      'TRUS probe with needle guide inserted into rectum. Deep pelvic abscess visualised directly abutting anterior/posterior rectal wall. Povidone-iodine rectal prep. 18G needle advanced through rectal wall into abscess cavity under live TRUS. Purulent fluid aspirated. 0.035" wire placed. 8F pigtail catheter placed transrectally and loop locked inside cavity. Catheter cut short or taped to perianal skin to drain freely into rectum/bag.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bed rest x 2 hours.',
      hematomaChecks: 'Monitor for rectal bleeding or fever.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['IV Metronidazole 500mg TDS + Ceftriaxone 1g BD'],
      redFlags: ['Heavy rectal bleeding', 'Pelvic pain', 'Catheter dislodgement'],
    },
    consentId: 'consent-pelvic-drainage',
  },

  // 15. Pelvic Abscess Transvaginal Drainage
  {
    id: 'cat02-pelvic-abscess-transvaginal',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Transvaginal Ultrasound (TVUS)-Guided Drainage of Pelvic Abscess / TOA',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'N73.9',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Tubo-Ovarian Abscess (TOA) / Pouch of Douglas Collection'],
    sedation: 'IV Conscious Sedation + Paracervical / Vaginal Vault Infiltration',
    accessSiteDefault: 'Posterior vaginal fornix (culdocentesis route)',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" guidewire, 18G needle',
    proceduralNarrativeTemplate:
      'Lithotomy position. Sterile vaginal prep. Endovaginal probe with needle guide positioned in posterior fornix. Thick-walled tubo-ovarian abscess imaged. Puncture through posterior fornix into abscess cavity. Pus aspirated and sent for microbiology. 8F pigtail catheter deployed over wire into cavity. Catheter secured to vaginal vault or perineum.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Rest in bed x 2 hours.',
      hematomaChecks: 'Monitor vaginal bleeding and vitals.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Broad-spectrum IV antibiotics for PID/TOA', 'Analgesia'],
      redFlags: ['Vaginal hemorrhage', 'Acute abdominal pain', 'High fever'],
    },
    consentId: 'consent-pelvic-drainage',
  },

  // 16. Transgluteal Pelvic Abscess Drainage
  {
    id: 'cat02-transgluteal-pelvic-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT-Guided Transgluteal Percutaneous Drainage of Deep Pelvic Collection',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K65.0',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Deep Presacral / Ischiorectal / Piriformis Space Pelvic Collection'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Prone transgluteal route through greater sciatic foramen medially',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" Amplatz stiff wire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Prone position. Deep pelvic abscess visualized. Transgluteal trajectory planned passing through sacrospinous ligament as close to the sacrum as possible to remain medial to the sciatic nerve and inferior gluteal vessels. 18G needle advanced into collection under CT guidance. Thick pus aspirated. Wire looped in cavity. 10F locking pigtail catheter placed. Drain secured to buttock.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine or contralateral lateral bedrest x 4 hours. Avoid sitting directly on catheter.',
      hematomaChecks: 'Check sciatic nerve motor and sensory function (foot dorsiflexion, numbness) and vitals q30m x 2h.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['IV Antibiotics', 'Tab Paracetamol 650mg TDS'],
      redFlags: ['Sciatica / severe shooting leg pain', 'Foot drop', 'Gluteal hematoma'],
    },
    consentId: 'consent-pelvic-drainage',
  },

  // 17. Diagnostic Paracentesis
  {
    id: 'cat02-paracentesis-diagnostic',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Diagnostic Abdominal Paracentesis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'R18.8',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Peritoneal Cavity / Ascitic Fluid'],
    sedation: 'Local Anesthesia (2% Lignocaine 5 mL)',
    accessSiteDefault: 'Left lower quadrant (2 fingerbreadths medial and superior to ASIS)',
    sheathDefault: '20G/22G spinal needle or angiocath',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Ultrasound confirmed fluid pocket in left iliac fossa free of bowel loops and inferior epigastric vessels. Local anesthesia injected with "Z-track" technique. 20G needle advanced into peritoneal cavity under US guidance. 50 mL straw-colored ascitic fluid aspirated into syringes and sent for cell count, cytology, albumin (SAAG calculation), total protein, gram stain, culture, and ADA. Needle removed, dry dressing applied.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Rest quietly in bed x 1 hour on right side or supine.',
      hematomaChecks: 'Inspect puncture site for ascitic fluid leakage.',
      hydrationProtocol: 'Routine oral fluids.',
      medications: ['Symptomatic care'],
      redFlags: ['Persistent puncture leak', 'Abdominal pain', 'Dizziness'],
    },
    consentId: 'consent-paracentesis',
    calculatorId: 'calc-saag',
  },

  // 18. Large-Volume Therapeutic Paracentesis + Albumin
  {
    id: 'cat02-paracentesis-therapeutic-albumin',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Large-Volume Paracentesis (LVP) with Intravenous Albumin Infusion',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'R18.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Peritoneal Cavity / Refractory Tense Ascites'],
    sedation: 'Local Anesthesia (2% Lignocaine 10 mL)',
    accessSiteDefault: 'Left lower quadrant under ultrasound guidance',
    sheathDefault: '8F/10F multi-sidehole peritoneal dialysis catheter or Caldwell needle',
    cathetersAndWires: '0.035" wire, 8F catheter',
    proceduralNarrativeTemplate:
      'Ultrasound marked deepest pocket in LLQ away from inferior epigastric artery. "Z-track" technique used to prevent post-procedure ascites leakage. 8F multi-sidehole catheter introduced over wire. Connected to vacuum evacuation bottles. 6.5 Liters of ascitic fluid evacuated over 90 minutes. Intravenous 20% Human Albumin infused concomitantly at 8 grams per liter of ascites removed beyond 5 Liters (16g albumin administered) to prevent paracentesis-induced circulatory dysfunction (PICD). Catheter removed, purse-string suture placed.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Supine bedrest x 2 hours. Pressure dressing over puncture site.',
      hematomaChecks: 'Monitor blood pressure and pulse q15m x 1h, then q30m x 2h (watch for post-paracentesis hypotension).',
      hydrationProtocol: 'Oral fluids ad libitum; maintain sodium restriction per liver protocol.',
      medications: ['IV Human Albumin 20% as per volume removed', 'Tab Spironolactone + Furosemide resumed next day'],
      redFlags: ['Post-paracentesis circulatory dysfunction (hypotension, syncope)', 'Persistent fluid leakage through dressing', 'Oliguria'],
    },
    consentId: 'consent-paracentesis',
    calculatorId: 'calc-child-pugh',
  },

  // 19. Tunnelled Peritoneal Catheter Insertion (PleurX)
  {
    id: 'cat02-pleurx-peritoneal-catheter',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Tunnelled Indwelling Peritoneal Catheter (PleurX) Placement for Malignant Ascites',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Tunnelled Long-Term Indwelling Catheter for Refractory Ascites / Pleural Effusion',
      packageCode: '2849-IN010A',
      icd10: 'R18.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Peritoneal Cavity / Anterior Abdominal Wall Subcutaneous Tunnel'],
    sedation: 'Local Anesthesia (2% Lignocaine with Adrenaline) + Conscious Sedation',
    accessSiteDefault: 'Right or left lower quadrant abdominal wall',
    sheathDefault: '15.5F peel-away introducer sheath',
    cathetersAndWires: 'PleurX 15.5F silicone fenestrated catheter with polyester cuff, tunneler',
    embolicOrImplants: 'PleurX indwelling catheter with polyester cuff',
    proceduralNarrativeTemplate:
      'Peritoneal entry site and cutaneous exit site (8 cm apart) selected and anesthetized. Subcutaneous tunnel created from exit site to entry site using blunt tunneler. PleurX catheter pulled through until cuff was 2 cm inside exit tract. 18G needle entered peritoneal cavity under US. Peel-away sheath introduced over wire. Fenestrated catheter advanced into pelvis. Peel-away sheath split and removed. Flow tested with evacuation of 1 L ascites. Catheter clamped and cap attached. Incisions sutured.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Rest quietly in bed x 2 hours. PleurX valve capped and dressed.',
      hematomaChecks: 'Inspect tunnel track and exit site for bleeding or fluid leak.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg TDS', 'Drainage schedule: 1000 mL every alternate day'],
      redFlags: ['Peritoneal infection (cloudy fluid, fever)', 'Leak around exit site', 'Hypotension'],
    },
    consentId: 'consent-pleurx-placement',
  },

  // 20. Denver Peritoneovenous Shunt Placement
  {
    id: 'cat02-denver-shunt-placement',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Fluoroscopy-Guided Denver Peritoneovenous Shunt Placement for Refractory Ascites',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'R18.0',
      tariffInr: 7000,
    },
    modality: 'HYBRID',
    targetAnatomy: ['Peritoneal Cavity, Subcutaneous Thoracoabdominal Tunnel, Internal Jugular Vein / SVC'],
    sedation: 'General Anesthesia or Deep Sedation',
    accessSiteDefault: 'Right internal jugular vein and right lower abdominal quadrant',
    sheathDefault: '8F/10F peel-away vascular sheath',
    cathetersAndWires: 'Denver shunt kit (peritoneal fenestrated limb, pump chamber, venous limb), tunneler',
    embolicOrImplants: 'Denver one-way valve shunt assembly',
    proceduralNarrativeTemplate:
      'Under sterile conditions, right IJV accessed under US and peel-away sheath placed. Right lower abdominal wall entered and multi-hole peritoneal catheter positioned in pelvis. Denver pump chamber positioned subcutaneously over lower costal margin (firm bony background for manual compression). Shunt limbs tunnelled. Venous limb advanced through peel-away into right atrium/SVC junction under fluoroscopy. Valve pump manually primed with prompt one-way forward flow. Punctures closed.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Semi-recumbent bedrest x 6 hours. Elastic abdominal binder applied.',
      hematomaChecks: 'Monitor CVP, respiratory rate, and check for signs of volume overload / DIC.',
      hydrationProtocol: 'Limit IV fluids; monitor for pulmonary edema.',
      medications: ['Diuretics as prescribed', 'Prophylactic IV Cefuroxime 1.5g', 'Pump chamber manual pumping protocol: 20 compressions QID'],
      redFlags: ['Acute pulmonary edema (dyspnea, pink frothy sputum)', 'DIC / spontaneous bleeding', 'Shunt occlusion'],
    },
    consentId: 'consent-denver-shunt',
  },

  // 21. Diagnostic Thoracentesis
  {
    id: 'cat02-thoracentesis-diagnostic',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Diagnostic Pleural Aspiration / Thoracentesis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J90',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pleural Space / Pleural Fluid'],
    sedation: 'Local Anesthesia (2% Lignocaine 5 mL)',
    accessSiteDefault: 'Posterior intercostal space along superior rib margin',
    sheathDefault: '20G/21G needle with 50 mL syringe',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Patient seated upright leaning forward over bedside table. Ultrasound localized pleural effusion, diaphragm, and lung border. Infiltration of local anesthesia down to parietal pleura over superior border of rib (avoiding intercostal neurovascular bundle). 20G needle introduced under US into fluid. 60 mL pleural fluid aspirated. Aliquots sent for Light criteria (LDH, protein), cell count, pH, glucose, cytology, gram stain, and GeneXpert.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Rest comfortably in bed x 1 hour.',
      hematomaChecks: 'Monitor SpO2 and respiratory rate.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Paracetamol PRN'],
      redFlags: ['Pleuritic chest pain', 'Persistent cough', 'Shortness of breath'],
    },
    consentId: 'consent-thoracentesis',
  },

  // 22. Therapeutic Thoracentesis
  {
    id: 'cat02-thoracentesis-therapeutic',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Large-Volume Therapeutic Thoracentesis',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J90',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Hemithorax Pleural Cavity'],
    sedation: 'Local Anesthesia (2% Lignocaine 10 mL)',
    accessSiteDefault: 'Posterior 7th-8th intercostal space superior to rib',
    sheathDefault: '8F Yueh / Centesis catheter with safety valve',
    cathetersAndWires: 'N/A',
    proceduralNarrativeTemplate:
      'Ultrasound marked fluid pocket. Local anesthesia administered. 8F centesis catheter with self-sealing valve introduced into pleural space. 1200 mL straw fluid evacuated by gravity/vacuum. Evacuation halted at 1200 mL to prevent re-expansion pulmonary edema. Real-time US confirmed lung re-expansion with no pneumothorax. Catheter removed on held expiration.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Rest in semi-Fowler position x 2 hours.',
      hematomaChecks: 'Monitor SpO2, respiratory rate, and blood pressure q15m x 1h, then q30m x 1h.',
      requiredImaging: 'Erect PA Chest X-ray if patient develops persistent cough, chest pain, or hypoxia.',
      hydrationProtocol: 'Routine fluids.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Re-expansion pulmonary edema (intractable cough, pink sputum, hypoxia)', 'Severe chest pain'],
    },
    consentId: 'consent-thoracentesis',
  },

  // 23. Small-Bore Pleural Pigtail Catheter Placement
  {
    id: 'cat02-pleural-pigtail-catheter',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Small-Bore Pigtail Catheter Placement for Empyema / Effusion',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J86.9',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pleural Cavity / Parapneumonic Effusion / Empyema'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Mid-axillary or posterior intercostal space',
    sheathDefault: '10F/12F locking pigtail pleural catheter',
    cathetersAndWires: '0.035" J-tip wire, 18G needle, dilators',
    proceduralNarrativeTemplate:
      'Ultrasound mapped loculated pleural collection. Anesthesia given. 18G needle entered collection. 0.035" wire passed into pleural apex. 10F/12F locking pigtail catheter introduced, locked, and connected to underwater seal chest drain system (-20 cm H2O suction). Immediate evacuation of turbid purulent fluid.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Maintain chest drain bottle upright and below chest level at all times.',
      hematomaChecks: 'Monitor air leak (bubbling) and fluid drainage rate q1h.',
      requiredImaging: 'Post-placement erect Chest X-ray to confirm pigtail loop position and lung expansion.',
      hydrationProtocol: 'Normal fluids.',
      medications: ['IV Antibiotics', 'Analgesics'],
      redFlags: ['Continuous vigorous bubbling (bronchopleural fistula)', 'Blocked drain with increasing dyspnea', 'Subcutaneous emphysema'],
    },
    consentId: 'consent-pleural-pigtail',
  },

  // 24. Intercostal Drainage Tube (ICD) Insertion
  {
    id: 'cat02-icd-chest-tube',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Fluoroscopy / Ultrasound-Guided Large-Bore Chest Tube (ICD) Placement',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J94.9',
      tariffInr: 7000,
    },
    modality: 'XA',
    targetAnatomy: ['Pleural Cavity / Hemothorax / Thick Empyema'],
    sedation: 'Local Anesthesia (2% Lignocaine 15 mL) + Conscious Sedation',
    accessSiteDefault: 'Triangle of safety (5th ICS mid-axillary line)',
    sheathDefault: '20F-28F straight chest tube with trocar',
    cathetersAndWires: '0.038" stiff Amplatz wire, serial dilators',
    proceduralNarrativeTemplate:
      'Hemothorax / thick empyema localized. Triangle of safety anesthetized. 18G needle passed into pleural cavity. Heavy guidewire placed. Serial dilatation to 24F. 24F chest tube advanced into posterior basal gutter under fluoroscopic guidance. Connected to underwater seal. Anchored with 1-0 silk horizontal mattress suture.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Semi-Fowler bedrest. Ensure chest bottle is always below patient level.',
      hematomaChecks: 'Measure hourly drainage and check dressing for soakage.',
      requiredImaging: 'Immediate post-procedure PA Chest X-ray.',
      hydrationProtocol: 'IV fluids as needed.',
      medications: ['Adequate analgesia (IV Tramadol / Paracetamol)', 'Antibiotics'],
      redFlags: ['Drainage > 200 mL/hr of frank blood (ongoing hemothorax)', 'Tension pneumothorax signs', 'Tube dislodgement'],
    },
    consentId: 'consent-icd',
  },

  // 25. Intrapleural Fibrinolytic & DNase Therapy (tPA + Pulmozyme)
  {
    id: 'cat02-intrapleural-tpa-dnase',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Intrapleural Fibrinolytic and DNase Therapy (tPA + Pulmozyme) for Multiloculated Empyema',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J86.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Multiseptated Empyema / Fibrinous Pleural Space'],
    sedation: 'Not required (administered via existing chest tube)',
    accessSiteDefault: 'Existing pleural pigtail or chest drain tube',
    sheathDefault: 'Existing chest tube',
    cathetersAndWires: 'N/A',
    embolicOrImplants: 'Tissue Plasminogen Activator (tPA 10 mg) + Dornase Alfa (DNase 5 mg)',
    proceduralNarrativeTemplate:
      'Under strict aseptic technique, tPA (10 mg in 50 mL normal saline) and DNase (5 mg in 50 mL normal saline) instilled sequentially through the chest tube into the multiloculated pleural space. Tube clamped for 2 hours while patient rotated (supine, right lateral, left lateral, prone) to distribute enzymes. Tube unclamped after 2 hours and connected to -20 cm H2O suction. Follow-up ultrasound demonstrated breakdown of loculations with massive drainage of pus.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Positional changes every 30 minutes during the 2-hour clamping period, then semi-recumbent.',
      hematomaChecks: 'Monitor chest drain effluent closely for signs of intrapleural bleeding.',
      requiredImaging: 'Bedside ultrasound / Chest X-ray next morning to assess clearance.',
      hydrationProtocol: 'Routine hydration.',
      medications: ['Continue IV broad-spectrum antibiotics', 'Paracetamol for pleuritic ache'],
      redFlags: ['Frank intrapleural hemorrhage (> 200 mL fresh blood)', 'Severe acute chest pain', 'Sudden desaturation'],
    },
    consentId: 'consent-pleural-fibrinolysis',
  },

  // 26. Tunnelled Pleural Catheter Insertion (PleurX)
  {
    id: 'cat02-pleurx-pleural-catheter',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Tunnelled Indwelling Pleural Catheter (PleurX) Insertion for Malignant Pleural Effusion',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Tunnelled Long-Term Indwelling Catheter for Refractory Ascites / Pleural Effusion',
      packageCode: '2849-IN010A',
      icd10: 'C78.2',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pleural Cavity / Lateral Chest Wall Subcutaneous Tunnel'],
    sedation: 'Local Anesthesia (2% Lignocaine + Adrenaline) + Mild Sedation',
    accessSiteDefault: 'Posterior/mid-axillary 6th-7th intercostal space',
    sheathDefault: '15.5F peel-away chest introducer sheath',
    cathetersAndWires: 'PleurX 15.5F fenestrated silicone catheter kit with polyester cuff, tunneler',
    embolicOrImplants: 'PleurX indwelling silicone catheter with cuff',
    proceduralNarrativeTemplate:
      'PleurX entry and anterior cutaneous exit sites anesthetized. Subcutaneous tunnel created. Catheter pulled through until cuff situated 2 cm within tract. Pleural puncture performed under US guidance. Peel-away sheath placed over wire. Catheter positioned in posterior pleural space. Sheath removed. Flow tested with vacuum bottle removing 800 mL effusion. Valve closed. Skin closed with non-absorbable sutures.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Rest x 2 hours. Keep valve protected with sterile cap and dry gauze.',
      hematomaChecks: 'Monitor for chest pain, bleeding at exit site, or subcutaneous emphysema.',
      requiredImaging: 'Erect Chest X-ray to document catheter track and baseline post-placement fluid level.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg TDS', 'Intermittent drainage protocol: drain up to 1000 mL every 48-72h'],
      redFlags: ['Pleural infection (fever, purulent drainage)', 'Loss of suction vacuum', 'Severe cough with hypoxia'],
    },
    consentId: 'consent-pleurx-placement',
  },

  // 27. Lung Abscess Catheter Drainage
  {
    id: 'cat02-lung-abscess-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT / Ultrasound-Guided Percutaneous Catheter Drainage of Refractory Lung Abscess',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J85.2',
      tariffInr: 7000,
    },
    modality: 'CT',
    targetAnatomy: ['Peripheral Pulmonary Cavitary Abscess abutting Pleura'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Transthoracic intercostal approach directly traversing adherent pleura',
    sheathDefault: '10F/12F locking pigtail catheter',
    cathetersAndWires: '0.035" stiff guidewire, 18G puncture needle, dilators',
    proceduralNarrativeTemplate:
      'CT confirmed large peripheral lung abscess with symphysis/pleural adhesion to chest wall (preventing empyema). Trajectory planned strictly through adherent pleural zone. 18G needle entered abscess under CT guidance. Thick purulent foul material evacuated. 0.035" wire coiled within cavity. 10F locking pigtail catheter deployed. Cavity gently rinsed with saline. Connected to underwater seal.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Dependent positioning with abscess side tilted down. Underwater seal bottle below chest level.',
      hematomaChecks: 'Watch for hemoptysis, air leak in water seal, and SpO2.',
      requiredImaging: 'Erect PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['IV Clindamycin 600mg TDS + Ceftriaxone 1g BD', 'Codeine 10mg PRN for cough'],
      redFlags: ['Massive hemoptysis', 'Tension pneumothorax (acute severe dyspnea, tracheal shift)', 'Persistent air leak'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 28. Pneumothorax Pigtail Catheter with Heimlich Valve
  {
    id: 'cat02-pneumothorax-heimlich-pigtail',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Percutaneous Pigtail Catheter Placement for Pneumothorax with Heimlich Flutter Valve',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'J93.9',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pleural Air Space / Apical Pneumothorax'],
    sedation: 'Local Anesthesia (2% Lignocaine 10 mL)',
    accessSiteDefault: '2nd intercostal space midclavicular line or 4th-5th ICS anterior axillary line',
    sheathDefault: '8.5F/10F pigtail catheter with trocar / Seldinger kit',
    cathetersAndWires: '0.035" J-tip guidewire, 18G needle',
    embolicOrImplants: 'Heimlich one-way flutter valve',
    proceduralNarrativeTemplate:
      'Ultrasound demonstrated "stratosphere/barcode sign" and absent lung sliding confirming pneumothorax. Puncture in 2nd ICS midclavicular line over superior rib border. Air aspirated freely. 0.035" guidewire passed toward pleural apex. 8.5F pigtail catheter placed and loop locked. Connected to Heimlich one-way flutter valve. Immediate flutter valve mobilization with air egress. Post-procedure lung sliding reappeared on ultrasound.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Ambulatory with Heimlich valve attached to chest wall. Ensure arrow on Heimlich valve points away from patient.',
      hematomaChecks: 'Monitor respiratory rate, SpO2, and check flutter valve function during coughing.',
      requiredImaging: 'Erect PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.',
      hydrationProtocol: 'Oral hydration.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Progressive shortness of breath', 'Subcutaneous emphysema', 'Valve blockage'],
    },
    consentId: 'consent-pneumothorax',
  },

  // 29. Emergency Pericardiocentesis under US
  {
    id: 'cat02-pericardiocentesis-emergency',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Emergency Pericardiocentesis for Cardiac Tamponade',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'I31.9',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pericardial Sac / Cardiac Tamponade Fluid'],
    sedation: 'Local Anesthesia (2% Lignocaine) + Continuous ECG Monitoring',
    accessSiteDefault: 'Subxiphoid approach (Larrey point) or apical parasternal approach',
    sheathDefault: '6F/8F locking pigtail catheter',
    cathetersAndWires: '0.035" J-tip guidewire, 18G needle, ECG lead attached to needle',
    proceduralNarrativeTemplate:
      'Echocardiography showed large pericardial effusion with right ventricular diastolic collapse and dilated IVC. Subxiphoid space prepped. 18G needle introduced at 45 degree angle toward left shoulder under real-time ultrasound. Continuous negative suction applied. Dark non-clotting hemorrhagic pericardial fluid aspirated. 0.035" wire advanced and observed coiling safely in pericardial space on echocardiography. 6F pigtail catheter deployed. 350 mL evacuated with immediate hemodynamics normalization (BP rose from 78/50 to 118/74 mmHg). Drain secured to skin.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict bedrest in Cardiac ICU with continuous ECG and hemodynamics monitoring.',
      hematomaChecks: 'Monitor BP, heart rate, CVP, and drain volume hourly.',
      requiredImaging: 'Repeat echocardiogram at 4 hours post-drainage.',
      hydrationProtocol: 'IV fluids guided by CVP.',
      medications: ['IV Antibiotics', 'Analgesics as needed'],
      redFlags: ['Re-accumulation / cardiac tamponade (hypotension, raised JVP, muffled sounds)', 'ST segment elevation on ECG', 'Clotted blood in drain'],
    },
    consentId: 'consent-pericardiocentesis',
  },

  // 30. Indwelling Pericardial Pigtail Placement & Instillation
  {
    id: 'cat02-pericardial-pigtail-indwelling',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Percutaneous Indwelling Pericardial Catheter Placement & Sclerotherapy for Malignant Effusion',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'I31.3',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Pericardial Sac / Recurrent Malignant Pericardial Effusion'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Subxiphoid / parasternal intercostal route',
    sheathDefault: '6F/8F locking pigtail catheter',
    cathetersAndWires: '0.035" J-tip wire, 18G needle',
    embolicOrImplants: 'Bleomycin (15-30 units) or Cisplatin intrapericardial instillation',
    proceduralNarrativeTemplate:
      'Recurrent malignant pericardial effusion confirmed. Subxiphoid puncture under US. 6F multi-sidehole pigtail catheter positioned in pericardial space. Effusion drained to completion. Bleomycin sclerotherapy instilled through catheter for 1 hour then reopened to gravity. Catheter maintained for 48 hours until drainage < 25 mL/day.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Semi-Fowler bedrest in ICU x 6 hours.',
      hematomaChecks: 'Continuous telemetry and vitals monitoring.',
      requiredImaging: 'Echocardiogram prior to catheter removal.',
      hydrationProtocol: 'IV fluids 75 mL/hr.',
      medications: ['Analgesics for pericardial irritation', 'Antiemetics'],
      redFlags: ['Arrhythmias', 'Hypotension', 'Severe substernal chest pain'],
    },
    consentId: 'consent-pericardiocentesis',
  },

  // 31. Urinoma Catheter Drainage
  {
    id: 'cat02-urinoma-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'CT / Ultrasound-Guided Percutaneous Drainage of Retroperitoneal Urinoma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'N28.89',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Perirenal / Retroperitoneal Space / Urinoma Cavity'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Flank retroperitoneal approach',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" stiff wire, 18G needle',
    proceduralNarrativeTemplate:
      'Ultrasound identified perirenal fluid collection following ureteral injury/calculus. 18G needle inserted. Clear yellowish fluid aspirated (fluid creatinine > serum creatinine confirming urinoma). 8.5F locking pigtail catheter placed over guidewire. Cavity emptied completely.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bed rest x 2 hours.',
      hematomaChecks: 'Monitor drain volume vs Foley urinary output.',
      hydrationProtocol: 'Oral hydration.',
      medications: ['IV/Oral Ceftriaxone', 'Paracetamol'],
      redFlags: ['Gross hematuria', 'Drain blockage', 'Fever'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 32. Biloma Catheter Drainage
  {
    id: 'cat02-biloma-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound / CT-Guided Percutaneous Drainage of Post-Operative Biloma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K83.8',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Subhepatic / Gallbladder Fossa / Intrahepatic Biloma'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Right subcostal or intercostal approach',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle',
    proceduralNarrativeTemplate:
      'Ultrasound localized 8 cm fluid collection in gallbladder fossa post-laparoscopic cholecystectomy. 18G needle entered collection under real-time guidance. Frank dark-green bile aspirated (sent for bilirubin and culture). 10F locking pigtail catheter placed and secured. Total 350 mL bile evacuated.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bed rest x 2 hours. Keep drain bag dependent.',
      hematomaChecks: 'Record bile output volume every 8 hours.',
      hydrationProtocol: 'Maintain adequate hydration.',
      medications: ['IV Antibiotics', 'Analgesics'],
      redFlags: ['Persistent bile output > 300 mL/day (active duct leak needing ERCP/PTBD)', 'Biliary peritonitis', 'Fever'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 33. Pelvic Lymphocele Drainage
  {
    id: 'cat02-lymphocele-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Percutaneous Catheter Drainage of Pelvic Lymphocele',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'I89.8',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Post-Transplant / Post-Pelvic Dissection Lymphocele'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Iliac fossa anterior extraperitoneal route',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle',
    proceduralNarrativeTemplate:
      'Sonography revealed well-circumscribed anechoic pelvic collection compressing the transplant ureter/iliac vein. Extraperitoneal route selected under US. 18G needle passed into cavity. Clear pale-yellow fluid aspirated (fluid creatinine tested to rule out urinoma). 8.5F pigtail catheter deployed and locked.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bed rest x 2 hours.',
      hematomaChecks: 'Monitor drain output and lower extremity edema.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Prophylactic oral antibiotics', 'Paracetamol PRN'],
      redFlags: ['Infection of lymphocele', 'Catheter pull-out', 'Swelling in ipsilateral leg'],
    },
    consentId: 'consent-lymphocele-drainage',
  },

  // 34. Pelvic Lymphocele Sclerotherapy
  {
    id: 'cat02-lymphocele-sclerotherapy',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Percutaneous Sclerotherapy of Lymphocele using Povidone-Iodine / Bleomycin / Alcohol',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'I89.8',
      tariffInr: 7000,
    },
    modality: 'XA',
    targetAnatomy: ['Pelvic Lymphocele Cavity'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Existing lymphocele catheter',
    sheathDefault: 'Existing 8F/10F catheter',
    cathetersAndWires: 'N/A',
    embolicOrImplants: '10% Povidone-Iodine (Betadine) / Bleomycin (15-30 IU) / Absolute Alcohol (95%)',
    proceduralNarrativeTemplate:
      'Fluoroscopic contrast injection confirmed intact non-leaking cavity without communication to peritoneal cavity or vascular structures. Fluid completely evacuated. Sclerosant (10% Povidone-Iodine solution) instilled into cavity equal to 25% of cavity volume. Catheter clamped for 60 minutes while patient rotated into supine, prone, and lateral positions. Solution re-aspirated completely and catheter opened to gravity drainage.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Positional changes every 15 minutes during the 1-hour dwell time.',
      hematomaChecks: 'Monitor for pelvic pain and vital signs.',
      hydrationProtocol: 'Normal hydration.',
      medications: ['Tab Paracetamol 650mg TDS', 'Tab Tramadol 50mg PRN for visceral pain'],
      redFlags: ['Severe pelvic pain during sclerosant dwell', 'Fever', 'Catheter leakage'],
    },
    consentId: 'consent-lymphocele-drainage',
  },

  // 35. Infected Hematoma Evacuation
  {
    id: 'cat02-infected-hematoma-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound / CT-Guided Percutaneous Drainage of Infected Hematoma / Seroma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'T81.0',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Subcutaneous / Muscular / Retroperitoneal Hematoma Cavity'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Direct percutaneous approach over soft-tissue collection',
    sheathDefault: '12F/14F large bore pigtail catheter',
    cathetersAndWires: '0.035" Amplatz stiff wire, 18G needle, serial dilators',
    proceduralNarrativeTemplate:
      'Liquefied infected hematoma localized with ultrasound. Color Doppler verified no ongoing active arterial blush. 18G needle inserted. Dark altered lysing blood and purulent fluid aspirated. Guidewire coiled. 12F large bore drainage catheter placed. Saline irrigation performed to clear clotted debris. Catheter anchored to skin.',
    postOpCare: {
      immobilizationHours: 2,
      immobilizationInstructions: 'Bed rest x 2 hours.',
      hematomaChecks: 'Monitor drain effluent (watch for fresh bleeding vs dark altered blood).',
      hydrationProtocol: 'Oral fluids.',
      medications: ['IV Antibiotics', 'Paracetamol 650mg TDS'],
      redFlags: ['Sudden rush of bright red arterial blood in drain', 'Expanding hematoma', 'Hypotension'],
    },
    consentId: 'consent-abscess-drainage',
  },

  // 36. Simple Hepatic Cyst Percutaneous Sclerosis
  {
    id: 'cat02-hepatic-cyst-sclerosis',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Percutaneous Aspiration and Ethanol Sclerotherapy of Hepatic Cyst',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'K76.89',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Large Symptomatic Non-Parasitic Simple Hepatic Cyst'],
    sedation: 'Local Anesthesia (2% Lignocaine) + IV Conscious Sedation',
    accessSiteDefault: 'Transhepatic route traversing 1-2 cm of liver parenchyma',
    sheathDefault: '8F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle',
    embolicOrImplants: '99% Absolute Ethanol (up to 25% of cyst volume, max 100 mL)',
    proceduralNarrativeTemplate:
      'Large symptomatic simple hepatic cyst (11 cm) localized. Transhepatic puncture performed. Clear cyst fluid evacuated completely (sent for cytology, CEA, CA 19-9 to rule out mucinous cystic neoplasm). Contrast fluoroscopy confirmed no biliary connection. 99% sterile ethanol instilled (25% of original volume). Patient repositioned every 5 minutes for 20 minutes dwell time. Ethanol completely aspirated. Catheter removed.',
    postOpCare: {
      immobilizationHours: 4,
      immobilizationInstructions: 'Supine bedrest x 4 hours.',
      hematomaChecks: 'Monitor BP and abdominal pain (mild alcohol intoxication sensation may occur).',
      hydrationProtocol: 'Oral hydration.',
      medications: ['Tab Paracetamol 650mg TDS', 'IV Ondansetron 4mg'],
      redFlags: ['Severe persistent RUQ pain', 'Fever', 'Intoxication signs'],
    },
    consentId: 'consent-cyst-sclerosis',
  },

  // 37. ADPKD Dominant Cyst Sclerosis
  {
    id: 'cat02-adpkd-cyst-sclerosis',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound / CT-Guided Percutaneous Aspiration & Sclerotherapy of Dominant ADPKD Cyst',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'Q61.2',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Dominant Symptomatic Renal Cyst in Polycystic Kidney Disease'],
    sedation: 'Local Anesthesia + Conscious Sedation',
    accessSiteDefault: 'Posterior flank approach',
    sheathDefault: '8F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle',
    embolicOrImplants: '95% Absolute Alcohol or Bleomycin or Doxycycline',
    proceduralNarrativeTemplate:
      'Dominant painful cyst causing compressive flank pain localized. 18G needle entered cyst. 320 mL clear fluid aspirated. Cystogram confirmed no extravasation or communication with collecting system. Sclerosant instilled for 20 minutes with positional rolling, then evacuated. Catheter removed.',
    postOpCare: {
      immobilizationHours: 3,
      immobilizationInstructions: 'Bed rest flat x 3 hours.',
      hematomaChecks: 'Monitor vitals and flank pain.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg TDS'],
      redFlags: ['Flank pain exacerbation', 'Hematuria', 'Fever'],
    },
    consentId: 'consent-cyst-sclerosis',
    calculatorId: 'calc-ckd-epi',
  },

  // 38. Simple Renal Cortical Cyst Sclerotherapy
  {
    id: 'cat02-renal-cyst-sclerosis',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Percutaneous Aspiration & Absolute Alcohol Sclerotherapy of Simple Renal Cyst',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'N28.1',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Bosniak I/II Symptomatic Renal Cortical Cyst'],
    sedation: 'Local Anesthesia (2% Lignocaine)',
    accessSiteDefault: 'Flank / posterior lumbar route under US',
    sheathDefault: '6F/8F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle',
    embolicOrImplants: '99% Absolute Ethanol',
    proceduralNarrativeTemplate:
      'Bosniak I simple renal cortical cyst causing hydronephrosis/hypertension targeted. Under US guidance, 18G needle placed in cyst center. 240 mL clear fluid aspirated. Fluoroscopic cystography with 20% dilute contrast proved absence of communication with pelvicalyceal system. 40 mL 99% ethanol instilled, dwelled for 15 minutes, then completely aspirated. Complete collapse of cyst documented.',
    postOpCare: {
      immobilizationHours: 3,
      immobilizationInstructions: 'Bedrest supine x 3 hours.',
      hematomaChecks: 'Vitals q30m x 3h; inspect urine for blood.',
      hydrationProtocol: 'Oral fluids.',
      medications: ['Tab Paracetamol 650mg PRN'],
      redFlags: ['Hematuria', 'Flank pain', 'Fever'],
    },
    consentId: 'consent-cyst-sclerosis',
  },

  // 39. Post-Surgical Seroma Catheter Drainage
  {
    id: 'cat02-surgical-seroma-drainage',
    categoryNumber: 2,
    categoryName: 'Catheter Drainages, Fluid Aspiration & Stenting',
    title: 'Ultrasound-Guided Percutaneous Drainage of Post-Surgical Refractory Seroma',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Image Guided Percutaneous Drainage / Biliary Drainage / Cholecystostomy / Sclerotherapy',
      packageCode: '1849-IN057A',
      icd10: 'T81.89',
      tariffInr: 7000,
    },
    modality: 'US',
    targetAnatomy: ['Abdominal Wall / Inguinal / Mastectomy Flap Seroma Cavity'],
    sedation: 'Local Anesthesia',
    accessSiteDefault: 'Direct percutaneous route through healthy skin edge',
    sheathDefault: '8F/10F locking pigtail catheter',
    cathetersAndWires: '0.035" wire, 18G needle',
    proceduralNarrativeTemplate:
      'Ultrasound identified chronic encapsulated seroma cavity in surgical bed. 18G needle entered cavity under live sonography. Serous fluid evacuated. 8F pigtail catheter deployed. Low-pressure bulb suction (Jackson-Pratt type) connected. Cavity collapsed.',
    postOpCare: {
      immobilizationHours: 1,
      immobilizationInstructions: 'Compression bandage applied over cavity. Maintain negative pressure on bulb.',
      hematomaChecks: 'Record daily bulb output.',
      hydrationProtocol: 'Routine oral fluids.',
      medications: ['Paracetamol 650mg PRN'],
      redFlags: ['Erythema / cellulitis', 'Purulent drainage (infection of seroma)', 'Loss of suction'],
    },
    consentId: 'consent-abscess-drainage',
  },
];
