import { MasterProcedure } from './types';

/**
 * Category 08: Interventional Oncology Transcatheter Therapies (4 Procedures)
 * Strict Rajasthan MAAY / RGHS compatibility and SMS Medical College clinical protocols.
 */
export const CATEGORY_08_IO_TRANSCATHETER: MasterProcedure[] = [
  {
    id: 'cat08-ctace-lipiodol',
    categoryNumber: 8,
    categoryName: 'Interventional Oncology Transcatheter Therapies',
    title: 'Conventional Transarterial Chemoembolization (cTACE) with Lipiodol & Doxorubicin',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Chemoembolization (TACE)',
      packageCode: '1849-MG077A',
      icd10: 'C22.0',
      tariffInr: 35000,
    },
    modality: 'XA',
    targetAnatomy: ["Proper Hepatic Artery", "Right/Left Hepatic Artery", "Segmental Branches"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '5F 11cm Sheath',
    cathetersAndWires: '5F RH / Cobra / Simmons catheter, 2.0F - 2.7F microcatheter, 0.014" wire',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'Lipiodol-Doxorubicin Emulsion (10-15 mL) + Gelfoam sponge slurry',
    proceduralNarrativeTemplate:
      'Right CFA access. Celiac and superior mesenteric arteriography performed. Anatomy and portal vein patency confirmed. Selective right/left hepatic artery cannulation. 2.0F microcatheter advanced superselectively into tumor-feeding segmental branches. Dense tumor blush demonstrated with pathological neo-vascularity. 10 mL emulsion of Lipiodol and Doxorubicin (50mg) infused slowly under fluoroscopy until complete tumor saturation achieved. Embolization completed with gelfoam slurry until near-stasis in feeder. Completion run showed complete tumor devascularization and preserved non-target liver parenchyma.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine flat bedrest x 6 hours; right leg straight.',
      hematomaChecks: 'Monitor puncture site, vitals, pain score, and nausea q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Triphasic CT Abdomen at 4-6 weeks to assess Lipiodol retention and mRECIST response.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr x 12 hours.',
      medications: ["IV Ondansetron 8mg TDS", "IV Tramadol 50mg SOS", "IV Dexamethasone 8mg OD x 2 days", "Tab Pantoprazole 40mg OD"],
      redFlags: ["Acute post-embolization syndrome (severe pain, fever, nausea)", "Hepatic decompensation / jaundice", "Non-target embolization (gastric ulcer, cholecystitis)", "Groin hematoma"],
    },
    consentId: 'consent-tace',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat08-deb-tace',
    categoryNumber: 8,
    categoryName: 'Interventional Oncology Transcatheter Therapies',
    title: 'Drug-Eluting Bead TACE (DEB-TACE) with DC Beads / HepaSpheres',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Chemoembolization (TACE)',
      packageCode: '1849-MG077A',
      icd10: 'C22.0',
      tariffInr: 42000,
    },
    modality: 'XA',
    targetAnatomy: ["Hepatic Artery Segmental Branches"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA',
    sheathDefault: '5F Sheath',
    cathetersAndWires: '5F Cobra, 2.0F microcatheter, 0.014" wire',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: '100-300um DC Beads loaded with Doxorubicin (50-75mg)',
    proceduralNarrativeTemplate:
      'Celiac and common hepatic angiograms obtained. Superselective cannulation of tumor-feeding artery using 2.0F microcatheter. DC Beads (100-300um) loaded with 75mg doxorubicin injected slowly at 1 mL/min with non-ionic contrast under continuous fluoroscopy until endpoint of 5 beats to clear contrast column. Completion angiography showed total feeder occlusion with no non-target reflux.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours.',
      hematomaChecks: 'Groin check and post-embolization symptom monitoring q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Triphasic CT / MRI at 6 weeks.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["Antiemetics (Ondansetron 8mg TDS)", "Analgesics (Paracetamol + Tramadol)", "Proton-pump inhibitors"],
      redFlags: ["Post-embolization syndrome", "Hepatic abscess", "Groin bleeding"],
    },
    consentId: 'consent-tace',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat08-tare-y90',
    categoryNumber: 8,
    categoryName: 'Interventional Oncology Transcatheter Therapies',
    title: 'Transarterial Radioembolization (TARE / SIRT) with Y-90 Glass / Resin Microspheres',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Radioembolization (TARE / SIRT)',
      packageCode: '1849-MG078A',
      icd10: 'C22.0',
      tariffInr: 85000,
    },
    modality: 'XA',
    targetAnatomy: ["Right / Left Hepatic Artery", "Segmental Branches"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA at femoral head level',
    sheathDefault: '5F Sheath',
    cathetersAndWires: '5F Simmons, 2.0F microcatheter, 0.014" wire, non-target microcoils',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'Yttrium-90 Glass Microspheres (TheraSphere) or Resin Microspheres (SIR-Spheres)',
    proceduralNarrativeTemplate:
      'Indicated for unresectable HCC / intrahepatic cholangiocarcinoma with portal vein thrombosis. Prior Tc-99m MAA scan documented lung shunt fraction <10% and zero gastrointestinal shunting. Right CFA accessed. Selective catheterization with 2.0F microcatheter to target hepatic lobe/segment. Non-target branches (gastroduodenal, right gastric, falciform) prophylactically coiled if needed. Calculated dose of Y-90 microspheres delivered through microcatheter under strict radiation safety protocols. Post-delivery bremsstrahlung SPECT-CT / PET-CT performed confirming intense localized intratumoral radiation deposition.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Strict supine bedrest x 6 hours.',
      hematomaChecks: 'Radiation safety protocol; monitor groin and vitals q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Bremsstrahlung SPECT-CT within 24 hours; follow-up MRI Liver at 2-3 months.',
      hydrationProtocol: 'IV Normal Saline 75-100 mL/hr.',
      medications: ["Tab Prednisolone 20mg OD tapering over 2 weeks", "Tab Pantoprazole 40mg OD", "Tab Ondansetron 4mg TDS"],
      redFlags: ["Radiation-induced liver disease (RILD)", "Radiation pneumonitis", "Radiation-induced gastrointestinal ulceration"],
    },
    consentId: 'consent-tare-y90',
    calculatorId: 'cigarroa_macd',
  },
  {
    id: 'cat08-debiri-liver-mets',
    categoryNumber: 8,
    categoryName: 'Interventional Oncology Transcatheter Therapies',
    title: 'DEBIRI (DEB TACE with Irinotecan) for Colorectal Liver Metastases',
    maayRghsCompatibility: {
      schemeName: 'BOTH',
      packageName: 'Transcatheter Arterial Chemoembolization (TACE)',
      packageCode: '1849-MG077A',
      icd10: 'C78.7',
      tariffInr: 40000,
    },
    modality: 'XA',
    targetAnatomy: ["Hepatic Artery Branches"],
    sedation: 'Local Anesthesia with IV Conscious Sedation',
    accessSiteDefault: 'Right CFA',
    sheathDefault: '5F Sheath',
    cathetersAndWires: '5F Cobra, 2.0F microcatheter, 0.014" wire',
    microcatheterSystem: '2.0F microcatheter',
    embolicOrImplants: 'DC Beads (100-300um) loaded with 100mg Irinotecan',
    proceduralNarrativeTemplate:
      'Hepatic arteriography mapped multiple hypovascular and hypervascular colorectal metastases. Intra-arterial lidocaine (2% 5mL) infused prior to embolization to prevent acute irinotecan-mediated visceral pain. Irinotecan-loaded DC Beads (100-300um) delivered superselectively. Complete devascularization of target nodules confirmed.',
    postOpCare: {
      immobilizationHours: 6,
      immobilizationInstructions: 'Bedrest x 6 hours.',
      hematomaChecks: 'Groin check and pain monitoring q15m x 1h, q30m x 2h, then q1h.',
      requiredImaging: 'Contrast CT Abdomen at 6 weeks.',
      hydrationProtocol: 'IV Normal Saline 100 mL/hr.',
      medications: ["IV Ondansetron + Atropine (for cholinergic syndrome PRN)", "IV Tramadol 50mg"],
      redFlags: ["Severe visceral pain / cholinergic crisis", "Hepatic toxicity", "Fever"],
    },
    consentId: 'consent-tace',
    calculatorId: 'cigarroa_macd',
  },
];
