{{- if .Values.secrets.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vascule-database-secrets
  labels:
    {{- include "vascule-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-security
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    database-url: {{ .Values.secrets.sealedSecrets.encryptedDatabaseUrl | quote }}
    database-read-replica-url: {{ .Values.secrets.sealedSecrets.encryptedDatabaseReadReplicaUrl | quote }}
    abdm-private-key: {{ .Values.secrets.sealedSecrets.encryptedAbdmPrivateKey | quote }}
    abdm-public-key: {{ .Values.secrets.sealedSecrets.encryptedAbdmPublicKey | quote }}
    nextauth-secret: {{ .Values.secrets.sealedSecrets.encryptedNextauthSecret | quote }}
  template:
    metadata:
      name: vascule-database-secrets
      labels:
        {{- include "vascule-os.labels" . | nindent 8 }}
    type: Opaque
{{- else if .Values.secrets.standardSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vascule-database-secrets
  labels:
    {{- include "vascule-os.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-security
type: Opaque
stringData:
  database-url: {{ .Values.secrets.standardSecret.databaseUrl | quote }}
  database-read-replica-url: {{ .Values.secrets.standardSecret.databaseReadReplicaUrl | quote }}
  abdm-private-key: {{ .Values.secrets.standardSecret.abdmPrivateKey | quote }}
  abdm-public-key: {{ .Values.secrets.standardSecret.abdmPublicKey | quote }}
  nextauth-secret: {{ .Values.secrets.standardSecret.nextauthSecret | quote }}
{{- end }}
