import type {
  BedRecord,
  CtReviewRecord,
  EndoflowPatient,
  BookedCaseRecord,
  DopplerRecord,
} from "../dashboard/useEndoflowStore";

// ============================================================================
// DECOUPLED CLINICAL DEMO SEED DATA (SMS Medical College & Attached Hospitals)
// ============================================================================

export const DEMO_8_BEDS: BedRecord[] = [
  // 3 ICU Beds
  {
    id: "ICU-01",
    type: "ICU",
    title: "Liver ICU Bed 01",
    status: "occupied",
    ptName: "Lakshmi",
    crNo: "SMS-2026-LP01",
    diag: "Hypersplenism — Post Splenic Artery Embolization",
    doctor: "Dr. Meenu Bagarhatta",
    vitals: "120/80 mmHg, HR 76, SpO2 99%",
    hemostasisIntact: true,
    distalPulses: "Strong (+++)",
    ptId: "PT01",
  },
  {
    id: "ICU-02",
    type: "ICU",
    title: "Liver ICU Bed 02",
    status: "vacant",
    ptName: "-",
    crNo: "-",
    diag: "Ready for Emergency STAT Admission",
    doctor: "-",
    vitals: "-",
    hemostasisIntact: true,
    distalPulses: "-",
  },
  {
    id: "ICU-03",
    type: "ICU",
    title: "Liver ICU Bed 03",
    status: "vacant",
    ptName: "-",
    crNo: "-",
    diag: "Ready for Emergency STAT Admission",
    doctor: "-",
    vitals: "-",
    hemostasisIntact: true,
    distalPulses: "-",
  },

  // 5 Ward Beds
  {
    id: "Ward-01",
    type: "Ward",
    title: "Old Gastro IR Ward Bed 01",
    status: "occupied",
    ptName: "Roshan",
    crNo: "SMS-2026-RS01",
    diag: "Liver Abscess — Allowed to go Home (AJH)",
    doctor: "Dr. Naresh Mangalhara",
    vitals: "118/74 mmHg, HR 78, SpO2 98%",
    hemostasisIntact: true,
    distalPulses: "Strong (+++)",
  },
  {
    id: "Ward-02",
    type: "Ward",
    title: "IR Ward Bed 02",
    status: "vacant",
    ptName: "-",
    crNo: "-",
    diag: "Sterilized & Available for Elective Admission",
    doctor: "-",
    vitals: "-",
    hemostasisIntact: true,
    distalPulses: "-",
  },
  {
    id: "Ward-03",
    type: "Ward",
    title: "IR Ward Bed 03",
    status: "vacant",
    ptName: "-",
    crNo: "-",
    diag: "Sterilized & Available for Elective Admission",
    doctor: "-",
    vitals: "-",
    hemostasisIntact: true,
    distalPulses: "-",
  },
  {
    id: "Ward-04",
    type: "Ward",
    title: "IR Ward Bed 04",
    status: "vacant",
    ptName: "-",
    crNo: "-",
    diag: "Sterilized & Available for Elective Admission",
    doctor: "-",
    vitals: "-",
    hemostasisIntact: true,
    distalPulses: "-",
  },
  {
    id: "Ward-05",
    type: "Ward",
    title: "IR Ward Bed 05",
    status: "vacant",
    ptName: "-",
    crNo: "-",
    diag: "Sterilized & Available for Elective Admission",
    doctor: "-",
    vitals: "-",
    hemostasisIntact: true,
    distalPulses: "-",
  },
];

export const DEMO_CT_REVIEWS: CtReviewRecord[] = [
  {
    id: "CT-REV-001",
    patientName: "Bhanwar Lal Gurjar",
    age: 58,
    sex: "Male",
    date: "2026-09-13",
    primaryDiagnosis: "Cirrhosis with recurrent refractory UGI variceal bleeding",
    clinicalHistory: "58-year-old male with HCV-related cirrhosis, history of 2 prior bandings. Melena since 3 days, refractory to medical therapy.",
    presentingComplaints: "Recurrent hematemesis, melena, weakness, abdominal distension.",
    ctNumber: "SONI-PACS-99214",
    ctReviewNotes: "Review triple-phase CECT: Check main portal vein patency, assess splenic vein caliber and gastrorenal shunt for potential BRTO/TIPS.",
    smsBillId: "SMS-BILL-2026-8812",
    hospitalSource: "SONI Hospital",
    contactNumber: "9829144321",
    status: "Reviewed by Neel / Nilesh",
    reviewedBy: "Dr. Neel Yadav",
    reviewedAt: "13/09/2026 14:30",
    organSystem: "Liver & Hepatobiliary",
    diseaseKey: "brto_parto_gastric_varices",
    procedureTitle: "Balloon-Occluded Retrograde Transvenous Obliteration (BRTO)",
    postponeHistory: [],
  },
  {
    id: "CT-REV-002",
    patientName: "Shanti Devi Agarwal",
    age: 64,
    sex: "Female",
    date: "2026-09-13",
    primaryDiagnosis: "Right lung mass with active intermittent hemoptysis",
    clinicalHistory: "64-year-old female known case of bronchogenic CA, experiencing 150ml fresh hemoptysis episodes daily. Hemodynamically stable.",
    presentingComplaints: "Hemoptysis, chronic cough, right-sided pleuritic chest pain.",
    ctNumber: "SMS-CT-2026-4402",
    ctReviewNotes: "Review CT Thorax Angio: Identify hypertrophied right bronchial artery origin (T5/T6) and non-bronchial systemic collaterals.",
    smsBillId: "SMS-BILL-2026-9041",
    hospitalSource: "SMS Hospital",
    contactNumber: "9414233890",
    status: "To be reviewed by consultant",
    reviewedBy: "Dr. Nilesh DM",
    reviewedAt: "13/09/2026 16:00",
    organSystem: "Thoracic & Pulmonary",
    diseaseKey: "bronchial_artery_embo_bae",
    procedureTitle: "Bronchial Artery Embolization (BAE) - Massive Hemoptysis",
    postponeHistory: [],
  },
  {
    id: "CT-REV-003",
    patientName: "Mangi Lal Kumawat",
    age: 52,
    sex: "Male",
    date: "2026-09-13",
    primaryDiagnosis: "Malignant obstructive jaundice (Hilar Cholangiocarcinoma)",
    clinicalHistory: "52-year-old male presenting with progressive painless jaundice, pruritus, clay-colored stools. Total Bilirubin 18.4 mg/dL.",
    presentingComplaints: "Deep jaundice, dark urine, severe generalized itching, anorexia.",
    ctNumber: "SONI-PACS-98741",
    ctReviewNotes: "Review CECT Abdomen: Assess Bismuth-Corlette level (Type IIIa) and right vs left ductal dilatation for unilateral/bilateral PTBD.",
    smsBillId: "SMS-BILL-2026-7721",
    hospitalSource: "SONI Hospital",
    contactNumber: "9829567123",
    status: "Booking Cath-Lab on next available date",
    reviewedBy: "Dr. Neel Yadav",
    reviewedAt: "13/09/2026 17:15",
    organSystem: "Liver & Hepatobiliary",
    diseaseKey: "ptbd_biliary_stenting",
    procedureTitle: "Percutaneous Transhepatic Biliary Drainage (PTBD) & SEMS Stenting",
    postponeHistory: [],
  },
];

export const DEMO_ENDOFLOW_PATIENTS: EndoflowPatient[] = [
  {
    id: "PT01",
    name: "Ramswaroop Meena",
    age: 56,
    sex: "Male",
    hid: "SMS-2026-089",
    scanId: "PACS-IR-089",
    phone: "9829012345",
    unit: "Gastro Unit IV",
    postedBy: "Dr. Neel Yadav",
    time: "08:30 AM",
    summary:
      "Primary Budd-Chiari Syndrome with diffuse hepatic vein occlusion and refractory tense ascites. Rotterdam Class III. Planned for direct transcaval portosystemic decompression (DIPS).",
    procedureKey: "budd_chiari_dips",
    procedure: "Budd-Chiari Syndrome: Direct Intrahepatic Portosystemic Shunt (DIPS)",
    modality: "XA",
    status: "Post-Op ICU",
    scheme: "MAAY",
    schemeTid: "TID-9482103",
    beneficiaryId: "Jan Aadhaar 7821-9482-10",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "IPD",
      ward: "Liver ICU",
      bed: "LICU-04",
      podDay: "POD 0",
    },
    labs: {
      ast: 142,
      alt: 118,
      bili: 2.8,
      ldh: 420,
      alb: 2.9,
      creat: 0.92,
      inr: 1.45,
      plt: 125000,
      fib: 240,
      protc: 38,
      prots: 42,
      ascitesGrade: "tense",
    },
    preOp: {
      bedLocation: "Liver ICU LICU-04",
      npoHours: 8,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "16G Gray Right Forearm",
      calledToLab: true,
      labCleared: true,
    },
    postOp: {
      recoveryBed: "Liver ICU Bed LICU-04",
      punctureSiteSeal: "Hemostasis Intact",
      distalPulses: "Strong (+++)",
      instructions: "Target portosystemic gradient achieved: 6 mmHg. Maintain therapeutic heparin bridging. Doppler ultrasound at 24h.",
      sheathRemoved: true,
      dischargeReady: false,
    },
  },
  {
    id: "PT02",
    name: "Kamla Devi Sharma",
    age: 62,
    sex: "Female",
    hid: "SMS-2026-092",
    scanId: "PACS-IR-092",
    phone: "9414098765",
    unit: "Vascular Surgery Unit II",
    postedBy: "Dr. Ayushi Agarwal",
    time: "10:00 AM",
    summary:
      "Severe right lower limb claudication (Rutherford 3) with SFA critical stenosis. Planned for contralateral crossover femoral access, balloon angioplasty, and nitinol stenting.",
    procedureKey: "pad_sfa_angioplasty",
    procedure: "Peripheral Arterial Angioplasty & Nitinol Stenting (SFA / Popliteal)",
    modality: "XA",
    status: "Scheduled",
    scheme: "RGHS",
    schemeTid: "TID-8812903",
    beneficiaryId: "RGHS RJ-992140",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "IPD",
      ward: "IR Dedicated Ward (D-Block)",
      bed: "Bed 12",
      podDay: "Pre-Op",
    },
    labs: {
      ast: 24,
      alt: 28,
      bili: 0.8,
      ldh: 180,
      alb: 4.1,
      creat: 1.05,
      inr: 1.08,
      plt: 245000,
      fib: 310,
      protc: 88,
      prots: 92,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "IR Ward D-12",
      npoHours: 6,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "18G Green Left Forearm",
      calledToLab: false,
      labCleared: true,
    },
  },
  {
    id: "PT03",
    name: "Rajesh Kumawat",
    age: 44,
    sex: "Male",
    hid: "SMS-2026-104",
    scanId: "PACS-IR-104",
    phone: "9828112233",
    unit: "Chest Medicine Unit I",
    postedBy: "Dr. Neel Yadav",
    time: "11:15 AM",
    summary:
      "Massive hemoptysis (>400 mL in 24h) secondary to cavitary post-TB bronchiectasis in right upper lobe. Hypertrophied intercostobronchial trunk identified on CTA.",
    procedureKey: "bae_hemoptysis",
    procedure: "Bronchial Artery Embolization (BAE) for Massive Hemoptysis",
    modality: "XA",
    status: "In Cath-Lab",
    scheme: "MAAY",
    schemeTid: "TID-7719234",
    beneficiaryId: "Jan Aadhaar 5512-8821-33",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "Emergency",
      ward: "Cath-Lab Holding",
      bed: "PACU-01",
      podDay: "In Cath-Lab",
    },
    labs: {
      ast: 32,
      alt: 35,
      bili: 0.9,
      ldh: 210,
      alb: 3.7,
      creat: 0.88,
      inr: 1.12,
      plt: 195000,
      fib: 270,
      protc: 90,
      prots: 88,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "PACU-01",
      npoHours: 6,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "18G Green Right Forearm",
      calledToLab: true,
      labCleared: true,
    },
    inRoom: {
      activeSheathAccess: "5F Right Common Femoral Artery Sheath",
      elapsedFluoroSeconds: 878,
      contrastInjectedMl: 48,
      macdThresholdMl: 250,
      vitals: "110/72 mmHg, HR 102, SpO2 95%",
      targetArtery: "Right Intercostobronchial Trunk & RBA Branches",
      cathetersInUse: ["5F Mikaelsson Diagnostic", "2.4F Progreat Microcatheter", "355-500 um PVA"],
      currentStepDescription: "Superselective cannulation of tortuous bronchial branches. PVA particle embolization in progress.",
    },
  },
  {
    id: "PT04",
    name: "Shanti Bai",
    age: 49,
    sex: "Female",
    hid: "SMS-2026-115",
    scanId: "PACS-IR-115",
    phone: "9829554433",
    unit: "Medical Oncology Unit II",
    postedBy: "Dr. Rahul Verma",
    time: "01:00 PM",
    summary:
      "Solitary segment VI hepatic SOL (3.2 cm) detected on routine sonography. Targeted coaxial 18G core needle biopsy requested for histopathology and immunohistochemistry.",
    procedureKey: "core_biopsy",
    procedure: "USG-Guided Coaxial Core Needle Liver Biopsy",
    modality: "US",
    status: "Discharged",
    scheme: "GENERAL",
    schemeTid: "N/A",
    beneficiaryId: "CR-992140",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "Day-Care",
      ward: "Cath-Lab Recovery",
      bed: "Rec-03",
      podDay: "Discharge Ready",
    },
    labs: {
      ast: 44,
      alt: 48,
      bili: 1.1,
      ldh: 260,
      alb: 3.8,
      creat: 0.76,
      inr: 1.04,
      plt: 215000,
      fib: 290,
      protc: 95,
      prots: 92,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "Cath Recovery Rec-03",
      npoHours: 4,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "20G Pink",
      calledToLab: true,
      labCleared: true,
    },
    postOp: {
      recoveryBed: "Cath Recovery Rec-03",
      punctureSiteSeal: "Hemostasis Intact",
      distalPulses: "Strong (+++)",
      instructions: "Right lateral decubitus positioning maintained for 4 hours. Stable vitals. Discharged with oral analgesics.",
      sheathRemoved: true,
      dischargeReady: true,
    },
  },
  {
    id: "PT05",
    name: "Rameshwar Lal",
    age: 64,
    sex: "Male",
    hid: "SMS-2026-128",
    scanId: "PACS-CT-128",
    phone: "9829123488",
    unit: "Pulmonary Medicine Unit III",
    postedBy: "Dr. Neel Yadav",
    time: "02:00 PM",
    summary:
      "CT Thorax demonstrates 2.8 cm subsolid cavitary nodule in left upper lobe abutting visceral pleura. Coaxial 18G core needle biopsy under real-time CT fluoroscopy guidance.",
    procedureKey: "ct_biopsy",
    procedure: "CT-Guided Coaxial Core Needle Lung Biopsy",
    modality: "CT",
    status: "Pre-Op Pending",
    scheme: "MAAY",
    schemeTid: "TID-8812492",
    beneficiaryId: "Jan Aadhaar 4410-9982-12",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "IPD",
      ward: "IR Dedicated Ward (D-Block)",
      bed: "Bed 08",
      podDay: "Pre-Op",
    },
    labs: {
      ast: 28,
      alt: 30,
      bili: 0.7,
      ldh: 190,
      alb: 4.0,
      creat: 0.95,
      inr: 1.05,
      plt: 260000,
      fib: 320,
      protc: 92,
      prots: 90,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "IR Ward D-08",
      npoHours: 6,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "18G Green Right Hand",
      calledToLab: false,
      labCleared: true,
    },
  },
  {
    id: "PT06",
    name: "Sunita Sharma",
    age: 48,
    sex: "Female",
    hid: "SMS-2026-134",
    scanId: "PACS-CT-134",
    phone: "9414238811",
    unit: "Thoracic Surgery Unit I",
    postedBy: "Dr. Ayushi Agarwal",
    time: "02:45 PM",
    summary:
      "Contrast-enhanced CT chest shows 4.5 cm pre-vascular anterior mediastinal mass. Parasternal extrapleural CT-guided core biopsy to differentiate Thymoma vs Lymphoma.",
    procedureKey: "ct_biopsy",
    procedure: "CT-Guided Parasternal Mediastinal Mass Biopsy",
    modality: "CT",
    status: "Pre-Op Pending",
    scheme: "RGHS",
    schemeTid: "TID-7729104",
    beneficiaryId: "RGHS RJ-558291",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "Day-Care",
      ward: "Cath-Lab Recovery",
      bed: "Rec-04",
      podDay: "Pre-Op",
    },
    labs: {
      ast: 22,
      alt: 25,
      bili: 0.6,
      ldh: 175,
      alb: 4.2,
      creat: 0.82,
      inr: 1.02,
      plt: 230000,
      fib: 300,
      protc: 94,
      prots: 91,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "Cath Recovery Rec-04",
      npoHours: 5,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "20G Pink Left Arm",
      calledToLab: false,
      labCleared: true,
    },
  },
  {
    id: "PT07",
    name: "Maya Devi",
    age: 42,
    sex: "Female",
    hid: "SMS-2026-141",
    scanId: "PACS-US-141",
    phone: "9828445566",
    unit: "Endocrine Surgery Unit I",
    postedBy: "Dr. Neel Yadav",
    time: "03:30 PM",
    summary:
      "EU-TIRADS 5 right thyroid nodule (1.8 cm, punctate echogenic foci, taller-than-wide). USG-guided 23G FNAC performed with Rapid On-Site Evaluation (ROSE) confirming follicular neoplasm (Bethesda IV).",
    procedureKey: "fnac_clinic",
    procedure: "USG-Guided Thyroid FNAC with ROSE",
    modality: "ROSE",
    status: "Discharged",
    scheme: "MAAY",
    schemeTid: "TID-6629102",
    beneficiaryId: "Jan Aadhaar 9912-3344-55",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "Day-Care",
      ward: "Cath-Lab Recovery",
      bed: "Rec-01",
      podDay: "Discharge Ready",
    },
    labs: {
      ast: 20,
      alt: 22,
      bili: 0.5,
      ldh: 160,
      alb: 4.3,
      creat: 0.70,
      inr: 1.00,
      plt: 275000,
      fib: 280,
      protc: 98,
      prots: 96,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "Cath Recovery Rec-01",
      npoHours: 4,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "22G Blue",
      calledToLab: true,
      labCleared: true,
    },
    postOp: {
      recoveryBed: "Cath Recovery Rec-01",
      punctureSiteSeal: "Hemostasis Intact",
      distalPulses: "Strong (+++)",
      instructions: "No neck hematoma. Ice pack applied for 30 mins. Cytology slides dispatched to pathology.",
      sheathRemoved: true,
      dischargeReady: true,
    },
  },
  {
    id: "PT08",
    name: "Surendra Yadav",
    age: 51,
    sex: "Male",
    hid: "SMS-2026-147",
    scanId: "PACS-US-147",
    phone: "9414556677",
    unit: "ENT Unit II",
    postedBy: "Dr. Rahul Verma",
    time: "04:15 PM",
    summary:
      "Enlarged matted right level III cervical lymph nodes (2.4 cm) with central necrotic breakdown. 22G USG-guided FNAC with ROSE for GeneXpert MTB/RIF and cytology.",
    procedureKey: "fnac_clinic",
    procedure: "USG-Guided Cervical Lymph Node FNAC with ROSE",
    modality: "ROSE",
    status: "Scheduled",
    scheme: "GENERAL",
    schemeTid: "N/A",
    beneficiaryId: "CR-147029",
    preAuthStatus: "Approved",
    ipd: {
      admissionType: "Day-Care",
      ward: "Cath-Lab Recovery",
      bed: "Rec-02",
      podDay: "Pre-Op",
    },
    labs: {
      ast: 26,
      alt: 28,
      bili: 0.7,
      ldh: 185,
      alb: 4.1,
      creat: 0.85,
      inr: 1.03,
      plt: 250000,
      fib: 295,
      protc: 91,
      prots: 89,
      ascitesGrade: "none",
    },
    preOp: {
      bedLocation: "Cath Recovery Rec-02",
      npoHours: 4,
      inrChecked: true,
      creatinineChecked: true,
      consentSigned: true,
      ivCannulaGauge: "20G Pink",
      calledToLab: false,
      labCleared: true,
    },
  },
];

export const DEMO_BOOKED_CASES: BookedCaseRecord[] = [
  {
    id: "BC-2026-001",
    patientName: "Ramswaroop Meena",
    age: 56,
    sex: "Male",
    contactNumber: "9829012345",
    ssoNumber: "SMS-2026-089",
    location: "Jaipur, Rajasthan",
    scheduledDate: "2026-09-23",
    organSystem: "Liver & Hepatobiliary",
    diseaseKey: "budd_chiari_dips",
    procedureTitle: "Budd-Chiari Syndrome: Transcaval DIPS / Recanalization",
    bookedBy: "Dr. Neel Yadav (DM01)",
    bookedAt: "2026-09-22T08:00:00.000Z",
    orderedLabs: [
      "Liver Function Tests (Total & Direct Bilirubin, AST, ALT, Albumin)",
      "Renal Function Tests (Serum Creatinine, BUN, Electrolytes)",
      "Coagulation Profile (PT, INR, aPTT, Platelet Count, Fibrinogen)",
      "Complete Blood Count (Hb, TLC, Platelets)",
      "Blood Grouping & Crossmatching (4 Units PRBC, 4 Units FFP reserved)",
    ],
    specialInvestigations: [
      "JAK2 V617F Mutation Assay (Screening for Polycythemia Vera)",
      "Protein C Activity & Protein S Free Antigen",
      "Antithrombin III Functional Assay",
      "Factor V Leiden (G1691A) Mutation",
      "Serum Homocysteine",
    ],
    preScanAnatomy: {
      rhv: "Thrombotic Occlusion",
      mhv: "Patent (Target for Venoplasty)",
      lhv: "Thrombotic Occlusion",
      ivc_status: "Short Segment Suprahepatic Web",
      caudate: "Marked Hypertrophy (>3.5 cm)",
      right_ijv: "Patent & Fully Compressible (>10 mm)",
    },
    hardwareChecklist: [
      { id: "h1", item: "Transjugular Sheath", spec: "10F 45cm Ansel / Flexor Hydrophilic Guiding Sheath", checked: true },
      { id: "h2", item: "Colapinto Puncture Needle", spec: "RUPS-100 Colapinto Transcaval Access Set (10F)", checked: true },
      { id: "h3", item: "Extra-Stiff Guidewires", spec: "0.035\" 260cm Amplatz Extra-Stiff + 0.035\" Terumo Glidewire", checked: true },
      { id: "h4", item: "High-Pressure Angioplasty Balloons", spec: "Conquest / Atlas 8x40 mm & 10x40 mm Non-Compliant", checked: true },
      { id: "h5", item: "Viatorr TIPS Stent-Graft", spec: "Gore Viatorr Covered Stent: 10 mm diameter (7 cm covered + 2 cm bare)", checked: true },
      { id: "h6", item: "Intra-op Pressure Manometer", spec: "Electronic Transducer for Portal & Right Atrial Gradient", checked: true },
    ],
    rotterdamScore: {
      score: 1.42,
      classLevel: "Class III (High Risk)",
      oneYearSurvival: "63% without decompressive intervention",
    },
    postOpPlan: "Therapeutic LMWH (Enoxaparin 1 mg/kg s/c q12h) 4h post-sheath removal. Oral Apixaban 5mg BD from POD 2. 24h Doppler for shunt patency.",
    status: "Scheduled",
    npoVerified: true,
    labsVerified: true,
    bloodProductsVerified: true,
    hardwareVerified: true,
    screenedBy: "Dr. Neel Yadav",
    screenedAt: "2026-09-22T08:30:00.000Z",
    keptForTomorrow: true,
    admissionCardUpdated: true,
    codeAdditionStatus: "Added",
    rescheduleHistory: [],
  },
  {
    id: "BC-2026-002",
    patientName: "Kamla Devi Sharma",
    age: 62,
    sex: "Female",
    contactNumber: "9829023456",
    ssoNumber: "SMS-2026-092",
    location: "Jaipur, Rajasthan",
    scheduledDate: "2026-09-24",
    organSystem: "Peripheral Vascular",
    diseaseKey: "sfa_stenting",
    procedureTitle: "Superficial Femoral Artery (SFA) Recanalization & Stenting",
    bookedBy: "Dr. Nilesh Bansal (DM02)",
    bookedAt: "2026-09-22T09:00:00.000Z",
    orderedLabs: [
      "Coagulation Profile (PT, INR, aPTT, Platelets)",
      "Renal Function Tests & eGFR (Serum Creatinine)",
      "Lipid Profile & HbA1c",
    ],
    specialInvestigations: ["Lower Extremity Arterial Duplex Mapping"],
    preScanAnatomy: {
      lesion_length: "Long Segment (>15 cm TASC-D)",
      calcification: "Moderate Circumferential Calcification",
      run_off: "2-Vessel Runoff (Anterior Tibial + Peroneal Patent)",
    },
    hardwareChecklist: [
      { id: "h1", item: "Femoral Introducer Sheath", spec: "6F 45cm Destination / Parent Guiding Sheath", checked: true },
      { id: "h2", item: "Crossing Guidewire", spec: "0.035\" 300cm Terumo Glidewire Advantage / Command 0.014\"", checked: true },
      { id: "h3", item: "Drug-Eluting Stent (DES)", spec: "Eluvia / Zilver PTX 6 mm x 120 mm Paclitaxel-Eluting", checked: true },
    ],
    postOpPlan: "Dual Antiplatelet Therapy (DAPT): Aspirin 75 mg + Clopidogrel 75 mg OD x 6 months. Distal DP/PT pulse palpation q2h.",
    status: "Scheduled",
    npoVerified: false,
    labsVerified: false,
    bloodProductsVerified: false,
    hardwareVerified: false,
    screenedBy: null,
    screenedAt: null,
    keptForTomorrow: false,
    admissionCardUpdated: false,
    codeAdditionStatus: "Pending",
    rescheduleHistory: [],
  },
];

export const DEMO_DOPPLER_RECORDS: DopplerRecord[] = [
  {
    id: "DOP01",
    ptId: "PT01",
    name: "Ramswaroop Meena",
    age: 56,
    sex: "M",
    crNo: "SMS-2026-089",
    proc: "Direct Intrahepatic Portosystemic Shunt (DIPS)",
    implant: "Viatorr 10mm x 7cm covered",
    interval: "1m",
    intervalLabel: "1-Month Post-Op",
    dueDate: "2026-10-01",
    targetVessel: "Viatorr Shunt & Main PV",
    targetVelocity: "PSV: 90-190 cm/s | PV >30 cm/s",
    status: "Scheduled",
    lastPsv: 135.0,
    lastMpv: 36.5,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Pre-discharge Doppler shows widely patent shunt. Scheduled for 1-Month surveillance.",
  },
  {
    id: "DOP02",
    ptId: "PT02",
    name: "Govind Ram",
    age: 52,
    sex: "M",
    crNo: "SMS-2026-077",
    proc: "TIPS for Refractory Variceal Bleed",
    implant: "Viatorr 8mm x 8cm",
    interval: "1m",
    intervalLabel: "1-Month Post-Op",
    dueDate: "2026-09-24",
    targetVessel: "TIPS Shunt Tract",
    targetVelocity: "PSV: 90-190 cm/s",
    status: "Due This Week",
    lastPsv: 142.0,
    lastMpv: 34.0,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Due for 1-month post-op Doppler check this week.",
  },
  {
    id: "DOP03",
    ptId: "PT03",
    name: "Kailash Chand",
    age: 48,
    sex: "M",
    crNo: "SMS-2026-081",
    proc: "Budd-Chiari: Hepatic Vein Balloon Cavoplasty",
    implant: "Atlas 12mm High-Pressure Balloon",
    interval: "3m",
    intervalLabel: "3-Month Post-Op",
    dueDate: "2026-09-25",
    targetVessel: "Right Hepatic Vein & IVC",
    targetVelocity: "Continuous hepatofugal flow",
    status: "Due This Week",
    lastPsv: 88.0,
    lastMpv: 28.0,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Due for 3-month surveillance to rule out elastic recoil or restenosis.",
  },
  {
    id: "DOP04",
    ptId: "PT04",
    name: "Kamla Devi Sharma",
    age: 62,
    sex: "F",
    crNo: "SMS-2026-092",
    proc: "SFA Angioplasty & Nitinol Stenting",
    implant: "EverFlex 6mm x 100mm Nitinol Stent",
    interval: "1m",
    intervalLabel: "1-Month Post-Op",
    dueDate: "2026-10-02",
    targetVessel: "Superficial Femoral Artery",
    targetVelocity: "PSV <150 cm/s | PSVR <2.0",
    status: "Scheduled",
    lastPsv: 110.0,
    lastMpv: 0,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Bilateral pedal pulses bounding. Next check in 1 month.",
  },
  {
    id: "DOP05",
    ptId: "PT05",
    name: "Manish Saini",
    age: 34,
    sex: "M",
    crNo: "SMS-2026-SUR-402",
    proc: "May-Thurner Left Iliac Venous Stenting",
    implant: "Wallstent 14mm x 90mm",
    interval: "1m",
    intervalLabel: "1-Month Post-Op",
    dueDate: "2026-09-26",
    targetVessel: "Left Common Iliac Vein",
    targetVelocity: "Phasic venous flow with respiration",
    status: "Due This Week",
    lastPsv: 70.0,
    lastMpv: 0,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Due this week for 1-month venous duplex check to evaluate in-stent flow.",
  },
  {
    id: "DOP06",
    ptId: "PT06",
    name: "Santosh Meena",
    age: 58,
    sex: "F",
    crNo: "SMS-2026-107",
    proc: "Dialysis Brachiocephalic AVF Fistuloplasty",
    implant: "Conquest 6mm x 40mm Balloon",
    interval: "3m",
    intervalLabel: "3-Month Post-Op",
    dueDate: "2026-09-27",
    targetVessel: "Brachial Artery & Cephalic Vein",
    targetVelocity: "Volume Flow >600 mL/min",
    status: "Due This Week",
    lastPsv: 220.0,
    lastMpv: 0,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Due this week for 3-month volume flow and thrill assessment.",
  },
  {
    id: "DOP07",
    ptId: "PT07",
    name: "Anita Jain",
    age: 55,
    sex: "F",
    crNo: "SMS-2026-099",
    proc: "PTBD & Biliary SEMS Stenting",
    implant: "Niti-S 10mm x 80mm Biliary Stent",
    interval: "completed",
    intervalLabel: "1-Month Post-Op",
    dueDate: "2026-08-28",
    targetVessel: "Common Bile Duct",
    targetVelocity: "IHBR Decompressed | Caliber 6mm",
    status: "Completed",
    lastPsv: 0,
    lastMpv: 0,
    patency: "Widely Patent (Normal Velocity)",
    notes: "Ultrasound verified complete biliary decompression and normal bilirubin (0.9 mg/dL).",
  },
];
