import { ALL_MASTER_PROCEDURES, MASTER_CATEGORIES_METADATA, MasterProcedure } from "../../lib/masterCatalog";

/**
 * 16 Core Daily Routine Interventional Radiology Procedures at SMS Hospital, Jaipur.
 * These represent ~90% of routine daily clinical volume in the SMS Angiosuites & Ultrasound rooms.
 */
export interface DailyRoutineProcedureItem {
  id: string;
  shortTitle: string;
  fullTitle: string;
  specialty: string;
  modality: "XA" | "US" | "CT";
  packageCode: string;
  icd10: string;
  badge: "Daily Routine" | "Emergency / Daily" | "Specialized Daily" | "Acute Care" | "Emergency / Routine";
  indicationDefault: string;
  preOpDiagnosis: string;
  postOpDiagnosis: string;
  accessSiteDefault: string;
  sheathDefault: string;
  fluoroTimeMinutes: number;
  dapGyCm2: number;
  contrastMedia: string;
  contrastVolumeMl: number;
}

export const DAILY_ROUTINE_IR_PROCEDURES: DailyRoutineProcedureItem[] = [
  {
    id: "cat10-venaseal-gsv",
    shortTitle: "Varicose Veins (VenaSeal / EVLT)",
    fullTitle: "Endovenous Ablation (EVLA / VenaSeal) + Ultrasound-Guided Foam Sclerotherapy (UGFS)",
    specialty: "Venous",
    modality: "US",
    packageCode: "P-IR-VEN-01",
    icd10: "I83.9",
    badge: "Daily Routine",
    indicationDefault: "Symptomatic lower limb varicose veins with CEAP C2-C6 venous insufficiency and severe reflux (>0.5s) at saphenofemoral junction",
    preOpDiagnosis: "Primary Great Saphenous Vein (GSV) Truncal Incompetence with Stasis Dermatitis (CEAP C4a)",
    postOpDiagnosis: "Status Post 100% Endovenous Cyanoacrylate Closure / EVLA of GSV with Completion Duplex Verified Occlusion",
    accessSiteDefault: "Distal GSV (Below Knee Paratibial Puncture under Real-Time Ultrasound)",
    sheathDefault: "5F Terumo Glidesheath / VenaSeal 5F Catheter",
    fluoroTimeMinutes: 0.0,
    dapGyCm2: 0.0,
    contrastMedia: "None (Ultrasound Guided)",
    contrastVolumeMl: 0,
  },
  {
    id: "cat07-bae-hemoptysis",
    shortTitle: "BAE (Massive Hemoptysis)",
    fullTitle: "Bronchial Artery Embolization (BAE) for Massive / Recurrent Hemoptysis",
    specialty: "Embolotherapy",
    modality: "XA",
    packageCode: "P-IR-EMB-01",
    icd10: "R04.2",
    badge: "Emergency / Daily",
    indicationDefault: "Massive / recurrent hemoptysis (>300 mL/24h) secondary to post-tubercular bronchiectasis with hypertrophied bronchial collaterals",
    preOpDiagnosis: "Severe Recurrent Hemoptysis secondary to Post-Tubercular Cavitary Bronchiectasis",
    postOpDiagnosis: "Successful Superselective Bronchial & Non-Bronchial Systemic Artery Embolization (PVA Particles 350-500um + Coils)",
    accessSiteDefault: "Right Common Femoral Artery (CFA) Retrograde Puncture",
    sheathDefault: "5F / 6F Terumo Glidesheath",
    fluoroTimeMinutes: 14.5,
    dapGyCm2: 24.8,
    contrastMedia: "Omnipaque 350",
    contrastVolumeMl: 45,
  },
  {
    id: "cat03-tips-viatorr",
    shortTitle: "TIPS / DIPS (Budd-Chiari)",
    fullTitle: "Transjugular Intrahepatic Portosystemic Shunt (TIPS) with Viatorr Stent-Graft",
    specialty: "HPB & Portal",
    modality: "XA",
    packageCode: "P-IR-HPB-01",
    icd10: "K76.6",
    badge: "Specialized Daily",
    indicationDefault: "Refractory cirrhotic ascites / Budd-Chiari syndrome with severe portal hypertension failing medical management and secondary prophylaxis",
    preOpDiagnosis: "Decompensated Cirrhosis / Budd-Chiari Syndrome with Refractory Variceal Bleeding & Tension Ascites",
    postOpDiagnosis: "Successful TIPS Creation (Viatorr 10mm x 8cm Stent-Graft) with Post-Shunt Portosystemic Gradient (PSG) < 12 mmHg",
    accessSiteDefault: "Right Internal Jugular Vein (RIJV) Puncture under Real-Time Ultrasound Guidance",
    sheathDefault: "10F Cook Rosch-Uchida / Haskal Transjugular Access Set",
    fluoroTimeMinutes: 28.4,
    dapGyCm2: 68.2,
    contrastMedia: "Visipaque 320",
    contrastVolumeMl: 85,
  },
  {
    id: "cat03-ptbd-right",
    shortTitle: "PTBD & Biliary Stenting",
    fullTitle: "Percutaneous Transhepatic Biliary Drainage (PTBD) & Self-Expanding Metal Stenting (SEMS)",
    specialty: "HPB & Portal",
    modality: "XA",
    packageCode: "P-IR-HPB-02",
    icd10: "K83.1",
    badge: "Daily Routine",
    indicationDefault: "Progressive obstructive jaundice with intractable pruritus and cholangitis secondary to inoperable periampullary / Klatskin tumor",
    preOpDiagnosis: "Malignant Obstructive Jaundice (Bismuth-Corlette Type III/IV Ductal Obstruction)",
    postOpDiagnosis: "Successful Right PTBD with 8.5F/10F Ring Catheter & Uncovered Nitinol Biliary Stent Deployment",
    accessSiteDefault: "Right 10th Intercostal Space (Mid-Axillary Line under US & Fluoroscopy)",
    sheathDefault: "6F Transitional Dilator / Ring Access Set",
    fluoroTimeMinutes: 12.8,
    dapGyCm2: 19.4,
    contrastMedia: "Omnipaque 300",
    contrastVolumeMl: 35,
  },
  {
    id: "cat02-liver-amebic-drainage",
    shortTitle: "PCD (Abscess Drainage)",
    fullTitle: "Percutaneous Catheter Drainage (PCD / Pigtail) for Liver Abscess / Abdominal Collection",
    specialty: "Drainages",
    modality: "US",
    packageCode: "P-IR-DRN-01",
    icd10: "K75.0",
    badge: "Daily Routine",
    indicationDefault: "Large liquefied liver abscess / deep abdominal collection (>5 cm) with high-grade spiking fevers and peritoneal irritation",
    preOpDiagnosis: "Amebic / Pyogenic Liver Abscess (Right Hepatic Lobe > 7 cm)",
    postOpDiagnosis: "Successful Ultrasound-Guided Placement of 10F/12F Locking Pigtail Catheter with Anchoring Suture & Dependent Bag Drainage",
    accessSiteDefault: "Right Intercostal / Subcostal Approach under Real-Time High-Resolution Ultrasound",
    sheathDefault: "10F / 12F Locking Pigtail Trocar Drainage System",
    fluoroTimeMinutes: 0.0,
    dapGyCm2: 0.0,
    contrastMedia: "None (US Guided) / 5mL diluted contrast for check",
    contrastVolumeMl: 0,
  },
  {
    id: "cat19-pcn-drainage",
    shortTitle: "PCN (Nephrostomy)",
    fullTitle: "Percutaneous Nephrostomy (PCN) & Antegrade Double-J (DJ) Ureteric Stenting",
    specialty: "Urology",
    modality: "XA",
    packageCode: "P-IR-URO-01",
    icd10: "N13.2",
    badge: "Daily Routine",
    indicationDefault: "Acute obstructive uropathy with hydronephrosis and urosepsis secondary to calculus obstruction or pelvic malignancy",
    preOpDiagnosis: "Severe Obstructive Uropathy with Gross Hydronephrosis and Impending Renal Failure",
    postOpDiagnosis: "Successful Right/Left PCN Insertion with 8.5F Locking Pigtail Nephrostomy Catheter and Free Clear Urine Output",
    accessSiteDefault: "Posterior Lower Calyx (Brodel's Avascular Plane) via Flank Approach",
    sheathDefault: "8F / 8.5F Neff Percutaneous Access Set",
    fluoroTimeMinutes: 6.5,
    dapGyCm2: 8.2,
    contrastMedia: "Omnipaque 300",
    contrastVolumeMl: 20,
  },
  {
    id: "cat08-ctace-lipiodol",
    shortTitle: "TACE (Hepatoma / HCC)",
    fullTitle: "Conventional Transarterial Chemoembolization (cTACE) for Hepatocellular Carcinoma",
    specialty: "Oncology",
    modality: "XA",
    packageCode: "P-IR-ONC-01",
    icd10: "C22.0",
    badge: "Daily Routine",
    indicationDefault: "Intermediate stage Hepatocellular Carcinoma (BCLC Stage B) with preserved liver function (Child-Pugh A/B) and no portal vein invasion",
    preOpDiagnosis: "Multifocal Hepatocellular Carcinoma (Segments VII/VIII) on Background Cirrhosis",
    postOpDiagnosis: "Successful Superselective cTACE (Lipiodol + Doxorubicin 50mg + Gelfoam Slurry) with Complete Tumor Devascularization",
    accessSiteDefault: "Right Common Femoral Artery (CFA) Retrograde Puncture",
    sheathDefault: "5F Terumo Glidesheath + 2.7F Progreat Microcatheter",
    fluoroTimeMinutes: 18.2,
    dapGyCm2: 38.6,
    contrastMedia: "Omnipaque 350",
    contrastVolumeMl: 65,
  },
  {
    id: "cat11-avf-fistulogram-angioplasty",
    shortTitle: "AV Fistuloplasty (Dialysis)",
    fullTitle: "Dialysis Arteriovenous (AV) Fistuloplasty & Central Venoplasty for Flow Salvage",
    specialty: "Dialysis Access",
    modality: "XA",
    packageCode: "P-IR-DIA-01",
    icd10: "T82.858",
    badge: "Daily Routine",
    indicationDefault: "Hemodialysis access dysfunction with high venous pressures (>200 mmHg) and drop in dialysis flow rates (<300 mL/min)",
    preOpDiagnosis: "Failing Radiocephalic / Brachiocephalic AV Fistula with Critical Swing-Point Anastomotic Stenosis",
    postOpDiagnosis: "Successful High-Pressure Balloon Angioplasty (Conquest 6mm x 40mm) with Complete Residual Stenosis < 10% and Palpable Thrill",
    accessSiteDefault: "Retrograde / Antegrade Cannulation of Cephalic / Basilic Outflow Vein",
    sheathDefault: "6F Radial / Hydrophilic Glidesheath",
    fluoroTimeMinutes: 9.4,
    dapGyCm2: 11.8,
    contrastMedia: "Visipaque 320",
    contrastVolumeMl: 30,
  },
  {
    id: "cat10-varicose-embolization-microcoils",
    shortTitle: "Varicocele Embolization",
    fullTitle: "Varicocele Transvenous Embolization (Pushable / Detachable Coils + Foam Sclerosant)",
    specialty: "Venous",
    modality: "XA",
    packageCode: "P-IR-VEN-02",
    icd10: "I86.1",
    badge: "Daily Routine",
    indicationDefault: "Symptomatic Grade III left-sided varicocele with chronic scrotal aching pain and subfertility (oligoasthenoteratozoospermia)",
    preOpDiagnosis: "Grade III Left Internal Spermatic Vein Incompetence with Scrotal Heaviness",
    postOpDiagnosis: "Successful Left Gonadal Vein Embolization (0.035\" Fibered Microcoils + 3% Polidocanol Foam) with Complete Retrograde Stasis",
    accessSiteDefault: "Right Internal Jugular Vein (RIJV) or Right Common Femoral Vein (CFV)",
    sheathDefault: "5F Cordis Cobra C2 Catheter / 5F Sheath",
    fluoroTimeMinutes: 11.2,
    dapGyCm2: 16.4,
    contrastMedia: "Omnipaque 300",
    contrastVolumeMl: 35,
  },
  {
    id: "cat07-splenic-trauma-embolization",
    shortTitle: "Splenic Artery Embo (SAE)",
    fullTitle: "Splenic Artery Embolization (SAE) for Blunt Abdominal Trauma / Hypersplenism",
    specialty: "Embolotherapy",
    modality: "XA",
    packageCode: "P-IR-EMB-02",
    icd10: "S36.03",
    badge: "Emergency / Daily",
    indicationDefault: "Grade III/IV splenic injury following blunt abdominal trauma with active contrast extravasation / pseudoaneurysm on CECT",
    preOpDiagnosis: "Traumatic Splenic Laceration with Intrasplenic Pseudoaneurysm & Hemoperitoneum",
    postOpDiagnosis: "Successful Proximal Splenic Artery Embolization with 0.035\" Gianturco Coils Preserving Distal Collateral Perfusion",
    accessSiteDefault: "Right Common Femoral Artery (CFA) Retrograde Puncture",
    sheathDefault: "5F Terumo Glidesheath + 4F/5F Cobra / Simmons Catheter",
    fluoroTimeMinutes: 15.6,
    dapGyCm2: 29.4,
    contrastMedia: "Omnipaque 350",
    contrastVolumeMl: 55,
  },
  {
    id: "cat18-uae-pph-emergency",
    shortTitle: "UAE (PPH / Fibroids)",
    fullTitle: "Uterine Artery Embolization (UAE) for Postpartum Hemorrhage (PPH) / Fibroids",
    specialty: "Women's Health",
    modality: "XA",
    packageCode: "P-IR-GYN-01",
    icd10: "O72.1",
    badge: "Emergency / Daily",
    indicationDefault: "Refractory postpartum hemorrhage unresponsive to uterotonics / symptomatic uterine fibroids causing menorrhagia",
    preOpDiagnosis: "Severe Secondary Postpartum Hemorrhage with Uterine Atony / Bleeding Cervical Pseudoaneurysm",
    postOpDiagnosis: "Successful Bilateral Uterine Artery Embolization with Gelfoam Slurry & PVA Particles (500-700um) with Immediate Hemostasis",
    accessSiteDefault: "Right Common Femoral Artery (CFA) Retrograde Puncture",
    sheathDefault: "5F Terumo Glidesheath + 2.7F Progreat Microcatheter",
    fluoroTimeMinutes: 13.8,
    dapGyCm2: 26.5,
    contrastMedia: "Visipaque 320",
    contrastVolumeMl: 50,
  },
  {
    id: "cat01-liver-core-target",
    shortTitle: "Image-Guided Biopsy",
    fullTitle: "Ultrasound / CT-Guided Percutaneous Automated Core Biopsy (Liver / Lung / Renal)",
    specialty: "Biopsies",
    modality: "US",
    packageCode: "P-IR-BIO-01",
    icd10: "Z01.89",
    badge: "Daily Routine",
    indicationDefault: "Focal liver lesion / solitary pulmonary nodule / renal cortical mass requiring histopathological diagnosis and biomarker profiling",
    preOpDiagnosis: "Space Occupying Lesion (SOL) of Liver / Lung under Diagnostic Investigation",
    postOpDiagnosis: "Successful Ultrasound / CT-Guided Core Biopsy (18G Coaxial System, 3 Cores Harvested) with Zero Complications",
    accessSiteDefault: "Direct Percutaneous Lesion Access under Real-Time Imaging",
    sheathDefault: "17G Coaxial Introducer + 18G Automated Tru-Cut Biopsy Gun",
    fluoroTimeMinutes: 0.0,
    dapGyCm2: 0.0,
    contrastMedia: "None (US Guided)",
    contrastVolumeMl: 0,
  },
  {
    id: "cat11-permacath-insertion",
    shortTitle: "Permacath (Dialysis Line)",
    fullTitle: "Tunneled Cuffed Hemodialysis Catheter (Permacath) / Chemoport Insertion",
    specialty: "Dialysis Access",
    modality: "XA",
    packageCode: "P-IR-DIA-02",
    icd10: "Z99.2",
    badge: "Daily Routine",
    indicationDefault: "End-Stage Renal Disease (ESRD) on maintenance hemodialysis requiring durable, infection-resistant central venous access",
    preOpDiagnosis: "End-Stage Renal Disease (ESRD) with Exhausted Peripheral Access",
    postOpDiagnosis: "Successful Ultrasound-Guided Right IJV Cannulation & Fluoroscopic Insertion of 14.5F x 28cm Tunneled Cuffed Dual-Lumen Permacath",
    accessSiteDefault: "Right Internal Jugular Vein (RIJV) Puncture with Anterior Chest Wall Subcutaneous Tunnel",
    sheathDefault: "14.5F Peel-Away Introducer Sheath",
    fluoroTimeMinutes: 3.5,
    dapGyCm2: 4.8,
    contrastMedia: "Omnipaque 300",
    contrastVolumeMl: 10,
  },
  {
    id: "cat04-diagnostic-runoff",
    shortTitle: "Diagnostic Angio (DSA)",
    fullTitle: "Diagnostic Digital Subtraction Angiography (Peripheral / Visceral / Neurovascular DSA)",
    specialty: "Arterial",
    modality: "XA",
    packageCode: "P-IR-ART-01",
    icd10: "I73.9",
    badge: "Daily Routine",
    indicationDefault: "Disabling intermittent claudication / rest pain / suspected visceral ischemia requiring definitive roadmapping before intervention",
    preOpDiagnosis: "Peripheral Arterial Disease (PAD) / Visceral Vascular Disease for Angiographic Evaluation",
    postOpDiagnosis: "Diagnostic DSA Completed: Detailed Vascular Anatomy, Collateral Flow, and Target Stenosis Mapped",
    accessSiteDefault: "Right / Left Common Femoral Artery (Retrograde / Antegrade)",
    sheathDefault: "4F / 5F Terumo Glidesheath",
    fluoroTimeMinutes: 7.2,
    dapGyCm2: 12.4,
    contrastMedia: "Omnipaque 300",
    contrastVolumeMl: 40,
  },
  {
    id: "cat04-sfa-dcb",
    shortTitle: "Peripheral Angioplasty (PAD)",
    fullTitle: "Lower Extremity Arterial Angioplasty & Stenting (DCB / Supera Stent)",
    specialty: "Arterial",
    modality: "XA",
    packageCode: "P-IR-ART-02",
    icd10: "I70.213",
    badge: "Daily Routine",
    indicationDefault: "Chronic Limb-Threatening Ischemia (CLTI) with rest pain or non-healing ischemic ulceration (Rutherford Category 4/5)",
    preOpDiagnosis: "Superficial Femoral Artery (SFA) Severe Occlusive Disease (TASC II B/C)",
    postOpDiagnosis: "Successful Subintimal Recanalization and Drug-Coated Balloon (DCB) Angioplasty with Restored Straight-Line In-Line Runoff to Foot",
    accessSiteDefault: "Contralateral Common Femoral Artery (Cross-Over Approach) or Ipsilateral Antegrade CFA",
    sheathDefault: "6F Destination 45cm Balkin Sheath",
    fluoroTimeMinutes: 21.0,
    dapGyCm2: 42.1,
    contrastMedia: "Omnipaque 350",
    contrastVolumeMl: 70,
  },
  {
    id: "cat10-dvt-cdt",
    shortTitle: "DVT Thrombolysis (CDT)",
    fullTitle: "Catheter-Directed Thrombolysis (CDT) & Pharmacomechanical Thrombectomy for Iliofemoral DVT",
    specialty: "Venous",
    modality: "XA",
    packageCode: "P-IR-VEN-03",
    icd10: "I80.2",
    badge: "Acute Care",
    indicationDefault: "Extensive acute (<14 days) iliofemoral deep vein thrombosis with severe phlegmasia cerulea dolens and limb-threatening venous gangrene",
    preOpDiagnosis: "Acute Left Iliofemoral Deep Vein Thrombosis with May-Thurner Left Common Iliac Vein Compression",
    postOpDiagnosis: "Successful CDT Infusion Catheter Placement (Cragg-McNamara) + AngioJet Thrombectomy with Complete Venous Flow Restoration",
    accessSiteDefault: "Left Popliteal Vein / Posterior Tibial Vein Puncture under Real-Time Ultrasound",
    sheathDefault: "6F Terumo Glidesheath + 5F Multi-Sidehole Infusion Catheter",
    fluoroTimeMinutes: 16.5,
    dapGyCm2: 28.0,
    contrastMedia: "Omnipaque 300",
    contrastVolumeMl: 50,
  },
];

/**
 * 12 Clean Clinical Specialty Groups partitioning the remaining 1,100+ master catalog procedures.
 */
export interface SpecialtyGroup {
  id: string;
  name: string;
  categoryNumbers: number[];
  iconName: string;
  count: number;
}

export const SPECIALTY_CATALOG_GROUPS: SpecialtyGroup[] = [
  {
    id: "hpb",
    name: "Hepatobiliary, Portal & Shunts (TIPS, PTBD, BRTO)",
    categoryNumbers: [3],
    iconName: "Activity",
    count: 0, // Populated dynamically
  },
  {
    id: "embolotherapy",
    name: "Embolotherapy & Emergency Hemostasis (BAE, Trauma, GI)",
    categoryNumbers: [7],
    iconName: "ShieldAlert",
    count: 0,
  },
  {
    id: "venous",
    name: "Venous Interventions & Varicose (VenaSeal, DVT, Filters)",
    categoryNumbers: [10],
    iconName: "GitCommit",
    count: 0,
  },
  {
    id: "oncology",
    name: "Interventional Oncology (TACE, TARE, Thermal Ablation)",
    categoryNumbers: [8, 9],
    iconName: "Target",
    count: 0,
  },
  {
    id: "biopsies_drainages",
    name: "Percutaneous Biopsies & Fluid Drainages (Core, PCD)",
    categoryNumbers: [1, 2],
    iconName: "Needle",
    count: 0,
  },
  {
    id: "dialysis",
    name: "Dialysis Access Salvage & Central Venous Lines",
    categoryNumbers: [11],
    iconName: "Activity",
    count: 0,
  },
  {
    id: "arterial_aortic",
    name: "Peripheral Arterial & Aortic Interventions (PAD, EVAR)",
    categoryNumbers: [4, 5, 6],
    iconName: "HeartPulse",
    count: 0,
  },
  {
    id: "urology",
    name: "Urological Interventions (PCN, Prostate PAE, Ureter)",
    categoryNumbers: [19],
    iconName: "Crosshair",
    count: 0,
  },
  {
    id: "womens_health",
    name: "Women's Health & Pelvic (Uterine UAE, Ovarian)",
    categoryNumbers: [18],
    iconName: "Users",
    count: 0,
  },
  {
    id: "neuro",
    name: "Neurovascular & Acute Stroke Interventions",
    categoryNumbers: [16],
    iconName: "Brain",
    count: 0,
  },
  {
    id: "msk_spine",
    name: "Musculoskeletal, Spine & Pain (Vertebroplasty, Blocks)",
    categoryNumbers: [14, 15],
    iconName: "Bone",
    count: 0,
  },
  {
    id: "gi_ped_emerging",
    name: "GI Enteric, Pediatric, Endocrine & Emerging",
    categoryNumbers: [12, 13, 17, 20, 21, 22],
    iconName: "Layers",
    count: 0,
  },
];
