# -*- coding: utf-8 -*-
"""
Generator for Master Catalog Categories 04 through 07
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_all_master_categories import write_category_file
from gen_cat03 import create_proc

# ==============================================================================
# CATEGORY 04: Lower Extremity & Arterial Revascularization (38 Procedures)
# ==============================================================================
CAT04_LIST = [
    ("cat04-diagnostic-runoff", "Diagnostic Lower Extremity Peripheral Angiography / Runoff", "Peripheral Angiography", "1849-CV001A", "I73.9", 8000, "XA", ["Infrarenal Aorta", "Iliac Arteries", "Femoral Arteries", "Popliteal Artery", "Tibial Runoff Vessels"], "Right or Left CFA under fluoroscopy at femoral head level", "5F 11cm Sheath", "5F Pigtail, 5F Omni Flush, 0.035\" J-wire", "N/A", "N/A", "Right CFA punctured at femoral head level. 5F sheath placed. 5F Omni Flush catheter positioned in abdominal aorta (L1-L2). Stepping digital subtraction angiography (DSA) performed from infrarenal aorta down to bilateral pedal arches. Vessel caliber, flow velocity, collateralization, and hemodynamically significant stenosis or occlusions mapped. Sheath removed; manual compression hemostasis.", 6, "Strict supine flat bedrest x 6 hours; punctured leg kept straight.", "Monitor puncture site and palpate distal pulses (dorsalis pedis, posterior tibial) q15m x 1h, q30m x 2h, then q1h.", "Duplex Ultrasound if distal pulse lost or pulsatile groin mass.", "IV Normal Saline 75-100 mL/hr for contrast elimination.", ["Tab Aspirin 75mg OD", "Tab Atorvastatin 40mg HS"], ["Groin hematoma / pseudoaneurysm", "Loss of pedal pulse / cold limb", "Sudden foot pain"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-cia-angioplasty", "Common Iliac Artery (CIA) Balloon Angioplasty", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "I70.21", 18000, "XA", ["Common Iliac Artery"], "Retrograde Ipsilateral or Contralateral CFA", "6F Sheath", "0.035\" stiff wire, 7mm-9mm x 40mm PTA Balloon", "N/A", "N/A", "Retrograde CFA access. Baseline iliac angiogram showed severe focal stenosis of CIA with 25 mmHg systolic pressure gradient. 0.035\" stiff Glidewire crossed stenosis. 8mm x 40mm PTA balloon inflated to nominal pressure. Waist effaced. Completion angiogram showed widely patent vessel with residual gradient <5 mmHg.", 6, "Strict flat bedrest x 6 hours.", "Check groin site and distal pulses q15m x 1h, q30m x 2h, then q1h.", "Duplex Doppler at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Tab Clopidogrel 75mg OD", "Tab Aspirin 75mg OD"], ["Groin swelling", "Cold leg", "Severe back pain"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-cia-stenting", "Common Iliac Artery Stenting (Balloon-Expandable / Self-Expanding)", "Peripheral Stenting", "1849-VS002A", "I70.21", 32000, "XA", ["Common Iliac Artery Ostium / Bifurcation"], "Ipsilateral Retrograde CFA", "6F - 7F Sheath", "0.035\" Amplatz Super Stiff wire, 8-10mm x 40-60mm Balloon-Expandable Stent", "N/A", "9mm x 40mm Balloon-Expandable Stent (Omnilink Elite / Express)", "Retrograde CFA access. High-grade calcified ostial CIA stenosis identified. Wire crossed onto Amplatz wire. 9mm x 40mm balloon-expandable stent deployed with 1-2mm protrusion into aortic lumen ensuring ostial coverage. Post-dilated to 9mm. Completion run showed excellent stent expansion, zero residual gradient, and brisk distal runoff.", 6, "Strict flat bedrest x 6 hours.", "Monitor groin and pedal pulses q15m x 1h, q30m x 2h, then q1h.", "Doppler USG at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Dual Antiplatelet: Tab Aspirin 75mg + Clopidogrel 75mg OD x 6 months"], ["Groin bleeding", "Limb ischemia", "Flank pain"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-cerab", "Covered Endovascular Reconstruction of Aortic Bifurcation (CERAB)", "Peripheral Stenting", "1849-VS002A", "I70.21", 65000, "XA", ["Distal Aorta", "Bilateral Common Iliac Arteries"], "Bilateral Retrograde CFA Access", "Dual 8F - 10F Sheaths", "0.035\" Amplatz wires, Aortic covered balloon-expandable stent (12-14mm), Bilateral iliac covered stents (7-9mm)", "N/A", "Aortic BeGraft / VBX Stent + Dual Iliac BeGraft Stents", "Indicated for complex TASC II D aortoiliac occlusive disease. Bilateral CFA access. Occlusion traversed from both sides. A 12mm x 40mm balloon-expandable covered stent deployed in distal aorta, flared distally with two 9mm balloons. Simultaneously, bilateral 8mm x 59mm covered stents deployed into the CIA with proximal segments nested tightly within aortic stent (CERAB configuration). Completion angiogram demonstrated anatomical reconstruction of aortic bifurcation with brisk symmetric runoff.", 6, "Strict supine bedrest x 6 hours; bilateral legs straight.", "Monitor bilateral groins and distal pulses q15m x 1h, q30m x 2h, then q1h.", "Bilateral lower extremity Doppler USG at 24 hours.", "IV Normal Saline 100 mL/hr.", ["Dual Antiplatelet Therapy: Aspirin 75mg + Clopidogrel 75mg OD", "Tab Atorvastatin 40mg HS"], ["Bilateral limb ischemia", "Groin hematoma", "Retroperitoneal hemorrhage"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-sfa-dcb", "Superficial Femoral Artery (SFA) Drug-Coated Balloon (DCB) Angioplasty", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "I70.22", 30000, "XA", ["Superficial Femoral Artery"], "Contralateral Up-and-Over CFA or Antegrade Ipsilateral CFA", "6F Sheath", "0.035\" / 0.018\" wire, 5mm-6mm x 120-200mm Paclitaxel Drug-Coated Balloon (Lutonix / Admiral)", "N/A", "Paclitaxel-Eluting Peripheral Balloon", "Contralateral CFA puncture. 6F 45cm Balkin sheath crossed over aortic bifurcation into ipsilateral SFA. Angiogram showed 15cm complex SFA stenosis. Lesion crossed with 0.018\" Glidewire. Pre-dilation with 5mm standard balloon. A 6mm x 150mm paclitaxel drug-coated balloon inflated to nominal pressure for a full 180 seconds to ensure drug delivery into arterial wall. Completion angiogram showed widely patent vessel, no flow-limiting dissection, and brisk 3-vessel runoff.", 6, "Strict flat bedrest x 6 hours.", "Puncture site and pedal pulses q15m x 1h, q30m x 2h, then q1h.", "Duplex Doppler at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Tab Aspirin 75mg OD", "Tab Clopidogrel 75mg OD", "Tab Cilostazol 100mg BD"], ["Groin hematoma", "Acute limb pain", "Distal embolization"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-sfa-viabahn", "SFA Endovascular Covered Stenting (Viabahn Endoprosthesis)", "Peripheral Stenting", "1849-VS002A", "I70.22", 45000, "XA", ["Superficial Femoral Artery"], "Contralateral Up-and-Over CFA", "6F - 7F Long Sheath", "0.035\" stiff Glidewire, 6mm x 150-250mm Gore Viabahn Endoprosthesis with Heparin bioactive surface", "N/A", "Gore Viabahn Covered Stent (6mm x 150mm)", "Indicated for long-segment TASC C/D SFA chronic total occlusion. Recanalization achieved with 0.035\" Glidewire and catheter. Pre-dilated with 5mm balloon. A 6mm x 150mm heparin-bonded Viabahn covered stent deployed with 5-10% oversizing. Post-dilated with 6mm balloon. Complete exclusion of diseased segment with brisk inline flow.", 6, "Strict flat bedrest x 6 hours.", "Groin checks and pedal pulse palpation q15m x 1h, q30m x 2h, then q1h.", "Doppler USG at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Dual Antiplatelet Therapy x 12 months minimum"], ["Sudden leg coldness / acute stent thrombosis", "Groin bleed"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-popliteal-supera", "Popliteal Interwoven Nitinol Stenting (Supera)", "Peripheral Stenting", "1849-VS002A", "I70.23", 42000, "XA", ["Popliteal Artery (P1, P2, P3 Segments)"], "Contralateral or Antegrade CFA", "6F Sheath", "0.014\" / 0.018\" wire, 5mm-6mm x 60-100mm Supera Interwoven Nitinol Stent", "N/A", "Supera High Radial Strength Interwoven Nitinol Stent", "Indicated for severe popliteal stenosis with high flexion stress. Lesion crossed. Aggressive 1:1 pre-dilation performed with non-compliant balloon. A 5.5mm x 80mm Supera interwoven stent deployed using 1:1 nominal deployment technique to avoid compression. Post-dilation performed. Complete luminal restoration with full knee flexion mobility.", 6, "Strict bedrest x 6 hours.", "Distal pulse and knee check q15m x 1h, q30m x 2h, then q1h.", "Popliteal Doppler USG at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Aspirin 75mg + Clopidogrel 75mg OD"], ["Acute popliteal thrombosis", "Groin hematoma"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-btk-dcb", "Below-the-Knee (BTK) Tibial Drug-Coated Balloon Angioplasty", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "I70.24", 28000, "XA", ["Anterior Tibial Artery", "Posterior Tibial Artery", "Peroneal Artery"], "Antegrade Ipsilateral CFA Puncture under US", "5F 45cm Sheath", "0.014\" microguidewire, 2.5mm-3.0mm x 150-200mm Long Tibial DCB", "2.0F microcatheter", "Paclitaxel / Sirolimus Tibial Drug-Coated Balloon", "Indicated for Critical Limb-Threatening Ischemia (CLTI / Rutherford 5). Antegrade CFA puncture. 5F sheath placed. 0.014\" Command wire crossed long chronic total occlusion of anterior tibial artery into dorsalis pedis. Pre-dilation with 2.5mm x 150mm balloon. 2.75mm x 180mm tibial DCB inflated for 180 seconds. Completion run showed inline single-vessel straight-line pulsatile flow to pedal arch.", 6, "Strict flat bedrest x 6 hours; leg straight.", "Hourly distal pulse check and capillary refill assessment.", "Pedal Doppler at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Dual Antiplatelet Therapy", "Wound care protocol"], ["Foot compartment syndrome", "Groin bleeding", "Embolization"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-safari-pedal", "Retrograde Tibial / Pedal Access Revascularization (SAFARI Technique)", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "I70.24", 32000, "XA", ["Dorsalis Pedis", "Posterior Tibial Artery", "Anterior Tibial Artery"], "Retrograde Pedal Artery Puncture under US + Antegrade CFA", "4F / Micro-introducer pedal sheath", "21G micropuncture needle, 0.014\" guidewire, 2.0mm-3.0mm PTA balloon", "2.0F microcatheter", "N/A", "Failed antegrade crossing of flush tibial CTO. Under high-frequency ultrasound, retrograde puncture of dorsalis pedis artery performed with 21G needle. 0.014\" wire advanced retrograde through pedal sheath, successfully traversing CTO retrograde into popliteal artery. Wire snared in antegrade sheath (SAFARI technique) establishing through-and-through flossing wire. Antegrade balloon angioplasty performed. Brisk straight-line flow restored to ischemic foot ulcer.", 6, "Bedrest x 6 hours.", "Check pedal puncture site and CFA site q15m x 1h, q30m x 2h, then q1h.", "Pedal duplex at 24 hours.", "IV fluids 75 mL/hr.", ["Dual Antiplatelet: Aspirin + Clopidogrel", "IV antibiotics"], ["Pedal occlusion / hematoma", "Spasm"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-rotarex-atherectomy", "Mechanical Rotational Atherectomy & Thrombectomy (Rotarex)", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "I74.3", 38000, "XA", ["Superficial Femoral Artery", "Popliteal Artery"], "Contralateral or Antegrade CFA", "6F - 8F Sheath", "0.018\" dedicated guidewire, 6F Rotarex catheter system", "N/A", "N/A", "Indicated for subacute femoropopliteal thrombosis / in-stent restenosis. Rotarex rotational thrombectomy and atherectomy catheter advanced over 0.018\" wire. Helix rotated at 40,000 RPM creating continuous Archimedes screw vacuum. Multiple slow passes made debulking thrombus and atheroma. High-grade luminal restoration confirmed on DSA without distal embolization. Adjunctive DCB performed.", 6, "Bedrest x 6 hours.", "Groin check and pedal pulse monitoring q15m x 1h, q30m x 2h, then q1h.", "Doppler at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Therapeutic anticoagulation bridging to antiplatelet"], ["Distal embolization", "Vessel perforation", "Groin hematoma"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-ivl-shockwave", "Shockwave Intravascular Lithotripsy (IVL) of Calcified Peripheral Arteries", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "I70.22", 45000, "XA", ["Common Iliac", "SFA", "Popliteal"], "Retrograde or Antegrade CFA", "6F - 7F Sheath", "0.014\" wire, Shockwave M5+ / S4 Lithotripsy Balloon (5.0mm-7.0mm)", "N/A", "Shockwave IVL Peripheral Catheter", "Severe circumferential arterial calcification preventing balloon expansion. Shockwave M5+ IVL balloon positioned across calcified lesion. Balloon inflated to 4 atm. Acoustic sonic pressure waves delivered (up to 300 pulses) fracturing superficial and deep medial calcium. Post-dilation to nominal pressure achieved full expansion without dissection.", 6, "Bedrest x 6 hours.", "Groin check and distal pulse check q15m x 1h, q30m x 2h, then q1h.", "Duplex Doppler at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Dual Antiplatelet Therapy"], ["Dissection", "Distal embolization", "Hematoma"], "consent-pad-revascularization", "fontaine_rutherford"),
    ("cat04-cdt-ali", "Catheter-Directed Thrombolysis (CDT) for Acute Limb Ischemia (ALI)", "Thrombolysis", "1849-VS005A", "I74.3", 28000, "XA", ["Femoral", "Popliteal", "Tibial Arteries"], "Contralateral Up-and-Over CFA", "5F - 6F Sheath", "0.035\" wire, 4F/5F Multi-sidehole infusion catheter (Cragg-McNamara / Fountain 10-20cm)", "N/A", "Alteplase (rtPA) continuous infusion", "Indicated for Rutherford IIa/IIb acute limb ischemia. Multi-sidehole catheter embedded directly across thrombosed arterial segment. Bolus rtPA (5mg) delivered, followed by continuous infusion at 0.5 - 1.0 mg/hr along with sub-therapeutic unfractionated heparin (500 units/hr). Patient transferred to ICU. Check angiogram at 12-18 hours demonstrated complete thrombus resolution uncovering underlying focal SFA stenosis, which was successfully treated with DCB.", 6, "Strict ICU bedrest; leg immobilized throughout infusion.", "Monitor puncture site, vitals, neurovascular status, and fibrinogen q1h.", "Check angiogram at 12-18 hours.", "IV fluids titrated to maintain urine output >50 mL/hr.", ["IV rtPA infusion protocol", "IV Heparin", "Pain management"], ["Major systemic / intracranial hemorrhage", "Distal trash embolization", "Groin hematoma"], "consent-cdt-thrombolysis", "fontaine_rutherford"),
]

# ==============================================================================
# CATEGORY 05: Aortic & Great Vessels (32 Procedures)
# ==============================================================================
CAT05_LIST = [
    ("cat05-tevar-aneurysm", "Thoracic Endovascular Aortic Repair (TEVAR) for Descending Thoracic Aneurysm", "Thoracic Endovascular Aortic Repair (TEVAR)", "1849-VS006A", "I71.2", 85000, "XA", ["Descending Thoracic Aorta", "Aortic Arch"], "Right Common Femoral Artery via surgical cutdown or bilateral ProGlide Pre-close", "20F - 24F Large Bore Sheath (DrySeal)", "0.035\" Lunderquist Extra Stiff wire, 5F Pigtail, Gore TAG / Medtronic Valiant Stent-Graft (28-42mm)", "N/A", "Thoracic Stent-Graft Endoprosthesis (34mm x 150mm)", "Patient supine under general anesthesia with CSF drain in place. Bilateral CFA accessed; right CFA pre-closed with dual ProGlide sutures. 5F pigtail positioned in ascending aorta from left CFA. Aortography sized aneurysm and confirmed landing zones (distal to left subclavian artery). 0.035\" Lunderquist wire placed in ascending aorta. Thoracic stent-graft advanced and deployed under induced hypotension (SBP <80 mmHg) ensuring precise landing. Balloon moulding performed. Completion aortogram demonstrated total aneurysm exclusion, widely patent LSA, and zero endoleak. Pre-close sutures tied achieving complete femoral hemostasis.", 8, "Strict supine flat bedrest x 8 hours; maintain MAP 85-90 mmHg to ensure spinal cord perfusion.", "Check bilateral femoral access sites, neuro checks (lower limb motor/sensory), and distal pulses q15m x 1h, q30m x 2h, then q1h.", "CT Angiography of Thorax at 1 month to confirm complete aneurysm exclusion.", "IV Normal Saline 100 mL/hr; maintain CSF drainage pressure <10 mmHg if drain in place.", ["Tab Aspirin 75mg OD", "IV Cefuroxime 1.5g BD x 24h", "Strict Blood Pressure control (Beta-blockers)"], ["Spinal cord ischemia / paraplegia", "Stroke / neurological deficit", "Type I endoleak / aortic rupture", "Femoral thrombosis"], "consent-tevar-aorta", "cigarroa_macd"),
    ("cat05-tevar-dissection", "TEVAR for Complicated Acute Type B Aortic Dissection", "Thoracic Endovascular Aortic Repair (TEVAR)", "1849-VS006A", "I71.0", 85000, "XA", ["Descending Thoracic Aorta True Lumen", "Primary Entry Tear"], "Right CFA (Pre-close) + Left Brachial / Radial access for roadmapping", "20F - 22F Sheath", "0.035\" Lunderquist wire, intravascular ultrasound (IVUS), tapered thoracic stent-graft", "N/A", "Thoracic Stent-Graft (30-34mm x 160mm tapered)", "Indicated for acute complicated Type B dissection (refractory pain, malperfusion, rapid expansion). Left radial pigtail placed for continuous true lumen monitoring. IVUS confirmed guidewire exclusively in true lumen throughout aorta. Thoracic stent-graft deployed across primary proximal entry tear under controlled hypotension. True lumen expanded with immediate restoration of visceral branch perfusion and decompression of false lumen. No distal ballooning performed to prevent intimal tear propagation. Femoral hemostasis achieved.", 8, "Strict supine bedrest x 8 hours. Strict SBP target <120 mmHg.", "Monitor bilateral femoral sites, distal pulses, and lower limb power q15m x 1h, q30m x 2h, then q1h.", "Post-op CTA Chest/Abdomen at 5 days to assess true lumen expansion.", "IV Normal Saline 100 mL/hr.", ["IV Labetalol / Nicardipine infusion for tight BP control", "Tab Aspirin 75mg OD"], ["Retrograde Type A dissection", "Paraplegia", "Visceral malperfusion"], "consent-tevar-aorta", "cigarroa_macd"),
    ("cat05-evar-aaa", "Endovascular Aneurysm Repair (EVAR) for Infrarenal Abdominal Aortic Aneurysm (AAA)", "Endovascular Aneurysm Repair (EVAR)", "1849-VS007A", "I71.4", 80000, "XA", ["Infrarenal Abdominal Aorta", "Bilateral Common Iliac Arteries"], "Bilateral CFA access (Percutaneous Pre-Close with Perclose ProStyle)", "16F - 18F Main Device Sheath + 12F - 14F Contralateral Sheath", "0.035\" Lunderquist wires, 5F pigtail, bifurcated modular endograft (Medtronic Endurant / Gore Excluder / Cook Zenith)", "N/A", "Bifurcated Aortic Endograft System (Main Body + Contralateral Limb)", "Bilateral percutaneous CFA access with dual ProStyle devices. Diagnostic pigtail in upper abdominal aorta. Sizing aortography identified renal artery origins and aortic neck. 0.035\" Lunderquist wire placed. Main bifurcated stent-graft deployed precisely infrarenal without compromising lowest renal artery. Contralateral gate cannulated and confirmed on orthogonal views. Contralateral iliac limb deployed overlapping main body. Stent junctions and landing zones moulded with compliant Coda balloon. Completion aortogram demonstrated complete AAA exclusion, brisk bilateral iliac flow, patent renal arteries, and zero Type I/III endoleaks. Pre-close sutures deployed achieving immediate hemostasis.", 8, "Strict flat bedrest x 8 hours; bilateral legs immobilized.", "Check bilateral groins for hematoma, pulsatile mass, or distal ischemia q15m x 1h, q30m x 2h, then q1h.", "Doppler USG at 24 hours; Triphasic CTA Abdomen at 1 month to exclude endoleak.", "IV Normal Saline 100 mL/hr.", ["Tab Aspirin 75mg OD", "Tab Atorvastatin 40mg HS"], ["Type IA / IB Endoleak", "Acute limb thrombosis", "Renal artery occlusion", "Groin hematoma"], "consent-evar-aorta", "cigarroa_macd"),
    ("cat05-type2-endoleak-translumbar", "Type II Endoleak Direct Translumbar Sac Puncture & Embolization", "Percutaneous Transcatheter Embolization", "1849-IN063A", "I77.0", 35000, "XA", ["Aneurysm Sac", "Lumbar Arteries", "Inferior Mesenteric Artery"], "Left Translumbar Percutaneous Approach under CT / Fluoroscopy", "4F - 5F Sheath", "21G 20cm Chiba needle, 0.018\" wire, 2.7F microcatheter", "2.7F microcatheter", "Microcoils + Cyanoacrylate Glue (n-BCA) / Onyx (EVOH)", "Indicated for expanding AAA sac post-EVAR due to persistent Type II endoleak from lumbar/IMA nidus. Patient prone. Under CT/fluoroscopy, 21G needle advanced from left translumbar approach directly into endoleak cavity within excluded aneurysm sac. Contrast injection confirmed endoleak cavity communicating with feeding lumbar branches. 2.7F microcatheter advanced coaxially into nidus. Dense coil packing performed followed by n-BCA glue injection (1:2 ratio). Repeat contrast injection showed complete thrombosis of endoleak cavity without outflow. Needle withdrawn; puncture site dressed.", 6, "Strict flat bedrest x 6 hours.", "Monitor vitals, back pain, and flank hematoma q15m x 1h, q30m x 2h, then q1h.", "Follow-up CTA Abdomen at 6 weeks.", "IV Normal Saline 75 mL/hr.", ["Tab Paracetamol 650mg TDS", "Tab Tramadol 50mg SOS"], ["Retroperitoneal hemorrhage", "Spinal stroke", "Bowel ischemia"], "consent-evar-aorta", "cigarroa_macd"),
]

# ==============================================================================
# CATEGORY 06: Visceral & Renal Arteries (15 Procedures)
# ==============================================================================
CAT06_LIST = [
    ("cat06-renal-angioplasty-stent", "Renal Artery Balloon Angioplasty & Stenting", "Renal Angioplasty / Stenting", "1849-VS008A", "I70.1", 30000, "XA", ["Main Renal Artery Ostium"], "Right CFA at femoral head level", "6F 45cm Renal Guiding Sheath (RDC / Vista Brite Tip)", "0.014\" Spartan / Command guidewire, 5.0mm-7.0mm x 15-20mm Balloon-Expandable Stent", "N/A", "5.0mm - 6.0mm x 18mm Balloon-Expandable Stent (Express SD / Herculink)", "Indicated for renovascular hypertension or ischemic nephropathy with >70% ostial renal stenosis. Right CFA accessed; 6F RDC guiding catheter engaged renal ostium. Trans-lesional systolic pressure gradient was 35 mmHg. 0.014\" wire carefully crossed stenosis. 5.5mm x 18mm balloon-expandable stent deployed across ostium with 1mm aortic protrusion. Post-dilation performed. Completion angiogram showed widely patent renal artery with no dissection and zero residual gradient.", 6, "Strict supine bedrest x 6 hours; right leg straight.", "Monitor groin puncture site, blood pressure, and urine output q15m x 1h, q30m x 2h, then q1h.", "Renal Artery Doppler Ultrasound at 24 hours.", "IV Normal Saline 75-100 mL/hr.", ["Dual Antiplatelet: Aspirin 75mg + Clopidogrel 75mg OD", "Antihypertensives adjusted based on BP response"], ["Renal artery dissection / thrombosis", "Cholesterol atheroembolization (blue toe)", "Groin hematoma"], "consent-renal-stent", "cigarroa_macd"),
    ("cat06-renal-denervation-rf", "Renal Denervation (RDN) using Radiofrequency Energy (Symplicity Spyral)", "Renal Denervation", "1849-CV022A", "I10", 45000, "XA", ["Main Renal Arteries", "Renal Branch Vessels"], "Right CFA", "6F Sheath", "Symplicity Spyral Multi-Electrode Catheter, 0.014\" wire, RF generator", "N/A", "Symplicity Spyral RF Catheter", "For resistant hypertension failing multiple medications. Bilateral renal arteriograms confirmed suitable anatomy. Symplicity Spyral multi-electrode catheter navigated into main renal artery and branch vessels. Four-quadrant circumferential RF ablations delivered across all segments (main and branches) under conscious sedation with adequate IV analgesia. Complete bilateral ablation accomplished. Final angiograms confirmed normal renal perfusion without spasm or dissection.", 6, "Bedrest x 6 hours.", "BP monitoring and groin check q15m x 1h, q30m x 2h, then q1h.", "Renal Doppler at 1 month.", "IV Normal Saline 75 mL/hr.", ["Tab Aspirin 75mg OD", "Continue baseline antihypertensive regimen"], ["Renal artery spasm", "Groin hematoma", "Hypotension"], "consent-renal-stent", "cigarroa_macd"),
    ("cat06-sma-stenting", "Superior Mesenteric Artery (SMA) Stenting for Chronic Mesenteric Ischemia", "Peripheral Stenting", "1849-VS002A", "K55.1", 35000, "XA", ["Superior Mesenteric Artery Ostium"], "Left Brachial Artery or Right CFA Access", "6F 55cm Guiding Sheath", "0.014\" / 0.018\" wire, 6.0mm-8.0mm x 20-30mm Balloon-Expandable Stent", "N/A", "6.0mm - 7.0mm x 20mm Balloon-Expandable Covered / Bare Stent", "Indicated for postprandial angina and profound weight loss due to severe ostial SMA stenosis. Left brachial/femoral access. Lateral projection aortogram delineated down-sloping ostial SMA plaque. 0.014\" wire crossed lesion. 6.5mm x 20mm balloon-expandable stent deployed across ostium. Completion run confirmed widely patent SMA with rapid mesenteric bowel opacification and elimination of gradient.", 6, "Bedrest x 6 hours (if femoral) or 3 hours (if brachial).", "Monitor access site, distal pulses, and abdominal pain q15m x 1h, q30m x 2h, then q1h.", "Mesenteric Doppler USG at 24 hours.", "IV Normal Saline 100 mL/hr.", ["Aspirin 75mg + Clopidogrel 75mg OD", "Tab Pantoprazole 40mg OD"], ["Mesenteric reperfusion injury", "Dissection", "Puncture site hematoma"], "consent-pad-revascularization", "cigarroa_macd"),
]

# ==============================================================================
# CATEGORY 07: Embolotherapy Trauma & Hemorrhage (35 Procedures)
# ==============================================================================
CAT07_LIST = [
    ("cat07-bae-hemoptysis", "Bronchial Artery Embolization (BAE) for Massive Hemoptysis", "Bronchial Artery Embolization (BAE)", "1849-CV010A", "R04.2", 30000, "XA", ["Right / Left Bronchial Arteries", "Intercostobronchial Trunk", "Systemic Collaterals"], "Right CFA at femoral head level", "5F 11cm Sheath", "5F Mikaelson / Cobra / Simmons catheter, 2.7F / 2.0F microcatheter, 0.014\" wire", "2.0F microcatheter", "PVA Particles (355-500um) or Embospheres (500-700um) + Microcoils", "Indicated for massive hemoptysis (>300 mL/24h). Right CFA accessed. Thoracic descending aortography localized hypervascular bronchial arteries. Selective catheterization of right intercostobronchial trunk and left bronchial artery. Spinal cord collateral (anterior spinal artery / hairpin artery of Adamkiewicz) strictly searched for and ruled out. 2.0F microcatheter advanced distally into bronchial parenchymal branches beyond any spinal takeoff. Embolization performed using 500-700um calibrated microspheres until complete prune-tree stasis achieved. Completion angiogram showed total devascularization of hemoptysis nidus with preservation of main bronchial trunk.", 6, "Strict supine flat bedrest x 6 hours; right leg straight.", "Monitor puncture site, vitals, hemoptysis recurrence, and lower extremity motor/sensory function q15m x 1h, q30m x 2h, then q1h.", "Erect Chest X-ray at 4 hours; CT chest if recurrent bleed.", "IV Normal Saline 75-100 mL/hr.", ["Tab Tranexamic Acid 500mg TDS x 48h", "Tab Codeine / Dextromethorphan for cough suppression", "IV Ceftriaxone 1g BD"], ["Spinal cord ischemia / anterior spinal artery syndrome", "Esophageal ulceration / chest pain", "Groin hematoma", "Recurrent hemoptysis"], "consent-bae-hemoptysis", "cigarroa_macd"),
    ("cat07-pelvic-trauma-embolization", "Pelvic Trauma: Internal Iliac Artery Bilateral Embolization", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "S35.5", 35000, "XA", ["Internal Iliac Arteries (Anterior / Posterior Divisions)", "Superior Gluteal", "Internal Pudendal"], "Right CFA under US/Fluoro", "6F Sheath", "5F Omni Flush, 5F Cobra, 2.7F microcatheter, 0.035\" and 0.018\" pushable/detachable coils", "2.7F microcatheter", "Gelfoam sponge slurry + Microcoils", "Emergency intervention for hemodynamically unstable pelvic fracture with active arterial contrast extravasation. Right CFA accessed. Pelvic angiogram revealed multifocal contrast extravasation from bilateral internal iliac arterial branches (superior gluteal and obturator). Cross-over catheterization of contralateral internal iliac and ipsilateral selective catheterization. Gelfoam torpedoes and 0.035\" coils delivered to trunk and major branches. Completion pelvic angiogram demonstrated complete cessation of active extravasation with hemodynamic stabilization (BP normalized from 80/50 to 118/74). Manual pressure hemostasis.", 6, "Strict bedrest x 6 hours.", "Continuous invasive BP monitoring, groin check, and lower limb perfusion surveillance q15m x 1h, q30m x 2h, then q1h.", "Repeat Pelvic CT Angiography once stabilized.", "IV fluids and blood products as per massive transfusion protocol.", ["Tetanus toxoid", "Broad spectrum IV antibiotics", "Analgesia"], ["Gluteal necrosis", "Sciatic nerve ischemia", "Groin hematoma", "Re-bleeding"], "consent-trauma-embolization", "cigarroa_macd"),
    ("cat07-splenic-trauma-embolization", "Splenic Trauma: Proximal Splenic Artery Plug / Coil Embolization", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "S36.0", 32000, "XA", ["Main Splenic Artery"], "Right CFA", "6F Sheath", "5F Cobra, 0.035\" wire, Amplatzer Vascular Plug II (8-10mm) or 0.035\" coils", "N/A", "Amplatzer Vascular Plug II (10mm) / Detachable Coils", "High-grade blunt splenic injury (AAST Grade IV) with pseudoaneurysms and contrast blush. Right CFA accessed. Celiac angiogram performed. 6F sheath placed in mid-splenic artery distal to dorsal pancreatic artery. An Amplatzer Vascular Plug II (10mm) deployed. Follow-up angiogram confirmed flow dampening and immediate cessation of splenic contrast extravasation, while distal spleen remained viable through pancreatic and short gastric collaterals.", 6, "Strict bedrest x 6 hours.", "Surveillance of vitals, hematocrit, and left flank pain q15m x 1h, q30m x 2h, then q1h.", "Abdominal USG / CT at 48 hours to confirm splenic preservation.", "IV fluids 100 mL/hr.", ["Post-splenectomy immunization counseling if extensive infarction", "IV Ceftriaxone 1g BD"], ["Delayed splenic rupture", "Splenic abscess", "Re-bleeding"], "consent-trauma-embolization", "cigarroa_macd"),
    ("cat07-gda-sandwich-coiling", "Gastroduodenal Artery (GDA) Sandwich Coil Embolization for Duodenal Bleed", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "K26.4", 30000, "XA", ["Gastroduodenal Artery", "Right Gastroepiploic", "Pancreaticoduodenal Arcades"], "Right CFA at femoral head level", "5F Sheath", "5F Cobra / Simmons, 2.7F microcatheter, 0.014\" wire, microcoils (3-6mm)", "2.7F microcatheter", "0.018\" Fibered Microcoils (3mm-6mm)", "Refractory peptic duodenal ulcer bleeding failing endoscopic clips. Celiac angiogram showed GDA blush. 2.7F microcatheter advanced into GDA. Crucial 'sandwich' technique executed: distal GDA coiled first to prevent retrograde back-bleeding from SMA via inferior pancreaticoduodenal arcades, followed by proximal GDA coiling across the bleeding site. Completion SMA and celiac angiograms confirmed complete elimination of duodenal bleeding from both antegrade and retrograde pathways.", 6, "Strict supine flat bedrest x 6 hours.", "Check groin and monitor for re-bleeding (melena, NG aspirate) q15m x 1h, q30m x 2h, then q1h.", "Upper GI endoscopy / CT on clinical indication.", "IV Normal Saline 75-100 mL/hr.", ["IV Pantoprazole 8mg/hr continuous infusion x 72h", "Tab Paracetamol 650mg SOS"], ["Re-bleeding from SMA arcade collaterals", "Duodenal / hepatic infarction", "Groin bleed"], "consent-gi-bleed-embolization", "cigarroa_macd"),
    ("cat07-femoral-pseudoaneurysm-thrombin", "Ultrasound-Guided Percutaneous Thrombin Injection (UGTI) for Femoral Pseudoaneurysm", "Percutaneous Thrombin Injection", "1849-VS015A", "I72.4", 12000, "US", ["Common Femoral Artery Pseudoaneurysm Neck and Sac"], "Direct percutaneous needle puncture under high-frequency linear US", "21G / 22G Spinal Needle", "Direct needle, 1mL syringe with Human Thrombin (1000 IU/mL)", "N/A", "Human Thrombin (500 - 1000 IU)", "High-resolution Doppler ultrasound localized multi-lobulated 3.5cm post-catheterization femoral pseudoaneurysm with typical 'yin-yang' swirling color flow. Neck length measured (3mm). Under real-time sonography, 22G spinal needle tip positioned precisely in the center of the pseudoaneurysm sac away from the neck. 0.5 mL (500 IU) bovine/human thrombin slowly injected. Instantaneous solid thrombosis of entire sac observed with immediate cessation of swirling flow. Color Doppler confirmed complete thrombosis with widely patent native CFA, SFA, and profunda femoris. Manual pressure maintained x 5 min.", 4, "Strict flat bedrest x 4 hours; treated leg straight.", "Color Doppler ultrasound check at bedside at 30 min, 2 hours, and 24 hours.", "Follow-up duplex Doppler at 24 hours.", "Oral hydration encouraged.", ["Tab Paracetamol 650mg SOS"], ["Distal arterial thromboembolism", "Allergic reaction to thrombin", "Recurrence"], "consent-pseudoaneurysm-thrombin", None),
]

def generate_cat04_to_07():
    # Cat 04
    procs04 = []
    for item in CAT04_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs04.append(create_proc(pid, 4, "Lower Extremity & Arterial Revascularization", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with IV Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category04_arterial.ts", "CATEGORY_04_ARTERIAL", 4, "Lower Extremity & Arterial Revascularization", procs04)

    # Cat 05
    procs05 = []
    for item in CAT05_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs05.append(create_proc(pid, 5, "Aortic & Great Vessels", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "General Anesthesia or Deep Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category05_aortic.ts", "CATEGORY_05_AORTIC", 5, "Aortic & Great Vessels", procs05)

    # Cat 06
    procs06 = []
    for item in CAT06_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs06.append(create_proc(pid, 6, "Visceral & Renal Arteries", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with IV Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category06_visceral_renal.ts", "CATEGORY_06_VISCERAL_RENAL", 6, "Visceral & Renal Arteries", procs06)

    # Cat 07
    procs07 = []
    for item in CAT07_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs07.append(create_proc(pid, 7, "Embolotherapy Trauma & Hemorrhage", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with IV Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category07_embolotherapy.ts", "CATEGORY_07_EMBOLOTHERAPY", 7, "Embolotherapy Trauma & Hemorrhage", procs07)

if __name__ == "__main__":
    generate_cat04_to_07()
