# -*- coding: utf-8 -*-
"""
Generator for Master Catalog Categories 08 through 12
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_all_master_categories import write_category_file
from gen_cat03 import create_proc

# ==============================================================================
# CATEGORY 08: Interventional Oncology Transcatheter (20 Procedures)
# ==============================================================================
CAT08_LIST = [
    ("cat08-ctace-lipiodol", "Conventional Transarterial Chemoembolization (cTACE) with Lipiodol & Doxorubicin", "Transcatheter Arterial Chemoembolization (TACE)", "1849-MG077A", "C22.0", 35000, "XA", ["Proper Hepatic Artery", "Right/Left Hepatic Artery", "Segmental Branches"], "Right CFA at femoral head level", "5F 11cm Sheath", "5F RH / Cobra / Simmons catheter, 2.0F - 2.7F microcatheter, 0.014\" wire", "2.0F microcatheter", "Lipiodol-Doxorubicin Emulsion (10-15 mL) + Gelfoam sponge slurry", "Right CFA access. Celiac and superior mesenteric arteriography performed. Anatomy and portal vein patency confirmed. Selective right/left hepatic artery cannulation. 2.0F microcatheter advanced superselectively into tumor-feeding segmental branches. Dense tumor blush demonstrated with pathological neo-vascularity. 10 mL emulsion of Lipiodol and Doxorubicin (50mg) infused slowly under fluoroscopy until complete tumor saturation achieved. Embolization completed with gelfoam slurry until near-stasis in feeder. Completion run showed complete tumor devascularization and preserved non-target liver parenchyma.", 6, "Strict supine flat bedrest x 6 hours; right leg straight.", "Monitor puncture site, vitals, pain score, and nausea q15m x 1h, q30m x 2h, then q1h.", "Triphasic CT Abdomen at 4-6 weeks to assess Lipiodol retention and mRECIST response.", "IV Normal Saline 100 mL/hr x 12 hours.", ["IV Ondansetron 8mg TDS", "IV Tramadol 50mg SOS", "IV Dexamethasone 8mg OD x 2 days", "Tab Pantoprazole 40mg OD"], ["Acute post-embolization syndrome (severe pain, fever, nausea)", "Hepatic decompensation / jaundice", "Non-target embolization (gastric ulcer, cholecystitis)", "Groin hematoma"], "consent-tace", "cigarroa_macd"),
    ("cat08-deb-tace", "Drug-Eluting Bead TACE (DEB-TACE) with DC Beads / HepaSpheres", "Transcatheter Arterial Chemoembolization (TACE)", "1849-MG077A", "C22.0", 42000, "XA", ["Hepatic Artery Segmental Branches"], "Right CFA", "5F Sheath", "5F Cobra, 2.0F microcatheter, 0.014\" wire", "2.0F microcatheter", "100-300um DC Beads loaded with Doxorubicin (50-75mg)", "Celiac and common hepatic angiograms obtained. Superselective cannulation of tumor-feeding artery using 2.0F microcatheter. DC Beads (100-300um) loaded with 75mg doxorubicin injected slowly at 1 mL/min with non-ionic contrast under continuous fluoroscopy until endpoint of 5 beats to clear contrast column. Completion angiography showed total feeder occlusion with no non-target reflux.", 6, "Bedrest x 6 hours.", "Groin check and post-embolization symptom monitoring q15m x 1h, q30m x 2h, then q1h.", "Triphasic CT / MRI at 6 weeks.", "IV Normal Saline 100 mL/hr.", ["Antiemetics (Ondansetron 8mg TDS)", "Analgesics (Paracetamol + Tramadol)", "Proton-pump inhibitors"], ["Post-embolization syndrome", "Hepatic abscess", "Groin bleeding"], "consent-tace", "cigarroa_macd"),
    ("cat08-tare-y90", "Transarterial Radioembolization (TARE / SIRT) with Y-90 Glass / Resin Microspheres", "Radioembolization (TARE / SIRT)", "1849-MG078A", "C22.0", 85000, "XA", ["Right / Left Hepatic Artery", "Segmental Branches"], "Right CFA at femoral head level", "5F Sheath", "5F Simmons, 2.0F microcatheter, 0.014\" wire, non-target microcoils", "2.0F microcatheter", "Yttrium-90 Glass Microspheres (TheraSphere) or Resin Microspheres (SIR-Spheres)", "Indicated for unresectable HCC / intrahepatic cholangiocarcinoma with portal vein thrombosis. Prior Tc-99m MAA scan documented lung shunt fraction <10% and zero gastrointestinal shunting. Right CFA accessed. Selective catheterization with 2.0F microcatheter to target hepatic lobe/segment. Non-target branches (gastroduodenal, right gastric, falciform) prophylactically coiled if needed. Calculated dose of Y-90 microspheres delivered through microcatheter under strict radiation safety protocols. Post-delivery bremsstrahlung SPECT-CT / PET-CT performed confirming intense localized intratumoral radiation deposition.", 6, "Strict supine bedrest x 6 hours.", "Radiation safety protocol; monitor groin and vitals q15m x 1h, q30m x 2h, then q1h.", "Bremsstrahlung SPECT-CT within 24 hours; follow-up MRI Liver at 2-3 months.", "IV Normal Saline 75-100 mL/hr.", ["Tab Prednisolone 20mg OD tapering over 2 weeks", "Tab Pantoprazole 40mg OD", "Tab Ondansetron 4mg TDS"], ["Radiation-induced liver disease (RILD)", "Radiation pneumonitis", "Radiation-induced gastrointestinal ulceration"], "consent-tare-y90", "cigarroa_macd"),
    ("cat08-debiri-liver-mets", "DEBIRI (DEB TACE with Irinotecan) for Colorectal Liver Metastases", "Transcatheter Arterial Chemoembolization (TACE)", "1849-MG077A", "C78.7", 40000, "XA", ["Hepatic Artery Branches"], "Right CFA", "5F Sheath", "5F Cobra, 2.0F microcatheter, 0.014\" wire", "2.0F microcatheter", "DC Beads (100-300um) loaded with 100mg Irinotecan", "Hepatic arteriography mapped multiple hypovascular and hypervascular colorectal metastases. Intra-arterial lidocaine (2% 5mL) infused prior to embolization to prevent acute irinotecan-mediated visceral pain. Irinotecan-loaded DC Beads (100-300um) delivered superselectively. Complete devascularization of target nodules confirmed.", 6, "Bedrest x 6 hours.", "Groin check and pain monitoring q15m x 1h, q30m x 2h, then q1h.", "Contrast CT Abdomen at 6 weeks.", "IV Normal Saline 100 mL/hr.", ["IV Ondansetron + Atropine (for cholinergic syndrome PRN)", "IV Tramadol 50mg"], ["Severe visceral pain / cholinergic crisis", "Hepatic toxicity", "Fever"], "consent-tace", "cigarroa_macd"),
]

# ==============================================================================
# CATEGORY 09: Interventional Oncology Percutaneous Ablation (25 Procedures)
# ==============================================================================
CAT09_LIST = [
    ("cat09-liver-mwa", "Ultrasound / CT-Guided Microwave Ablation (MWA) of Hepatocellular Carcinoma", "Microwave Ablation (MWA)", "1849-MG081A", "C22.0", 35000, "US", ["Liver Segment 6/7/8/4 Focal Lesion"], "Right intercostal or subcostal approach", "14G - 17G Microwave Antenna (Emprint / NeuWave)", "Coaxial needle, 14G-17G MWA antenna, microwave generator, cooling pump", "N/A", "N/A", "Patient supine/lateral. Ultrasound and CT fusion localized 2.8cm HCC in Segment 6. Sterile prep. Local infiltration with 2% lignocaine down to capsule. Under real-time ultrasound and CT guidance, a 14G internally cooled microwave antenna was advanced into the tumor center. Hydrodissection performed with 500 mL 5% Dextrose separating liver capsule from adjacent hepatic flexure of colon. Microwave energy applied at 65W for 6 minutes. Hyperechoic gas bubble completely enveloped tumor with a >5mm ablative safety margin. Track ablation performed during antenna removal. Immediate contrast-enhanced ultrasound confirmed complete non-enhancement (complete necrosis) of lesion.", 4, "Right lateral decubitus x 2 hours, then supine bedrest x 2 hours.", "Monitor puncture site, pain score, and vitals q15m x 1h, q30m x 2h, then q1h.", "Bedside USG if severe abdominal pain or drop in BP.", "Oral fluids after 2 hours.", ["Tab Paracetamol 650mg TDS", "Cap Pantoprazole 40mg OD", "IV Tramadol 50mg SOS"], ["Thermal injury to adjacent bowel / colon perforation", "Subcapsular hematoma / hemoperitoneum", "Biliary duct thermal stricture"], "consent-tumor-ablation", None),
    ("cat09-liver-rfa", "Ultrasound-Guided Radiofrequency Ablation (RFA) of Liver Tumors", "Radiofrequency Ablation (RFA)", "1849-MG080A", "C22.0", 30000, "US", ["Hepatic Parenchymal Tumor"], "Subcostal or intercostal approach", "17G RFA Expandable / Internally Cooled Needle", "17G Cool-tip / LeVeen RFA needle, grounding pads, RF generator", "N/A", "N/A", "Ultrasound-guided percutaneous access. Dual grounding pads placed on patient thighs. 17G internally cooled RF electrode advanced into tumor core. RF current applied with impedance control protocol, achieving roll-off after 12 minutes. Track ablation completed. Post-ablation ultrasound confirmed complete hyperechoic coverage with clear margins.", 4, "Bedrest x 4 hours.", "Vitals and site checks q15m x 1h, q30m x 2h, then q1h.", "Contrast CT at 1 month to confirm complete response.", "IV fluids 75 mL/hr.", ["Tab Paracetamol 650mg TDS", "Tab Pantoprazole 40mg OD"], ["Pneumothorax (if high dome)", "Bleeding", "Bile leak"], "consent-tumor-ablation", None),
    ("cat09-lung-mwa", "CT-Guided Microwave Ablation (MWA) of Primary / Secondary Lung Malignancy", "Microwave Ablation (MWA)", "1849-MG081A", "C34.9", 38000, "CT", ["Peripheral Lung Parenchymal Lesion"], "Percutaneous transthoracic approach under CT fluoroscopy", "16G - 17G Microwave Antenna", "CT grid, 17G MWA antenna, thermocouple, artificial pneumothorax set if needed", "N/A", "N/A", "Indicated for medically inoperable Stage I NSCLC or solitary lung metastasis. Non-contrast CT thorax performed for lesion targeting. Local anesthesia down to parietal pleura. A 17G microwave antenna was inserted coaxially into the lung nodule, avoiding bullae and pulmonary vessels. Verification scan confirmed central antenna positioning. Microwave ablation delivered at 45W for 5 minutes. Progressive ground-glass halo enveloped lesion representing target thermal margin. Track ablated. Post-procedure CT demonstrated complete lesion coverage.", 4, "Strict supine/ipsilateral dependent bedrest x 4 hours. Minimal coughing.", "Monitor oxygen saturation, respiratory rate, and chest pain q15m x 1h, q30m x 2h, then q1h.", "Erect / PA Chest X-ray at 2 to 4 hours post-procedure to rule out pneumothorax or hemothorax.", "IV Normal Saline 75 mL/hr.", ["Tab Codeine Phosphate 30mg PO TDS (cough suppression)", "Tab Paracetamol 650mg TDS", "Supplemental Oxygen to keep SpO2 >94%"], ["Pneumothorax requiring chest tube", "Hemoptysis", "Bronchopleural fistula", "Air embolism"], "consent-lung-ablation", None),
    ("cat09-renal-cryo", "Percutaneous CT-Guided Cryoablation of Renal Cell Carcinoma (T1a)", "Cryoablation", "1849-MG082A", "C64", 45000, "CT", ["Exophytic / Endophytic Renal Mass"], "Posterior or posterolateral retroperitoneal CT approach", "17G Cryoprobes (Galil / Boston Scientific IceRod)", "CT markers, multiple 17G cryoprobes (dual or triple configuration), argon-helium gas system", "N/A", "N/A", "Patient prone. CT localized 3.2cm right exophytic renal mass. Hydrodissection performed using 500 mL saline + dilute contrast displacing ascending colon 2cm away from kidney. Under CT guidance, three 17G IceRod cryoprobes placed into mass in triangular configuration spaced 1.5cm apart. Dual freeze-thaw cycle performed: 10-minute freeze, 8-minute passive thaw, 10-minute freeze. CT confirmed hypodense ice ball completely extending 5mm beyond tumor margins. Active thaw performed and cryoprobes removed under track coagulation.", 4, "Strict supine/prone flat bedrest x 4 hours.", "Monitor urine for gross hematuria, check BP and flank tenderness q15m x 1h, q30m x 2h, then q1h.", "Bedside USG if flank pain or tachycardia.", "IV Normal Saline 100 mL/hr.", ["Tab Paracetamol 650mg TDS", "Tab Tramadol 50mg SOS", "Cap Pantoprazole 40mg OD"], ["Gross hematuria / ureteral obstruction by clot", "Retroperitoneal hemorrhage", "Cryoneurolysis / flank paresthesia"], "consent-tumor-ablation", None),
    ("cat09-osteoid-osteoma-rfa", "CT-Guided Percutaneous Radiofrequency Ablation of Osteoid Osteoma", "Radiofrequency Ablation (RFA)", "1849-MG080A", "M89.8", 25000, "CT", ["Cortical Bone Nidus (Femur / Tibia / Spine)"], "Direct percutaneous cortical drill access", "Bonopty / Jamshidi bone biopsy coaxial system", "Powered bone drill, 17G RFA needle with 5mm active tip, RF generator", "N/A", "N/A", "Indicated for incapacitating nocturnal bone pain due to osteoid osteoma. Patient under spinal or general anesthesia. High-resolution thin-slice CT identified 6mm cortical nidus with surrounding sclerosis in proximal femur. Coaxial drill system traversed dense sclerotic bone directly into nidus. 17G RFA electrode placed with active tip centered in nidus. Target temperature maintained at 90°C for 6 minutes. Completion CT confirmed electrode position. Drill removed; sterile dressing applied. Immediate and permanent pain relief anticipated.", 4, "Bedrest x 4 hours.", "Neurovascular check of limb and pain assessment q30m x 2h, then q1h.", "Plain X-ray of limb prior to discharge.", "Oral hydration.", ["Tab Paracetamol 650mg TDS", "Tab Ibuprofen 400mg TDS x 3 days"], ["Cortical bone fracture", "Skin burn", "Incomplete nidus ablation"], "consent-tumor-ablation", None),
]

# ==============================================================================
# CATEGORY 10: Venous Interventions (26 Procedures) - EXPLICIT USER FOCUS
# ==============================================================================
CAT10_LIST = [
    # 1. VenaSeal GSV
    ("cat10-venaseal-gsv", "VenaSeal Cyanoacrylate Closure of Great Saphenous Vein (GSV)", "Endovenous Cyanoacrylate Closure (VenaSeal)", "1849-VS010A", "I83.9", 35000, "US", ["Great Saphenous Vein (GSV)", "Saphenofemoral Junction (SFJ)"], "Below-knee GSV access under real-time ultrasound guidance", "5F dedicated VenaSeal introducer sheath", "0.035\" J-wire, 5F dispensing catheter, VenaSeal gun with cyanoacrylate adhesive", "N/A", "VenaSeal Cyanoacrylate Medical Adhesive (5 mL)", "Patient supine. Duplex ultrasound confirmed saphenofemoral junction (SFJ) incompetence with severe reflux (>3.0s) and GSV dilation (8.5mm). Under ultrasound guidance, below-knee GSV punctured with 19G needle. 0.035\" wire advanced to common femoral vein. 5F delivery sheath and dispenser catheter positioned precisely 5 cm distal to SFJ under direct continuous sonography. Tumescent anesthesia NOT required. 0.09 mL of proprietary cyanoacrylate adhesive delivered via dispenser gun at index site, followed immediately by 3 minutes of direct ultrasound probe compression. Subsequent 0.09 mL glue aliquots delivered every 3 cm down the GSV with 30 seconds compression per segment down to puncture site. Immediate duplex scanning confirmed 100% complete occlusion and acoustic shadowing of GSV throughout treated segment with widely patent common femoral vein.", 1, "Immediate ambulation encouraged. Patient ambulates in recovery for 15-20 minutes.", "Check puncture site for bleeding; duplex ultrasound sweep of CFV to ensure zero glue protrusion q30m.", "Venous Duplex Ultrasound at 24-48 hours to confirm GSV occlusion and CFV patency.", "Encourage oral fluids.", ["Tab Paracetamol 650mg PO SOS", "Tab Ibuprofen 400mg PO BD x 3 days (if phlebitis occurs)"], ["Glue migration into common femoral vein / DVT", "Superficial phlebitis / red tender cord", "Paresthesia of saphenous nerve"], "consent-venous-ablation", "caprini_vte"),

    # 2. VenaSeal SSV
    ("cat10-venaseal-ssv", "VenaSeal Cyanoacrylate Closure of Small Saphenous Vein (SSV)", "Endovenous Cyanoacrylate Closure (VenaSeal)", "1849-VS010A", "I83.9", 35000, "US", ["Small Saphenous Vein (SSV)", "Saphenopopliteal Junction (SPJ)"], "Mid-calf SSV access under ultrasound guidance", "5F VenaSeal sheath", "0.035\" wire, 5F VenaSeal dispensing catheter, adhesive gun", "N/A", "VenaSeal Cyanoacrylate Adhesive", "Patient prone. Duplex ultrasound mapped incompetent small saphenous vein (SSV) draining into popliteal vein via SPJ. Mid-calf percutaneous micropuncture of SSV. Delivery catheter tip positioned precisely 3 cm distal to saphenopopliteal junction to safeguard sural nerve and popliteal vein. Cyanoacrylate glue delivered in standardized aliquots with compression. Completion duplex confirmed complete closure of SSV with fully patent popliteal vein.", 1, "Immediate ambulation for 15 minutes.", "Monitor calf puncture site and distal pulses q30m x 2h.", "Duplex ultrasound at 48 hours.", "Oral fluids.", ["Tab Paracetamol 650mg SOS", "Tab Ibuprofen 400mg BD x 2 days"], ["Sural nerve paresthesia", "Popliteal DVT", "Superficial phlebitis"], "consent-venous-ablation", "caprini_vte"),

    # 3. EVLA GSV
    ("cat10-evla-gsv", "Endovenous Laser Ablation (EVLA) of Great Saphenous Vein (GSV)", "Endovenous Laser Therapy (EVLT)", "1849-VS009A", "I83.9", 25000, "US", ["Great Saphenous Vein", "Saphenofemoral Junction"], "Knee level GSV puncture under ultrasound", "4F - 5F Introducer Sheath", "1470nm Radial Laser Fiber, tumescent infiltration pump, 0.035\" wire", "N/A", "1470nm Radial 2-ring Laser Fiber", "Ultrasound confirmed SFJ incompetence and GSV reflux. Below-knee GSV accessed; 1470nm radial laser fiber advanced to 2 cm distal to SFJ (inferior to superficial epigastric vein). Under ultrasound guidance, ultrasound-guided perivenous tumescent local anesthesia (500 mL dilute cold lignocaine + bicarbonate + adrenaline) infused circumferentially into the saphenous fascial sheath creating a >10mm fluid heat-sink collar. Laser activated at 7W-10W (continuous pullback delivering 60-80 J/cm). Post-ablation duplex confirmed total vein occlusion with no flow and patent CFV.", 1, "Immediate ambulation with Class II (20-30 mmHg) graduated compression stockings.", "Check puncture site and distal pulses q30m x 2h.", "Duplex ultrasound at 1 week.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Tab Ibuprofen 400mg BD x 3 days"], ["Deep vein thrombosis (EHIT)", "Skin burn / hyperpigmentation", "Saphenous nerve injury"], "consent-venous-ablation", "caprini_vte"),

    # 4. RFA GSV
    ("cat10-rfa-gsv", "Radiofrequency Ablation (RFA / ClosureFast) of Great Saphenous Vein", "Radiofrequency Ablation (RFA)", "1849-VS009A", "I83.9", 28000, "US", ["Great Saphenous Vein"], "Knee / upper calf GSV puncture under US", "7F ClosureFast Introducer Sheath", "0.025\" wire, ClosureFast 7F segmental RFA catheter (7cm heating element)", "N/A", "ClosureFast RFA Catheter", "Knee level GSV accessed under ultrasound. ClosureFast catheter advanced to 2.0 cm distal to SFJ. Perivenous tumescent anesthesia delivered under ultrasound guidance along entire GSV. Catheter heated to 120°C for two 20-second cycles at SFJ and one 20-second cycle per 7cm segment sequentially during stepwise pullback. Duplex confirmed complete thermal vein occlusion and patent deep venous system.", 1, "Immediate ambulation; Class II stockings applied.", "Check puncture site q30m x 2h.", "Duplex USG at 1 week.", "Oral hydration.", ["Tab Paracetamol 650mg SOS", "Tab Ibuprofen 400mg BD x 2 days"], ["EHIT (Endovenous Heat-Induced Thrombosis)", "Paresthesia", "Phlebitis"], "consent-venous-ablation", "caprini_vte"),

    # 5. Foam Sclerotherapy Varicose Veins
    ("cat10-foam-sclerotherapy", "Ultrasound-Guided Foam Sclerotherapy (STS / Polidocanol) for Varicose Veins", "Varicose Vein Sclerotherapy", "1849-VS011A", "I83.8", 12000, "US", ["Tortuous Varicose Tributaries", "Nonsaphenous Varices"], "Direct percutaneous puncture under high-frequency linear US", "23G - 25G Butterfly needles", "Tessari 3-way stopcock method, 1% - 3% Sodium Tetradecyl Sulfate (STS) or Polidocanol, room air/CO2 (1:4 ratio)", "N/A", "STS / Polidocanol Sclerosant Microfoam (max 10 mL per session)", "High-resolution ultrasound mapped tortuous superficial varicose tributaries and refluxing channels. Tessari method used to generate microfoam by mixing 2 mL of 1% or 3% STS with 8 mL air across a 3-way stopcock. Direct puncture of target varices with 23G butterfly needle. Intraluminal venous blood flashback confirmed. Microfoam slowly injected under real-time ultrasound monitoring. Sonography showed displacement of blood and acute spasm/echogenic foam filling the entire variceal lumen without deep venous spillover. Direct manual massage and eccentric compression pads applied.", 1, "Immediate ambulation for 30 minutes. Continuous Class II compression stocking worn for 7 days.", "Monitor puncture sites and distal perfusion q15m x 1h.", "Clinical and duplex review at 2-4 weeks.", "Oral hydration.", ["Tab Paracetamol 650mg SOS"], ["Deep vein thrombosis", "Cutaneous necrosis / extravasation", "Visual scotoma / migraine (transient microemboli)", "Hyperpigmentation"], "consent-venous-sclerotherapy", "caprini_vte"),

    # 6. Incompetent Perforator Vein Sclerotherapy
    ("cat10-perforator-sclerotherapy", "Incompetent Perforator Vein Ultrasound-Guided Foam Sclerotherapy", "Varicose Vein Sclerotherapy", "1849-VS011A", "I83.0", 12000, "US", ["Incompetent Cockett / Boyd Perforator Veins"], "Direct puncture of perforator vein at fascial defect level", "21G - 23G Needle", "High-frequency US probe, Tessari foam generator, 3% Polidocanol / STS foam", "N/A", "Polidocanol 3% Foam Sclerosant (2-3 mL)", "Duplex ultrasound identified incompetent calf perforator vein with >500ms bidirectional reflux and diameter >4mm traversing deep muscular fascia. Under direct ultrasound guidance, 21G needle advanced precisely into perforator lumen above deep muscular fascia. 2 mL of 3% STS/polidocanol foam injected under sonographic vision. Foam visualized filling perforator with immediate spasm and thrombosis; injection halted before foam entered deep posterior tibial veins. Local compression applied.", 1, "Immediate walking encouraged; compression bandage applied.", "Check for local skin blanching or pain q30m x 1h.", "Duplex ultrasound at 2 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["Deep venous thrombosis", "Skin ulceration", "Phlebitis"], "consent-venous-sclerotherapy", "caprini_vte"),

    # 7. Incompetent Perforator Vein Cyanoacrylate Glue Embolization
    ("cat10-perforator-glue", "Incompetent Perforator Vein Cyanoacrylate Glue Embolization", "Varicose Vein Embolization", "1849-VS013A", "I83.0", 22000, "US", ["Incompetent Perforator Vein Trunk"], "Direct percutaneous puncture under ultrasound", "20G / 21G Needle or 4F Micro-sheath", "2.0F microcatheter, 0.014\" wire, 5% Dextrose flush, n-BCA glue", "2.0F microcatheter", "n-Butyl Cyanoacrylate (n-BCA) Glue / Histoacryl + Lipiodol (1:1 ratio)", "Indicated for recalcitrant venous stasis ulcer overlying incompetent perforator vein. High-frequency ultrasound mapped fascial defect. 20G needle entered perforator trunk. 2.0F microcatheter advanced just superficial to deep fascia. Microcatheter flushed with D5W. Under continuous ultrasound surveillance, 0.3 mL of n-BCA glue + Lipiodol (1:1 ratio) delivered into perforator lumen. Immediate ultrasound transducer compression applied over the site for 60 seconds. Repeat duplex confirmed permanent solid echogenic cast obliterating the perforator with patent deep calf veins. Puncture site dressed.", 1, "Immediate ambulation; compression wrap applied over ulcer.", "Check puncture site and ulcer dressing q30m x 1h.", "Duplex ultrasound at 1 week.", "Oral fluids.", ["Tab Paracetamol 650mg SOS", "Ulcer local care kit"], ["Deep vein glue migration / DVT", "Local foreign body reaction", "Tender granuloma"], "consent-venous-sclerotherapy", "caprini_vte"),

    # 8. Varicose Vein Embolization using Microcoils
    ("cat10-varicose-embolization-microcoils", "Varicose Vein Embolization using Microcoils", "Varicose Vein Embolization", "1849-VS013A", "I83.9", 25000, "XA", ["Pelvic Escape Point Varices", "Saphenous Stump Collaterals"], "Retrograde Transfemoral or Direct Percutaneous Access under US/Fluoro", "4F - 5F Sheath", "5F Cobra, 2.7F microcatheter, 0.014\" wire, detachable fibered microcoils", "2.7F microcatheter", "Detachable Fibered Microcoils (0.018\", 4-8mm)", "Indicated for recurrent varicose veins arising from pelvic venous leak (obturator/pudendal escape points) or complex tortuous tributary lakes. Sheath placed. 2.7F microcatheter navigated directly into refluxing feeder vein. Selective varicography mapped outflow. Multiple 0.018\" detachable fibered platinum microcoils deployed forming dense mechanical occlusion scaffold. Flow stasis achieved with no reflux on completion run.", 2, "Bedrest x 2 hours.", "Monitor access site and distal perfusion q30m x 2h.", "Duplex ultrasound at 2 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["Coil migration", "Superficial phlebitis", "Puncture hematoma"], "consent-venous-ablation", "caprini_vte"),

    # 9. Varicose Vein Embolization using Cyanoacrylate Glue
    ("cat10-varicose-embolization-glue", "Varicose Vein Embolization using Cyanoacrylate Glue (n-BCA)", "Varicose Vein Embolization", "1849-VS013A", "I83.9", 24000, "XA", ["Recurrent Varicose Vein Nidus", "Incompetent Tributary Veins"], "Direct percutaneous puncture under ultrasound or transcatheter", "4F Sheath or 20G Needle", "2.7F microcatheter, 0.014\" wire, D5W non-ionic flush", "2.7F microcatheter", "n-BCA Cyanoacrylate Glue + Lipiodol (1:2 ratio)", "Puncture of dominant varicose tributary under ultrasound. 2.7F microcatheter advanced into nidus. D5W flush administered. Under fluoroscopy, 1.5 mL of n-BCA cyanoacrylate glue mixed with Lipiodol (1:2 ratio) slowly injected until total cast formed obliterating the variceal complex. Microcatheter swiftly withdrawn. Duplex confirmed complete absence of flow in treated varices.", 2, "Bedrest x 2 hours.", "Check puncture site and distal pulses q30m x 2h.", "Duplex ultrasound at 2 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["Glue migration into deep venous system", "Local inflammatory phlebitis", "Skin pigmentation"], "consent-venous-ablation", "caprini_vte"),

    # 10. Varicose Vein Embolization using Combined Coils Plus Glue
    ("cat10-varicose-embolization-coils-glue", "Varicose Vein Embolization using Combined Microcoils Plus Cyanoacrylate Glue", "Varicose Vein Embolization", "1849-VS013A", "I83.9", 30000, "XA", ["High-Flow Variceal Tributaries", "Aneurysmal Saphenous Collaterals"], "Direct ultrasound puncture or Transfemoral approach", "5F Sheath", "5F Cobra, 2.7F microcatheter, 0.014\" wire, microcoils (4-8mm), D5W flush", "2.7F microcatheter", "Detachable Microcoils + n-BCA Cyanoacrylate Glue / Lipiodol (1:2 ratio)", "For high-flow aneurysmal varicose tributaries where glue alone risks deep venous migration. 2.7F microcatheter navigated to target segment. Distal mechanical flow barrier created using three 0.018\" fibered microcoils. Following non-ionic D5W flush, 1.5 mL of n-BCA glue + Lipiodol delivered behind coil nest. Glue rapidly polymerized within the coil matrix creating an impervious, permanent plug. Total occlusion confirmed on completion run.", 2, "Bedrest x 2 hours.", "Site check and pulse check q30m x 2h.", "Duplex ultrasound at 2 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["Phlebitis", "Coil/glue migration", "Hematoma"], "consent-venous-ablation", "caprini_vte"),

    # 11. Iliofemoral DVT Catheter-Directed Thrombolysis (CDT)
    ("cat10-dvt-cdt", "Iliofemoral Deep Vein Thrombosis (DVT) Catheter-Directed Thrombolysis", "Thrombolysis", "1849-VS005A", "I80.2", 28000, "XA", ["Iliac Vein", "Common Femoral Vein", "Femoral Vein"], "Ipsilateral Popliteal Vein Puncture under ultrasound", "6F 11cm Sheath", "0.035\" Glidewire, 5F multi-sidehole infusion catheter (Cragg-McNamara 20-30cm)", "N/A", "Alteplase (rtPA) continuous infusion", "Indicated for extensive acute iliofemoral DVT (phlegmasia cerulea dolens). Ipsilateral popliteal vein punctured under US; 6F sheath placed. Venography showed occlusive thrombus spanning from popliteal vein through common iliac vein into IVC. Glidewire crossed into IVC. Multi-sidehole catheter embedded within thrombus. Bolus rtPA (5mg) delivered, followed by continuous infusion at 0.5 - 1.0 mg/hr with IV unfractionated heparin (500 units/hr). Check venogram at 18 hours demonstrated complete clot lysis revealing severe underlying May-Thurner left common iliac compression, subsequently stented.", 6, "Strict ICU bedrest; leg elevated 15 degrees.", "Monitor puncture site, limb circumference, and fibrinogen levels q2h.", "Check venography at 12-24 hours.", "IV Normal Saline 75 mL/hr.", ["rtPA protocol", "IV Heparin", "Analgesia"], ["Major hemorrhage / retroperitoneal hematoma", "Pulmonary embolism", "Intracranial bleeding"], "consent-dvt-thrombectomy", "caprini_vte"),

    # 12. May-Thurner Stenting
    ("cat10-may-thurner-stenting", "May-Thurner Syndrome Balloon Angioplasty & Dedicated Venous Stenting", "Venous Stenting", "1849-VS014A", "I87.1", 42000, "XA", ["Left Common Iliac Vein", "IVC Confluence"], "Left Popliteal or Left CFV Access", "9F - 10F 45cm Sheath", "0.035\" stiff Glidewire, 12mm-16mm PTA balloon, dedicated venous stent (Venovo / Abre 14-16mm x 60-90mm)", "N/A", "14mm - 16mm x 80mm Dedicated Self-Expanding Nitinol Venous Stent", "Indicated for extrinsic compression of left common iliac vein by right common iliac artery against lumbar spine. Access via left CFV/popliteal. Venogram in 30° RAO projection showed high-grade compression of left CIV with extensive pelvic collateralization. Pull-through gradient was 8 mmHg. Lesion pre-dilated with 12mm balloon. A 14mm x 80mm dedicated Nitinol venous stent (Abre / Venovo) deployed with 3-5mm extension into IVC. Post-dilated with 14mm non-compliant balloon. Completion venogram demonstrated full stent expansion, brisk inline venous drainage into IVC, zero collateral runoff, and normalization of pressure gradient to 0 mmHg.", 6, "Strict flat bedrest x 6 hours; left leg straight.", "Monitor access site, distal pulses, and left thigh circumference q15m x 1h, q30m x 2h, then q1h.", "Venous Duplex Ultrasound at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Therapeutic Anticoagulation: Enoxaparin 1mg/kg BD bridging to DOAC (Rivaroxaban / Apixaban) x 6-12 months"], ["In-stent thrombosis", "Contralateral iliac vein obstruction by stent overhang", "Groin hematoma"], "consent-venous-stenting", "caprini_vte"),

    # 13. IVC Filter Placement
    ("cat10-ivc-filter-placement", "Inferior Vena Cava (IVC) Filter Placement (Infrarenal)", "IVC Filter Placement", "1849-VS016A", "I82.9", 25000, "XA", ["Infrarenal Inferior Vena Cava"], "Right IJV or Right CFV under ultrasound", "6F - 8.5F Filter Delivery Sheath", "0.035\" J-wire, 5F Pigtail with radiopaque marker increments, Retrievable IVC Filter (Cook Celect / Bard Denali / Cordis TrapEase)", "N/A", "Retrievable Nitinol IVC Filter (Cook Celect / Bard Denali)", "Indicated for acute DVT/PE with absolute contraindication to anticoagulation (recent ICH / GI bleed). Right IJV accessed; 5F pigtail placed in distal IVC. Inferior vena cavogram documented: patent IVC lumen, normal caliber (diameter 19mm, <28mm limit), absence of duplication/circumaortic renal collar, and lowest renal vein inflow level (L1-L2). 8.5F delivery sheath positioned. Retrievable IVC filter deployed with filter apex centered and aligned precisely at or immediately below lowest renal vein margin. Cavogram confirmed symmetrical filter expansion, zero tilt (<5 degrees), and intact hook.", 2, "Bedrest x 2 hours (neck access) or 4 hours (femoral).", "Monitor puncture site q15m x 1h, then q30m.", "Plain Abdominal Radiograph at 24h to document baseline filter position.", "Oral fluids.", ["Resume therapeutic anticoagulation as soon as primary contraindication resolves", "Tab Paracetamol 650mg SOS"], ["Filter tilt / migration", "IVC perforation", "Filter thrombosis / bilateral leg edema"], "consent-ivc-filter", "caprini_vte"),

    # 14. IVC Filter Retrieval
    ("cat10-ivc-filter-retrieval", "Percutaneous IVC Filter Retrieval (Standard / Complex)", "IVC Filter Retrieval", "1849-VS017A", "Z98.890", 28000, "XA", ["Infrarenal IVC", "Right IJV"], "Right Internal Jugular Vein (IJV) under US", "9F - 11F 45cm Long Retrieval Sheath", "5F Cobra, 10mm-15mm Gooseneck Snare / Loop Snare, 0.035\" stiff wire", "N/A", "N/A", "Right IJV accessed; 9F sheath placed. Preliminary inferior vena cavogram confirmed absence of significant thrombus burden within filter basket (<25% cone volume). Gooseneck snare manipulated under fluoroscopy to engage retrieval hook of filter. Sheath advanced over hook while maintaining steady tension. Filter collapsed smoothly into retrieval sheath and withdrawn intact. Repeat cavogram showed widely patent IVC without extravasation or luminal narrowing.", 2, "Bedrest x 2 hours.", "Neck site check and vitals monitoring q15m x 1h, then q30m.", "None routine.", "Oral hydration.", ["Continue indicated oral anticoagulation"], ["IVC wall tear / hemorrhage", "Filter strut fracture / embolization", "Neck hematoma"], "consent-ivc-filter", "caprini_vte"),

    # 15. SVC Stenting
    ("cat10-svc-stenting", "Superior Vena Cava (SVC) Syndrome Balloon Angioplasty & Dedicated Stenting", "Venous Stenting", "1849-VS014A", "I87.1", 38000, "XA", ["Superior Vena Cava", "Right / Left Innominate Veins", "Right Atrium"], "Right CFV and/or Right Basilic / Brachial Vein", "10F - 12F Sheath", "0.035\" stiff Glidewire, 10mm-14mm balloon, 14mm-18mm x 60-80mm Self-Expanding Stent (Wallstent / Abre)", "N/A", "16mm x 60mm Self-Expanding Venous Stent", "Emergency intervention for life-threatening SVC syndrome (facial edema, orthopnea, cerebral venous congestion due to lung malignancy). Right CFV accessed. Cavography revealed high-grade SVC stenosis with extensive azygos collateral flow. Wire crossed stricture into innominate vein. Pre-dilated with 10mm balloon. 16mm x 60mm self-expanding stent deployed spanning from innominate vein to cavoatrial junction. Post-dilated to 14mm. Immediate rapid inline venous return to right atrium demonstrated with dramatic reduction in collateral filling.", 4, "Head-of-bed elevated 30-45 degrees; bedrest x 4 hours.", "Monitor facial swelling, respiratory status, and groin access site q15m x 1h, q30m x 2h, then q1h.", "Chest Radiograph at 24 hours.", "IV Normal Saline 75 mL/hr.", ["IV Dexamethasone 8mg BD", "Therapeutic LMWH Enoxaparin 1mg/kg BD"], ["Stent migration into right atrium", "SVC rupture / pericardial tamponade", "Acute pulmonary edema (preload surge)"], "consent-venous-stenting", "caprini_vte"),

    # 16. Pulmonary Embolism CDT (EKOS)
    ("cat10-pe-cdt-ekos", "Acute Pulmonary Embolism Ultrasound-Accelerated Thrombolysis (EKOS)", "Thrombolysis", "1849-VS005A", "I26.9", 45000, "XA", ["Main Pulmonary Artery", "Right and Left Pulmonary Arteries"], "Right Common Femoral Vein under ultrasound", "Dual 6F 45cm Sheaths", "0.035\" stiff wire, 5F Grollman / Berman catheter, Dual EKOS Acoustic Pulse Thrombolysis Catheters (12cm treatment zone)", "N/A", "Alteplase (rtPA) + Ultrasound Acoustic Core", "Indicated for submassive/massive acute pulmonary embolism with RV dysfunction (RV/LV ratio >0.9, elevated troponin). Right CFV accessed. Pulmonary angiogram and baseline pulmonary arterial pressures recorded (PAP 58/28, mean 38 mmHg). EKOS catheters navigated bilaterally into right and left main pulmonary arteries. Ultrasound cores inserted. Low-dose rtPA initiated at 0.5 mg/hr per catheter with ultrasound acoustic energy delivery for 12 hours. Patient transferred to ICU. Post-lysis PAP decreased to mean 22 mmHg with dramatic RV recovery on echocardiogram.", 6, "Strict ICU bedrest during infusion.", "Monitor vitals, SpO2, bleeding, and neurological status q1h.", "Check echocardiogram and follow-up CTPA at 24-48 hours.", "IV Normal Saline titrated to maintain CVP 8-12 mmHg.", ["rtPA infusion protocol", "Unfractionated heparin protocol"], ["Major bleeding / intracranial hemorrhage", "Pulmonary artery rupture", "Arrhythmia"], "consent-pe-thrombectomy", "pesi_score"),
]

# ==============================================================================
# CATEGORY 11: Dialysis Access & Central Venous (29 Procedures)
# ==============================================================================
CAT11_LIST = [
    ("cat11-permacath-insertion", "Right IJV Tunnelled Cuffed Hemodialysis Catheter (Permacath) Placement", "Tunnelled Dialysis Catheter (Permacath)", "1849-IN064A", "N18.6", 15000, "XA", ["Right Internal Jugular Vein", "Cavoatrial Junction"], "Right IJV puncture under ultrasound + Anterior chest wall exit site", "Dual-lumen peel-away sheath (14F - 16F)", "18G needle, 0.035\" J-wire, vascular tunneler, 14.5F 19-23cm Permacath", "N/A", "14.5F 19cm/23cm Cuffed Dual-Lumen Tunnelled Catheter (Ash Split / Palindrome)", "Right IJV accessed under real-time ultrasound; 0.035\" J-wire positioned in IVC. Subcutaneous tunnel created over right anterior chest wall with tunneler. Permacath pulled through tunnel placing Dacron cuff 2 cm inside subcutaneous tunnel from exit site. 15F peel-away sheath introduced into IJV. Catheter advanced through peel-away sheath under fluoroscopy, positioning tip precisely in mid right atrium. Both lumens aspirated with brisk flow (>350 mL/min) and flushed with heparin lock solution. Sheath peeled away. Suture closure of puncture and exit sites.", 2, "Bedrest x 2 hours; head elevated 30 degrees.", "Inspect neck puncture and chest tunnel exit site for hematoma or oozing q30m x 2h.", "Erect Chest X-ray at 2 hours to confirm catheter tip position at mid right atrium and rule out pneumothorax.", "IV fluids as clinically required by nephrology.", ["Heparin lock solution instilled in catheter lumens (volume per lumen printed on hub)", "Tab Paracetamol 650mg SOS"], ["Catheter-related bloodstream infection", "Air embolism", "Pneumothorax / hemothorax", "Catheter kinking"], "consent-dialysis-access", None),
    ("cat11-avf-fistulogram-angioplasty", "Diagnostic Fistulogram & High-Pressure Balloon Angioplasty for Dysfunctional AVF", "Percutaneous Transluminal Angioplasty (PTA)", "1849-VS001A", "T82.8", 18000, "XA", ["Arteriovenous Fistula Outflow Vein", "Anastomosis", "Juxta-anastomotic Segment"], "Antegrade / Retrograde direct puncture of AVF vein under US", "6F Vascular Sheath", "0.035\" stiff Glidewire, 5mm - 8mm x 40mm High-Pressure PTA Balloon (Conquest / Dorado 20-30 atm)", "N/A", "High-Pressure PTA Balloon", "Indicated for elevated venous dialysis pressures and prolonged post-cannulation bleeding in radiocephalic AVF. AVF vein accessed with 6F sheath. Diagnostic fistulography demonstrated a critical 85% stenosis in the juxta-anastomotic cephalic vein segment with significant collaterals. 0.035\" Glidewire crossed lesion into brachial artery. 6mm x 40mm ultra-high-pressure balloon inflated to 26 atm for 90 seconds until balloon waist completely effaced. Completion angiogram showed excellent luminal restoration (>90% caliber), elimination of pressure gradient, and vigorous palpable thrill. Sheath removed; purse-string suture hemostasis.", 2, "Keep access arm elevated on pillow for 2 hours; do NOT bend arm.", "Check puncture site and palpate AVF thrill q15m x 1h, then q30m x 2h.", "Duplex ultrasound if loss of thrill.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["AVF rupture / hematoma", "Acute thrombosis / loss of thrill", "Pseudoaneurysm"], "consent-fistula-angioplasty", None),
    ("cat11-central-venous-stenting", "Central Venous Stenosis (CVS) Dedicated Stenting for Failing AVF", "Venous Stenting", "1849-VS014A", "I87.1", 35000, "XA", ["Innominate Vein", "Subclavian Vein", "SVC"], "Transfemoral or via AVF Sheath Access", "8F - 10F Sheath", "0.035\" stiff wire, 12mm-14mm x 60mm self-expanding bare / covered stent (Fluency / Abre)", "N/A", "12mm x 60mm Self-Expanding Stent", "Indicated for massive ipsilateral arm edema and AVF dysfunction due to chronic central venous catheter stenosis of left innominate vein. Retrograde traversal of high-grade innominate vein stricture. Pre-dilated with 10mm balloon. 12mm x 60mm self-expanding dedicated stent deployed across stricture. Post-dilated to 12mm. Rapid inline drainage into SVC established with immediate decompression of arm collaterals. Dialysis flow restored.", 4, "Bedrest x 4 hours.", "Arm check and vitals q30m x 2h.", "Duplex at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Therapeutic anticoagulation if indicated"], ["Stent migration", "Central vein rupture", "Re-stenosis"], "consent-venous-stenting", None),
]

# ==============================================================================
# CATEGORY 12: Lymphatics (16 Procedures)
# ==============================================================================
CAT12_LIST = [
    ("cat12-intranodal-lymphangiography", "Ultrasound-Guided Intranodal Lymphangiography with Lipiodol", "Lymphangiography", "1849-IN065A", "I89.8", 18000, "XA", ["Bilateral Inguinal Lymph Nodes", "Cisterna Chyli", "Thoracic Duct"], "Bilateral superficial inguinal lymph node hilum under ultrasound", "25G - 27G Butterfly Needle", "High-frequency ultrasound probe, infusion pump, Lipiodol Ultra-Fluid (10-15 mL)", "N/A", "Ethiodized Oil (Lipiodol Ultra-Fluid)", "Indicated for localization of high-output chylothorax or chylous ascites. High-frequency ultrasound identified bilateral superficial inguinal lymph nodes. 25G butterfly needle advanced under real-time ultrasound into the transitional zone between cortex and hilum. Injection of Lipiodol at 0.2 - 0.4 mL/min using dedicated infusion pump. Serial fluoroscopy tracked opacification of iliac lymphatics, cisterna chyli (at L1-L2), and thoracic duct. Pathological chylous leak identified at mid-thoracic level.", 4, "Strict flat bedrest x 4 hours.", "Inspect bilateral groin puncture sites q30m x 2h.", "Erect Chest Radiograph at 4 hours to verify thoracic duct anatomy and rule out pulmonary oil embolization.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["Pulmonary oil microembolization / hypoxia", "Hypersensitivity to Lipiodol", "Groin lymphocele"], "consent-lymphangiography", None),
    ("cat12-thoracic-duct-embolization", "Thoracic Duct Cannulation & Embolization with Microcoils and Onyx / Glue", "Percutaneous Lymphatic Embolization", "1849-IN063A", "I89.8", 45000, "XA", ["Cisterna Chyli", "Thoracic Duct Trunk"], "Transabdominal anterior puncture under fluoroscopic roadmapping", "21G 15cm Chiba Needle", "0.014\" microguidewire, 2.0F - 2.4F microcatheter, microcoils (2-4mm), Onyx 18 or n-BCA glue", "2.0F microcatheter", "Detachable Microcoils (2-3mm) + Liquid Embolic (Onyx 18 / n-BCA)", "Indicated for intractable high-output traumatic/iatrogenic chylothorax (>1000 mL/day). Following intranodal Lipiodol opacification, cisterna chyli and retroperitoneal lymphatics visualized at L1-L2. Transabdominal puncture performed with 21G Chiba needle directly into cisterna chyli under biplane fluoroscopy. 0.014\" microguidewire manipulated cephalad into main thoracic duct. 2.0F microcatheter advanced past aortic hiatus to just below leak level. Thoracic ductogram delineated exact disruption. Microcatheter positioned; multiple 2mm-3mm detachable microcoils deployed followed by Onyx-18 / n-BCA liquid embolic cast. Completion lymphangiogram showed complete occlusion of duct without further mediastinal extravasation. Chest tube output dropped to zero within 24 hours.", 6, "Strict supine flat bedrest x 6 hours.", "Monitor vitals, puncture site, and chest tube drainage q30m x 2h, then q1h.", "Erect Chest X-ray at 2 to 4 hours post-procedure to monitor pneumothorax/hemothorax.", "IV Normal Saline 75-100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Paracetamol 650mg TDS"], ["Pneumothorax", "Bowel perforation", "Non-target glue/Onyx migration"], "consent-lymphatic-embolization", None),
]

def generate_cat08_to_12():
    # Cat 08
    procs08 = []
    for item in CAT08_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs08.append(create_proc(pid, 8, "Interventional Oncology Transcatheter Therapies", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with IV Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category08_io_transcatheter.ts", "CATEGORY_08_IO_TRANSCATHETER", 8, "Interventional Oncology Transcatheter Therapies", procs08)

    # Cat 09
    procs09 = []
    for item in CAT09_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs09.append(create_proc(pid, 9, "Interventional Oncology Percutaneous Ablation", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category09_io_ablation.ts", "CATEGORY_09_IO_ABLATION", 9, "Interventional Oncology Percutaneous Ablation", procs09)

    # Cat 10
    procs10 = []
    for item in CAT10_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs10.append(create_proc(pid, 10, "Venous Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia / Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category10_venous.ts", "CATEGORY_10_VENOUS", 10, "Venous Interventions", procs10)

    # Cat 11
    procs11 = []
    for item in CAT11_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs11.append(create_proc(pid, 11, "Central Venous Access & Hemodialysis", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category11_dialysis_access.ts", "CATEGORY_11_DIALYSIS_ACCESS", 11, "Central Venous Access & Hemodialysis", procs11)

    # Cat 12
    procs12 = []
    for item in CAT12_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs12.append(create_proc(pid, 12, "Lymphatic Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category12_lymphatics.ts", "CATEGORY_12_LYMPHATICS", 12, "Lymphatic Interventions", procs12)

if __name__ == "__main__":
    generate_cat08_to_12()
