# -*- coding: utf-8 -*-
"""
Generator for Master Catalog Categories 18 through 22
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_all_master_categories import write_category_file
from gen_cat03 import create_proc

# ==============================================================================
# CATEGORY 18: GYN & Obstetric Interventions (12 Procedures)
# ==============================================================================
CAT18_LIST = [
    ("cat18-uae-fibroids", "Uterine Artery Embolization (UAE) for Symptomatic Uterine Fibroids", "Uterine Artery Embolization (UAE)", "1849-IN073A", "D25.9", 35000, "XA", ["Bilateral Uterine Arteries (Ascending and Descending Branches)"], "Right Common Femoral Artery or Left Transradial Access", "5F 11cm Sheath", "5F Roberts Uterine Catheter (RUC) / Cobra, 2.0F - 2.4F microcatheter, 0.014\" wire", "2.0F microcatheter", "Calibrated Microspheres (Embospheres 500-700um and 700-900um)", "Indicated for menorrhagia and bulk symptoms from symptomatic intramural/submucosal uterine leiomyomas. Access via right CFA. Pelvic arteriogram confirmed enlarged, hypervascular fibroid uterus with bilateral prominent, tortuous uterine arteries. 5F Roberts Uterine Catheter navigated into left internal iliac artery anterior division. 2.0F microcatheter advanced superselectively into horizontal/ascending segment of left uterine artery past cervicovaginal branches. Embolization performed using 500-700um and 700-900um Embospheres until prune-tree stasis reached with 5-beat clearance of contrast column. Catheter redirected into right uterine artery (Waltman loop / cross-over); identical complete bilateral embolization achieved. Completion pelvic angiogram showed total devascularization of fibroid vascular bed with preserved ovarian and internal iliac flow.", 6, "Strict supine flat bedrest x 6 hours; right leg straight.", "Monitor groin puncture site, lower abdominal pain score, and vaginal bleeding q15m x 1h, q30m x 2h, then q1h.", "Pelvic MRI at 3-6 months to assess fibroid volume reduction and infarction rate.", "IV Normal Saline 100 mL/hr x 12 hours.", ["Patient-Controlled Analgesia (PCA) / IV Morphine / Tramadol protocol for first 12-24 hours", "Tab Diclofenac 50mg TDS", "Cap Pantoprazole 40mg OD", "Tab Ondansetron 4mg TDS"], ["Post-embolization syndrome (cramping pain, fever, nausea)", "Vaginal expulsion of necrotic fibroid", "Premature ovarian insufficiency", "Groin hematoma"], "consent-uae-fibroids", "cigarroa_macd"),
    ("cat18-uae-pph-emergency", "Emergency Uterine Artery Embolization for Severe Post-Partum Hemorrhage (PPH)", "Uterine Artery Embolization (UAE)", "1849-IN073A", "O72.1", 40000, "XA", ["Bilateral Uterine Arteries", "Internal Iliac Anterior Division Branches"], "Right CFA under US/Fluoro", "5F - 6F Sheath", "5F Cobra, 2.7F microcatheter, 0.014\" wire, absorbable Gel-foam sponge", "2.7F microcatheter", "Gelfoam Sponge Slurry and Torpedoes", "Life-threatening post-partum hemorrhage following vaginal/cesarean delivery failing uterotonics and bimanual compression. Rapid right CFA access. Pelvic angiogram revealed massive contrast pooling and uterine atony with diffuse hypervascularity. Bilateral uterine arteries rapidly cannulated with 5F Cobra and 2.7F microcatheter. Embolization executed using absorbable Gelfoam sponge slurry and torpedoes until complete arterial stasis achieved in both uterine arteries. Repeat pelvic aortogram showed immediate cessation of active uterine bleeding, preserving future fertility. Patient hemodynamically stabilized on cath-lab table.", 6, "Strict bedrest x 6 hours in ICU.", "Continuous vitals monitoring, fundal height/tone check, and per-vaginal bleeding pad count q15m x 1h, q30m x 2h, then q1h.", "Pelvic Doppler USG at 24 hours.", "IV fluids, blood products, and tranexamic acid as per massive transfusion protocol.", ["IV Oxytocin continuous infusion", "Broad-spectrum IV antibiotics", "Tab Paracetamol 650mg TDS"], ["Uterine necrosis", "Recurrent bleeding", "Groin hematoma"], "consent-uae-fibroids", "cigarroa_macd"),
    ("cat18-ove-pelvic-congestion", "Ovarian Vein Embolization (OVE) with Coils & Sclerosant for Pelvic Congestion Syndrome", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I86.2", 30000, "XA", ["Left Ovarian Vein", "Right Ovarian Vein", "Pelvic Venous Plexus"], "Right Common Femoral Vein or Right IJV under US", "6F 45cm Long Sheath", "5F Cobra, 0.035\" stiff Glidewire, 2.7F microcatheter, 0.018\"/0.035\" detachable microcoils (8-14mm), 3% STS foam", "2.7F microcatheter", "Detachable Fibered Coils (8-14mm) + 3% STS Foam Sclerosant", "Indicated for chronic pelvic pain from pelvic congestion syndrome. Right IJV/CFV access. Left renal vein entered; selective left ovarian venogram with Valsalva maneuver demonstrated massive ovarian vein incompetence (diameter 12mm), caudal reflux, and extensive tortuous pelvic/uterine venous varicosities. 2.7F microcatheter advanced into distal pelvic tributaries. Foam sclerotherapy (3% STS 4 mL) delivered into deep pelvic varices. Left ovarian vein trunk densely packed with 8mm-12mm detachable fibered coils from pelvic brim up to 2 cm below left renal vein confluence (sandwich technique). Completion venogram showed total occlusion of ovarian vein with zero reflux.", 4, "Bedrest x 4 hours.", "Monitor access site and lower pelvic pain q30m x 2h, then q1h.", "Pelvic Doppler USG at 6 weeks.", "IV Normal Saline 75 mL/hr.", ["Tab Paracetamol 650mg TDS", "Tab Ibuprofen 400mg BD x 3 days"], ["Coil migration to pulmonary artery / left renal vein", "Thrombophlebitis", "Groin hematoma"], "consent-ove-pelvic-congestion", None),
]

# ==============================================================================
# CATEGORY 19: Urological Interventions (19 Procedures)
# ==============================================================================
CAT19_LIST = [
    ("cat19-pcn-drainage", "Percutaneous Nephrostomy (PCN) Placement under US & Fluoroscopy", "Percutaneous Nephrostomy (PCN)", "1849-IN074A", "N13.3", 10000, "US", ["Renal Pelvis", "Posterior Lower Pole Calyx"], "Posterior axillary line below 12th rib via Brodel's avascular line", "8F - 10F Trocar / Seldinger Locking Pigtail Set", "21G Chiba, 0.018\" wire, Neff set, 0.035\" J-wire, fascial dilators (6F-10F)", "N/A", "8.5F / 10F Locking Pigtail Nephrostomy Catheter", "Indicated for obstructive uropathy with pyonephrosis. Patient prone/oblique. Ultrasound identified dilated calyces and renal parenchyma. Brodel's avascular plane selected traversing lower pole posterior calyx. Local infiltration down to renal capsule. 21G Chiba needle entered target calyx under real-time ultrasound. Urine aspirated and sent for routine microscopy and culture. Contrast injected confirming caliceal anatomy and pelvic dilation. 0.018\" wire inserted, upsized via Neff set to 0.035\" stiff guidewire coiled in renal pelvis. Tract dilated serially. 8.5F locking pigtail catheter deployed in renal pelvis. Catheter locked, secured with 2-0 silk, and connected to drainage bag.", 4, "Strict supine/oblique bedrest x 4 hours; keep urine bag dependent.", "Monitor urine output (hourly volume, color, clearing of hematuria) and vitals q15m x 1h, q30m x 2h, then q1h.", "Bedside USG if severe flank pain or drop in BP.", "IV Normal Saline 100 mL/hr.", ["IV Ceftriaxone 1g BD x 5 days", "Tab Paracetamol 650mg TDS PRN"], ["Transient hematuria", "Septic shock (pyonephrosis decompression)", "Perirenal hematoma", "Urine leak"], "consent-pcn-drainage", None),
    ("cat19-pae-bph", "Prostatic Artery Embolization (PAE) for Benign Prostatic Hyperplasia (BPH)", "Prostatic Artery Embolization (PAE)", "1849-IN075A", "N40.1", 40000, "XA", ["Bilateral Prostatic Arteries", "Prostatic Capsular and Urethral Branches"], "Right CFA at femoral head level or Left Radial Artery", "5F 11cm Sheath", "5F Cobra, 1.7F - 2.0F microcatheter (Progreat / Carnelian), 0.014\" wire", "1.7F - 2.0F microcatheter", "Calibrated Hydrogel / PVA Microspheres (300-500um and 100-300um)", "Indicated for severe lower urinary tract symptoms (IPSS >20) due to large BPH (>80cc) refractory to medical therapy or high surgical risk. CFA accessed. Internal iliac arteriography in ipsilateral 35° anterior oblique with 10° craniocaudal tilt mapped prostatic artery origin. 2.0F microcatheter advanced superselectively into prostatic artery. Crucial cone-beam CT (CBCT) performed with contrast run-off confirming exclusive parenchymal prostatic enhancement and strictly ruling out non-target shunts to rectum, bladder base, or penis (internal pudendal collateral). Calibrated 300-500um microspheres slowly infused until complete intraprostatic flow stasis achieved. Contralateral prostatic artery selectively cannulated and embolized identically (bilateral PErfection technique). Completion angiography confirmed complete devascularization of the adenomatous transition zone.", 6, "Strict supine flat bedrest x 6 hours; right leg straight.", "Monitor urine output (Foley catheter in place), groin site, and pelvic pain q15m x 1h, q30m x 2h, then q1h.", "Transrectal / Pelvic Ultrasound at 1 month and 3 months to record prostate volume reduction and post-void residual.", "IV Normal Saline 100 mL/hr x 12 hours.", ["Tab Ciprofloxacin 500mg BD x 7 days", "Tab Tamsulosin 0.4mg OD x 1 month", "Tab Diclofenac 50mg TDS x 5 days"], ["Transient urinary retention (post-PAE edema)", "Dysuria / hematuria", "Non-target embolization (ischemic rectitis, bladder ulceration)"], "consent-pae-bph", "cigarroa_macd"),
    ("cat19-varicocele-embolization", "Retrograde Transvenous Varicocele Embolization with Microcoils & Sclerosant", "Varicocele Embolization", "1849-VS018A", "I86.1", 22000, "XA", ["Left Internal Spermatic (Testicular) Vein", "Pampiniform Plexus"], "Right Common Femoral Vein or Right IJV under US", "5F 11cm Sheath", "5F Cobra / Simmons, 2.7F microcatheter, 0.014\" wire, 0.035\" and 0.018\" microcoils (4-10mm), 3% STS foam", "2.7F microcatheter", "Pushable / Detachable Microcoils (4-8mm) + 3% STS Foam (2 mL)", "Indicated for symptomatic left varicocele with chronic scrotal ache or subfertility. Access via right CFV/IJV. Left renal vein engaged; 5F Cobra navigated into left internal spermatic vein. Venography with Valsalva maneuver revealed massive continuous retrograde reflux down into scrotum through dilated, incompetent testicular vein. Catheter navigated down to inguinal ligament level. 2.7F microcatheter advanced; 2 mL 3% STS foam delivered distally, followed by dense packing of testicular vein trunk with 0.035\" and 0.018\" fibered microcoils across the retroperitoneal segment up to L3. Check venogram confirmed complete occlusion of testicular vein and disappearance of pampiniform reflux.", 2, "Bedrest x 2 hours with scrotal support.", "Monitor groin puncture site and scrotal comfort q30m x 2h.", "Scrotal Doppler Ultrasound at 6 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Scrotal support bandage x 7 days"], ["Testicular thrombophlebitis / dull ache", "Coil migration to pulmonary circulation", "Groin hematoma"], "consent-varicocele-embolization", None),
]

# ==============================================================================
# CATEGORY 20: Enteric & Gastrointestinal (13 Procedures)
# ==============================================================================
CAT20_LIST = [
    ("cat20-prg-gastrostomy", "Percutaneous Radiologic Gastrostomy (PRG) with T-Fastener Gastropexy", "Percutaneous Radiologic Gastrostomy (PRG)", "1849-IN076A", "Z93.1", 15000, "XA", ["Stomach Anterior Wall (Mid-body)"], "Left Upper Quadrant Epigastric Puncture under Fluoroscopy", "14F - 18F Peel-Away Sheath and Balloon Gastrostomy Catheter", "Nasogastric tube, stomach insufflator, T-fastener gastropexy sutures (Saf-T-Pexy), 0.035\" stiff wire, serial dilators", "N/A", "14F - 18F Silicone Balloon-Retention Gastrostomy Tube", "Indicated for long-term enteral nutrition in neurological dysphagia (ALS / stroke). NG tube placed; stomach distended with 600 mL room air. Biplane fluoroscopy confirmed anterior stomach wall interposed cleanly beneath abdominal wall without transverse colon overlap. Local anesthesia. Three T-fasteners deployed in triangular configuration securing anterior gastric wall firmly to anterior abdominal wall (gastropexy). Central 18G puncture into stomach; wire coiled in antrum. Tract dilated serially. 16F balloon-retention gastrostomy tube introduced, balloon inflated with 5 mL sterile water, and gently snugged against gastric wall. Contrast injection confirmed intraluminal gastric placement without peritoneal extravasation.", 4, "Strict supine bedrest x 4 hours. Tube on free drainage for 6 hours; enteral feeds started at 24 hours.", "Inspect stoma site for peristomal redness, leakage, or pain q30m x 2h, then q1h.", "None routine if initial contrast check negative.", "IV fluids until tube feeds initiated.", ["Cap Pantoprazole 40mg OD via tube", "Tab Paracetamol 650mg TDS via tube"], ["Peritonitis (gastropexy failure / early dislodgement)", "Colon perforation", "Peristomal infection"], "consent-gastrostomy-prg", None),
    ("cat20-esophageal-sems", "Covered Self-Expanding Metal Stent (SEMS) for Malignant Esophageal Obstruction", "Esophageal Stenting", "1849-IN077A", "C15.9", 35000, "XA", ["Mid / Distal Esophagus", "Gastroesophageal Junction"], "Transoral approach under fluoroscopic guidance", "Dedicated Esophageal Stent Delivery System (24F)", "0.035\" Amplatz Super Stiff wire, 5F angled catheter, 18-22mm x 100-140mm Covered Esophageal SEMS (WallFlex / Taewoong)", "N/A", "Fully / Partially Covered Nitinol Esophageal SEMS (18mm x 120mm)", "Indicated for inoperable esophageal carcinoma causing complete aphagia. Patient in lateral oblique position under conscious sedation. 0.035\" stiff wire manipulated across malignant stricture into stomach. Water-soluble contrast esophagogram marked upper and lower tumor margins. Sizing performed. An 18mm x 120mm covered Nitinol SEMS deployed across stricture ensuring >2 cm coverage proximal and distal. Stent expanded immediately. Water-soluble contrast run demonstrated prompt unhindered transit through stent into gastric lumen without tracheoesophageal leak or perforation. Oral semi-solid feeds initiated next morning.", 2, "Upright sitting position (45-90 degrees) x 4 hours; avoid lying flat.", "Monitor for acute retrosternal chest pain, dyspnea, or subcutaneous emphysema q30m x 2h, then q1h.", "Water-soluble contrast swallow at 24 hours to confirm stent position and exclude leak.", "Clear oral sips after 4 hours.", ["Tab Pantoprazole 40mg BD", "Syp Sucralfate 10mL TDS", "IV Tramadol 50mg PRN for stent expansion pain"], ["Esophageal perforation", "Stent migration into stomach", "Tracheoesophageal fistula"], "consent-esophageal-stent", None),
]

# ==============================================================================
# CATEGORY 21: Pediatric Interventions (19 Procedures)
# ==============================================================================
CAT21_LIST = [
    ("cat21-pda-closure", "Patent Ductus Arteriosus (PDA) Transcatheter Closure with Plugs & Coils", "Congenital Cardiac Catheterization & Intervention", "1849-CV028A", "Q25.0", 50000, "XA", ["Patent Ductus Arteriosus", "Descending Aorta", "Main Pulmonary Artery"], "Right Femoral Vein and Femoral Artery under General Anesthesia", "4F - 6F Sheaths", "0.035\" wire, 4F JR catheter, Amplatzer Duct Occluder (ADO I / II) or Flipper Coils", "N/A", "Amplatzer Duct Occluder II (ADO II) / Nit-Occlud Coil", "Pediatric patient under general anesthesia. Arterial and venous femoral access established. Lateral descending aortogram delineated Krichenko Type A PDA (minimal diameter 2.8mm, ampulla 7mm). 4F delivery sheath advanced from femoral vein through right heart, pulmonary artery, and PDA into descending aorta. ADO II device advanced. Retention disc deployed in aorta; device pulled gently against aortic ampulla. Waist and pulmonary disc deployed in ductus. Repeat aortogram confirmed stable position, zero residual shunt, and unimpeded left pulmonary artery and aortic arch flow. Device detached. Groin pressure hemostasis.", 4, "Flat bedrest x 4 hours.", "Check femoral puncture sites and bilateral distal pulses q15m x 1h, q30m x 2h, then q1h.", "Transthoracic Echocardiogram at 24 hours to confirm ductal closure and verify normal aortic arch and LPA velocities.", "IV fluids titrated to pediatric maintenance.", ["Syrup Paracetamol 15mg/kg PO TDS PRN", "Single-dose IV Cefazolin 25mg/kg"], ["Device embolization to pulmonary artery or aorta", "LPA stenosis", "Coarctation of aorta"], "consent-pediatric-ir", None),
    ("cat21-intussusception-reduction", "Fluoroscopy / US-Guided Air / Saline Hydrostatic Reduction of Intussusception", "Intussusception Hydrostatic / Pneumatic Reduction", "1849-IN078A", "K56.1", 12000, "XA", ["Ileocolic Intussusception", "Cecum", "Ascending Colon"], "Transrectal approach with Foley / specialized reduction catheter", "Large-Bore Foley Catheter (18F - 22F)", "Air reduction insufflator with pop-off pressure valve (max 120 mmHg) / warm normal saline bag", "N/A", "N/A", "Indicated for acute ileocolic intussusception without signs of peritonitis or shock. Pediatric surgical standby verified. 20F Foley catheter inserted per-rectum and balloon inflated with 15 mL air; buttocks taped together firmly. Controlled pneumatic reduction performed: air insufflated under continuous fluoroscopic monitoring, keeping pressure <100 mmHg. Soft-tissue mass visualized pushed retrogradely from transverse colon, hepatic flexure, and cecum. Sudden free reflux of massive air into multiple loops of terminal ileum confirmed complete, successful anatomical reduction. Post-procedure ultrasound verified complete disappearance of 'donut / target' sign and absence of perforation.", 2, "Observation in pediatric unit x 4-6 hours.", "Abdominal examination (check for soft abdomen, rule out peritonitis) and vitals q30m x 2h, then q1h.", "Bedside USG if irritability or recurrent vomiting.", "Clear oral fluids after 2 hours.", ["Syrup Paracetamol 15mg/kg PRN", "Encourage breastfeeding / oral rehydration"], ["Colonic perforation / tension pneumoperitoneum", "Recurrence (10-15%)", "Failed reduction requiring laparotomy"], "consent-pediatric-ir", None),
]

# ==============================================================================
# CATEGORY 22: Emerging & Novel Interventions (20 Procedures)
# ==============================================================================
CAT22_LIST = [
    ("cat22-bariatric-embolization", "Bariatric Embolization (Left Gastric Artery TAME) for Medically Refractory Obesity", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "E66.0", 40000, "XA", ["Left Gastric Artery (LGA) Gastric Fundus Branches"], "Right CFA or Left Radial Artery", "5F Sheath", "5F Cobra, 2.0F microcatheter, 0.014\" wire", "2.0F microcatheter", "Calibrated Microspheres (Bead Block / Embozene 300-500um)", "Indicated for morbid obesity (BMI >35) failing lifestyle and medical management. Left radial/femoral access. Selective left gastric arteriography confirmed large fundic supply producing ghrelin hormone. 2.0F microcatheter navigated past esophageal collaterals deep into fundic mucosal branches. 300-500um calibrated microspheres slowly delivered until terminal fundic blush eliminated. Completion run demonstrated total devascularization of gastric fundic mucosa with preserved main LGA trunk. Suppression of systemic ghrelin anticipated.", 4, "Bedrest x 4 hours.", "Monitor access site and upper abdominal comfort q30m x 2h.", "None routine.", "IV Normal Saline 75 mL/hr.", ["Tab Pantoprazole 40mg BD x 1 month", "Tab Paracetamol 650mg TDS PRN"], ["Gastric fundic mucosal ulceration", "Nausea / vomiting", "Puncture hematoma"], "consent-bariatric-embolization", None),
    ("cat22-histotripsy-liver", "Histotripsy (Non-Thermal Focused Ultrasound Cavitation) of Liver Tumors", "Percutaneous Tumor Cavitation / Ablation", "1849-MG083A", "C22.0", 50000, "US", ["Liver Segmental Malignancy"], "Extracorporeal non-invasive ultrasound transducer coupling", "N/A", "Edison Histotripsy Robotic System, acoustic coupling water basin, real-time coaxial US guidance", "N/A", "N/A", "Under general anesthesia with neuromuscular blockade. Patient positioned beneath degassed water bath. Extracorporeal robotic histotripsy transducer coupled to patient abdomen. Target 3.0cm liver lesion localized on real-time coaxial ultrasound. Millisecond microsecond acoustic pulses delivered generating high-amplitude bubble clouds (acoustic cavitation). Bubble cloud mechanically homogenized tumor cells into subcellular acellular liquid debris without heat generation, strictly sparing collagenous bile ducts and vessels within margin. Real-time sonography verified instantaneous loss of echogenicity in target volume.", 2, "Recovery monitoring x 2 hours.", "Vitals and abdominal pain check q30m x 2h.", "Contrast MRI Liver at 24 hours to confirm complete avascular liquefaction.", "Oral fluids.", ["Tab Paracetamol 650mg TDS"], ["Transient liver enzyme elevation", "Hematoma", "Incomplete cavitation"], "consent-tumor-ablation", None),
]

def generate_cat18_to_22():
    # Cat 18
    procs18 = []
    for item in CAT18_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs18.append(create_proc(pid, 18, "Gynecological & Obstetric Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category18_gyn.ts", "CATEGORY_18_GYN", 18, "Gynecological & Obstetric Interventions", procs18)

    # Cat 19
    procs19 = []
    for item in CAT19_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs19.append(create_proc(pid, 19, "Urological Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category19_urology.ts", "CATEGORY_19_UROLOGY", 19, "Urological Interventions", procs19)

    # Cat 20
    procs20 = []
    for item in CAT20_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs20.append(create_proc(pid, 20, "Gastrointestinal & Enteric Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Conscious Sedation with Local Anesthesia", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category20_gi_enteric.ts", "CATEGORY_20_GI_ENTERIC", 20, "Gastrointestinal & Enteric Interventions", procs20)

    # Cat 21
    procs21 = []
    for item in CAT21_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs21.append(create_proc(pid, 21, "Pediatric Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "General Anesthesia or Deep Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category21_pediatric.ts", "CATEGORY_21_PEDIATRIC", 21, "Pediatric Interventions", procs21)

    # Cat 22
    procs22 = []
    for item in CAT22_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs22.append(create_proc(pid, 22, "Emerging & Novel Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia / Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category22_emerging.ts", "CATEGORY_22_EMERGING", 22, "Emerging & Novel Interventions", procs22)

if __name__ == "__main__":
    generate_cat18_to_22()
