# -*- coding: utf-8 -*-
"""
Generator for Master Catalog Categories 13 through 17
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_all_master_categories import write_category_file
from gen_cat03 import create_proc

# ==============================================================================
# CATEGORY 13: Vascular Anomalies & Malformations (24 Procedures)
# ==============================================================================
CAT13_LIST = [
    ("cat13-vm-bleomycin", "Percutaneous Sclerotherapy of Venous Malformations with Bleomycin", "Vascular Malformation Sclerotherapy", "1849-IN066A", "D18.0", 25000, "US", ["Low-Flow Venous Malformation (Head / Neck / Extremity)"], "Direct percutaneous puncture under real-time ultrasound", "21G - 23G Butterfly Needle", "Ultrasound machine, non-ionic contrast, Bleomycin (max 15 mg / session or 0.5 mg/kg)", "N/A", "Bleomycin Aqueous Solution / Foam", "Real-time ultrasound localized multi-septated spongy low-flow venous malformation with phleboliths. Sterile prep. Direct puncture with 21G butterfly needle into dominant venous lake. Slow dark venous blood return confirmed. Direct phlebography under subtraction fluoroscopy verified lesion boundaries and absence of rapid deep venous drainage. Bleomycin (10 units dissolved in 5 mL saline + 5 mL non-ionic contrast) injected slowly under continuous fluoroscopic vision. Pressure dressing applied.", 2, "Bedrest x 2 hours; elevate treated limb if extremity.", "Monitor for acute local swelling, skin blanching, or airway edema q30m x 2h.", "Bedside USG if excessive swelling; follow-up MRI at 6-8 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Tab Prednisolone 20mg OD x 3 days (reduces post-sclerosis swelling)"], ["Airway compromise (head/neck lesions)", "Skin ulceration / necrosis", "Pulmonary toxicity (cumulative dose monitoring)"], "consent-vascular-malformation", None),
    ("cat13-avm-onyx", "High-Flow Arteriovenous Malformation (AVM) Transcatheter Embolization with Onyx", "Percutaneous Transcatheter Embolization", "1849-IN063A", "Q27.3", 55000, "XA", ["High-Flow AVM Nidus", "Arterial Feeders", "Dominant Draining Veins"], "Right CFA at femoral head level", "6F Sheath", "5F Guiding catheter, DMSO-compatible microcatheter (Apollo / Marathon / Sonic), 0.014\" wire, DMSO, Onyx 18 / 34", "1.5F - 2.7F DMSO-compatible microcatheter", "Onyx 18 / 34 (Ethylene Vinyl Alcohol Copolymer)", "Right CFA access. Selective arteriography identified complex high-flow AVM with multiple feeding pedicles and early venous drainage. DMSO-compatible detachable-tip microcatheter navigated superselectively into the nidus. Microcatheter flushed with non-ionic contrast, followed by 0.25 mL DMSO dead-space fill. Under continuous roadmap fluoroscopy, Onyx-18 slowly infused forming a proximal plug around the microcatheter tip. Reflux-and-push technique utilized to fill entire nidus and dominant outflow vein. Microcatheter detached cleanly. Post-embolization angiogram demonstrated total devascularization of AVM nidus.", 6, "Strict supine flat bedrest x 6 hours; right leg straight.", "Monitor puncture site, limb neurovascular status, and facial/cranial nerve exams q15m x 1h, q30m x 2h, then q1h.", "Repeat MRI / Angiography at 3 months.", "IV Normal Saline 100 mL/hr.", ["IV Dexamethasone 8mg BD", "Tab Paracetamol 650mg TDS"], ["Ischemic skin necrosis", "Non-target intracranial/pulmonary embolization", "Compartment syndrome"], "consent-vascular-malformation", "cigarroa_macd"),
    ("cat13-pavm-plugs-coils", "Pulmonary Arteriovenous Malformation (PAVM) Embolization with Vascular Plugs / Coils", "Pulmonary AVM Embolization", "1849-CV023A", "Q28.0", 40000, "XA", ["Pulmonary Artery Feeding Branch", "PAVM Sac", "Draining Pulmonary Vein"], "Right Common Femoral Vein under ultrasound", "7F - 8F 45cm Sheath", "0.035\" stiff Glidewire, 5F Berman / Grollman catheter, Amplatzer Vascular Plug IV / II (6-12mm) and 0.018\"/0.035\" detachable coils", "2.7F microcatheter", "Amplatzer Vascular Plug IV + Detachable Coils", "Indicated for hereditary hemorrhagic telangiectasia (HHT / Osler-Weber-Rendu) with feeding artery >2mm causing hypoxemia or paradoxical stroke risk. Right CFV access. Selective pulmonary arteriography identified 7mm feeding artery supplying a 20mm PAVM sac. 7F sheath navigated into feeding branch. Sizing performed. An Amplatzer Vascular Plug IV (9mm, 30-50% oversizing) deployed precisely in the distal feeding artery within 1 cm of sac, strictly preserving normal adjacent pulmonary arterial branches. Complementary detachable microcoils packed proximal to plug. Completion run showed complete occlusion of feeding artery with preserved normal pulmonary parenchyma. Arterial PO2 improved immediately from 68 to 92 mmHg on room air.", 4, "Bedrest x 4 hours.", "Monitor SpO2, respiratory rate, and groin puncture site q15m x 1h, q30m x 2h, then q1h.", "Erect Chest X-ray at 2 to 4 hours post-procedure to confirm plug stability and rule out pneumothorax.", "Oral fluids.", ["Tab Paracetamol 650mg SOS"], ["Pleurisy / pleuritic chest pain (pulmonary infarction)", "Paradoxical plug migration into left atrium / systemic circulation", "Air embolism"], "consent-pavm-embolization", None),
]

# ==============================================================================
# CATEGORY 14: MSK Embolization & Sports Medicine (38 Procedures)
# ==============================================================================
CAT14_LIST = [
    ("cat14-gae-knee-oa", "Genicular Artery Embolization (GAE) for Mild-to-Moderate Knee Osteoarthritis", "Genicular Artery Embolization (GAE)", "1849-IN067A", "M17.1", 30000, "XA", ["Descending Genicular Artery", "Superior Medial / Lateral Genicular Arteries", "Inferior Medial Genicular Artery"], "Ipsilateral Antegrade CFA or Contralateral Retrograde CFA Access", "4F - 5F 11cm Sheath", "4F/5F Glidecath / Cobra, 1.7F - 2.0F Microcatheter (Progreat / Carnelian), 0.014\" wire", "1.7F - 2.0F microcatheter", "Imipenem/Cilastatin (IPM/CS) micro-particles (100-300um) or Embozene (75-100um) calibrated microspheres", "Indicated for severe refractory knee pain from medial compartment osteoarthritis (Kellgren-Lawrence Grade 2-3) failing physical therapy and injections. CFA accessed. Selective popliteal arteriogram performed with knee extended. Hypervascular pathological neo-angiogenesis 'blush' identified in medial compartment supplied by descending and inferior medial genicular arteries. 2.0F microcatheter advanced superselectively into the hypervascular genicular branches. 100-200um calibrated microspheres slowly infused until pathological blush completely resolved while preserving the normal main trunk of the genicular artery. Completion run showed complete disappearance of abnormal synoviocyte capillary blush.", 4, "Bedrest x 4 hours; knee in comfortable semi-flexed position.", "Check groin site, pedal pulses, and knee skin temperature/color q15m x 1h, q30m x 2h, then q1h.", "None routine.", "Oral hydration.", ["Tab Paracetamol 650mg TDS x 3 days", "Tab Celecoxib 100mg BD x 3 days"], ["Cutaneous ischemia / transient skin erythema", "Distal foot embolization", "Groin hematoma"], "consent-gae-embolization", None),
    ("cat14-frozen-shoulder-embolization", "Shoulder / Adhesive Capsulitis (Frozen Shoulder) Embolization", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "M75.0", 28000, "XA", ["Anterior / Posterior Circumflex Humeral Arteries", "Thoracoacromial Trunk", "Suprascapular Artery"], "Right Radial or CFA Access", "4F - 5F Sheath", "4F Cobra, 1.7F - 2.0F microcatheter, 0.014\" wire", "1.7F microcatheter", "Embozene microspheres (75-100um) or Imipenem/Cilastatin slurry", "Indicated for intractable chronic adhesive capsulitis in the freezing/frozen phase. Diagnostic subclavian and axillary arteriograms demonstrated hypervascular synovial blush over anterior glenohumeral joint capsule and rotator interval supplied by circumflex humeral and thoracoacromial branches. Microcatheter navigated into capsule feeders. Slow particulate embolization performed until pathological synovial blush cleared. Immediate improvement in passive range of motion demonstrated in recovery.", 2, "Bedrest x 2 hours (if radial access, wrist band x 2h).", "Radial/femoral puncture site check and neurovascular check of arm q15m x 1h, then q30m.", "None routine.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Early active/passive shoulder physiotherapy from Day 2"], ["Transient skin discoloration over deltoid", "Radial artery spasm", "Hematoma"], "consent-gae-embolization", None),
    ("cat14-tennis-elbow-tame", "Lateral Epicondylitis (Tennis Elbow) Transcatheter Arterial Micro-Embolization (TAME)", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "M77.1", 25000, "XA", ["Radial Recurrent Artery", "Interosseous Recurrent Artery"], "Ipsilateral Brachial or Radial Access", "4F Micro-sheath", "4F catheter, 1.7F microcatheter, 0.014\" wire", "1.7F microcatheter", "Imipenem/Cilastatin emulsion or 100um microspheres", "For chronic refractory lateral epicondylitis. Brachial angiogram revealed abnormal capillary hypervascularity at common extensor tendon insertion. Microcatheter navigated into radial recurrent branch. Embolization performed until hypervascularity abolished. Pain score (VAS) improved significantly post-procedure.", 2, "Arm resting on sling x 2 hours.", "Monitor puncture site and radial pulse q30m x 2h.", "None routine.", "Oral fluids.", ["Tab Paracetamol 650mg TDS"], ["Transient forearm numbness", "Hematoma"], "consent-gae-embolization", None),
    ("cat14-shoulder-barbotage", "Ultrasound-Guided Barbotage & Lavage for Calcific Shoulder Tendinopathy", "Ultrasound-Guided Joint / Tendon Intervention", "1849-IN068A", "M75.3", 8000, "US", ["Supraspinatus Tendon Calcific Deposit", "Subacromial Bursa"], "Direct percutaneous under high-frequency linear US", "18G - 20G Needles (Dual Needle Technique)", "Linear 12-18 MHz US probe, warm normal saline syringes, 1% lignocaine, 40mg Triamcinolone", "N/A", "Triamcinolone Acetonide 40mg", "High-frequency ultrasound identified dense 14mm calcific deposit with acoustic shadowing in supraspinatus tendon. Under local anesthesia, two 18G needles positioned within calcification under real-time ultrasound. Continuous pulsing lavage (barbotage) with warm sterile saline performed across the needles, flushing and aspirating creamy calcium slurry into syringes. Calcific deposit fully debulked. 40mg triamcinolone + 2 mL 1% lignocaine injected into subacromial-subdeltoid bursa. Post-procedure ultrasound confirmed near-total clearance of calcium.", 1, "Arm in sling for 24 hours.", "Check puncture site and shoulder range of motion.", "Ultrasound review at 4 weeks.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Gentle pendulum exercises from 24 hours"], ["Subdeltoid bursitis flare", "Tendon rupture (avoid intratendinous steroid)", "Infection"], "consent-joint-injection", None),
]

# ==============================================================================
# CATEGORY 15: Spine & Pain Interventions (35 Procedures)
# ==============================================================================
CAT15_LIST = [
    ("cat15-pvp-vertebroplasty", "Percutaneous Vertebroplasty (PVP) for Osteoporotic Vertebral Compression Fracture", "Vertebroplasty", "1849-IN069A", "M80.0", 22000, "XA", ["Vertebral Body (L1/L2/T12/T11)"], "Bilateral Transpedicular Approach under Biplane Fluoroscopy", "11G / 13G Vertebroplasty Beveled Needles", "11G/13G biopsy/access needles, hydraulic cement delivery syringe, radiopaque PMMA bone cement", "N/A", "Polymethylmethacrylate (PMMA) High-Viscosity Bone Cement (3-5 mL)", "Patient prone. Biplane fluoroscopy aligned pedicular rings and vertebral endplates. Local anesthesia down to periosteum. 11G beveled vertebroplasty needles advanced transpedicularly into anterior 1/3 of L1 vertebral body. Biopsy obtained. PMMA bone cement mixed to toothpaste-like viscosity. Under continuous biplane lateral fluoroscopy, 4.0 mL of radiopaque PMMA cement incrementally injected into the vertebral body, ensuring uniform trabecular interdigitation from endplate to endplate. Injection strictly halted upon any posterior cortical or epidural venous extension. Needles rotated and withdrawn with stylets. Sterile dressing.", 4, "Strict flat supine bedrest x 2 hours (to allow PMMA polymerization), then log-roll bedrest x 2 hours.", "Neurological examination (lower limb power, sensation, deep tendon reflexes) q15m x 1h, q30m x 2h, then q1h.", "Post-procedure Plain Radiograph / CT Spine to verify cement distribution and exclude canal extravasation.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Cap Pantoprazole 40mg OD", "Anti-osteoporotic therapy (Calcium, Vit D3, Teriparatide)"], ["Cement leakage into spinal canal / epidural space (cord compression)", "Cement pulmonary embolism", "Adjacent level vertebral fracture"], "consent-vertebroplasty", None),
    ("cat15-bkp-kyphoplasty", "Balloon Kyphoplasty (BKP) for Thoracic / Lumbar Vertebral Compression Fracture", "Kyphoplasty", "1849-IN070A", "M80.0", 35000, "XA", ["Vertebral Body (Thoracolumbar)"], "Bilateral Transpedicular / Extrapedicular Approach", "10G Working Cannulas", "10G access needles, inflatable bone tamp balloons (15mm/20mm), digital pressure syringe, PMMA cement", "N/A", "Kyphoplasty Balloon Tamps + High-Viscosity PMMA Bone Cement", "Prone position. 10G access cannulas placed bilaterally into anterior vertebral body. Inflatable bone tamps inserted and inflated slowly with contrast under pressure monitoring (up to 250 psi) until vertebral height restored and a controlled cancellous cavity created. Balloons deflated and removed. Cavity filled under low pressure with high-viscosity PMMA cement (4.5 mL total). Height restoration confirmed without cement leakage. Cannulas removed.", 4, "Flat bedrest x 2 hours, then mobilized with lumbar corset.", "Neuro checks of lower limbs q15m x 1h, q30m x 2h, then q1h.", "Plain X-ray spine.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Lumbar belt support"], ["Spinal cord compression", "Balloon rupture", "Embolism"], "consent-vertebroplasty", None),
    ("cat15-celiac-plexus-neurolysis", "CT-Guided Percutaneous Celiac Plexus Neurolysis (CPN) for Pancreatic Cancer Pain", "Celiac Plexus Block / Neurolysis", "1849-IN071A", "C25.9", 15000, "CT", ["Celiac Plexus", "Retrocrural Space", "Pre-aortic Celiac Axis"], "Bilateral Transcrural / Retrocrural Approach under CT guidance", "20G - 22G 15cm Chiba Needles", "CT guidance, 22G needles, 0.5% Bupivacaine, Absolute Ethanol (99%) mixed with contrast", "N/A", "Absolute Alcohol (99%) 40-50 mL + 0.5% Bupivacaine", "Indicated for intractable upper abdominal back pain from unresectable pancreatic head carcinoma. Patient prone. Non-contrast CT identified celiac trunk origin. 22G 15cm Chiba needles advanced bilaterally from retrocrural approach with needle tips positioned anterolateral to aorta at celiac artery level. Aspiration negative for blood and urine. Contrast injection (2 mL) confirmed excellent retroperitoneal diffusion around celiac axis. 10 mL of 0.5% bupivacaine injected bilaterally (diagnostic relief verified), followed by slow injection of 40 mL absolute alcohol (99%). Immediate sympathetic blockade evidenced by warming of feet. Needles withdrawn.", 4, "Strict flat bedrest x 4 hours.", "Monitor blood pressure closely (hypotension surveillance) and pain score q15m x 1h, q30m x 2h, then q1h.", "None routine.", "Liberal IV hydration (100-150 mL/hr) to counteract post-neurolysis orthostatic hypotension.", ["Tab Paracetamol 650mg TDS", "IV Tramadol PRN", "Titrate down baseline opioid doses by 50% to prevent overdose"], ["Severe orthostatic hypotension", "Transient diarrhea (parasympathetic hyperactivity)", "Retroperitoneal hematoma / aortic injury", "Paraplegia (anterior spinal artery ischemia)"], "consent-celiac-neurolysis", None),
    ("cat15-lumbar-transforaminal-esi", "Lumbar Transforaminal Epidural Steroid Injection (TFESI) / Selective Nerve Root Block", "Epidural Steroid Injection", "1849-IN072A", "M54.16", 8000, "XA", ["L4 / L5 / S1 Neural Foramen and Nerve Root"], "Subpedicular Oblique Approach under Fluoroscopy", "22G / 25G 9cm Quincke Needle", "C-arm fluoroscope, 22G needle, extension tubing, non-ionic contrast, Dexamethasone 8mg + 0.25% Bupivacaine", "N/A", "Dexamethasone (Non-particulate) 8mg + Bupivacaine 0.25%", "Indicated for acute L5 radiculopathy due to paracentral disc herniation. Prone position. C-arm obliqued 25° and tilted cranio-caudally to align L5 superior articular process. 22G needle advanced into safe triangle below L5 pedicle. Under live fluoroscopy, 1.0 mL non-ionic contrast injected demonstrating classic perineural flow along L5 nerve root into the anterior epidural space without vascular uptake. Mixture of 8mg non-particulate dexamethasone and 1.5 mL 0.25% bupivacaine slowly injected. Complete reproduction and immediate resolution of radicular leg pain.", 1, "Recovery observation x 1 hour. Ambulate with assistance.", "Check lower extremity power, proprioception, and puncture site q30m.", "None routine.", "Oral fluids.", ["Tab Paracetamol 650mg SOS", "Continue physical therapy"], ["Intravascular injection / spinal cord infarction (mitigated by non-particulate steroid)", "Dural puncture headache", "Transient leg weakness"], "consent-epidural-injection", None),
]

# ==============================================================================
# CATEGORY 16: Neurovascular Interventions (35 Procedures)
# ==============================================================================
CAT16_LIST = [
    ("cat16-diagnostic-4v-dsa", "Diagnostic 4-Vessel Cerebral Digital Subtraction Angiography (DSA)", "Cerebral Angiography", "1849-CV020A", "I67.9", 15000, "XA", ["Bilateral Internal Carotid Arteries", "Bilateral Vertebral Arteries", "Circle of Willis"], "Right Common Femoral Artery or Right Radial Artery", "5F 11cm Vascular Sheath", "5F Simmons-2 / Berenstein / H1 catheter, 0.035\" hydrophilic Glidewire", "N/A", "N/A", "Right CFA punctured at femoral head level; 5F sheath placed. 5F Simmons-2 catheter advanced over 0.035\" Glidewire into aortic arch. Selective catheterization of right and left common carotid arteries, internal carotid arteries, and dominant vertebral artery performed. High-frame-rate digital subtraction angiography obtained in AP, lateral, and 3D rotational views with 3D reconstruction of Circle of Willis. Vessel caliber, aneurysm morphology, arteriovenous shunting, collateral flow, and venous sinus phases analyzed. Sheath removed; Angio-Seal vascular closure device deployed achieving instantaneous hemostasis.", 4, "Bedrest x 2 hours (with closure device) or 6 hours (with manual compression); right leg straight.", "Monitor puncture site, distal pedal pulses, and neurological status (NIHSS assessment) q15m x 1h, q30m x 2h, then q1h.", "None routine unless acute neurological deficit occurs.", "IV Normal Saline 100 mL/hr for rapid contrast clearance.", ["Tab Aspirin 75mg OD (if diagnostic)", "Tab Paracetamol 650mg SOS"], ["Stroke / TIA (iatrogenic thromboembolism or dissection)", "Groin hematoma / retroperitoneal bleed", "Contrast-induced encephalopathy"], "consent-cerebral-dsa", "cigarroa_macd"),
    ("cat16-stroke-thrombectomy", "Acute Ischemic Stroke: Mechanical Thrombectomy with Stent Retriever & Direct Aspiration", "Mechanical Thrombectomy for Stroke", "1849-CV024A", "I63.5", 75000, "XA", ["Terminal ICA", "Middle Cerebral Artery (M1/M2 Segments)", "Basilar Artery"], "Right CFA at femoral head level under US/Fluoro", "8F 90cm Guiding Sheath (Ballast / Cerebase) or 8F Balloon Guide Catheter (FlowGate2)", "0.035\" stiff wire, 6F large-bore aspiration catheter (React 71 / Penumbra RED 72), 0.021\" microcatheter, 0.014\" microwire (Synchro), Stent Retriever (Solitaire X / Trevo 4-6mm)", "0.021\" microcatheter", "Solitaire X / Trevo NXT Stent Retriever + Aspiration Catheter", "Emergency code stroke within 24h window for acute right MCA M1 segment occlusion (NIHSS 18). Right CFA accessed; 8F Balloon Guide Catheter positioned in cervical right ICA. Distal intracranial aspiration catheter (React 71) and 0.021\" microcatheter advanced over 0.014\" wire across M1 occlusion. Microcatheter run confirmed distal M2 branch patency. Solitaire X (4mm x 40mm) stent retriever deployed across clot and unsheathed for 3 minutes for clot integration. Balloon guide inflated with flow arrest. Combined aspiration and stent retriever retrieval performed (SAVE/CAPTIVE technique) under continuous high vacuum aspiration. Thrombus extracted in toto on first pass. Immediate repeat intracranial DSA demonstrated complete, flawless TICI 3 reperfusion with widely patent right MCA and anterior cerebral branches. NIHSS dropped from 18 to 4 in cath-lab.", 6, "Strict flat bedrest x 6 hours in Neuro-ICU. Maintain SBP strictly between 120-140 mmHg.", "Continuous neurological examination (NIHSS and GCS) and groin puncture site check q15m x 1h, q30m x 2h, then q1h.", "Non-contrast CT Brain at 24 hours to rule out hemorrhagic transformation and confirm salvage of ischemic penumbra.", "IV Normal Saline 75-100 mL/hr; maintain euvolemia.", ["Stat CT Brain before initiating antiplatelet therapy", "Tab Atorvastatin 80mg OD", "IV Labetalol infusion PRN for BP control"], ["Intracranial hemorrhage / hemorrhagic transformation", "Vessel perforation / subarachnoid hemorrhage", "Distal clot embolization to new territory", "Groin hematoma"], "consent-stroke-thrombectomy", "cigarroa_macd"),
    ("cat16-aneurysm-coiling", "Intracranial Aneurysm Endosaccular Coiling with Detachable Microcoils", "Endovascular Coiling of Aneurysm", "1849-CV025A", "I60.9", 70000, "XA", ["Anterior Communicating / Posterior Communicating / MCA Bifurcation Aneurysm Sac"], "Right CFA at femoral head level", "6F 90cm Guiding Sheath", "0.035\" stiff wire, 5F distal access catheter, 1.7F microcatheter (Headway / Excelsior SL-10), 0.014\" Synchro wire, Detachable Platinum Microcoils (Target / Axium / Cosmos)", "1.7F microcatheter", "Detachable Platinum Microcoils (Framing, Filling, and Finishing Coils)", "Under general anesthesia, right CFA accessed; 6F guiding catheter navigated into petrous ICA. Working 3D-rotational angiographic view selected. 1.7F microcatheter steam-shaped and navigated into center of 6mm PCom aneurysm sac. Framing coil (Target 3D 6mm x 15cm) deployed creating stable 3D basket. Subsequent filling and finishing microcoils deployed sequentially until complete dense coil packing achieved (>30% packing density). Completion DSA in all projections showed total aneurysm occlusion (Raymond-Roy Class I) with widely patent parent ICA and PCom branches. Sheath removed; Angio-Seal closure.", 6, "Strict flat bedrest x 6 hours.", "Continuous neurological and hemodynamic monitoring in Neuro-ICU q15m x 1h, q30m x 2h, then q1h.", "Post-procedure Non-contrast CT Brain; MRA at 6 months.", "IV Normal Saline 100 mL/hr.", ["Therapeutic IV Heparin protocol", "Nimodipine 60mg PO q4h (if subarachnoid hemorrhage)", "Tab Paracetamol 650mg TDS"], ["Intraprocedural aneurysm rupture", "Thromboembolism of parent vessel / acute stroke", "Coil protrusion into parent artery"], "consent-aneurysm-coiling", "cigarroa_macd"),
    ("cat16-mma-embolization", "Middle Meningeal Artery (MMA) Embolization for Chronic Subdural Hematoma (cSDH)", "Middle Meningeal Artery Embolization", "1849-CV026A", "I62.0", 38000, "XA", ["Middle Meningeal Artery (Anterior and Posterior Convexity Branches)"], "Right CFA or Right Radial Artery", "5F Sheath", "5F Envoy / Simmons, 1.5F - 1.7F microcatheter (Magic / Marathon), 0.014\" wire", "1.5F microcatheter", "PVA particles (150-250um) or Liquid Embolic (Onyx 18 / Squid 12) or n-BCA glue", "Indicated for recurrent or non-surgical chronic subdural hematoma (cSDH) in elderly patients. Access established. External carotid arteriography performed. 1.5F microcatheter navigated superselectively into anterior and posterior convex branches of MMA distal to petrous and sphenoid origins. Absence of dangerous anastomoses (meningo-ophthalmic, ophthalmic artery collateral) rigorously confirmed on magnified oblique runs. Micro-embolization performed using 150-250um PVA particles followed by Onyx-18 cast in proximal trunks. Complete devascularization of neovascular subdural membrane achieved, stopping microvascular re-bleeding and promoting hematoma resorption.", 4, "Bedrest x 4 hours.", "Neurological monitoring and access site check q15m x 1h, q30m x 2h, then q1h.", "Non-contrast CT Brain at 1 month to document complete hematoma resolution.", "Oral fluids.", ["Tab Paracetamol 650mg TDS", "Tab Levetiracetam 500mg BD (seizure prophylaxis)"], ["Ophthalmic artery embolization / vision loss", "Facial nerve palsy (petrosal branch)", "Hematoma recurrence"], "consent-cerebral-dsa", "cigarroa_macd"),
    ("cat16-carotid-stenting", "Carotid Artery Stenting (CAS) with Distal Embolic Protection Device (EPD)", "Carotid Artery Stenting", "1849-VS003A", "I65.2", 45000, "XA", ["Internal Carotid Artery Bulbar Stenosis", "Common Carotid Artery"], "Right CFA at femoral head level", "6F - 8F 90cm Guiding Sheath", "0.035\" stiff wire, Distal Embolic Protection Device (SpiderFX / FilterWire EZ), 0.014\" wire, Carotid Nitinol Stent (Acculink / Protégé / CGuard), 5.0mm x 20mm Monorail PTA balloon", "N/A", "Dedicated Self-Expanding Nitinol Carotid Stent (7-10mm x 30-40mm tapered)", "Symptomatic >70% high-grade bulbar ICA stenosis. Right CFA access. 6F 90cm sheath positioned in distal common carotid artery. Selective carotid angiogram confirmed critical eccentric stenosis. Distal embolic protection filter (SpiderFX 5mm) navigated across stenosis and deployed in cervical ICA below skull base. Pre-dilation performed with 3.5mm balloon. Self-expanding tapered carotid stent (8x6mm x 40mm) deployed across carotid bifurcation. Post-dilation performed with 5.0mm balloon under atropine coverage (1mg IV given to prevent carotid sinus bradycardia). Embolic protection filter captured and retrieved smoothly. Basket inspection showed captured atheromatous debris. Completion DSA confirmed widely patent carotid bulb, zero residual stenosis, and normal intracranial cerebral circulation without distal branch cutoffs.", 6, "Strict flat bedrest x 6 hours; continuous arterial BP monitoring.", "Neurological checks and blood pressure surveillance q15m x 1h, q30m x 2h, then q1h.", "Carotid Doppler Ultrasound at 24 hours.", "IV Normal Saline 75-100 mL/hr.", ["Dual Antiplatelet Therapy: Aspirin 75mg + Clopidogrel 75mg OD x 3 months", "Tab Atorvastatin 40mg HS", "Maintain SBP 110-130 mmHg"], ["Hyperperfusion syndrome / intracranial hemorrhage", "Distal stroke / atheroembolism", "Severe hemodynamic depression (bradycardia/hypotension)", "Groin hematoma"], "consent-carotid-stenting", "cigarroa_macd"),
]

# ==============================================================================
# CATEGORY 17: Endocrine, Head & Neck (16 Procedures)
# ==============================================================================
CAT17_LIST = [
    ("cat17-thyroid-rfa", "Ultrasound-Guided Radiofrequency Ablation (RFA) of Benign Thyroid Nodules", "Radiofrequency Ablation (RFA)", "1849-MG080A", "E04.1", 25000, "US", ["Benign Thyroid Nodule (Colloid / Adenomatous)"], "Transisthmic approach under high-frequency linear ultrasound", "18G Internally Cooled RFA Thyroid Needle (7cm, 5-10mm active tip)", "Linear 12-18 MHz probe, 18G RFA needle, RF generator, peristaltic cold saline pump", "N/A", "N/A", "High-frequency ultrasound mapped 3.5cm symptomatic benign thyroid nodule causing dysphagia. Benignity confirmed on dual prior FNACs. Local anesthesia with 1% lignocaine; hydrodissection with 5% Dextrose performed into thyroid capsule to create danger-zone safety buffer protecting recurrent laryngeal nerve in tracheoesophageal groove. Under real-time continuous ultrasound, 18G thyroid RFA needle inserted via transisthmic approach. Moving-shot technique utilized: nodule divided into multiple conceptual units, ablating from posterior to anterior and medial to lateral. Transient hyperechoic vapor clouds enveloped entire nodule. Completion ultrasound confirmed total ablation of nodular tissue with patent carotid artery and normal vocal cord movement on real-time US.", 2, "Bedrest x 2 hours with ice pack applied over anterior neck.", "Inspect neck for swelling, monitor voice quality (check for hoarseness) q30m x 2h.", "Thyroid Ultrasound at 1, 3, and 6 months to record volume reduction ratio (VRR).", "Oral fluids.", ["Tab Paracetamol 650mg TDS x 3 days", "Tab Ibuprofen 400mg BD x 2 days"], ["Recurrent laryngeal nerve injury / vocal cord palsy", "Neck hematoma", "Skin burn"], "consent-thyroid-ablation", None),
    ("cat17-avs-conn", "Adrenal Vein Sampling (AVS) with Cosyntropin Stimulation for Primary Aldosteronism", "Adrenal Vein Sampling (AVS)", "1849-CV027A", "E26.0", 25000, "XA", ["Right Adrenal Vein", "Left Adrenal Vein", "Infrarenal IVC"], "Right Common Femoral Vein under US", "5F - 6F Sheath", "0.035\" wire, 5F dedicated Adrenal catheters (Cobra, Mikaelson, C2, Bentson-Hanafee)", "N/A", "N/A", "For differentiation of unilateral aldosterone-producing adenoma from bilateral adrenal hyperplasia. Continuous IV cosyntropin infusion running at 50 mcg/hr. Right CFV access. 5F catheter navigated into left common phrenic/adrenal vein trunk; blood samples drawn for aldosterone and cortisol. Cannulation of small, slit-like right adrenal vein directly entering posterior IVC achieved with dedicated C2 catheter; position confirmed by gentle hand contrast injection demonstrating typical triangular glandular blush. Blood samples drawn from right adrenal vein, left adrenal vein, and infrarenal IVC. Selectivity index (adrenal cortisol / IVC cortisol >5.0) and lateralization index calculated. Catheter removed; manual compression.", 4, "Bedrest x 4 hours.", "Groin check q30m x 2h.", "None routine.", "Oral fluids.", ["Continue baseline antihypertensives"], ["Adrenal vein rupture / hematoma", "Adrenal infarction", "Groin hematoma"], "consent-adrenal-sampling", None),
]

def generate_cat13_to_17():
    # Cat 13
    procs13 = []
    for item in CAT13_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs13.append(create_proc(pid, 13, "Vascular Anomalies & Malformations", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category13_anomalies.ts", "CATEGORY_13_ANOMALIES", 13, "Vascular Anomalies & Malformations", procs13)

    # Cat 14
    procs14 = []
    for item in CAT14_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs14.append(create_proc(pid, 14, "MSK Embolization & Sports Medicine", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category14_msk.ts", "CATEGORY_14_MSK", 14, "MSK Embolization & Sports Medicine", procs14)

    # Cat 15
    procs15 = []
    for item in CAT15_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs15.append(create_proc(pid, 15, "Spine & Pain Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category15_spine_pain.ts", "CATEGORY_15_SPINE_PAIN", 15, "Spine & Pain Interventions", procs15)

    # Cat 16
    procs16 = []
    for item in CAT16_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs16.append(create_proc(pid, 16, "Neurovascular Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia with Conscious Sedation / General Anesthesia", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category16_neuro.ts", "CATEGORY_16_NEURO", 16, "Neurovascular Interventions", procs16)

    # Cat 17
    procs17 = []
    for item in CAT17_LIST:
        pid, title, pkg, pcode, icd, tar, mod, anat, acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc = item
        procs17.append(create_proc(pid, 17, "Endocrine, Head & Neck Interventions", title, "BOTH", pkg, pcode, icd, tar, mod, anat, "Local Anesthesia", acc, sh, cath, micro, emb, narr, imm_h, imm_in, hem, img, hyd, meds, red, cons, calc))
    write_category_file("category17_endocrine.ts", "CATEGORY_17_ENDOCRINE", 17, "Endocrine, Head & Neck Interventions", procs17)

if __name__ == "__main__":
    generate_cat13_to_17()
