# -*- coding: utf-8 -*-
"""
Generator for Master Catalog Categories 03 through 07
"""
import os
import sys

# Add current dir
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_all_master_categories import write_category_file

def create_proc(pid, cat_num, cat_name, title, scheme_name, pkg_name, pkg_code, icd10, tariff,
                modality, anatomy, sedation, access, sheath, catheters, micro, embolic,
                narrative, immo_hours, immo_inst, hematoma, img, hydration, meds, red_flags,
                consent, calc=None):
    return {
        "id": pid,
        "categoryNumber": cat_num,
        "categoryName": cat_name,
        "title": title,
        "maayRghsCompatibility": {
            "schemeName": scheme_name,
            "packageName": pkg_name,
            "packageCode": pkg_code,
            "icd10": icd10,
            "tariffInr": tariff
        },
        "modality": modality,
        "targetAnatomy": anatomy,
        "sedation": sedation,
        "accessSiteDefault": access,
        "sheathDefault": sheath,
        "cathetersAndWires": catheters,
        "microcatheterSystem": micro,
        "embolicOrImplants": embolic,
        "proceduralNarrativeTemplate": narrative,
        "postOpCare": {
            "immobilizationHours": immo_hours,
            "immobilizationInstructions": immo_inst,
            "hematomaChecks": hematoma,
            "requiredImaging": img,
            "hydrationProtocol": hydration,
            "medications": meds,
            "redFlags": red_flags
        },
        "consentId": consent,
        "calculatorId": calc
    }

# ==============================================================================
# CATEGORY 03: HPB & PORTAL HYPERTENSION (50 Procedures)
# ==============================================================================
CAT03_LIST = [
    # PTBD and Biliary
    ("cat03-ptbd-right", "Right Percutaneous Transhepatic Biliary Drainage (PTBD)", "Percutaneous Transhepatic Biliary Drainage (PTBD)", "1849-IN058A", "K83.1", 12000, "XA", ["Right Hepatic Duct", "CBD"], "Right 10th intercostal mid-axillary line", "8.5F/10F Biliary sheath", "21G Chiba, 0.018\" Nitinol, 0.035\" stiff Glidewire, 5F KMP", "N/A", "8.5F / 10F Ring-type locking pigtail catheter", "Real-time sonography and fluoroscopy guided right peripheral duct puncture with 21G Chiba needle. Cholangiogram confirmed high-grade biliary obstruction. 0.018\" wire upsized to 0.035\" stiff Glidewire. Stricture crossed into duodenum. 8.5F/10F locking internal-external biliary drainage catheter deployed bridging stricture. Locked and connected to bag.", 4, "Supine bedrest x 4 hours; keep bag dependent.", "Check puncture site for bile/blood q30m x 2h, then q1h.", "Bedside USG if peritonism or hemodynamic instability.", "IV Normal Saline 100 mL/hr.", ["IV Piperacillin-Tazobactam 4.5g TDS", "Tab Ursodeoxycholic Acid 300mg BD"], ["Biliary peritonitis", "Septic cholangitis with rigors", "Hemobilia"], "consent-ptbd-drainage", "cigarroa_macd"),
    ("cat03-ptbd-left", "Left Percutaneous Transhepatic Biliary Drainage (PTBD)", "Percutaneous Transhepatic Biliary Drainage (PTBD)", "1849-IN058A", "K83.1", 12000, "XA", ["Left Hepatic Duct (Segment 3/2)", "CBD"], "Subxiphoid epigastric approach under US", "8.5F Biliary sheath", "21G Chiba, 0.018\" wire, 0.035\" stiff Glidewire, 5F Kumpe", "N/A", "8.5F locking biliary catheter", "Subxiphoid ultrasound localized dilated Segment 3 duct. Punctured with 21G Chiba. Cholangiogram obtained. 0.018\" wire transitioned to 0.035\" stiff wire. Stricture traversed into duodenum. 8.5F internal-external drainage catheter positioned with sideholes bridging stricture. Locked and secured.", 4, "Supine bedrest x 4 hours; keep drainage bag dependent.", "Monitor subxiphoid site for bile leak q30m x 2h.", "Bedside USG if peritonism.", "IV Normal Saline 100 mL/hr.", ["IV Piperacillin-Tazobactam 4.5g TDS", "Tab Paracetamol 650mg TDS"], ["Peritonitis", "Hemobilia", "Rigors"], "consent-ptbd-drainage", "cigarroa_macd"),
    ("cat03-ptbd-bilateral", "Bilateral Percutaneous Transhepatic Biliary Drainage", "Percutaneous Transhepatic Biliary Drainage (PTBD)", "1849-IN058A", "C22.1", 20000, "XA", ["Right and Left Hepatic Ducts", "Biliary Confluence"], "Right intercostal and subxiphoid approaches", "Dual 8.5F Sheaths", "21G Chiba needles, 0.035\" Glidewires, 5F Cobra catheters", "N/A", "Dual 8.5F/10F locking biliary drainage catheters", "Indicated for Bismuth-Corlette Type IV hilar cholangiocarcinoma with isolated right and left ductal systems. Sequential ultrasound-guided punctures of right Segment 6 and left Segment 3 ducts. Bilateral internal-external 8.5F locking catheters deployed across strictures into duodenum. Excellent bilateral decompression achieved.", 4, "Strict bedrest x 4 hours. Keep both bags dependent.", "Monitor bilateral sites q30m x 2h, then q1h.", "Bedside USG if acute pain.", "IV fluids 100 mL/hr.", ["IV Piperacillin-Tazobactam 4.5g TDS", "IV Ondansetron 4mg BD"], ["Peritonitis", "Sepsis", "Bleeding"], "consent-ptbd-drainage", "cigarroa_macd"),
    ("cat03-biliary-stent-uncovered", "Percutaneous Transhepatic Biliary Stenting (Uncovered SEMS)", "Biliary Stenting", "1849-IN059A", "C24.0", 25000, "XA", ["Common Bile Duct", "Duodenum"], "Mature PTBD tract access", "8F Vascular Sheath", "0.035\" Amplatz Super Stiff wire, 5F Glidecath, 8-10mm x 60-80mm Nitinol SEMS", "N/A", "10mm x 80mm Uncovered Nitinol SEMS", "Access through mature PTBD tract. Cholangiogram defined stricture length. 0.035\" Amplatz wire advanced into duodenum. 10mm x 80mm uncovered self-expanding Nitinol stent deployed across stricture under fluoroscopy. Brisk contrast drainage into duodenum. 8.5F check catheter left above stent.", 4, "Supine bedrest x 4 hours. Tube clamped after 24h if afebrile.", "Vitals and site check q30m x 2h, then q1h.", "Cholangiogram at 24h prior to catheter removal.", "IV fluids 100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Ursodeoxycholic Acid 300mg BD"], ["Peritonitis", "Melena", "Fever"], "consent-biliary-stent", "cigarroa_macd"),
    ("cat03-biliary-stent-covered", "Percutaneous Transhepatic Biliary Stenting (Covered SEMS)", "Biliary Stenting", "1849-IN059A", "K83.1", 30000, "XA", ["Distal Common Bile Duct", "Ampulla of Vater"], "PTBD tract", "8F - 10F Vascular Sheath", "0.035\" Amplatz wire, 10mm x 60-80mm fully covered SEMS", "N/A", "10mm x 70mm Fully Covered SEMS (Viabil / Hanarostent)", "Catheterization across distal CBD stricture. Amplatz wire placed into duodenum. 10mm x 70mm fully covered Nitinol SEMS deployed across stricture preventing tumor ingrowth. Free contrast run-off into duodenum confirmed.", 4, "Bedrest x 4 hours.", "Abdominal exam and vitals q30m x 2h.", "Check fluoroscopy before tube removal.", "IV fluids 100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Pantoprazole 40mg OD"], ["Pancreatitis", "Peritonitis", "Stent migration"], "consent-biliary-stent", "cigarroa_macd"),
    ("cat03-intraductal-rfa", "Percutaneous Intraductal Radiofrequency Ablation (RFA) of Biliary Malignancy", "Radiofrequency Ablation (RFA)", "1849-MG080A", "C24.0", 35000, "XA", ["Common Bile Duct", "Biliary Confluence"], "PTBD tract", "8F Vascular Sheath", "0.035\" stiff wire, 8F Habib EndoHPB bipolar RF catheter", "N/A", "Habib EndoHPB Bipolar RFA Catheter", "Via mature PTBD tract, 8F Habib EndoHPB bipolar RFA catheter positioned across malignant biliary stricture under fluoroscopic guidance. Bipolar RF energy delivered at 10W for 90 seconds. Catheter repositioned for overlapping ablation. Post-ablation balloon clearance and stent placement performed.", 4, "Bedrest x 4 hours.", "Vitals and abdominal checks q30m x 2h.", "Bedside USG if acute pain.", "IV fluids 100 mL/hr.", ["IV Piperacillin-Tazobactam 4.5g TDS", "Tab Tramadol 50mg SOS"], ["Hemobilia", "Biliary perforation", "Pancreatitis"], "consent-biliary-rfa", "cigarroa_macd"),
    ("cat03-biliary-stone-extraction", "Percutaneous Transhepatic Biliary Stone Extraction & Balloon Dilation", "Biliary Stone Extraction / Sclerotherapy", "1849-IN057A", "K80.5", 18000, "XA", ["Common Bile Duct", "Duodenum"], "PTBD tract", "10F - 12F Sheath", "0.035\" Amplatz wire, Dormia basket, 10-12mm occlusion/sweeping balloon catheter", "N/A", "N/A", "Mature PTBD tract upsized to 10F. Cholangiogram demonstrated CBD calculi. Sphincter of Oddi dilated with 10mm balloon. 10mm stone extraction balloon catheter used to sweep stones antegrade into duodenum. Remaining calculi captured and fragmented using Dormia basket. Clearance confirmed on repeat cholangiogram.", 4, "Bedrest x 4 hours. Keep catheter on free drainage.", "Monitor for hemobilia and acute pancreatitis q30m x 2h.", "Cholangiogram at 48h.", "IV hydration 100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Paracetamol 650mg TDS"], ["Severe pancreatitis", "Perforation", "Cholangitis"], "consent-ptbd-drainage", "cigarroa_macd"),
    ("cat03-cholecystostomy-transhepatic", "Ultrasound-Guided Percutaneous Transhepatic Cholecystostomy", "Cholecystostomy", "1849-IN057A", "K81.0", 10000, "US", ["Gallbladder Lumen"], "Right 9th/10th intercostal space traversing liver bare area", "8F - 10F Trocar pigtail catheter", "18G puncture needle, 0.035\" stiff J-wire, 8F/10F locking pigtail", "N/A", "8.5F Locking Pigtail Catheter", "Real-time ultrasound localized distended, thick-walled hydropic gallbladder. Transhepatic route through liver bed chosen to prevent peritoneal bile peritonitis. 18G needle entered gallbladder lumen; thick purulent bile aspirated. 0.035\" J-wire coiled in lumen. 8.5F locking pigtail catheter deployed, locked, and connected to drainage bag.", 4, "Bedrest x 4 hours. Keep bag dependent.", "Monitor vitals, site, and bile drainage q30m x 2h, then q1h.", "Bedside USG if pain or leakage.", "IV fluids 100 mL/hr.", ["IV Piperacillin-Tazobactam 4.5g TDS", "IV Tramadol 50mg SOS"], ["Peritonitis", "Bile leakage", "Catheter dislodgement"], "consent-cholecystostomy", None),
    
    # Portal HTN & TIPS
    ("cat03-hvpg-measurement", "Hepatic Venous Pressure Gradient (HVPG) Measurement", "Hepatic Venous Pressure Gradient (HVPG)", "1849-CV021A", "K76.6", 8000, "XA", ["Right Hepatic Vein", "IVC"], "Right IJV under US", "6F 11cm Sheath", "7F Balloon-tipped occlusion catheter, 0.035\" J-wire, pressure transducer", "N/A", "N/A", "Right IJV accessed; 6F sheath placed. 7F balloon catheter advanced into right hepatic vein. Free Hepatic Venous Pressure (FHVP) and IVC pressure recorded in triplicate. Balloon inflated; Wedged Hepatic Venous Pressure (WHVP) measured in triplicate with contrast verification of complete occlusion. HVPG calculated (WHVP - FHVP). Pressure tracings archived.", 2, "Bedrest x 2 hours; neck in neutral position.", "Check right neck site q15m x 1h, then q30m.", "None routine.", "Oral fluids allowed immediately.", ["Tab Paracetamol 650mg PO SOS"], ["Neck hematoma", "Airway compromise", "Stridor"], "consent-hvpg", "cigarroa_macd"),
    ("cat03-tips-viatorr", "Transjugular Intrahepatic Portosystemic Shunt (TIPS) with Viatorr Stent-Graft", "Transjugular Intrahepatic Portosystemic Shunt (TIPS)", "1849-IN060A", "K76.6", 65000, "XA", ["Right Hepatic Vein", "Right Branch of Portal Vein", "Main Portal Vein", "IVC"], "Right IJV under US", "10F 40cm TIPS Introducer Sheath", "16G Rosch-Uchida/Colapinto needle, 0.035\" stiff wire, 8mm/10mm PTA balloon", "2.7F microcatheter", "10mm x 70-80mm (2cm bare) Viatorr Controlled Expansion TIPS Endoprosthesis", "Right IJV access; 10F sheath advanced into right hepatic vein. Baseline FHVP and IVC pressures recorded. Transhepatic parenchymal puncture directed towards right portal vein bifurcation. Portal vein entered; portogram obtained. Portal pressure measured. Tract dilated with 8mm balloon. 10mm x 80mm Viatorr stent-graft deployed. Post-dilation with 8mm balloon. Portosystemic gradient decreased to <12 mmHg. Sheath removed; manual compression.", 4, "Strict supine bedrest x 4 hours; head elevated 30 degrees.", "Monitor neck site and vitals q15m x 1h, q30m x 2h, then q1h.", "Duplex Doppler Ultrasound of TIPS shunt at 24 hours to record baseline velocities.", "IV Normal Saline 75-100 mL/hr, strict fluid balance.", ["Syp Lactulose 30mL TDS", "Tab Rifaximin 550mg BD", "IV Ceftriaxone 1g BD x 48h"], ["Hepatic encephalopathy", "Intra-abdominal hemorrhage", "Acute right heart failure"], "consent-tips", "meld3_score"),
    ("cat03-dips-ivus", "Direct Intrahepatic Portocaval Shunt (DIPS) under IVUS", "Transjugular Intrahepatic Portosystemic Shunt (TIPS)", "1849-IN060A", "I82.0", 75000, "XA", ["Retrohepatic IVC", "Caudate Lobe", "Main Portal Vein"], "Right IJV under US", "10F 40cm TIPS Sheath", "IVUS catheter, 16G Colapinto needle, 0.035\" stiff Glidewire, 8mm/10mm balloon", "2.7F microcatheter", "10mm x 70-80mm Viatorr Stent-Graft", "Indicated for Budd-Chiari syndrome with total hepatic vein occlusion. 10F sheath placed in retrohepatic IVC. IVUS catheter advanced to identify portal vein bifurcation. 16G needle punctured anteriorly from IVC through caudate directly into portal vein. Wire secured in SMV. Tract dilated with 8mm balloon. 10mm Viatorr deployed from portal vein into retrohepatic IVC. Portosystemic gradient reduced to <10 mmHg.", 6, "Strict supine bedrest x 6 hours.", "Neck inspection, vitals and neuro checks q15m x 1h, q30m x 2h, then q1h.", "Duplex Doppler Ultrasound at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Syp Lactulose 30mL TDS", "Tab Rifaximin 550mg BD", "IV Ceftriaxone 1g BD"], ["Encephalopathy", "Abdominal distension", "Hypotension"], "consent-tips", "rotterdam_bcs"),
    ("cat03-tips-revision-angioplasty", "TIPS Shunt Revision with Balloon Angioplasty & Relining", "Transjugular Intrahepatic Portosystemic Shunt (TIPS)", "1849-IN060A", "K76.6", 40000, "XA", ["TIPS Shunt Lumen", "Hepatic Vein Outflow", "Portal Vein Inflow"], "Right IJV", "10F Vascular Sheath", "0.035\" Amplatz Super Stiff wire, 8mm-10mm x 40mm PTA balloon, 10mm Viatorr / covered stent", "N/A", "10mm x 60mm Stent-Graft (Viabahn / Viatorr)", "Right IJV access. TIPS shunt cannulated; baseline portosystemic gradient elevated at 18 mmHg. Shunt venogram showed pseudointimal hyperplasia and hepatic vein outflow stenosis. 8mm and 10mm high-pressure balloon dilation performed. A 10mm x 60mm stent-graft deployed relining the shunt from portal vein to IVC. Rest gradient normalized to 8 mmHg with brisk flow.", 4, "Bedrest x 4 hours.", "Vitals and neck check q15m x 1h, q30m x 2h.", "TIPS Doppler at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Syp Lactulose 30mL TDS", "Tab Rifaximin 550mg BD"], ["Encephalopathy", "Recurrent variceal bleed", "Groin/neck hematoma"], "consent-tips", "meld3_score"),
    
    # Budd-Chiari Syndrome Procedures
    ("cat03-bcs-hv-angioplasty", "Budd-Chiari Syndrome: Hepatic Vein Web Balloon Angioplasty", "Venoplasty", "1849-VS012A", "I82.0", 20000, "XA", ["Right / Middle Hepatic Vein Ostium", "Retrohepatic IVC"], "Right IJV or Right CFV", "8F 45cm Vascular Sheath", "5F MPA / Cobra, 0.035\" stiff Glidewire, 10-12mm x 40mm High-Pressure PTA Balloon", "N/A", "N/A", "Right IJV access; 8F sheath placed. Venogram showed focal web occlusion at right hepatic vein ostium with spider-web collaterals. Wire and 5F MPA manipulated across web into distal parenchymal hepatic vein. High trans-stenotic gradient (>15 mmHg) noted. Serial balloon dilatations with 10mm and 12mm high-pressure balloons effaced waist completely. Completion venogram demonstrated brisk clearance into IVC without collateral filling. Gradient reduced to <3 mmHg.", 4, "Bedrest for 4 hours.", "Neck puncture site check q15m x 1h, q30m x 2h.", "Hepatic Vein Doppler Ultrasound at 24 hours to confirm patency and triphasic flow.", "IV Normal Saline 75 mL/hr x 6h.", ["LMWH Enoxaparin 1mg/kg SC BD", "Tab Paracetamol 650mg SOS"], ["Sudden severe RUQ pain", "Neck hematoma", "Rapid recurrence of ascites"], "consent-bcs-angioplasty", "rotterdam_bcs"),
    ("cat03-bcs-hv-stenting", "Budd-Chiari Syndrome: Hepatic Vein Dedicated Venous Stenting", "Venous Stenting", "1849-VS014A", "I82.0", 35000, "XA", ["Right / Middle Hepatic Vein", "IVC"], "Right IJV or Transhepatic access", "9F-10F 45cm Sheath", "0.035\" Amplatz Super Stiff wire, 12-14mm x 60mm self-expanding venous stent (Venovo / Abre)", "N/A", "14mm x 60mm Self-Expanding Nitinol Venous Stent", "Indicated for recurrent/elastic stenosis of hepatic vein in Budd-Chiari failing POBA. Right IJV access. Hepatic vein cannulated across focal stricture onto Amplatz wire. Pre-dilation with 10mm balloon showed significant recoil (>50%). 14mm x 60mm self-expanding Nitinol venous stent deployed across ostial lesion extending 3-5mm into IVC. Post-dilated with 12mm balloon. Completion venogram showed brisk inline drainage. Rest gradient normalized to 2 mmHg.", 4, "Supine bedrest x 4 hours.", "Vitals and neck site checks q30m x 2h, then q1h.", "Hepatic Vein Doppler Ultrasound at 24 hours.", "IV Normal Saline 75 mL/hr.", ["LMWH Enoxaparin 1mg/kg BD bridging to oral anticoagulation", "Tab Pantoprazole 40mg OD"], ["RUQ pain", "Hematoma", "Dyspnea"], "consent-bcs-angioplasty", "rotterdam_bcs"),
    ("cat03-bcs-ivc-cavoplasty", "Budd-Chiari Syndrome: IVC Balloon Cavoplasty", "Venoplasty", "1849-VS012A", "I82.0", 22000, "XA", ["Inferior Vena Cava (Retrohepatic)", "Right Atrium"], "Right CFV under US", "10F - 12F 45cm Sheath", "0.035\" stiff wire, 18mm - 24mm x 40mm Large Diameter PTA Balloon (Atlas Gold / XXL)", "N/A", "N/A", "Right CFV accessed; 10F sheath placed. Cavography revealed critical membranous stenosis of retrohepatic IVC with extensive collaterals. Pull-through gradient between distal IVC and RA was 24 mmHg. 0.035\" Amplatz wire crossed into RA. Sequential cavoplasty performed with 18mm and 20mm balloons until waist fully abolished. Repeat cavogram showed rapid contrast clearance into RA with disappearance of collateral flow. Pull-through gradient decreased to <3 mmHg. Sheath removed; manual compression hemostasis.", 6, "Strict supine flat bedrest x 6 hours; right leg straight.", "Monitor right groin for hematoma or bleeding; check distal pulses q15m x 1h, q30m x 2h, then q1h.", "IVC Doppler Ultrasound at 24 hours.", "IV Normal Saline 100 mL/hr x 6h.", ["LMWH Enoxaparin 1mg/kg SC BD", "Tab Paracetamol 650mg SOS"], ["Groin hematoma / pseudoaneurysm", "Severe back pain", "Bilateral lower extremity edema"], "consent-bcs-angioplasty", "rotterdam_bcs"),
    ("cat03-bcs-ivc-stenting", "Budd-Chiari Syndrome: Inferior Vena Cava (IVC) Dedicated Stenting", "Venous Stenting", "1849-VS014A", "I82.0", 45000, "XA", ["Retrohepatic / Suprahepatic IVC", "Cavoatrial Junction"], "Right CFV and Right IJV", "12F - 14F Long Vascular Sheath", "0.035\" Lunderquist Extra Stiff wire, 20-24mm x 60-80mm Large Caliber Stent", "N/A", "22mm x 70mm Self-Expanding IVC Stent", "Indicated for long-segment severe retrohepatic IVC occlusion in Budd-Chiari syndrome unresponsive to POBA alone. Bilateral femoral/jugular access. Lesion crossed and pre-dilated. A 22mm x 70mm large caliber self-expanding IVC stent deployed across retrohepatic obstruction ensuring upper edge sits precisely at cavoatrial junction. Post-dilation performed with 20mm balloon. Cavography confirmed widely patent IVC channel with immediate hemodynamic relief. Gradient dropped from 22 mmHg to 2 mmHg.", 6, "Strict bedrest x 6 hours.", "Groin check q15m x 1h, q30m x 2h, then q1h.", "Doppler USG of IVC and liver at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Therapeutic LMWH bridging to long-term Warfarin/DOAC (target INR 2.0-3.0)"], ["Groin bleeding", "Cardiac arrhythmia", "Hypotension"], "consent-bcs-angioplasty", "rotterdam_bcs"),
    ("cat03-bcs-sharp-recanalization", "Budd-Chiari Syndrome: Sharp Recanalization of Occluded Hepatic Vein / IVC", "Venoplasty", "1849-VS012A", "I82.0", 42000, "XA", ["Occluded Hepatic Vein", "Retrohepatic IVC"], "Dual Right IJV and Transhepatic Access under US/Fluoro", "8F Sheaths", "Transjugular Colapinto needle / Chiba needle, Rösch-Uchida set, Gooseneck Snare, 0.035\" Glidewire", "N/A", "10mm-12mm Venous Stent", "For chronic complete fibrotic occlusion of hepatic vein in Budd-Chiari syndrome where standard wire navigation failed. Simultaneous access via right IJV and percutaneous transhepatic route. Transhepatic catheter positioned in proximal patent vein stump, while IJV catheter with target snare positioned in IVC at expected ostium. Under biplane fluoroscopic alignment, Chiba/Colapinto needle punctured sharply from hepatic vein across fibrotic septum directly into snare in IVC. Wire captured with snare and pulled through IJV creating continuous through-and-through circuit. Serial balloon angioplasty and 10mm dedicated stent deployed restoring venous drainage.", 6, "Strict supine bedrest x 6 hours.", "Surveillance of neck and transhepatic puncture sites q15m x 1h, q30m x 2h, then q1h.", "Immediate bedside USG and Doppler USG at 24h.", "IV Normal Saline 100 mL/hr.", ["Therapeutic LMWH Enoxaparin 1mg/kg BD", "IV Ceftriaxone 1g BD"], ["Severe intraperitoneal hemorrhage / hemoperitoneum", "Puncture outside vascular lumen", "Acute shock"], "consent-bcs-angioplasty", "rotterdam_bcs"),

    # Variceal & Collateral Embolization (BRTO, PARTO, CARTO, Glue, Coils+Glue, Veno-Venous)
    ("cat03-brto-varices", "Balloon-Occluded Retrograde Transvenous Obliteration (BRTO) of Gastric Varices", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I85.0", 35000, "XA", ["Gastrorenal Shunt", "Fundic Gastric Varices", "Left Renal Vein"], "Right CFV or Right IJV", "8F - 9F 45cm Ansel Sheath", "5F Cobra, 8.5F Occlusion Balloon Catheter (10-12mm), 2.7F microcatheter, 0.014\" wire", "2.7F microcatheter", "3% STS Foam Sclerosant mixed with Lipiodol (1:1 ratio)", "Right CFV accessed; 8F sheath placed. Left renal venogram identified large gastrorenal shunt draining fundic gastric varices. An 8.5F occlusion balloon catheter navigated into outflow of gastrorenal shunt. Balloon inflated until complete occlusion confirmed on retrograde venography. Retrograde varicography mapped variceal complex and excluded non-target collaterals. A 2.7F microcatheter advanced into varices. 18 mL of 3% STS foam sclerosant mixed with Lipiodol (1:1 ratio) slowly injected under continuous fluoroscopy until variceal complex filled. Occlusion balloon maintained inflated for 45 minutes. Sclerosant aspirated; balloon deflated. Completion venography confirmed complete thrombosis of gastric varices.", 6, "Strict flat supine bedrest x 6 hours; right leg straight.", "Monitor groin access site for bleeding or hematoma; check distal pulses q15m x 1h, q30m x 2h, then q1h.", "Follow-up Contrast CT Abdomen or Upper GI Endoscopy at 4-6 weeks to document variceal eradication.", "IV Normal Saline 100 mL/hr x 8 hours to promote renal clearance.", ["IV Pantoprazole 40mg BD", "IV Ceftriaxone 1g BD x 3 days", "Tab Paracetamol 650mg TDS"], ["Severe hematemesis / melena", "Hemoglobinuria (hemolysis)", "Left flank pain (renal vein thrombosis)"], "consent-brto-parto", "meld3_score"),
    ("cat03-parto-varices", "Plug-Assisted Retrograde Transvenous Obliteration (PARTO) of Gastric Varices", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I85.0", 38000, "XA", ["Gastrorenal Shunt", "Gastric Fundic Varices"], "Right CFV", "8F 45cm Sheath", "5F Cobra, 0.035\" stiff wire, 2.7F microcatheter, Amplatzer Vascular Plug II (10-14mm)", "2.7F microcatheter", "Amplatzer Vascular Plug II (AVP II) and Gelfoam sponge slurry / 3% STS foam", "Right CFV access. 8F sheath advanced into gastrorenal shunt. Sizing venography determined narrowest shunt diameter to be 9mm. An Amplatzer Vascular Plug II (12mm, 30-50% oversizing) deployed in the distal narrow segment of gastrorenal shunt. Through a 2.7F microcatheter passed through or alongside plug into gastric varices, gelfoam sponge slurry and 3% STS sclerosant foam were injected until complete stasis achieved within gastric fundic varices. Plug detached. No post-procedure balloon indwelling required. Rapid permanent obliteration confirmed.", 6, "Strict supine bedrest x 6 hours; access leg straight.", "Monitor groin puncture site q15m x 1h, q30m x 2h, then q1h.", "Abdominal Doppler USG / CT at 4 weeks.", "IV Normal Saline 75-100 mL/hr.", ["IV Pantoprazole 40mg BD", "Tab Paracetamol 650mg SOS"], ["Active GI bleeding", "Groin hematoma", "Flank pain"], "consent-brto-parto", "meld3_score"),
    ("cat03-carto-varices", "Coil-Assisted Retrograde Transvenous Obliteration (CARTO) of Gastric Varices", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I85.0", 36000, "XA", ["Gastrorenal Shunt", "Gastric Fundic Varices"], "Right CFV", "7F - 8F Sheath", "5F Cobra, 2.7F microcatheter, 0.014\" wire, 0.035\" and 0.018\" detachable/pushable microcoils", "2.7F microcatheter", "Detachable fibered coils (8-14mm) + 3% STS foam sclerosant", "Right CFV access; 8F sheath placed. Left renal vein and gastrorenal shunt cannulated. Gastrorenal shunt outflow packed densely with 0.035\" and 0.018\" fibered metallic microcoils (CARTO technique) creating flow restriction matrix. Through microcatheter positioned deep to coil pack, 3% STS foam sclerosant mixed with Lipiodol injected directly into gastric variceal lumen until complete stagnation. Final venography showed complete occlusion of shunt and varices.", 6, "Strict supine bedrest x 6 hours.", "Check puncture site and distal pulses q15m x 1h, q30m x 2h, then q1h.", "CT Abdomen at 4 weeks to verify variceal sclerosis.", "IV Normal Saline 75 mL/hr.", ["IV Pantoprazole 40mg BD", "Tab Paracetamol 650mg SOS"], ["Hematemesis", "Melena", "Groin swelling"], "consent-brto-parto", "meld3_score"),
    ("cat03-glue-varices", "Cyanoacrylate Glue (n-BCA / Histoacryl) Variceal Embolization", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I85.0", 34000, "XA", ["Gastroesophageal Varices", "Portosystemic Collateral Nidus"], "Transjugular (via TIPS/IJV) or Transhepatic Access", "6F - 7F Sheath", "5F Simmons / Cobra, 2.7F microcatheter, 0.014\" microwire, 5% Dextrose flush", "2.7F microcatheter", "n-Butyl Cyanoacrylate (n-BCA) glue mixed with Lipiodol (1:1 to 1:2 ratio)", "Indicated for active bleeding or secondary prophylaxis of large gastroesophageal varices. Portal venous access achieved via transjugular/TIPS route. Selective catheterization of coronary vein / left gastric vein using 5F Cobra and 2.7F microcatheter. Varicography mapped inflow and draining channels. Microcatheter advanced into variceal nidus. Microcatheter thoroughly flushed with 5% Dextrose (D5W) to remove all ionic flush. Under high-resolution subtraction fluoroscopy, 3.0 mL of n-BCA cyanoacrylate glue mixed with Lipiodol (1:1.5 ratio) injected rapidly into varices until complete solid cast formed. Microcatheter immediately withdrawn in single swift motion to prevent glue adherence to catheter tip. Repeat portogram demonstrated total occlusion of bleeding varices with patent main portal flow.", 4, "Bedrest for 4 hours.", "Puncture site and vitals surveillance q15m x 1h, q30m x 2h, then q1h.", "Chest X-ray to confirm absence of non-target pulmonary glue embolization; Endoscopy at 4 weeks.", "IV Normal Saline 75 mL/hr.", ["IV Pantoprazole 40mg BD", "IV Ceftriaxone 1g BD"], ["Pleuritic chest pain / dyspnea (pulmonary glue embolus)", "Upper GI bleed", "Fever"], "consent-bcs-embolization", "meld3_score"),
    ("cat03-coils-plus-glue-collaterals", "Combined Coils Plus Cyanoacrylate Glue Embolization of Portosystemic Collaterals", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I85.0", 40000, "XA", ["Left Gastric Vein", "Posterior Gastric Veins", "Splenorenal Collaterals"], "Transjugular (TIPS access) or Transhepatic Puncture", "7F Sheath", "5F Cobra, 2.7F microcatheter, 0.014\" wire, microcoils (4mm-8mm), D5W flush", "2.7F microcatheter", "Detachable / Pushable Microcoils (0.018\") + n-BCA glue / Lipiodol (1:2 ratio)", "Indicated for high-flow portosystemic collaterals causing variceal hemorrhage or shunt encephalopathy. Portal venous system accessed. Left gastric / posterior gastric collateral cannulated. Because of high-velocity flow, distal coil scaffold placed using three 0.018\" fibered microcoils to reduce flow velocity and anchor embolic agent. Through the microcatheter flushed with non-ionic D5W, 2.5 mL of n-BCA cyanoacrylate glue + Lipiodol (1:2 ratio) was delivered behind the coil scaffold. The glue polymerized rapidly within the coil mesh, achieving instantaneous, solid, durable closure without distal systemic glue migration. Completion run confirmed total collateral obliteration.", 4, "Bedrest for 4 hours.", "Access site surveillance q15m x 1h, q30m x 2h, then q1h.", "Chest X-ray to document coil/glue stability and rule out pulmonary migration.", "IV Normal Saline 75 mL/hr.", ["IV Pantoprazole 40mg BD", "Tab Paracetamol 650mg SOS"], ["Chest pain", "Hemoptysis", "Melena"], "consent-bcs-embolization", "meld3_score"),
    ("cat03-bcs-veno-venous-collateral-coiling-glue", "Budd-Chiari Syndrome: Intrahepatic Veno-Venous Collateral Embolization using Microcoils and Glue", "Percutaneous Transvenous Embolization / Obliteration of Varices", "1849-IN061A", "I82.0", 38000, "XA", ["Intrahepatic Veno-Venous Collateral Veins", "Accessory Hepatic Veins", "IVC"], "Right IJV or Transhepatic Parenchymal Approach under US", "6F - 7F Sheath", "5F MPA / Cobra, 2.0F / 2.7F microcatheter, 0.014\" microguidewire", "2.0F / 2.7F microcatheter", "Detachable 0.014\"/0.018\" Microcoils + Cyanoacrylate Glue (n-BCA) with Lipiodol (1:2 ratio)", "In Budd-Chiari syndrome with persistent steal or shunt insufficiency due to prominent tortuous intrahepatic veno-venous collaterals, transhepatic/transjugular access was established. Diagnostic venography delineated extensive large-caliber intrahepatic veno-venous bypass channels diverting flow away from revascularized hepatic veins. A 2.0F microcatheter was navigated superselectively into dominant communicating venous channel. Detachable microcoils were deployed to create an embolic nest, followed by slow injection of n-BCA glue and Lipiodol mixture (1:2 ratio) after D5W flush. Complete occlusive thrombosis of the collateral circuit was achieved with redirection of hepatopetal and hepatic venous outflow through primary stented hepatic vein. Rest run showed excellent parenchymal perfusion without residual collateral runoff.", 4, "Strict supine bedrest x 4 hours.", "Monitor neck / transhepatic puncture site q15m x 1h, q30m x 2h, then q1h.", "Hepatic Doppler USG at 24 hours to assess hepatic vein velocity and flow pattern.", "IV Normal Saline 75 mL/hr x 6 hours.", ["Therapeutic LMWH (Enoxaparin 1mg/kg BD)", "Tab Paracetamol 650mg SOS"], ["Sudden severe RUQ pain", "Hypotension", "Increasing ascites"], "consent-bcs-embolization", "rotterdam_bcs"),

    # Portal Vein Interventions & Spleen
    ("cat03-pve-ipsilateral", "Portal Vein Embolization (PVE) - Ipsilateral Approach", "Portal Vein Embolization (PVE)", "1849-IN062A", "K76.8", 35000, "XA", ["Right Portal Vein Branches (Segments 5, 6, 7, 8)", "Main Portal Vein"], "Right intercostal transhepatic US puncture", "6F 11cm Sheath", "21G Chiba, 0.018\" wire, 0.035\" Glidewire, 5F Cobra, 2.7F microcatheter", "2.7F microcatheter", "PVA particles (300-500um), n-BCA glue + Lipiodol (1:5 ratio), or Amplatzer Plugs / Coils", "Indicated to induce future liver remnant (FLR) hypertrophy prior to extended right hepatectomy. Right portal branch accessed under US with 21G Chiba; 6F sheath placed. Portography mapped right and left portal systems and confirmed adequate FLR branch anatomy (Segments 2, 3, 4). 5F Cobra and 2.7F microcatheter advanced selectively into Segment 5/8 and 6/7 branches. Embolization performed using PVA particles (300-500um) followed by n-BCA glue-Lipiodol mixture (1:5 ratio) and vascular plugs/coils. Care taken to strictly spare Segment 4 and left portal branches. Completion portogram demonstrated total occlusion of right portal branches with brisk diverted flow into left portal vein. Puncture tract plugged with gelfoam slurry.", 4, "Right lateral decubitus x 2 hours, then supine bedrest x 2 hours.", "Vitals and abdominal checks q15m x 1h, q30m x 2h, then q1h.", "Volumetric CT Abdomen at 3-4 weeks to calculate Future Liver Remnant (FLR) hypertrophy rate.", "IV Normal Saline 100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Paracetamol 650mg TDS PRN"], ["Peritonitis", "High fever", "Drop in Hb"], "consent-pve", "cigarroa_macd"),
    ("cat03-pve-contralateral", "Portal Vein Embolization (PVE) - Contralateral Approach", "Portal Vein Embolization (PVE)", "1849-IN062A", "K76.8", 35000, "XA", ["Right Portal Vein Branches", "Left Portal Vein Trunk"], "Subxiphoid transhepatic left lobe puncture (Segment 3)", "6F 25cm Long Sheath", "21G Chiba, 0.035\" stiff wire, 5F reverse curve catheter, 2.7F microcatheter", "2.7F microcatheter", "Microcoils + PVA Particles (300-500um) + n-BCA Glue", "Puncture of left Segment 3 portal branch under real-time ultrasound. Reverse curve catheter advanced across confluence into right anterior and posterior portal branches. Embolization executed using microcoils and glue. Subxiphoid sheath removed; tract plugged with gelfoam torpedo.", 4, "Bedrest x 4 hours.", "Vitals and site check q30m x 2h, then q1h.", "Volumetric CT at 3-4 weeks.", "IV Normal Saline 100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Paracetamol 650mg TDS"], ["Subcapsular hematoma", "Peritoneal irritation", "Sepsis"], "consent-pve", "cigarroa_macd"),
    ("cat03-hepatic-vein-deprivation", "Hepatic Vein Deprivation (HVD / Bi-Embolization)", "Portal Vein Embolization (PVE)", "1849-IN062A", "K76.8", 45000, "XA", ["Right Portal Vein Branches", "Right Hepatic Vein", "Accessory Right Hepatic Vein"], "Right transhepatic (portal) and Right IJV (hepatic vein)", "6F and 8F Sheaths", "0.035\" stiff wires, 5F catheters, 2.7F microcatheters, vascular plugs", "2.7F microcatheter", "Amplatzer Vascular Plugs (AVP II 14-18mm) + n-BCA glue and Lipiodol", "Combined simultaneous portal and hepatic venous embolization (HVD) to accelerate future liver remnant hypertrophy. Right portal vein embolized with PVA and n-BCA. Right IJV accessed; 8F sheath placed in right hepatic vein. An Amplatzer Vascular Plug II deployed in right hepatic vein 15mm from IVC junction, followed by n-BCA glue injection. Total inflow and outflow occlusion of right liver achieved.", 4, "Strict bedrest x 4 hours.", "Vitals and dual puncture site checks q15m x 1h, q30m x 2h, then q1h.", "Volumetric CT Abdomen at 14-21 days (demonstrating rapid FLR growth).", "IV Normal Saline 100 mL/hr.", ["IV Ceftriaxone 1g BD", "Tab Paracetamol 650mg TDS"], ["Severe hepatic necrosis pain", "Ascites", "Fever"], "consent-pve", "cigarroa_macd"),
    ("cat03-pv-recanalization-stent-ehpvo", "Portal Vein Recanalization & Stenting for Chronic Extrahepatic Portal Vein Obstruction (EHPVO)", "Venous Stenting", "1849-VS014A", "I81", 45000, "XA", ["Cavernous Portal Vein", "Splenic Vein", "SMV Junction"], "Transhepatic or Transsplenic Access under US", "7F - 8F 45cm Sheath", "0.035\" Terumo Glidewire, 5F Kumpe, 8mm-10mm x 40-60mm dedicated self-expanding venous stent", "N/A", "10mm x 60mm Self-Expanding Nitinol Stent (Venovo / Abre)", "Transsplenic/transhepatic puncture into cavernous portal system. Hydrophilic guidewire navigated across chronic fibrous occlusion into SMV/splenic vein confluence. Serial balloon dilatations performed with 6mm and 8mm balloons. 10mm x 60mm self-expanding venous stent deployed restoring inline hepatopetal portal flow. Portosystemic collateral decompression confirmed. Puncture tract sealed with coils/glue.", 6, "Strict flat bedrest x 6 hours; left lateral decubitus for spleen pressure x 2 hours.", "Continuous vitals and puncture site monitoring q15m x 1h, q30m x 2h, then q1h.", "Portal Doppler USG at 24 hours.", "IV Normal Saline 100 mL/hr.", ["Therapeutic LMWH Enoxaparin 1mg/kg BD", "IV Ceftriaxone 1g BD"], ["Intraperitoneal bleeding", "Splenic subcapsular hematoma", "Portal re-thrombosis"], "consent-pv-stent", "cigarroa_macd"),
    ("cat03-splenic-artery-embolization-partial", "Partial Splenic Artery Embolization (PSE) for Hypersplenism / Portal HTN", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "D73.1", 25000, "XA", ["Splenic Artery Lower / Mid Pole Branches"], "Right CFA at femoral head level", "5F 11cm Sheath", "5F Cobra / Simmons, 2.7F microcatheter, 0.014\" wire", "2.7F microcatheter", "PVA particles (500-700um) or Gel-foam torpedoes / microcoils", "Right CFA accessed. Celiac angiogram performed; splenic artery cannulated with 5F Cobra. 2.7F microcatheter advanced superselectively into lower pole and mid-pole intrasplenic branches, strictly sparing the upper pole (aiming for 50-60% splenic volume infarction). Embolization performed using 500-700um PVA particles until focal stasis achieved. Completion angiogram showed preserved upper pole perfusion. Sheath removed; manual compression hemostasis.", 6, "Strict flat bedrest x 6 hours; right leg straight.", "Monitor groin and left upper quadrant pain; vitals q15m x 1h, q30m x 2h, then q1h.", "Bedside USG / CT abdomen if severe splenic pain or sepsis.", "IV Normal Saline 100 mL/hr x 12 hours.", ["IV Tramadol 50mg TDS + Paracetamol 1g TDS (Post-Embolization Syndrome protocol)", "IV Ceftriaxone 1g BD x 5 days", "Cap Pantoprazole 40mg OD"], ["Splenic abscess", "Splenic rupture", "Pleural effusion / left basal atelectasis"], "consent-splenic-embolization", "cigarroa_macd"),
    ("cat03-splenic-artery-embolization-proximal", "Proximal Splenic Artery Embolization for Portal Overperfusion", "Transcatheter Arterial Embolization (TAE)", "1849-IN063A", "K76.6", 28000, "XA", ["Main Splenic Artery Trunk (Mid-segment)"], "Right CFA", "6F Sheath", "5F Cobra, 0.035\" wire, Amplatzer Vascular Plug II (8-12mm) or large 0.035\" coils", "N/A", "Amplatzer Vascular Plug II (AVP II 10mm) or 0.035\" Gianturco Coils", "Celiac angiogram confirmed massive splenomegaly with severe portal hyperflow. 6F sheath placed in proximal splenic artery distal to dorsal pancreatic artery origin and proximal to pancreatica magna. An Amplatzer Vascular Plug II deployed. Angiogram showed flow dampening with preserved distal parenchymal perfusion via short gastric and gastroepiploic collaterals. Groin closed.", 6, "Strict flat bedrest x 6 hours.", "Groin checks and distal pulses q15m x 1h, q30m x 2h, then q1h.", "Doppler USG at 24 hours.", "IV Normal Saline 75 mL/hr.", ["Tab Paracetamol 650mg TDS PRN", "Cap Pantoprazole 40mg OD"], ["Groin hematoma", "Splenic infarction", "Fever"], "consent-splenic-embolization", "cigarroa_macd"),
]

print(f"Cat 03 has {len(CAT03_LIST)} procedures prepared.")

def generate_cat03():
    procs = []
    for item in CAT03_LIST:
        pid, title, pkg_name, pkg_code, icd10, tariff, mod, anat, access, sheath, cath, micro, embolic, narr, immo_h, immo_inst, hem, img, hyd, meds, red, consent, calc = item
        procs.append(create_proc(
            pid=pid, cat_num=3, cat_name="Hepatobiliary & Portal Interventions",
            title=title, scheme_name="BOTH", pkg_name=pkg_name, pkg_code=pkg_code,
            icd10=icd10, tariff=tariff, modality=mod, anatomy=anat,
            sedation="Local Anesthesia with IV Conscious Sedation",
            access=access, sheath=sheath, catheters=cath, micro=micro, embolic=embolic,
            narrative=narr, immo_hours=immo_h, immo_inst=immo_inst, hematoma=hem,
            img=img, hydration=hyd, meds=meds, red_flags=red, consent=consent, calc=calc
        ))
    write_category_file("category03_hpb_portal.ts", "CATEGORY_03_HPB_PORTAL", 3, "Hepatobiliary & Portal Interventions", procs)

if __name__ == "__main__":
    generate_cat03()
