import { MasterHardwareItem } from "./types";

/**
 * SMS Hospital Jaipur - Interventional Radiology Cath-Lab Consumables Catalog
 * Strictly authentic inventory maintained in SMS DSA Angiosuite.
 */
export const MASTER_HARDWARE_CATALOG: MasterHardwareItem[] = [
  {
    "id": "ndl-01",
    "sku": "RMSCL-SURG-CHIBA-18G",
    "name": "Chiba Biopsy / Puncture Needle 18G 15cm",
    "imageUrl": "/images/hardware/ndl-01.jpg",
    "category": "Needles & Biopsy",
    "specification": "18 Gauge x 15 cm Echogenic Bevel Tip Thin-Wall Access Needle",
    "frenchOrGauge": "18G",
    "lengthOrDiameter": "15 cm",
    "manufacturer": "Cook Medical",
    "brandName": "Chiba",
    "boxColor": {
      "primary": "#8B0000",
      "secondary": "#1A202C",
      "accent": "#E53E3E",
      "text": "#FFFFFF",
      "badgeBg": "#FFF5F5",
      "badgeText": "#9B2C2C"
    },
    "packagingType": "BOX",
    "productSilhouette": "NEEDLE",
    "brochureHighlights": [
      "Micro-etched echogenic tip provides sharp ultrasound acoustic reflection at steep angles",
      "Thin-wall cannula architecture maximizes inner lumen clearance for smooth 0.035 in wire passage",
      "Color-coded ergonomic Luer hub with precision depth stop and calibrated centimeter graduations"
    ],
    "clinicalIndications": "Direct percutaneous access, initial abdominal/visceral puncture, PTBD, and fluid collection aspiration",
    "currentStock": 18,
    "reorderLevel": 8,
    "unit": "Needles",
    "rmsclMatchingCode": "RMSCL-SURG-CHIBA-18G",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 1250,
    "lastLot": "LOT-CK-882194",
    "expiryDate": "2028-11-30",
    "ifuHighlights": "Inspect needle shaft for straightness. Advance under real-time ultrasound or fluoroscopic guidance."
  },
  {
    "id": "ndl-02",
    "sku": "RMSCL-SURG-CHIBA-21G",
    "name": "Chiba Fine Micropuncture Needle 21G 15cm",
    "imageUrl": "/images/hardware/ndl-02.jpg",
    "category": "Needles & Biopsy",
    "specification": "21 Gauge x 15 cm Ultra-Thin Fine Needle for 0.018 in Guidewire Entry",
    "frenchOrGauge": "21G",
    "lengthOrDiameter": "15 cm",
    "manufacturer": "Cook Medical",
    "brandName": "Micropuncture Chiba",
    "boxColor": {
      "primary": "#7B1FA2",
      "secondary": "#212121",
      "accent": "#AB47BC",
      "text": "#FFFFFF",
      "badgeBg": "#F3E5F5",
      "badgeText": "#6A1B9A"
    },
    "packagingType": "BOX",
    "productSilhouette": "NEEDLE",
    "brochureHighlights": [
      "Ultra-fine 21G bevel minimizes bleeding risk during non-dilated intrahepatic bile duct puncture",
      "Seamlessly accepts 0.018 in platinum-tipped starter guidewires",
      "High-tensile surgical stainless steel prevents cannula buckling during deep parenchymal traversal"
    ],
    "clinicalIndications": "Left hepatic duct puncture, pediatric vascular access, non-dilated renal calyx access",
    "currentStock": 14,
    "reorderLevel": 6,
    "unit": "Needles",
    "rmsclMatchingCode": "RMSCL-SURG-CHIBA-21G",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 950,
    "lastLot": "LOT-CK-910283",
    "expiryDate": "2028-09-30",
    "ifuHighlights": "Ideal for initial parenchymal entry before converting to 4F/6F sheath via transition dilator."
  },
  {
    "id": "wir-01",
    "sku": "RMSCL-SURG-GLIDE-150A",
    "name": "Radifocus Guidewire M Hydrophilic 0.035 in 150cm Angled",
    "imageUrl": "/images/hardware/wir-01.jpg",
    "category": "Guidewires",
    "specification": "0.035 inch x 150 cm Polyurethane Jacket with Hydrophilic M-Coat Angled Tip",
    "frenchOrGauge": "0.035\"",
    "lengthOrDiameter": "150 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Radifocus Glidewire",
    "boxColor": {
      "primary": "#007A3E",
      "secondary": "#1C1C1C",
      "accent": "#B78727",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#137333"
    },
    "packagingType": "DISPENSER_TUBE",
    "productSilhouette": "WIRE",
    "brochureHighlights": [
      "Super-elastic nitinol alloy core provides extreme kink resistance and 1:1 torque responsiveness",
      "Pioneering cross-linked M-Coat hydrophilic surface provides near-frictionless vessel navigation",
      "Atraumatic tapered tungsten-infused radiopaque polyurethane tip provides superb fluoroscopic visibility"
    ],
    "clinicalIndications": "Standard visceral selection, peripheral roadmapping, crossing tortuous vessels, catheter exchanges",
    "currentStock": 32,
    "reorderLevel": 12,
    "unit": "Wires",
    "rmsclMatchingCode": "RMSCL-SURG-GLIDE-150A",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 2400,
    "lastLot": "LOT-TR-994821",
    "expiryDate": "2029-01-31",
    "ifuHighlights": "Always keep wire wet with heparinized normal saline. Never retract through an uncovered metal needle bevel."
  },
  {
    "id": "wir-02",
    "sku": "RMSCL-SURG-GLIDE-260S",
    "name": "Radifocus Guidewire Stiff Hydrophilic 0.035 in 260cm",
    "imageUrl": "/images/hardware/wir-02.png",
    "category": "Guidewires",
    "specification": "0.035 inch x 260 cm Stiff Shaft Nitinol Core with Hydrophilic M-Coat",
    "frenchOrGauge": "0.035\"",
    "lengthOrDiameter": "260 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Glidewire Stiff",
    "boxColor": {
      "primary": "#006233",
      "secondary": "#1C1C1C",
      "accent": "#E2B93B",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#006233"
    },
    "packagingType": "DISPENSER_TUBE",
    "productSilhouette": "WIRE",
    "brochureHighlights": [
      "Enhanced stiff nitinol core transitions into a soft 3 cm atraumatic angled radiopaque tip",
      "Extended 260 cm exchange length supports long balloon/stent catheter delivery over the wire",
      "Superior backup support in tortuous iliacs and visceral arteries without vessel straightening trauma"
    ],
    "clinicalIndications": "Long sheath delivery, PTA balloon exchanges, EVAR contralateral leg cannulation, TIPS tracking",
    "currentStock": 16,
    "reorderLevel": 6,
    "unit": "Wires",
    "rmsclMatchingCode": "RMSCL-SURG-GLIDE-260S",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 3400,
    "lastLot": "LOT-TR-881904",
    "expiryDate": "2028-10-31",
    "ifuHighlights": "Maintain wire tip fluoroscopy at all times during rapid over-the-wire catheter exchanges."
  },
  {
    "id": "itm-04",
    "sku": "RMSCL-SURG-SHEATH-6F",
    "name": "Radifocus Introducer II 6F 11cm",
    "imageUrl": "/images/hardware/itm-04.jpg",
    "category": "Access Sheaths",
    "specification": "6 French x 11 cm Cross-Cut Hemostatic Valve Sheath with 0.035 in Dilator",
    "frenchOrGauge": "6F",
    "lengthOrDiameter": "11 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Radifocus Introducer II",
    "boxColor": {
      "primary": "#007A3E",
      "secondary": "#1C1C1C",
      "accent": "#B78727",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#137333"
    },
    "packagingType": "BOX",
    "productSilhouette": "SHEATH",
    "brochureHighlights": [
      "Seamless dilator-to-sheath taper minimizes puncture resistance and femoral hematoma rate",
      "Cross-cut hemostatic seal withstands up to 250 psi backpressure with zero blood weeping",
      "Smooth sidearm with 3-way stopcock for continuous arterial line pressure monitoring and flushing"
    ],
    "clinicalIndications": "Standard common femoral artery and vein access for visceral, peripheral, and neuro procedures",
    "currentStock": 22,
    "reorderLevel": 10,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-SHEATH-6F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 1250,
    "lastLot": "LOT-TR-7821940",
    "expiryDate": "2028-06-30",
    "ifuHighlights": "Ensure J-tip guidewire exits dilator tip before advancing sheath unit through skin and arterial wall."
  },
  {
    "id": "sth-03",
    "sku": "RMSCL-SURG-SLENDER-6F",
    "name": "Glidesheath Slender 6F Transradial Access Sheath",
    "imageUrl": "/images/hardware/sth-03.jpg",
    "category": "Access Sheaths",
    "specification": "6 French x 10 cm Thin-Wall Radial Sheath (Outer Diameter Equivalent to 5F)",
    "frenchOrGauge": "6F (5F OD)",
    "lengthOrDiameter": "10 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Glidesheath Slender",
    "boxColor": {
      "primary": "#D69E2E",
      "secondary": "#1C1C1C",
      "accent": "#ECC94B",
      "text": "#FFFFFF",
      "badgeBg": "#FEFCBF",
      "badgeText": "#744210"
    },
    "packagingType": "BOX",
    "productSilhouette": "SHEATH",
    "brochureHighlights": [
      "Unique thin-wall design: 6F internal lumen delivers 6F catheters while maintaining 5F outer footprint",
      "Significantly reduces radial artery spasm, occlusion, and access site hematoma in transradial IR",
      "Fully coated with hydrophilic M-coat for frictionless radial artery entry"
    ],
    "clinicalIndications": "Transradial uterine artery embolization (TR-UAE), hepatic TACE, mesenteric revascularization",
    "currentStock": 12,
    "reorderLevel": 5,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-SLENDER-6F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 2800,
    "lastLot": "LOT-TR-220194",
    "expiryDate": "2028-10-31",
    "ifuHighlights": "Administer radial cocktail (Verapamil 2.5mg + Nitroglycerin 200mcg + Heparin 5000U) via sideport immediately."
  },
  {
    "id": "cat-01",
    "sku": "RMSCL-SURG-COBRA-5F",
    "name": "Super Torque Plus Cobra Catheter 5F 65cm (C2)",
    "imageUrl": "/images/hardware/cat-01.png",
    "category": "Diagnostic Catheters",
    "specification": "5 French x 65 cm Polyurethane Braided Angiographic Catheter (Cobra C2 Curve)",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "65 cm",
    "manufacturer": "Cordis",
    "brandName": "Super Torque Cobra",
    "boxColor": {
      "primary": "#1A365D",
      "secondary": "#1A202C",
      "accent": "#3182CE",
      "text": "#FFFFFF",
      "badgeBg": "#EBF8FF",
      "badgeText": "#2B6CB0"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "High-density wire braided polyurethane wall delivers 100% 1:1 rotational responsiveness",
      "Classic C2 curve seats selectively into descending branch origins: Celiac axis, Superior Mesenteric (SMA), Renals",
      "1200 psi high-pressure burst rating supports rapid diagnostic contrast bolus injection"
    ],
    "clinicalIndications": "Visceral angiography, celiac/SMA trunk cannulation, renal diagnostic runs, pre-TACE roadmapping",
    "currentStock": 18,
    "reorderLevel": 8,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-COBRA-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 2200,
    "lastLot": "LOT-CD-881920",
    "expiryDate": "2028-08-31",
    "ifuHighlights": "Form curve in descending abdominal aorta over 0.035 in Glidewire; pull down gently into visceral ostium."
  },
  {
    "id": "cat-02",
    "sku": "RMSCL-SURG-SIM2-5F",
    "name": "Super Torque Plus Simmons Catheter 5F 100cm (Sim 2)",
    "imageUrl": "/images/hardware/cat-02.png",
    "category": "Diagnostic Catheters",
    "specification": "5 French x 100 cm Recurved Sidewinder Angiographic Catheter (Simmons 2 Curve)",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "100 cm",
    "manufacturer": "Cordis",
    "brandName": "Simmons 2",
    "boxColor": {
      "primary": "#285E61",
      "secondary": "#1A202C",
      "accent": "#38B2AC",
      "text": "#FFFFFF",
      "badgeBg": "#E6FFFA",
      "badgeText": "#234E52"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "Recurved shepherd crook curve excels at engaging acutely downward-angled visceral ostia in elderly patients",
      "Easily reformed in aortic arch, left subclavian, or contralateral iliac artery",
      "Provides rock-solid backup support for coaxial microcatheter advancement into tortuous vessels"
    ],
    "clinicalIndications": "Steep-angle SMA selection, tortuous celiac trunks, left gastric artery cannulation in upper GI bleed",
    "currentStock": 14,
    "reorderLevel": 6,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-SIM2-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 2400,
    "lastLot": "LOT-CD-774810",
    "expiryDate": "2028-10-31",
    "ifuHighlights": "Reform the Sim-2 loop against aortic valve leaflets or left subclavian ostium prior to descending cannulation."
  },
  {
    "id": "cat-03",
    "sku": "RMSCL-SURG-PIGTAIL-5F",
    "name": "Royal Flush Plus Pigtail Catheter 5F 100cm High Flow",
    "imageUrl": "/images/hardware/cat-03.jpg",
    "category": "Diagnostic Catheters",
    "specification": "5 French x 100 cm High-Flow 1200 psi Pigtail with 6 Sideholes",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "100 cm",
    "manufacturer": "Cook Medical",
    "brandName": "Royal Flush Plus",
    "boxColor": {
      "primary": "#742A2A",
      "secondary": "#1A202C",
      "accent": "#E53E3E",
      "text": "#FFFFFF",
      "badgeBg": "#FFF5F5",
      "badgeText": "#742A2A"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "Six sideholes in circular distal pigtail loop deliver uniform omni-directional contrast dispersion",
      "High-pressure rating (1200 psi) safely handles 15-25 mL/sec power-injector runs without catheter recoil",
      "Atraumatic circular tip prevents intimal jet lesions and mural contrast extravasation"
    ],
    "clinicalIndications": "Abdominal aortography, pelvic runoff, thoracic arch DSA, IVC cavography",
    "currentStock": 24,
    "reorderLevel": 10,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-PIGTAIL-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 1900,
    "lastLot": "LOT-CK-661029",
    "expiryDate": "2028-12-31",
    "ifuHighlights": "Ensure circular pigtail is fully formed in aorta lumen and aspirate vigorously before contrast bolus."
  },
  {
    "id": "cat-04",
    "sku": "RMSCL-SURG-MPA-5F",
    "name": "Impress Multipurpose Catheter 5F 100cm (MPA-1)",
    "imageUrl": "/images/hardware/cat-04.png",
    "category": "Diagnostic Catheters",
    "specification": "5 French x 100 cm Straight Tip Catheter with Dual Opposing Sideholes (MPA-1)",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "100 cm",
    "manufacturer": "Merit Medical",
    "brandName": "Impress Multipurpose",
    "boxColor": {
      "primary": "#9C4221",
      "secondary": "#1A202C",
      "accent": "#DD6B20",
      "text": "#FFFFFF",
      "badgeBg": "#FEEBC8",
      "badgeText": "#7B341E"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "Versatile multipurpose tip configuration for pulmonary, visceral, and peripheral venous cannulation",
      "Dual sideholes prevent vacuum suction adherence to vessel walls during manual or power injection",
      "Reinforced braided shaft allows torque control from femoral or jugular access sites"
    ],
    "clinicalIndications": "Pulmonary angiography, hepatic vein pressure gradient (HVPG), inferior vena cava filter retrieval",
    "currentStock": 16,
    "reorderLevel": 6,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-MPA-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 2100,
    "lastLot": "LOT-MM-330192",
    "expiryDate": "2028-09-30",
    "ifuHighlights": "For HVPG, wedge firmly in right hepatic vein branch until free backflow ceases and contrast pools."
  },
  {
    "id": "itm-02",
    "sku": "RMSCL-SURG-MICROCATH-018",
    "name": "Progreat 2.7F 130cm Coaxial Microcatheter",
    "imageUrl": "/images/hardware/itm-02.png",
    "category": "Microcatheters",
    "specification": "2.7 French x 130 cm Tungsten Coil Coaxial Microcatheter with 0.021 in Inner Lumen",
    "frenchOrGauge": "2.7F",
    "lengthOrDiameter": "130 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Progreat 2.7F",
    "boxColor": {
      "primary": "#007A3E",
      "secondary": "#1C1C1C",
      "accent": "#B78727",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#137333"
    },
    "packagingType": "BOX",
    "productSilhouette": "MICROCATHETER",
    "brochureHighlights": [
      "Gradual stiffness transition with tungsten braiding provides unparalleled trackability in tortuous anatomy",
      "Generous 0.021 in inner lumen handles 300-500 µm calibrated microspheres without clogging",
      "Smooth PTFE inner lining ensures zero friction during 0.014 in and 0.018 in microcoil delivery"
    ],
    "clinicalIndications": "TACE for hepatocellular carcinoma, bronchial artery embolization, selective renal hemorrhage embolization",
    "currentStock": 8,
    "reorderLevel": 6,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-MICROCATH-018",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 16500,
    "lastLot": "LOT-TR-9482103",
    "expiryDate": "2028-02-28",
    "ifuHighlights": "Continuous heparinized saline flush via rotating hemostatic valve required during all manipulations."
  },
  {
    "id": "mic-02",
    "sku": "RMSCL-SURG-PROG-20F",
    "name": "Progreat 2.0F 150cm Superselective Microcatheter",
    "imageUrl": "/images/hardware/mic-02.png",
    "category": "Microcatheters",
    "specification": "2.0 French x 150 cm Ultra-Low Profile Distal Segment for Subsegmental Superselection",
    "frenchOrGauge": "2.0F",
    "lengthOrDiameter": "150 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Progreat 2.0F Omega",
    "boxColor": {
      "primary": "#006233",
      "secondary": "#1C1C1C",
      "accent": "#E2B93B",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#006233"
    },
    "packagingType": "BOX",
    "productSilhouette": "MICROCATHETER",
    "brochureHighlights": [
      "Slim 2.0F outer profile navigates beyond subsegmental hepatic bifurcations without inducing spasm",
      "Gold radiopaque dual-marker system enables high-magnification submillimeter landing accuracy",
      "Compatible with 0.014 in microguidewires and fine liquid embolic mixtures"
    ],
    "clinicalIndications": "Subsegmental HCC TACE, distal GI bleed superselection, intracranial distal branches",
    "currentStock": 6,
    "reorderLevel": 3,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-PROG-20F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 18200,
    "lastLot": "LOT-TR-551920",
    "expiryDate": "2028-04-30",
    "ifuHighlights": "Do not exceed maximum pressure rating of 500 psi during manual syringe injection."
  },
  {
    "id": "stn-07",
    "sku": "RMSCL-SURG-WALLFLEX-BIL",
    "name": "WallFlex Biliary Fully Covered SEMS 10mm x 60mm",
    "imageUrl": "/images/hardware/stn-07.jpg",
    "category": "Stents & Endoprostheses",
    "specification": "10 mm x 60 mm Platinum-Cored Nitinol Fully Covered Biliary Stent with Permalume & Loop",
    "frenchOrGauge": "8F Sheath",
    "lengthOrDiameter": "10mm x 60mm",
    "manufacturer": "Boston Scientific",
    "brandName": "WallFlex Biliary",
    "boxColor": {
      "primary": "#744210",
      "secondary": "#1A202C",
      "accent": "#D69E2E",
      "text": "#FFFFFF",
      "badgeBg": "#FEFCBF",
      "badgeText": "#744210"
    },
    "packagingType": "BOX",
    "productSilhouette": "STENT",
    "brochureHighlights": [
      "Permalume silicone covering prevents tumor and tissue ingrowth throughout entire stricture length",
      "Platinol wire construction provides high radiopacity along the entire stent body without separate markers",
      "Integrated braided PTFE retrieval suture loop permits removal or repositioning for up to 12 months"
    ],
    "clinicalIndications": "Malignant common bile duct (CBD) obstruction, benign refractory post-cholecystectomy biliary strictures",
    "currentStock": 6,
    "reorderLevel": 3,
    "unit": "Stents",
    "rmsclMatchingCode": "RMSCL-SURG-WALLFLEX-BIL",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 44000,
    "lastLot": "LOT-BS-331029",
    "expiryDate": "2028-08-31",
    "ifuHighlights": "Deploy under combined fluoroscopic and cholangiographic roadmapping. Avoid occluding intrahepatic branch ducts."
  },
  {
    "id": "itm-06",
    "sku": "RMSCL-SURG-COIL-004",
    "name": "Tornado Embolization Coil 4mm x 2mm",
    "imageUrl": "/images/hardware/itm-06.jpg",
    "category": "Embolics & Coils",
    "specification": "Fibered Platinum 4mm x 2mm for 0.018 in or 0.035 in Delivery",
    "frenchOrGauge": "0.018\" / 0.035\"",
    "lengthOrDiameter": "4mm x 2mm",
    "manufacturer": "Cook Medical",
    "brandName": "Tornado Coil",
    "boxColor": {
      "primary": "#742A2A",
      "secondary": "#1A202C",
      "accent": "#E53E3E",
      "text": "#FFFFFF",
      "badgeBg": "#FFF5F5",
      "badgeText": "#742A2A"
    },
    "packagingType": "DISPENSER_TUBE",
    "productSilhouette": "COIL",
    "brochureHighlights": [
      "Conical microcoil geometry anchors firmly against vessel walls resisting distal embolic migration",
      "High-density synthetic Dacron fibers trigger rapid platelet adherence and fibrin crosslinking",
      "Platinum construction ensures crisp radiopacity for verified dense packing"
    ],
    "clinicalIndications": "Acute gastrointestinal bleeding (GDA sandwich), pulmonary AVM occlusion, traumatic arterial lacerations",
    "currentStock": 15,
    "reorderLevel": 6,
    "unit": "Coils",
    "rmsclMatchingCode": "RMSCL-SURG-COIL-004",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 11200,
    "lastLot": "LOT-CK-3819204",
    "expiryDate": "2027-05-30",
    "ifuHighlights": "Push gently through microcatheter using 0.018 in wire or specialized coil pusher. Verify nest formation."
  },
  {
    "id": "itm-03",
    "sku": "RMSCL-DRUG-LIPIODOL-10ML",
    "name": "Lipiodol Ultra-Fluid (Ethiodized Oil 10 mL Ampoule)",
    "imageUrl": "/images/hardware/itm-03.jpg",
    "category": "Embolics & Coils",
    "specification": "Ethiodized Oil (480 mg Iodine/mL) 10 mL Glass Ampoule for TACE and Lymphangiography",
    "frenchOrGauge": "10 mL Ampoule",
    "lengthOrDiameter": "10 mL",
    "manufacturer": "Guerbet",
    "brandName": "Lipiodol Ultra-Fluid",
    "boxColor": {
      "primary": "#B7791F",
      "secondary": "#1A202C",
      "accent": "#D69E2E",
      "text": "#FFFFFF",
      "badgeBg": "#FEFCBF",
      "badgeText": "#744210"
    },
    "packagingType": "AMPOULE_TRAY",
    "productSilhouette": "AMPOULE",
    "brochureHighlights": [
      "Selective persistent microvascular retention in tumor neovasculature of hepatocellular carcinoma (HCC)",
      "High radiopacity (480 mg I/mL) enables real-time fluoroscopic visualization of tumor uptake",
      "Essential radio-opaque carrier for Doxorubicin / Epirubicin and polymerization modulator for cyanoacrylate glue"
    ],
    "clinicalIndications": "Transarterial chemoembolization (cTACE), intranodal lymphangiography for thoracic duct leaks, nBCA glue dilution",
    "currentStock": 18,
    "reorderLevel": 8,
    "unit": "Ampoules",
    "rmsclMatchingCode": "RMSCL-DRUG-LIPIODOL-10ML",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 8500,
    "lastLot": "LOT-GB-5510931",
    "expiryDate": "2028-03-31",
    "ifuHighlights": "Draw using 5-micron filter needle. Emulsify with chemotherapeutic agent in 1:2 to 1:3 ratio using three-way stopcock."
  },
  {
    "id": "emb-08",
    "sku": "RMSCL-SURG-VENASEAL",
    "name": "VenaSeal Cyanoacrylate Closure System for Varicose Veins",
    "imageUrl": "/images/hardware/emb-08.jpg",
    "category": "Embolics & Coils",
    "specification": "Proprietary Medical Cyanoacrylate Adhesive 5 mL with Dispenser Gun and 5F Delivery Sheath",
    "frenchOrGauge": "5F Delivery",
    "lengthOrDiameter": "5 mL Kit",
    "manufacturer": "Medtronic",
    "brandName": "VenaSeal Closure",
    "boxColor": {
      "primary": "#002B49",
      "secondary": "#001A2C",
      "accent": "#0085CA",
      "text": "#FFFFFF",
      "badgeBg": "#E0F2FE",
      "badgeText": "#0369A1"
    },
    "packagingType": "BOX",
    "productSilhouette": "AMPOULE",
    "brochureHighlights": [
      "Non-thermal, non-tumescent endovenous closure eliminates need for painful perivenous tumescent anesthesia injections",
      "Zero nerve heat injury risk adjacent to small saphenous vein (SSV) sural nerve or tibial nerve",
      "Allows immediate post-procedure return to normal daily activities with no compression stockings required"
    ],
    "clinicalIndications": "Incompetent great saphenous vein (GSV), small saphenous vein (SSV), anterior accessory saphenous reflux",
    "currentStock": 6,
    "reorderLevel": 2,
    "unit": "Kits",
    "rmsclMatchingCode": "RMSCL-SURG-VENASEAL",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 58000,
    "lastLot": "LOT-MD-119203",
    "expiryDate": "2028-07-31",
    "ifuHighlights": "Deliver 0.09 mL glue bolus every 3 cm under ultrasound compression for 3 minutes at saphenofemoral junction."
  },
  {
    "id": "drn-01",
    "sku": "RMSCL-SURG-DAWSON-10F",
    "name": "Ultrathane Dawson-Mueller Drainage Catheter 10.2F 25cm with Mac-Loc",
    "imageUrl": "/images/hardware/drn-01.jpg",
    "category": "Drainage & Access",
    "specification": "10.2 French x 25 cm Hydrophilic AQ Coated Multipurpose Locking Loop Catheter",
    "frenchOrGauge": "10.2F",
    "lengthOrDiameter": "25 cm",
    "manufacturer": "Cook Medical",
    "brandName": "Dawson-Mueller",
    "boxColor": {
      "primary": "#2C5282",
      "secondary": "#1A202C",
      "accent": "#4299E1",
      "text": "#FFFFFF",
      "badgeBg": "#EBF8FF",
      "badgeText": "#2C5282"
    },
    "packagingType": "BOX",
    "productSilhouette": "DRAIN",
    "brochureHighlights": [
      "Patented Mac-Loc suture locking system prevents accidental pigtail unraveling or tube displacement",
      "Ultrathane polymer formulation resists bile acid degradation and encrustation in long-term drain placements",
      "Large oval sideholes positioned along the inner loop diameter ensure continuous drainage without clogging"
    ],
    "clinicalIndications": "Percutaneous transhepatic biliary drainage (PTBD), deep abdominal/pelvic abscess drainage, nephrostomy",
    "currentStock": 16,
    "reorderLevel": 6,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-DAWSON-10F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 3900,
    "lastLot": "LOT-CK-441029",
    "expiryDate": "2028-10-31",
    "ifuHighlights": "Activate hydrophilic coating with sterile water. Snap Mac-Loc lever firmly until click is heard."
  },
  {
    "id": "drn-02",
    "sku": "RMSCL-SURG-RESOLVE-8F",
    "name": "ReSolve Mini Locking Drainage Catheter 8.5F 25cm",
    "imageUrl": "/images/hardware/drn-02.png",
    "category": "Drainage & Access",
    "specification": "8.5 French x 25 cm Compact Low-Profile Pigtail with Depth Markers & Suture Anchor",
    "frenchOrGauge": "8.5F",
    "lengthOrDiameter": "25 cm",
    "manufacturer": "Merit Medical",
    "brandName": "ReSolve Mini",
    "boxColor": {
      "primary": "#9B2C2C",
      "secondary": "#1A202C",
      "accent": "#E53E3E",
      "text": "#FFFFFF",
      "badgeBg": "#FFF5F5",
      "badgeText": "#9B2C2C"
    },
    "packagingType": "BOX",
    "productSilhouette": "DRAIN",
    "brochureHighlights": [
      "Mini pigtail loop is 40% smaller than conventional designs, ideal for small fluid pockets and pediatric abscesses",
      "Centimeter depth markings on catheter shaft facilitate exact cutaneous anchoring",
      "Internal locking pull-thread with protective silicone sleeve prevents skin irritation"
    ],
    "clinicalIndications": "Small pelvic abscesses, subhepatic collections, empyema drainage, palliative ascites drainage",
    "currentStock": 12,
    "reorderLevel": 5,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-RESOLVE-8F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 3600,
    "lastLot": "LOT-MM-772910",
    "expiryDate": "2028-12-31",
    "ifuHighlights": "Deploy over 0.035 in stiff wire. Pull string snugly until secure circle forms inside cavity."
  },
  {
    "id": "cat-05",
    "sku": "RMSCL-SURG-SIM1-5F",
    "name": "Super Torque Plus Simmons Catheter 5F 100cm (Sim 1)",
    "imageUrl": "/images/hardware/cat-05.jpg",
    "category": "Diagnostic Catheters",
    "specification": "5F 100cm Simmons 1 Secondary Curve Angiographic Selective Catheter (1200 psi)",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "100 cm Length / Sim 1 Curve",
    "manufacturer": "Cordis",
    "brandName": "Super Torque Plus Sim 1",
    "boxColor": {
      "primary": "#004B87",
      "secondary": "#002849",
      "accent": "#00A3E0",
      "text": "#FFFFFF",
      "badgeBg": "#E1F5FE",
      "badgeText": "#0277BD"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "Simmons 1 primary loop formation enables selective cannulation of downward-pointing visceral and arch branches",
      "High-torque polyurethane shaft provides 1:1 rotational response during aortic loop reconstruction",
      "Rated for power contrast injections up to 1200 psi for diagnostic roadmap DSA"
    ],
    "clinicalIndications": "Selective engagement of celiac axis, SMA, renal arteries, and bovine aortic arch branches",
    "currentStock": 15,
    "reorderLevel": 5,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-SIM1-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 3200,
    "lastLot": "LOT-CD-551029",
    "expiryDate": "2028-09-30",
    "ifuHighlights": "Reconstitute curve in ascending aorta or aortic bifurcation before engaging downward-angled vessel origins."
  },
  {
    "id": "cat-11",
    "sku": "RMSCL-SURG-MPA2-5F",
    "name": "Impress Multipurpose Catheter 5F 100cm (MPA-2)",
    "imageUrl": "/images/hardware/cat-11.jpg",
    "category": "Diagnostic Catheters",
    "specification": "5F 100cm Multipurpose A2 (MPA-2) Angiographic Catheter with 2 Side Holes & End Hole (1200 psi)",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "100 cm Length / MPA-2",
    "manufacturer": "Merit Medical",
    "brandName": "Impress MPA-2",
    "boxColor": {
      "primary": "#003865",
      "secondary": "#001D36",
      "accent": "#0088CC",
      "text": "#FFFFFF",
      "badgeBg": "#EBF5FB",
      "badgeText": "#005B8A"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "Straight tip with subtle angled beak and two opposing side-holes facilitates high-volume non-recoil contrast delivery",
      "Versatile multi-specialty utility across visceral, pelvic, and neurovascular roadmapping procedures",
      "Hydrophilic-coated shaft glides through severe peripheral vascular tortuosity with minimal resistance"
    ],
    "clinicalIndications": "Visceral aortography, lower extremity runoff, selective internal iliac angiography, and venous sampling",
    "currentStock": 16,
    "reorderLevel": 6,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-MPA2-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 3100,
    "lastLot": "LOT-MM-661029",
    "expiryDate": "2029-02-28",
    "ifuHighlights": "Ensure side-holes are fully within target vessel lumen prior to power injection to prevent extravasation."
  },
  {
    "id": "cat-17",
    "sku": "RMSCL-SURG-MARKERPIG-5F",
    "name": "Royal Flush Centimeter Marker Pigtail Catheter 5F 100cm",
    "imageUrl": "/images/hardware/cat-17.jpg",
    "category": "Diagnostic Catheters",
    "specification": "5F 100cm High-Flow Centimeter Marker Pigtail Angiographic Catheter with 1 cm Radiopaque Bands",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "100 cm Length / 20 cm Marker Band Zone",
    "manufacturer": "Cook Medical",
    "brandName": "Royal Flush Marker",
    "boxColor": {
      "primary": "#1E3A8A",
      "secondary": "#0F172A",
      "accent": "#3B82F6",
      "text": "#FFFFFF",
      "badgeBg": "#EFF6FF",
      "badgeText": "#1E40AF"
    },
    "packagingType": "BOX",
    "productSilhouette": "CATHETER",
    "brochureHighlights": [
      "Integrated platinum marker bands spaced exactly 1 cm apart provide parallax-free anatomic length calibration",
      "High-flow Royal Flush construction delivers up to 25 mL/sec contrast for high-detail aortography and runoffs",
      "Pigtail tip with six side holes minimizes vessel wall recoil and jet dissection during power injection"
    ],
    "clinicalIndications": "Diagnostic aortography, EVAR/TEVAR stent-graft sizing, iliofemoral measurement, and peripheral runoff calibration",
    "currentStock": 14,
    "reorderLevel": 5,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-MARKERPIG-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 3800,
    "lastLot": "LOT-CK-551029",
    "expiryDate": "2029-02-28",
    "ifuHighlights": "Align markers along target aortic segment. Calibrate digital DSA caliper tool directly against catheter marker intervals."
  },
  {
    "id": "plg-08",
    "sku": "RMSCL-SURG-NESTER-18",
    "name": "Nester Platinum Fibered Embolization Microcoil 0.018 in",
    "imageUrl": "/images/hardware/plg-08.png",
    "category": "Embolics & Coils",
    "specification": "0.018 in Soft Platinum Pushable Microcoil with Interwoven Synthetic Dacron Fibers",
    "frenchOrGauge": "0.018 in Microcoil",
    "lengthOrDiameter": "4mm x 7cm / 6mm x 14cm",
    "manufacturer": "Cook Medical",
    "brandName": "Nester Microcoil",
    "boxColor": {
      "primary": "#1E3A8A",
      "secondary": "#172554",
      "accent": "#3B82F6",
      "text": "#FFFFFF",
      "badgeBg": "#DBEAFE",
      "badgeText": "#1E40AF"
    },
    "packagingType": "BOX",
    "productSilhouette": "COIL",
    "brochureHighlights": [
      "High-density synthetic Dacron fibers activate the intrinsic coagulation cascade rapidly",
      "Flexible platinum alloy adapts closely to irregularly shaped vascular beds without wall rupture",
      "Economical pushable format delivered smoothly with standard 0.014 in or 0.018 in microguidewires"
    ],
    "clinicalIndications": "Bronchial artery embolization for hemoptysis, lower gastrointestinal bleeding, and varicocele occlusion",
    "currentStock": 16,
    "reorderLevel": 6,
    "unit": "Coils",
    "rmsclMatchingCode": "RMSCL-SURG-NESTER-18",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 11500,
    "lastLot": "LOT-CK-881920",
    "expiryDate": "2028-12-31",
    "ifuHighlights": "Push steadily through microcatheter using 0.014 in microguidewire. Confirm complete emergence from tip before wire retrieval."
  },
  {
    "id": "bil-01",
    "sku": "RMSCL-SURG-ZILVER635-SEMS",
    "name": "Zilver 635 Biliary Self-Expanding Metallic Stent (SEMS) 10x60mm",
    "imageUrl": "/images/hardware/bil-01.png",
    "category": "Stents & Endoprostheses",
    "specification": "6F Low-Profile Delivery Self-Expanding Laser-Cut Nitinol Biliary Stent (10mm x 60mm)",
    "frenchOrGauge": "6F Delivery System",
    "lengthOrDiameter": "10 mm Diameter x 60 mm Length",
    "manufacturer": "Cook Medical",
    "brandName": "Zilver 635 Biliary",
    "boxColor": {
      "primary": "#1E3A8A",
      "secondary": "#172554",
      "accent": "#3B82F6",
      "text": "#FFFFFF",
      "badgeBg": "#DBEAFE",
      "badgeText": "#1E40AF"
    },
    "packagingType": "BOX",
    "productSilhouette": "STENT",
    "brochureHighlights": [
      "Slim 6F system allows transhepatic deployment across tight malignant biliary strictures without prior balloon dilatation",
      "Open-cell nitinol design preserves intrahepatic lateral branch bile drainage at bifurcation",
      "Gold radiopaque markers on both ends guarantee exact fluoroscopic positioning accuracy"
    ],
    "clinicalIndications": "Palliative drainage of malignant biliary obstruction due to cholangiocarcinoma and pancreatic cancer",
    "currentStock": 6,
    "reorderLevel": 2,
    "unit": "Stents",
    "rmsclMatchingCode": "RMSCL-SURG-ZILVER635-SEMS",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 56000,
    "lastLot": "LOT-CK-110294",
    "expiryDate": "2028-11-30",
    "ifuHighlights": "Position with at least 10 mm margin above and below stricture. Deploy using thumb-wheel trigger without forward push."
  },
  {
    "id": "bil-02",
    "sku": "RMSCL-SURG-NITIS-BILIARY",
    "name": "Niti-S Biliary Fully Covered SEMS 10mm x 80mm",
    "imageUrl": "/images/hardware/bil-02.png",
    "category": "Stents & Endoprostheses",
    "specification": "Fully Silicone-Covered Braided Nitinol Biliary Stent with Platinum Retrieval Lasso",
    "frenchOrGauge": "8F System",
    "lengthOrDiameter": "10 mm Diameter x 80 mm Length",
    "manufacturer": "Taewoong Medical",
    "brandName": "Niti-S Biliary",
    "boxColor": {
      "primary": "#1A365D",
      "secondary": "#0F172A",
      "accent": "#38BDF8",
      "text": "#FFFFFF",
      "badgeBg": "#E0F2FE",
      "badgeText": "#0369A1"
    },
    "packagingType": "BOX",
    "productSilhouette": "STENT",
    "brochureHighlights": [
      "Full silicone membrane prevents malignant tumor ingrowth through stent struts",
      "Integrated braided lasso allows endobiliary or percutaneous snare retrieval if revision is needed",
      "Braided architecture delivers high flexibility across curved common bile duct anatomy"
    ],
    "clinicalIndications": "Distal common bile duct malignant obstructions and benign refractory post-cholecystectomy strictures",
    "currentStock": 5,
    "reorderLevel": 2,
    "unit": "Stents",
    "rmsclMatchingCode": "RMSCL-SURG-NITIS-BILIARY",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 62000,
    "lastLot": "LOT-TW-882109",
    "expiryDate": "2029-01-31",
    "ifuHighlights": "Ensure covered portion does not occlude cystic duct takeoff to prevent secondary acute cholecystitis."
  },
  {
    "id": "bil-07",
    "sku": "RMSCL-SURG-RING-BILIARY",
    "name": "Ring Biliary Drainage Catheter Multiple Sideholes 8.3F 40cm",
    "imageUrl": "/images/hardware/bil-07.png",
    "category": "Drainage & Access",
    "specification": "8.3F Radiopaque Polyurethane Internal-External Biliary Drainage Catheter with Locking Loop",
    "frenchOrGauge": "8.3F",
    "lengthOrDiameter": "40 cm (Multiple Sideholes)",
    "manufacturer": "Cook Medical",
    "brandName": "Ring Biliary Catheter",
    "boxColor": {
      "primary": "#1E3A8A",
      "secondary": "#172554",
      "accent": "#3B82F6",
      "text": "#FFFFFF",
      "badgeBg": "#DBEAFE",
      "badgeText": "#1E40AF"
    },
    "packagingType": "BOX",
    "productSilhouette": "DRAIN",
    "brochureHighlights": [
      "Dual-segment sidehole configuration drains both intrahepatic bile ducts and passes bile into duodenum",
      "Mac-Loc suture retention loop prevents accidental catheter dislodgement from duodenal lumen",
      "Lubricious Ultrathane polymer minimizes encrustation and bile sludge buildup over extended dwell times"
    ],
    "clinicalIndications": "Percutaneous transhepatic biliary drainage (PTBD) with internal-external bile diversion",
    "currentStock": 15,
    "reorderLevel": 5,
    "unit": "Catheters",
    "rmsclMatchingCode": "RMSCL-SURG-RING-BILIARY",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 12500,
    "lastLot": "LOT-CK-330192",
    "expiryDate": "2029-03-31",
    "ifuHighlights": "Confirm proximal sideholes reside within intrahepatic ducts and distal sideholes rest in duodenum on completion cholangiogram."
  },
  {
    "id": "sth-4f",
    "sku": "RMSCL-SURG-SHEATH-4F",
    "name": "Radifocus Introducer II 4F 11cm",
    "imageUrl": "/images/hardware/itm-04.jpg",
    "category": "Access Sheaths",
    "specification": "4 French x 11 cm Radial / Femoral Introducer Sheath with Hemostatic Cross-Cut Valve and 0.035 in Guidewire",
    "frenchOrGauge": "4F",
    "lengthOrDiameter": "11 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Radifocus Introducer II",
    "boxColor": {
      "primary": "#007A3E",
      "secondary": "#1C1C1C",
      "accent": "#B78727",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#137333"
    },
    "packagingType": "BOX",
    "productSilhouette": "SHEATH",
    "brochureHighlights": [
      "Seamless dilator-to-sheath taper minimizes puncture resistance and femoral hematoma rate",
      "Cross-cut hemostatic seal withstands up to 250 psi backpressure with zero blood weeping",
      "Smooth sidearm with 3-way stopcock for continuous arterial line pressure monitoring and flushing"
    ],
    "clinicalIndications": "Pediatric intervention, distal radial artery access, and diagnostic peripheral angiography",
    "currentStock": 22,
    "reorderLevel": 10,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-SHEATH-4F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 1450,
    "lastLot": "LOT-TR-7821940",
    "expiryDate": "2028-06-30",
    "ifuHighlights": "Ensure J-tip guidewire exits dilator tip before advancing sheath unit through skin and arterial wall."
  },
  {
    "id": "sth-5f",
    "sku": "RMSCL-SURG-SHEATH-5F",
    "name": "Radifocus Introducer II 5F 11cm",
    "imageUrl": "/images/hardware/itm-04.jpg",
    "category": "Access Sheaths",
    "specification": "5 French x 11 cm Femoral / Radial Introducer Sheath with Hemostatic Cross-Cut Valve and 0.035 in Dilator",
    "frenchOrGauge": "5F",
    "lengthOrDiameter": "11 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Radifocus Introducer II",
    "boxColor": {
      "primary": "#007A3E",
      "secondary": "#1C1C1C",
      "accent": "#B78727",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#137333"
    },
    "packagingType": "BOX",
    "productSilhouette": "SHEATH",
    "brochureHighlights": [
      "Seamless dilator-to-sheath taper minimizes puncture resistance and femoral hematoma rate",
      "Cross-cut hemostatic seal withstands up to 250 psi backpressure with zero blood weeping",
      "Smooth sidearm with 3-way stopcock for continuous arterial line pressure monitoring and flushing"
    ],
    "clinicalIndications": "Standard 5F visceral diagnostic angiography, uterine artery embolization, and bronchial artery embolization",
    "currentStock": 22,
    "reorderLevel": 10,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-SHEATH-5F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 1550,
    "lastLot": "LOT-TR-7821940",
    "expiryDate": "2028-06-30",
    "ifuHighlights": "Ensure J-tip guidewire exits dilator tip before advancing sheath unit through skin and arterial wall."
  },
  {
    "id": "sth-7f",
    "sku": "RMSCL-SURG-SHEATH-7F",
    "name": "Radifocus Introducer II 7F 11cm",
    "imageUrl": "/images/hardware/itm-04.jpg",
    "category": "Access Sheaths",
    "specification": "7 French x 11 cm Large-Bore Femoral Introducer Sheath with Cross-Cut Hemostatic Valve",
    "frenchOrGauge": "7F",
    "lengthOrDiameter": "11 cm",
    "manufacturer": "Terumo Interventional Systems",
    "brandName": "Radifocus Introducer II",
    "boxColor": {
      "primary": "#007A3E",
      "secondary": "#1C1C1C",
      "accent": "#B78727",
      "text": "#FFFFFF",
      "badgeBg": "#E6F4EA",
      "badgeText": "#137333"
    },
    "packagingType": "BOX",
    "productSilhouette": "SHEATH",
    "brochureHighlights": [
      "Seamless dilator-to-sheath taper minimizes puncture resistance and femoral hematoma rate",
      "Cross-cut hemostatic seal withstands up to 250 psi backpressure with zero blood weeping",
      "Smooth sidearm with 3-way stopcock for continuous arterial line pressure monitoring and flushing"
    ],
    "clinicalIndications": "Large bore catheter interventions, peripheral stent placement, and mechanical thrombectomy",
    "currentStock": 22,
    "reorderLevel": 10,
    "unit": "Units",
    "rmsclMatchingCode": "RMSCL-SURG-SHEATH-7F",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 1750,
    "lastLot": "LOT-TR-7821940",
    "expiryDate": "2028-06-30",
    "ifuHighlights": "Ensure J-tip guidewire exits dilator tip before advancing sheath unit through skin and arterial wall."
  },
  {
    "id": "emb-pva-355",
    "sku": "RMSCL-SURG-PVA-355",
    "name": "Contour PVA Embolization Particles (355-500 µm)",
    "imageUrl": "/images/hardware/emb-07.jpg",
    "category": "Embolics & Coils",
    "specification": "Polyvinyl Alcohol (PVA) Flake Particulates calibrated 355 to 500 microns (1 Vial)",
    "frenchOrGauge": "355-500 µm",
    "lengthOrDiameter": "1 Vial (approx 100 mg)",
    "manufacturer": "Boston Scientific",
    "brandName": "Contour PVA",
    "boxColor": {
      "primary": "#0B3C5D",
      "secondary": "#1D2731",
      "accent": "#328CC1",
      "text": "#FFFFFF",
      "badgeBg": "#EBF3F8",
      "badgeText": "#0B3C5D"
    },
    "packagingType": "VIAL",
    "productSilhouette": "COIL",
    "brochureHighlights": [
      "Irregular polyvinyl alcohol flakes promote mechanical occlusion and intense perivascular inflammatory thrombosis",
      "Calibrated sizing for targeted distal arteriolar occlusion without non-target capillary transit",
      "Compatible with standard 2.0F - 2.8F microcatheters with contrast-saline suspension"
    ],
    "clinicalIndications": "Pre-operative embolization of Juvenile Nasopharyngeal Angiofibroma (JNA), meningioma, hypervascular visceral tumors, and recurrent hemoptysis",
    "currentStock": 12,
    "reorderLevel": 4,
    "unit": "Vials",
    "rmsclMatchingCode": "RMSCL-SURG-PVA-355",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 5800,
    "lastLot": "LOT-BS-883192",
    "expiryDate": "2028-12-31",
    "ifuHighlights": "Suspend in 50:50 non-ionic contrast and sterile saline. Inject under continuous real-time subtracted fluoroscopy."
  },
  {
    "id": "emb-pva-500",
    "sku": "RMSCL-SURG-PVA-500",
    "name": "Contour PVA Embolization Particles (500-710 µm)",
    "imageUrl": "/images/hardware/emb-07.jpg",
    "category": "Embolics & Coils",
    "specification": "Polyvinyl Alcohol (PVA) Flake Particulates calibrated 500 to 710 microns (1 Vial)",
    "frenchOrGauge": "500-710 µm",
    "lengthOrDiameter": "1 Vial (approx 100 mg)",
    "manufacturer": "Boston Scientific",
    "brandName": "Contour PVA",
    "boxColor": {
      "primary": "#0B3C5D",
      "secondary": "#1D2731",
      "accent": "#328CC1",
      "text": "#FFFFFF",
      "badgeBg": "#EBF3F8",
      "badgeText": "#0B3C5D"
    },
    "packagingType": "VIAL",
    "productSilhouette": "COIL",
    "brochureHighlights": [
      "Larger particulate calibration for mid-sized feeding arteriolar occlusion",
      "Rapid biocompatible thrombus induction with vessel wall adherence",
      "Smooth passage through 0.021 in to 0.027 in inner lumen microcatheters"
    ],
    "clinicalIndications": "Uterine Artery Embolization (UAE / UFE) for fibroids, bronchial artery embolization, and lower GI bleeding",
    "currentStock": 10,
    "reorderLevel": 3,
    "unit": "Vials",
    "rmsclMatchingCode": "RMSCL-SURG-PVA-500",
    "rmsclStatus": "MATCHED",
    "tariffCappedInr": 5800,
    "lastLot": "LOT-BS-883193",
    "expiryDate": "2028-12-31",
    "ifuHighlights": "Slow controlled injection using 1 mL or 3 mL Luer-lock syringes to avoid catheter clumping."
  }
];
